import type { Metadata } from "next";
import { withOg } from "@/lib/shared/pageMetadata";
import {
    PaperLayout,
    PaperSection,
    PaperSubsection,
    PaperRun,
    PaperRemark,
} from "@/components/papers/PaperLayout";
import { Math } from "@/components/papers/Math";
import { RpgfScheduleFigure } from "@/components/figures/RpgfScheduleFigure";

export const metadata: Metadata = withOg({
    title: "Substrate-Broadening Retroactive Public-Goods Funding — Figaro Protocol",
    description:
        "An allocation mechanism that distributes 600M florins to clause authors and assembly designers of record over nine annual accrual periods on a rising budget schedule, scoring clauses and assemblies by distinct live-staked sellers of record rather than volume or value, counted on chain the moment a process settles, with Sybil resistance carried by a two-sided live stake whose cost bound the paper derives.",
});

function FormalBlock({ label, children }: { label: string; children: React.ReactNode }) {
    return (
        <div className="border-l-2 border-default pl-6 my-3 space-y-3">
            <p className="text-sm font-semibold text-ink-heading">{label}</p>
            {children}
        </div>
    );
}

function Proof({ children }: { children: React.ReactNode }) {
    return (
        <div className="my-3 space-y-3 text-ink-body">
            <p>
                <span className="italic text-ink-muted">Proof. </span>
                {children}
            </p>
        </div>
    );
}

export default function SubstrateBroadeningRpgfPaper() {
    return (
        <PaperLayout slug="substrate-broadening-rpgf"
            title="Substrate-Broadening Retroactive Public-Goods Funding"
            subtitle="Allocating a Fixed Reserve on Adoption Counted as It Happens"
            author="Figaro"
            date="July 2026"
            watermark="Figaro Protocol · Preprint"
            keywords="retroactive public goods funding, mechanism design, resource allocation, verified usage accounting, permissionless recording, deterministic allocation, clause authoring, assembly design, coordination protocols"
            abstract={
                <>
                    <p>
                        A permissionless coordination protocol grows as its substrate is extended &mdash; in the Figaro protocol, by the <em>clauses</em> that define new attestation and agreement types and the <em>assemblies</em> that compose them into reusable coordinations. Authoring a clause or composing an assembly is public-goods work: once registered, it is usable by every participant at no charge and no recurring revenue to its author. This paper specifies the mechanism by which the florin funds that work retroactively: a fixed 600-million-unit reserve, paid out over nine annual accrual periods on a schedule that rises across the years &mdash; 15% over the first two, 30% over the next three, 55% over the last four &mdash; allocated to clause authors and assembly designers of record by a rule fixed in the deployed contracts. The rule rewards <em>substrate-broadening</em> &mdash; adoption by many distinct value-adders in processes that actually settled &mdash; over volume or value moved, and it is uniform: no tag, category, or authored identity multiplies a score. Counting rules close the cheap farming vectors &mdash; settled processes only, one count per process per clause or assembly, a minimum-support floor below which a clause or assembly scores nothing &mdash; and Sybil resistance is carried by a two-sided live stake in the chain&rsquo;s base currency: breadth is counted in the units that stake prices, one live staked identity per unit, with no arrangement of wallets that returns more than one unit per identity. We derive the resulting bound: fabricating score costs capital linear in the score fabricated, at a unit price fixed by the deposit, the withdrawal cooldown and the length of an accrual period; and capturing a given fraction of a period&rsquo;s budget costs capital convex in that fraction and unbounded as it approaches one. That stake is exposure to the network&rsquo;s own growth, not a fee; distribution is uniform pro rata.
                    </p>
                    <p>
                        The allocation rests on no trusted party, because it rests on no claim about the past. What a settled coordination leaves on the chain is narrow and exact: the commitments the parties signed, the bonds those commitments locked, and the fact of resolution &mdash; while the work itself, and every passage of value between the parties, happened off the record. The mechanism scores that shape and never its contents or its worth. Adoption is counted on chain the moment it occurs: anyone may record that a settled process used a given clause or assembly, and the recording contract verifies both halves of that claim from state the chain already holds &mdash; that the order resolved, and that the clause or assembly was committed in the signed agreement. Accrual buckets into fixed periods whose numbers stop moving the instant a period ends, so a payout is arithmetic over quantities that can no longer change. Because the chain cannot look backwards, reconstructing adoption after the fact would require someone to <em>post</em> the answer, a <em>bond</em> to make posting costly, a <em>challenge</em> to contest it, and a <em>forum</em> to award the bonds; recording the fact when it happens removes that chain of consequences at its root.
                    </p>
                </>
            }
            references={
                <>
                    <li>Buterin, V., Hitzig, Z., &amp; Weyl, E. G. A Flexible Design for Funding Public Goods. <em>Management Science</em>, 65(11):5171&ndash;5187, 2019.</li>
                    <li>Douceur, J. R. The Sybil Attack. In <em>Peer-to-Peer Systems (IPTPS 2002)</em>, Lecture Notes in Computer Science 2429, pp. 251&ndash;260. Springer, 2002.</li>
                    <li>Optimism Collective. <em>Retroactive Public Goods Funding</em>. Optimism PBC Blog, July 2021.</li>
                    <li>Optimism Foundation. <em>Optimistic Rollups</em>. Optimism Technical Documentation, 2021.</li>
                </>
            }
        >
            <PaperSection title="1. Introduction">
                <p>
                    The Figaro settlement kernel is deliberately minimal. A process is opened and extended by dual-signed commitments, each of which locks a bond from both parties &mdash; the seller&rsquo;s keyed to the value the chain has accumulated at its own link &mdash; and the buyer alone resolves, settling every order in the process at once. Two features of that arrangement set the terms for everything below, and this paper restates them rather than assuming its reader has them. The kernel is a boundary, not an observer: the work, the goods, and every passage of value between the parties happen off the record, and what the chain holds of all that is the commitments, the bonds, and the resolution. And resolution is the buyer&rsquo;s own acceptance, taken when it is satisfied and terminal once taken &mdash; which makes a resolved order the only event in the record that reports a coordination actually completed, and therefore the only event an adoption count can honestly be built on. Everything that gives a bonded commitment meaning beyond &ldquo;party A paid party B&rdquo; &mdash; what was promised, what was attested, what credential was presented, what handoff occurred &mdash; lives in <em>clauses</em>: content-typed agreement and attestation definitions, each registered permissionlessly on the clause registry. Clauses compose into <em>assemblies</em>: reusable coordinations that a designer publishes once and that any buyer can instantiate thereafter. Clauses and assemblies are the protocol&rsquo;s substrate. The reachable surface of coordinations the protocol can express is exactly the set of clauses and assemblies that exist.
                </p>
                <p>
                    Authoring a clause or composing an assembly is public-goods work in the strict sense. A registered clause is non-rival (one author&rsquo;s registration does not consume another&rsquo;s ability to use it), non-excludable (anyone may attest under a registered clause), and uncompensated by the protocol&rsquo;s own operation (the kernel takes no fee, and there is no per-attestation or per-settlement revenue path). The author who writes a high-quality logistics-attestation clause, or the designer who composes a handoff assembly that a hundred unrelated buyers later instantiate, captures none of the value their work creates for the network. This is the canonical under-provision problem of public goods, reproduced at the protocol-substrate layer.
                </p>
                <p>
                    Retroactive public-goods funding (RPGF), developed in practice by the Optimism Collective (2021), addresses under-provision by rewarding work after its value is observable rather than speculating on it in advance. The intuition is that judging impact is easier in retrospect than prospect. This paper specifies a fully mechanized instance of that intuition for clause authoring and assembly design: a fixed florin reserve, paid out in annual instalments over the years that follow the work, allocated by an objective scoring function computed over on-chain settlement history &mdash; with no committee, no vote, no discretionary curation, and no privileged party who supplies the inputs. Where Optimism&rsquo;s practice retains human badgeholder panels to score impact, this mechanism replaces the panel with a rule and the ballot with a count the chain keeps for itself; what it keeps from that lineage is the retroactivity and the discipline of <em>fixing the rule in public</em> before the work it will judge has been done.
                </p>
                <PaperRun title="Contribution.">
                    The contribution is a concrete, fixed allocation mechanism with three properties we develop in turn: (i) it scores clauses and assemblies by <em>substrate-broadening</em> &mdash; the number of distinct value-adders who carried them in settled processes &mdash; rather than by volume or value, and does so <em>uniformly</em> across every one of them, behind counting rules that close the cheap farming vectors; (ii) it resists Sybil manufacture not with a per-wallet cap or a weighting scheme but with a two-sided live stake in the chain&rsquo;s base currency, counting breadth in exactly the units that stake has priced, and we <em>derive</em> the resulting cost of fabricated score rather than asserting that fabrication is expensive; and (iii) it removes the verification problem rather than solving it, by counting adoption on chain as it happens instead of reconstructing it afterwards &mdash; which is what leaves the payout with no root to post, no bond to stake, no window to challenge, and no forum to adjudicate.
                </PaperRun>
                <PaperRun title="Paper organization.">
                    Section 2 states the allocation problem &mdash; what is allocated, to whom, and under what constraints. Section 3 develops the substrate-broadening objective. Section 4 states the counting rules that make the objective farming-resistant, including the seller-side stake gate and the minimum-support floor, and what the count deliberately refuses to interpret. Section 5 gives the scoring formula and the breadth-over-volume rationale. Section 6 develops the uniform reward and the two-sided stake that carries Sybil resistance. Section 7 derives the Sybil bound that stake buys, and states plainly what it does not buy. Section 8 develops the uniform pro-rata distribution and author eligibility. Section 9 develops the counting-as-it-happens construction and its trust model. Section 10 shows why reconstruction-based verification fails regardless of technique, working through two representative approaches within that branch. Section 11 states scope and limitations. Section 12 concludes.
                </PaperRun>
            </PaperSection>

            <PaperSection title="2. The Allocation Problem">
                <PaperRun title="What is allocated.">
                    The florin reserves 600 million units &mdash; 60% of its fixed supply &mdash; to fund clause authors and assembly designers. Accrual runs in nine annual periods, each with its own budget fixed at deployment. The budgets group into three rising tranches: 15% of the reserve across the first two years, 30% across the next three, and 55% across the last four, split equally within each group, so the nine annual slices are 45M, 45M, 60M, 60M, 60M, and then 82.5M four times over. The claim unit is the period, not the tranche &mdash; a wallet claims from one closed period&rsquo;s budget at a time, and the grouping is deployment data describing how the nine figures were chosen; the contracts themselves know only periods and their budgets.
                </PaperRun>
                <RpgfScheduleFigure idPrefix="substrate-broadening-rpgf-schedule" />
                <PaperRun title="Why the schedule rises.">
                    The budgets rise rather than front-load, and the reason is measurement. This mechanism pays on evidence, and the evidence is thinnest exactly when the network is youngest: in the first year the denominator every share is divided by is small, which makes it both the least informative reading of what was actually adopted and the most manipulable &mdash; a fixed quantity of fabricated score buys a far larger fraction of a small honest total than of a large one, a relation Section 7 makes quantitative. Putting the largest budgets where the measurement is best is what aligns the reserve with the thing it claims to measure, and it shrinks the worst case at precisely the moment the mechanism is least able to defend itself. Early, evidence-poor funding is not thereby abandoned; it is simply not this instrument&rsquo;s job. The separately-held treasury allocation exists to fund work by human judgment before the evidence exists, which is the right instrument for that job and the wrong one for this.
                </PaperRun>
                <PaperRun title="Why the period is a year.">
                    Periods are annual, and the length answers considerations that pull in opposite directions. Two argue for a short period. An author deciding whether the reward is worth pursuing has to price the lag between doing the work and being paid for it, and a multi-year lag is not priceable in a token that has no protocol-set price &mdash; the shorter the accrual period, the less of that unpriceable waiting the author is asked to absorb. And the accrual period is the denominator in the capital cost of a fabricated identity: a registration deposit can be asked back and re-posted under a fresh address, so the number of identities one unit of capital can furnish within a period is the period&rsquo;s length divided by the withdrawal cooldown, and shortening the period narrows that recycling window directly &mdash; up to the point where a cooldown as long as the period makes each fabricated identity cost the whole deposit (Section 7). One consideration argues the other way, and it is the same one that shapes the budget schedule: a period&rsquo;s accrual is the evidence that period is paid on, and a short period is a thin reading. The honest total that fabricated score has to dilute grows with the window it is measured over, so cutting the period cuts the denominator an adversary must overcome. A year is where the two meet &mdash; long enough that a period&rsquo;s accrual is a meaningful reading of what was adopted, short enough that a cooldown of a few weeks prices identity churn at a real fraction of the deposit. The period boundaries and the per-period budgets are one schedule, not two: the reward contract refuses to deploy unless it is handed exactly one budget per accrual period, so the two cannot drift apart, and no party can accelerate, delay, or resize any of it afterwards.
                </PaperRun>
                <PaperRun title="To whom.">
                    Allocation goes to authors and designers <em>of record</em> &mdash; the first-write-wins wallets that registered the clause or the assembly, for as long as the registration stake behind it stays live (the author-eligibility gate of Section 8). A clause&rsquo;s author of record is the wallet that first registered that identifier at that version &mdash; a further version is a separate registration, with its own author of record, its own stake, and its own adoption to accrue on; an assembly&rsquo;s designer of record is the wallet that first registered its composition. One resolved process credits its assembly&rsquo;s designer and, independently, the author of every clause the parties committed within it. There is no per-attestation, per-seller, or per-settlement reward path: a seller who attests heavily under someone else&rsquo;s clause earns nothing from RPGF, and a buyer who settles a thousand processes earns nothing from RPGF. The recipient set is exactly the set of clause authors and assembly designers with non-zero eligible adoption, determined by registry state, with no curation step.
                </PaperRun>
                <PaperRun title="Under what constraints.">
                    The mechanism operates under constraints inherited from the protocol&rsquo;s design discipline. It must introduce no governance surface (every governance parameter is an attack surface the protocol exists to avoid) and no human curation (which would reintroduce the discretionary authority the protocol displaces). It must resist gaming: because the recipient is decided by an objective formula over public data, the formula must not reward behavior that is cheap to manufacture and uncorrelated with genuine substrate growth. And it must be verifiable: a participant assessing the token should be able to confirm that each period&rsquo;s budget was allocated by the stated rule, not by an allocator&rsquo;s preference and not over inputs an allocator chose.
                </PaperRun>
                <PaperRemark title="Why not prospective or per-use funding.">
                    Two alternatives are deliberately excluded. <em>Prospective</em> funding &mdash; grants decided before the work by a body that predicts impact &mdash; reintroduces exactly the discretion this retroactive layer displaces. Prospective, discretionary funding is not thereby ruled out of the wider ecosystem: a separately-held treasury exists precisely to fund work by human judgment going forward, deciding what to fund rather than matching a crowd. But that is a distinct instrument for a distinct job, and the retroactive, formula-based allocation developed here, attached to the registered clause or assembly, is what this paper specifies. <em>Per-use</em> funding (a micro-payment on each attestation under a clause) couples issuance to a gameable per-event trigger, which invites wash-attestation to farm the reward and makes what is issued a function of manufactured activity rather than of demonstrated adoption. Retroactive, lump-sum, formula-based allocation avoids both failure modes: impact is observed, not predicted, and the reward attaches to the durable registration &mdash; the clause, the assembly &mdash; rather than to the gameable event (an attestation).
                </PaperRemark>
            </PaperSection>

            <PaperSection title="3. The Substrate-Broadening Objective">
                <p>
                    The schedule fixes how many florins each period distributes but not <em>which</em> authors receive them or in what proportion. That is decided by the objective the mechanism optimizes for, and the choice of objective is the substantive design decision. We call it <em>substrate-broadening</em>.
                </p>
                <p>
                    A clause or assembly broadens the protocol&rsquo;s substrate to the extent that it is adopted across genuinely distinct coordination relationships. The reachable surface of the protocol is not the number of times any single relationship transacts; it is the number of distinct relationships the protocol can express and secure. A clause that fifty unrelated sellers of record each adopt has extended the protocol into fifty value-adding practices that did not previously coordinate through it. A clause that one seller uses fifty times has deepened a single practice but not broadened the surface. Both are valuable; only the first is <em>substrate-broadening</em>, and that is the quantity the mechanism rewards.
                </p>
                <p>
                    An objective is only as good as the statistic that stands in for it, and here the choice of statistic is constrained by something outside the objective: breadth must be measured in units the mechanism can <em>price</em>, or the measurement is manufacturable and the objective is a wish. The unit is therefore the distinct <em>seller of record</em> &mdash; the value-adder on a settled process &mdash; each of whom holds a live deposit in the chain&rsquo;s base currency. Section 4 states the rule and why the counterparty <em>pair</em>, the intuitively obvious unit of a relationship, is the wrong one; Section 7 shows what the seller unit buys that no other choice does.
                </p>
                <PaperRun title="The settled-only principle.">
                    The objective is measured only over work that settled. A process contributes to a clause&rsquo;s or an assembly&rsquo;s score only once that process has resolved &mdash; the recording contract asks the settlement kernel for the order&rsquo;s status and refuses anything that is not resolved. A clause written into agreements that never reach resolution earns nothing; a clause or assembly with no settled adoption in a period receives zero by absence. This ties the reward to completed coordination rather than to declared intent, and it removes the cheapest gaming vector &mdash; manufacturing unsettled commitments to inflate a count &mdash; because an unsettled commitment cannot be recorded at all. Settlement is the first of the counting rules developed in Section 4.
                </PaperRun>
                <PaperRun title="Relation to quadratic funding.">
                    The diversity-over-volume principle has a direct antecedent in quadratic funding (Buterin, Hitzig, &amp; Weyl, 2019), where a public good&rsquo;s match weights the square of the summed square-roots of individual contributions &mdash; <Math>{"\\bigl(\\sum_i \\sqrt{c_i}\\bigr)^2"}</Math> &mdash; so that many small contributions outweigh few large ones and broad support outweighs concentrated support. Substrate-broadening applies the same intuition on a different axis: it rewards breadth of <em>adoption</em> (distinct staked sellers of record) over depth of use (repeated transactions), so that a clause embraced widely outscores one used intensively by few. The resemblance is one of intuition only. This mechanism is not quadratic funding, and the protocol operates no matching pool: there are no donors, no matched contributions, and no funded pool split by a crowd &mdash; the reward is a fixed reserve divided by observed adoption, and its exponents are not quadratic. What it borrows from that lineage is solely the commitment to weighting breadth above magnitude.
                </PaperRun>
            </PaperSection>

            <PaperSection title="4. The Counting Rules and Farming Resistance">
                <p>
                    Because the recipient is decided by an objective count, the count must not reward behavior that is cheap to manufacture and uncorrelated with genuine substrate growth. Six conditions govern what may be <em>recorded</em> at all, and they are not filters applied downstream by an aggregator: each is checked by the recording call itself against chain state before it will accept a record, so an ineligible record does not enter the accounting and then get removed &mdash; it never lands. Three further rules govern how the admitted records become a score: what breadth is counted in, how much support a clause or assembly needs before it scores anything, and how the two routes by which records arrive are scored against that requirement.
                </p>
                <p>
                    One property of the arrangement is worth stating before the rules, because every one of them depends on it: a record that lands is permanent. The counters, the score, and the period&rsquo;s running total move at the moment a record is admitted, and from then on they can only grow: records arriving one at a time increment them, and a proved batch rewrites them with cumulative figures that are refused outright if they fall below what is already stored. Either way there is no pass over history, no recomputation at period end, and no state anywhere that could retract or shrink a landed record. Every gate below is therefore a gate on the <em>moment of recording</em>, and the questions &ldquo;what must be true for a record to land&rdquo; and &ldquo;what happens to a landed record later&rdquo; have one answer between them: the first is checked, the second never arises.
                </p>
                <ul className="space-y-2 list-disc pl-6 text-sm">
                    <li><span className="font-semibold text-ink-heading">Settled only.</span> The record names an order, and the recording contract recomputes that order&rsquo;s hash from the signed commitment struct and asks the settlement kernel for its status. An unknown order is refused; an order that has not resolved is refused. Adoption is what a finished process leaves behind (Section 3).</li>
                    <li><span className="font-semibold text-ink-heading">Committed in the signed agreement.</span> The clause or assembly must be a committed leaf of the agreement hash the two parties signed, proved by Merkle inclusion against that hash, under the same leaf construction the protocol&rsquo;s attestation surface uses. Nobody can credit a clause or assembly to a process that did not use it, because the proof is checked against a digest neither party can restate after signing.</li>
                    <li><span className="font-semibold text-ink-heading">One process, one count.</span> A record names one order; the process that order belongs to counts once for the clause or assembly, once ever &mdash; not once per period, so a settlement counted in one period cannot be counted again when the next one opens. A repeat record is refused rather than absorbed, so nothing is gained by recording the same settlement twice, and the record may safely be attempted by anyone at any time. One consequence bounds what breadth can mean and is easier stated here than discovered later: because the process counts once for that clause or assembly, the seller credited for it is the seller of the order the record named, whichever of a multi-seller process&rsquo;s orders that happens to be. A process contributes one process to the count and at most one seller to the breadth, never several.</li>
                    <li><span className="font-semibold text-ink-heading">Seller staked.</span> The process counts only if its seller of record holds a live registration stake in the chain&rsquo;s base currency, which is what prices the seller identity. Asking for the deposit back de-surfaces the seller from the participant registry at the moment of the request rather than when the capital is finally released, and from that moment their settled trade confers no further reward &mdash; including trade that settled earlier in the period and had not yet been recorded. What was already recorded stands, by the permanence above. The practical consequence is a habit rather than a rule: recording belongs at settlement, when the seller is definitionally still staked. A seller who withdraws in order to deny some author a record must stay unstaked through the period&rsquo;s end to make it stick, forfeiting their own eligibility and leaving their capital locked for the cooldown while they do &mdash; which is why the mechanism carries the exposure rather than machinery against it. The buyer side is ungated, and deliberately: anyone may buy, and requiring a buyer to post capital before their purchase can count toward someone else&rsquo;s reward would tax the one role the protocol most wants unencumbered.
                    </li>
                    <li><span className="font-semibold text-ink-heading">Registration live.</span> The clause or assembly the record names must itself hold a live registration stake at that moment, and the recording call refuses the record otherwise. Without this gate a self-authored agreement could commit any thirty-two-byte key and accrue score to it at the cost of gas, inflating the shared denominator every honest author is paid out of. This is the author half of the two-sided stake applied at the moment of the record; Section 8 gives the other half of its application, at the claim.
                    </li>
                    <li><span className="font-semibold text-ink-heading">Not protocol floor.</span> Three registrations are excluded at deployment &mdash; the two clauses every order carries, and the provenance clause every assembly-composed process carries &mdash; and a record naming one of them is refused by the recording call exactly as an unstaked seller or a dead registration is. The exclusion is not a judgment of merit but of what the count would be measuring: those three ride every process by construction, so their counters would report how many processes settled rather than anyone&rsquo;s adoption. The provenance clause is the interesting case, since it is the very leaf through which an assembly&rsquo;s designer is credited (Section 9); it carries the credit and earns nothing for carrying it.
                    </li>
                    <li><span className="font-semibold text-ink-heading">Breadth counts distinct staked sellers.</span> A seller who carries the same clause or assembly repeatedly within a period adds to the process count each time and one unit of breadth once, so the exponents alone bound what repeating a single practice is worth. The unit matters more than the discount does. Breadth is counted in exactly the units the stake prices: one unit of it requires one live staked seller identity, and no arrangement of wallets returns more than one unit per identity &mdash; <Math>{"k"}</Math> identities yield <Math>{"k"}</Math> units and never more. What one such identity costs in capital is a separate question, answered in Section 7 from the deposit, the cooldown and the period length; the property established here is the absence of leverage, not the size of the price. Distinct (buyer, seller) <em>pairs</em> would be the intuitively obvious unit, but pairs cannot be priced at all: the buyer side holds no stake, so one staked seller trading with <Math>{"N"}</Math> fresh buyer wallets would manufacture <Math>{"N"}</Math> units of the score&rsquo;s dominant term at the cost of gas alone. Staking both sides does not repair it: <Math>{"k"}</Math> staked buyers trading with <Math>{"m"}</Math> staked sellers would mint <Math>{"k \\cdot m"}</Math> pairs out of <Math>{"k + m"}</Math> deposits, which is quadratic leverage on capital rather than none. Distinct staked sellers is the leverage-free statistic, and that leverage-freedom is precisely the property the bound of Section 7 rests on.
                    </li>
                    <li><span className="font-semibold text-ink-heading">Minimum support.</span> A clause or assembly scores nothing in a period until some floor number of distinct staked sellers &mdash; three, at the reference deployment &mdash; have carried it there. The floor withholds <em>scoring</em>, never counting: the counters accrue below it and the full score springs into existence the moment the third distinct staked seller lands, so nothing is lost, only deferred. What it filters is the thinnest and cheapest kind of entry, the registration that one or two identities stand behind &mdash; a shard split off an existing clause to multiply claims, a squatted identifier, a trivial rider committed alongside real work &mdash; and it filters them without reading a word of what any of them says. What the floor does not do is make such entries impossible, and this paper does not claim it does: three staked identities are three deposits and three settled processes, which is a price and not a barrier, and Section 7 quotes that price exactly, as the cheapest score the mechanism will recognize. The floor&rsquo;s work is to raise the price of the cheapest entry on the board from nothing to that figure, and to keep single-identity noise out of the denominator honest authors are paid from. The pricing itself is done by the stake, here as everywhere else in this mechanism.
                    </li>
                    <li><span className="font-semibold text-ink-heading">One floor per accrual route.</span> Records reach the counter by two routes &mdash; orders settled one at a time, and orders settled in proved batches &mdash; and the counter keeps a separate tally of <Math>{"(c, d)"}</Math> for each, scores each on its own, and sums the two scores. The floor accordingly applies to each route&rsquo;s own tally. The reason is that the counter holds counts and not the sets of sellers behind them, so it cannot take the union of the two routes&rsquo; sellers without risking counting one seller twice. Flooring each route on its own can only under-pay a clause or assembly whose support is genuinely split across both; it can never let one seller straddle the two and count twice toward the floor. Safety in the direction that under-pays is the deliberate choice, and it is the same choice the score summation makes.
                    </li>
                </ul>
                <PaperRun title="What the count refuses to interpret.">
                    What the rules check is deliberately shallow: every one is decided by comparing two hashes, reading one status word, reading one stake flag, or comparing one counter against a fixed threshold, so no participant has to agree with a curator about what a clause <em>means</em> in order to agree about what it scored. The count reads no clause or assembly content and consults no approval list; the minimum-support floor is no exception, since it asks how many staked sellers stood behind a registration and nothing whatever about what it says. Two structural exclusions are the only refinements, and both are rules already stated above rather than interpretations laid over them: the three protocol-floor registrations earn nothing, their counters reporting how many processes settled rather than any author&rsquo;s adoption; and a clause or assembly earns only while the registration stake behind it stays live, checked when a record lands and again at the claim (Section 8). Neither is a judgment of merit, and neither reads a word of content. The consequence is that a clause or assembly carried by many settled processes and many staked sellers scores for that fact alone. Where it is genuine substrate &mdash; a clause a hundred unrelated sellers chose to adopt &mdash; a large score is the intended outcome, and the uniform rule pays it without apology. Where it is mere protocol plumbing that every order carries by construction, it is one of the excluded floor clauses above and scores nothing. There is no third case in between for a cap to bound (Section 8).
                </PaperRun>
                <PaperRun title="Recording is permissionless and opt-in.">
                    Anyone may record; nothing is trusted about the caller, because the proof is what is checked. In practice the party who records is the party with the incentive &mdash; the author or designer, for whom the record is how the work is counted &mdash; and the gas is theirs. An unrecorded settlement simply does not count. The evidence is not lost &mdash; the signed agreement and the resolution stay on chain &mdash; but a record lands in whichever period is open when it is made, and once a period has ended nothing can be added to it. Recording therefore has to be current, and the cost of being current is paid by the party it benefits rather than by the network.
                </PaperRun>
            </PaperSection>

            <PaperSection title="5. The Scoring Formula">
                <p>
                    Each clause and each assembly carries, per period, two counters and the score they determine. The counters move as records land; the score is recomputed on the spot and the period&rsquo;s running total moves by the difference, so no pass over history is ever required:
                </p>
                <div className="my-3 overflow-x-auto">
                    <Math display>{"\\text{score}(a) \\;=\\; \\begin{cases} c(a)^{\\,1/3}\\;\\cdot\\; d(a)^{\\,2/3}, & d(a) \\;\\ge\\; d_{\\min},\\\\[4pt] 0, & \\text{otherwise.}\\end{cases}"}</Math>
                </div>
                <ul className="space-y-1 list-disc pl-6 text-sm">
                    <li><Math>{"c(a)"}</Math> &mdash; the number of distinct settled <em>processes</em> recorded against a clause or assembly <Math>{"a"}</Math> in the period.</li>
                    <li><Math>{"d(a)"}</Math> &mdash; the number of distinct live-staked <em>sellers of record</em> across those processes: one per counted process, being the seller of the order that record named, and each such seller counted once however often they trade within the period (Section 4).</li>
                    <li><Math>{"d_{\\min}"}</Math> &mdash; the minimum-support floor, three at the reference deployment, applied to each accrual route&rsquo;s own tally (Section 4).</li>
                </ul>
                <p>
                    There is no weight term. Every clause and every assembly is scored by the same function of its own two counters &mdash; no tag, category, or authored identity multiplies it &mdash; so the reward is uniform across the whole substrate and privileges no class of work. Section 6 develops why that uniformity is the design choice and where Sybil resistance goes once no weight and no cap carry it.
                </p>
                <p>
                    A clause or assembly with zero processes, or with fewer than <Math>{"d_{\\min}"}</Math> distinct staked sellers, scores zero. Above the floor the exponents do the work, and they are constitutive of the mechanism rather than settings within it: breadth carries <Math>{"\\tfrac23"}</Math> and volume <Math>{"\\tfrac13"}</Math>, in that ratio, for every clause and every assembly, fixed at deployment. What that arrangement <em>achieves</em> is what the paper can state. The number of distinct value-adders dominates the raw process count: holding the product <Math>{"c \\cdot d"}</Math> fixed, a clause or assembly scores higher the more its activity is spread across distinct sellers rather than concentrated in repeated processes carried by the same one. The achievement is easiest to read in the equivalent form <Math>{"\\text{score} = d \\cdot (c/d)^{1/3}"}</Math>: a clause or assembly scores its distinct staked sellers, multiplied by its average repeat depth under a cube root. The volume exponent is therefore precisely the elasticity of reward to repeat depth &mdash; eight times the depth earns twice the score &mdash; and where every staked seller carries exactly one process (<Math>{"c = d"}</Math>) the score is that seller count itself. The reading behind it is that a new adopter is more informative about substrate growth than another observation of a known one, repeat observations having diminishing informational returns; that reading is a judgment about adoption, offered as one, and it is the whole of what the exponents encode. We note for completeness that they are not offered as a Sybil defense, and cannot be one: no scoring function can distinguish a fabricated seller identity from a genuine one, since any concavity that dampens the former dampens the latter identically. Resistance is located in the cost of an identity (Sections 6 and 7) &mdash; which is exactly why the statistic sitting under the dominant exponent had to be one the stake prices.
                </p>
                <PaperRun title="Integer arithmetic throughout.">
                    The score is computed with integer arithmetic and no floating point anywhere. The integer form is <Math>{"\\lfloor\\sqrt[3]{\\,c\\,d^{2}\\cdot 10^{18}}\\,\\rfloor"}</Math> above the floor and zero below it, a floor integer cube root taken over a fixed-point scale large enough that the flooring error is negligible. The scale factor is what lets a monotone quantity be maintained exactly: the score is stored, and when a record moves <Math>{"c"}</Math> or <Math>{"d"}</Math>, the period&rsquo;s total moves by the new score less the stored one. There is no accumulated drift to reconcile, and an off-chain reader mirroring the same integer operations obtains the identical number rather than an approximation of it. The scale multiplies every clause&rsquo;s and every assembly&rsquo;s score by the same constant, so it cancels out of every share and every ratio the mechanism forms; where Section 7 reasons about score it works in the unscaled quantity <Math>{"(c\\,d^{2})^{1/3}"}</Math>, and a unit price quoted there is a price per unit of that quantity.
                </PaperRun>
                <PaperRun title="Value is deliberately excluded.">
                    Neither payment nor bond size enters the formula. The protocol&rsquo;s cost to move one unit of value equals its cost to move a trillion; a clause that broadens coordination across many small settlements has done the same substrate work as one used in a few large ones. Weighting by value would import a &ldquo;total value locked matters&rdquo; metric from financial protocols that the coordination layer rejects &mdash; and it would skew the reward toward whoever authors the clauses that high-value transactions happen to use, which is uncorrelated with how broadly a clause extends the substrate. The omission is principled, not an oversight.
                </PaperRun>
            </PaperSection>

            <PaperSection title="6. Uniform Reward and the Two-Sided Stake">
                <p>
                    The score of Section 5 has no weight term: every clause and every assembly is scored by the same function of its own adoption, and no tag, category, or authored identity multiplies it. This section develops why that uniformity is the design choice, and where Sybil resistance goes once neither a weight nor a cap is available to carry it.
                </p>
                <PaperRun title="Why the reward is uniform.">
                    A weighting scheme &mdash; paying more for the category of work the substrate is judged to need most &mdash; requires the mechanism to make and keep current a standing judgment about which category that is. That judgment is a curatorial act wearing an arithmetic disguise: it privileges a class of work in advance of the evidence, it must be defended against every author whose equally-real work it pays less, and it is exactly the discretion the rest of the mechanism exists to refuse. Uniformity declines to make it. The substrate is broadened not by the mechanism deciding which coordination matters and subsidizing it, but by rewarding every kind of real, settled, breadth-spanning adoption on the same terms, and letting the record of what participants actually adopted &mdash; not a designer&rsquo;s prior about what they should &mdash; determine the split. Every clause&rsquo;s and every assembly&rsquo;s score is its own usage alone, and the neutrality that principle buys is the same neutrality the kernel holds: the mechanism takes no position on which work is worth doing.
                </PaperRun>
                <PaperRun title="Where Sybil resistance goes: the two-sided live stake.">
                    Without a weight to tune or a cap to bind, the score is a direct, uniform function of two counts, and the question is what stops those counts being manufactured. The answer is a stake, in the chain&rsquo;s base currency, required live on both sides of a countable event. <em>Seller side</em> (Section 4): a settled process counts only if its seller of record holds a live registration stake when the record lands, and because breadth itself is counted in distinct such sellers, this single gate prices the score&rsquo;s dominant term directly &mdash; one live staked identity per unit of breadth, with no wallet arrangement that turns capital into leverage. <em>Author side</em> (Sections 4 and 8): the clause or assembly must hold a live registration stake for a record naming it to land at all, and its author must still hold that stake when the closed period is claimed &mdash; so an author cannot register, farm a reward, and withdraw the capital that was supposed to make the registration costly.
                    The two gates read at different moments, and the difference is the whole of the withdrawal model. A landed record is permanent, so the seller&rsquo;s stake governs what may still be recorded and nothing else: a seller who asks for the deposit back stops conferring reward from the moment of the request &mdash; on trade that has settled but not yet been recorded as much as on trade to come &mdash; while what was recorded while they were staked stands. The author&rsquo;s stake is read twice, at each record and again at the claim, so withdrawing before the claim forfeits the whole period, including adoption already counted. Neither side is a per-transaction fee and neither is refunded by the reward. What the arrangement is worth against a determined adversary is a number, not a posture, and Section 7 derives it.
                </PaperRun>
                <PaperRun title="The stake is alignment, not a cost.">
                    The natural reading of a required stake is a cost to be minimized, but that reading misses what the denomination does. The stake is posted in the chain&rsquo;s base currency &mdash; the unit in which gas is paid &mdash; and demand for that unit rises with the very trade the substrate carries: more settled processes mean more transactions, and more transactions mean more base-currency demand to fuel them. A contributor who stakes is therefore holding exposure to the growth their own work helps produce, not paying a fee into a void. The two units the mechanism touches are divided by <em>function</em>, and are not a matched pair of protocol denominations. The reward is minted in the florin, from the fixed reserve, to whoever broadened the substrate; the stake is posted in the chain&rsquo;s base currency, by every registrant, in the asset whose demand their collective trade drives. Only one of the two is fixed by a protocol operation, and it is the base currency: gas is paid in it, and so are the registration deposits both halves of the stake consist of &mdash; the seller&rsquo;s in the participant registry, the author&rsquo;s in the clause and assembly registries. The coupling between settlement and the florin runs one way only, and the direction is the whole of the point. No settlement operation mints, consults, or denominates in the florin: a process settles in whatever fungible token its parties chose, and while parties are free to choose the florin as that token, nothing in the settlement layer prefers, requires, or rewards it if they do. The distribution layer plainly does mint florins &mdash; that is what it is for &mdash; and it mints them by reading what settlement has already recorded. Nothing it does reaches back the other way: no bond, no payout, and no party&rsquo;s position in an open process turns on anything this mechanism counts, scores, or pays. A reward that could move a bonded position would be a party to the settlement equilibrium rather than a reader of its record, and this one is a reader. The design goal is growth-alignment, not a Sybil-deterrence arms race &mdash; the stake makes honest contribution the position a rational participant already wants to hold.
                </PaperRun>
                <PaperRemark title="What the stake does and does not deter.">
                    Base-currency appreciation, if it comes, aligns everyone who stakes &mdash; including a Sybil free-riding on others&rsquo; genuine growth &mdash; so it aligns the honest majority rather than deterring the adversary. We do not overstate it. The anti-Sybil bite is narrower and concrete, and it is structural rather than motivational: reward accrues only while the stake stays live, so a farm cannot register, farm, and withdraw; the base fee burned on every transaction is a real, non-recoverable per-trade cost in the base currency that scales with fabricated volume; and the reserve is a fixed pool a farmer <em>dilutes</em> rather than inflates, so fabricated adoption competes for a share it cannot enlarge. Those are qualitative statements, and on their own they would be a posture rather than a design. The next section turns them into a price.
                </PaperRemark>
            </PaperSection>

            <PaperSection title="7. The Sybil Bound">
                <p>
                    A mechanism that pays out real value on a public count owes its readers a price list. It is not enough to say that fabricating adoption costs something; the question a participant assessing the token actually has is <em>how much</em>, in what units, and how that cost grows with the share of the reserve an adversary is trying to take. This section answers all three. The setting is the classical one Douceur (2002) named: identities are free to create in an open system, so any mechanism that counts them must either tie an identity to a scarce resource or accept that its count can be manufactured. This mechanism takes the first branch, and what follows works out the exchange rate between that scarce resource and the reward. The result rests on one structural property established in Section 4 &mdash; that breadth is counted in distinct staked sellers, so a unit of the score&rsquo;s dominant term costs a deposit and never less &mdash; and on nothing about the florin&rsquo;s price, which the design deliberately does not set.
                </p>
                <PaperSubsection title="7.1 The two costs an adversary faces">
                    <p>
                        Write <Math>{"D"}</Math> for the registration deposit a seller of record must post, <Math>{"T"}</Math> for the cooldown between requesting that deposit back and being able to claim it, and <Math>{"P"}</Math> for the length of an accrual period. Eligibility ends at the <em>request</em>, not at the release, so an adversary can run one unit of capital through a sequence of identities within a period: register a fresh address, settle and record with it, request the deposit, wait out the cooldown, register the next. The number of identities one deposit can furnish in a period is therefore bounded by <Math>{"\\lceil P/T \\rceil"}</Math>, and the capital cost of holding one fabricated staked-seller identity for one period is
                    </p>
                    <div className="my-3 overflow-x-auto">
                        <Math display>{"\\delta \\;=\\; \\frac{D}{\\lceil P/T \\rceil} \\;\\approx\\; D\\,\\frac{T}{P}\\,, \\qquad \\text{saturating at } \\delta = D \\text{ once } T \\ge P."}</Math>
                    </div>
                    <p>
                        Two readings follow immediately. A cooldown of zero makes <Math>{"\\delta"}</Math> vanish and the deposit prices nothing at all, because a single unit of capital serves unboundedly many identities in sequence; and a cooldown at or above one accrual period makes each fabricated identity cost the full deposit, which is the strongest the parameter pair can be. The deposit and the cooldown are one price, never two, and neither is meaningful alone.
                    </p>
                    <p>
                        Write <Math>{"g"}</Math> for the marginal cost of one fabricated settled process: the gas of its commit and resolve legs on the cheapest settlement route available, plus the calldata of the usage record and the counter&rsquo;s marginal write. This is a measured constant of a given deployment, not a modelling assumption, and it belongs beside <Math>{"D"}</Math> and <Math>{"T"}</Math> in the published parameters &mdash; the batched route moves it by better than an order of magnitude relative to settling one order at a time, which is exactly why it must be measured on the route the adversary would actually use rather than assumed. We credit the adversary with nothing else: a fabricated process must also lock and unlock bonds and clear the protocol&rsquo;s non-zero payment floor, and we do not count the time-value of that capital. The bound is conservative in the adversary&rsquo;s favour.
                    </p>
                    <p>
                        Four constants and one measurement are what a reader needs, and each is published: the seller-side registration deposit <Math>{"D"}</Math> and the withdrawal cooldown <Math>{"T"}</Math>, which together price a fabricated seller identity; the accrual-period length <Math>{"P"}</Math> over which that identity must be held; the author-side registration deposit, which prices an authored registration and appears in Section 7.3; and the measured <Math>{"g"}</Math>. Nothing else enters what follows &mdash; in particular no florin price does, and Section 7.3 says why the mechanism could not honestly use one.
                    </p>
                </PaperSubsection>
                <PaperSubsection title="7.2 The cost of fabricated score">
                    <p>
                        Consider an adversary who wants score <Math>{"s"}</Math> on a clause they author, and who is free to choose how much of it to buy with identities and how much with volume. With <Math>{"n"}</Math> fabricated staked sellers and <Math>{"c"}</Math> fabricated settled processes, the score is <Math>{"s = (c\\,n^{2})^{1/3}"}</Math>. Every seller needs at least one process, so <Math>{"c \\ge n"}</Math>, and the minimum-support floor requires <Math>{"n \\ge d_{\\min}"}</Math>. The adversary&rsquo;s problem is
                    </p>
                    <div className="my-3 overflow-x-auto">
                        <Math display>{"\\min_{n,\\,c}\\;\\; C \\;=\\; n\\,\\delta \\;+\\; c\\,g \\qquad \\text{subject to} \\qquad (c\\,n^{2})^{1/3} = s, \\quad c \\ge n \\ge d_{\\min}."}</Math>
                    </div>
                    <FormalBlock label="Proposition (Unit price of fabricated score).">
                        <p>
                            For <Math>{"s \\ge s_{0}"}</Math>, where <Math>{"s_{0} = d_{\\min}\\max\\{1,\\,(\\delta/2g)^{1/3}\\}"}</Math>, the minimum cost of fabricating score <Math>{"s"}</Math> is <Math>{"C^{*}(s) = \\gamma \\, s"}</Math>, where
                        </p>
                        <div className="my-3 overflow-x-auto">
                            <Math display>{"\\gamma \\;=\\; \\begin{cases} \\delta + g, & \\delta \\le 2g,\\\\[4pt] 3\\cdot 2^{-2/3}\\,\\delta^{2/3}g^{1/3} \\;\\approx\\; 1.89\\,\\delta^{2/3}g^{1/3}, & \\delta > 2g.\\end{cases}"}</Math>
                        </div>
                        <p>
                            The cost of fabricated score is <em>linear in the score fabricated</em> in both regimes, and the two expressions agree at <Math>{"\\delta = 2g"}</Math>, where both equal <Math>{"3g"}</Math>.
                        </p>
                    </FormalBlock>
                    <Proof>
                        Relax <Math>{"c \\ge n"}</Math> and substitute the score constraint <Math>{"c = s^{3}/n^{2}"}</Math>, giving <Math>{"C(n) = n\\delta + g\\,s^{3}/n^{2}"}</Math>. This is strictly convex on <Math>{"n > 0"}</Math>, and <Math>{"C'(n) = \\delta - 2g\\,s^{3}/n^{3} = 0"}</Math> yields the interior optimum <Math>{"n^{*} = s\\,(2g/\\delta)^{1/3}"}</Math>, hence <Math>{"c^{*} = s\\,(\\delta/2g)^{2/3}"}</Math>. Feasibility of the relaxed optimum requires <Math>{"c^{*} \\ge n^{*}"}</Math>, i.e. <Math>{"(\\delta/2g)^{2/3} \\ge (2g/\\delta)^{1/3}"}</Math>, which holds exactly when <Math>{"\\delta \\ge 2g"}</Math>. In that regime, substituting back gives <Math>{"C^{*} = s\\,\\delta^{2/3}\\bigl[(2g)^{1/3} + g\\,(2g)^{-2/3}\\bigr] = s\\,\\delta^{2/3}g^{1/3}\\,2^{-2/3}(2+1) = 3\\cdot 2^{-2/3}\\,\\delta^{2/3}g^{1/3}\\,s"}</Math>. When <Math>{"\\delta < 2g"}</Math> the relaxed optimum violates <Math>{"c \\ge n"}</Math>. Along the constraint curve <Math>{"c(n) = s^{3}/n^{2}"}</Math>, feasibility <Math>{"c \\ge n"}</Math> is exactly <Math>{"n \\le s"}</Math>, and <Math>{"n^{*} > s"}</Math> in this regime, so <Math>{"C"}</Math> is strictly decreasing across the whole feasible interval and the minimum sits at its right endpoint <Math>{"n = c = s"}</Math>, giving <Math>{"C^{*} = (\\delta + g)\\,s"}</Math>. At <Math>{"\\delta = 2g"}</Math> the corner and interior solutions coincide at <Math>{"n = c = s"}</Math> and both expressions give <Math>{"3g\\,s"}</Math>, so <Math>{"\\gamma"}</Math> is continuous. Neither branch depends on <Math>{"s"}</Math>, so <Math>{"C^{*}"}</Math> is exactly linear in <Math>{"s"}</Math> in each. Finally, the optimizing <Math>{"n"}</Math> in each branch is <Math>{"s"}</Math> and <Math>{"s(2g/\\delta)^{1/3}"}</Math> respectively, and requiring it to satisfy the floor <Math>{"n \\ge d_{\\min}"}</Math> is exactly <Math>{"s \\ge s_{0}"}</Math>. <Math>{"\\square"}</Math>
                    </Proof>
                    <p>
                        The two regimes have a plain reading. When identities are cheap relative to trade (<Math>{"\\delta \\le 2g"}</Math>), the adversary buys pure breadth: one fabricated process per fabricated seller, never repeating, because under the cube root a second process from the same seller is worth less than a first process from a new one. When identities are expensive (<Math>{"\\delta > 2g"}</Math>), gas-bought volume starts substituting for them, and the adversary runs <Math>{"(\\delta/2g)^{2/3}"}</Math> processes per identity. Below the threshold <Math>{"s_{0}"}</Math> the minimum-support floor binds before either optimum is reachable: the adversary must post <Math>{"d_{\\min}"}</Math> deposits whether the score they want needs them or not, so small fabricated scores cost strictly more than <Math>{"\\gamma s"}</Math>. That is the floor doing precisely the work it was put there to do, and it is why the linear regime is the conservative one to quote.
                    </p>
                    <PaperRemark title="Linearity is the property, and it is what the pair statistic destroyed.">
                        The result worth holding is not the constant but the shape: <Math>{"C^{*}"}</Math> is linear in <Math>{"s"}</Math>, so fabricated score has a flat unit price and there is no scale at which the adversary&rsquo;s capital buys more than proportionally. That property is a direct consequence of counting breadth in units the stake prices. Under distinct (buyer, seller) pairs it fails outright: one staked seller and <Math>{"N"}</Math> free buyer wallets produce <Math>{"N"}</Math> units of the dominant term from a single deposit, so <Math>{"C^{*}"}</Math> would be bounded above by a constant in <Math>{"\\delta"}</Math> however large the fabricated score, and no choice of deposit or cooldown could repair it. Pricing both sides does not repair it either, only softens it: <Math>{"k"}</Math> staked buyers and <Math>{"m"}</Math> staked sellers mint <Math>{"k \\cdot m"}</Math> pairs from <Math>{"k+m"}</Math> deposits, which is a quadratic return on capital. Distinct staked sellers is the statistic for which the return on capital is exactly one for one, and that is the whole of the case for it.
                    </PaperRemark>
                    <PaperRemark title="An honesty note on the deposit.">
                        Raising the deposit does not raise the adversary&rsquo;s cost indefinitely. Once <Math>{"\\delta"}</Math> passes <Math>{"2g"}</Math>, <Math>{"\\gamma"}</Math> grows only as <Math>{"\\delta^{2/3}"}</Math>, because volume bought with gas substitutes for identities under the cube root: doubling the deposit past that point buys about a 59% increase in the adversary&rsquo;s unit cost, not a doubling. The deposit is a diminishing-returns quantity and the paper says so plainly. Two consequences follow for anyone reading the deployed values. The cooldown is the more powerful of the pair below saturation, since <Math>{"\\delta"}</Math> is linear in <Math>{"T/P"}</Math> until it saturates at <Math>{"D"}</Math>; and there is no deposit large enough to substitute for the requirement that <Math>{"g"}</Math> be measured on the cheapest settlement route actually available, since it is <Math>{"g"}</Math> that sets the floor the deposit is working against. What the deposit cannot do is make fabrication impossible, and no honest reading of this arithmetic should suggest otherwise; what it does is set a published, checkable price.
                    </PaperRemark>
                </PaperSubsection>
                <PaperSubsection title="7.3 Dilution: what capital buys of a period&rsquo;s budget">
                    <p>
                        Score is not paid in absolute terms; a wallet receives its score over the period&rsquo;s total. So the adversary&rsquo;s real objective is a <em>share</em>. Let <Math>{"S_h"}</Math> be the honest score accrued in the period &mdash; everything genuine adopters recorded &mdash; and let the adversary want a fraction <Math>{"\\varphi \\in (0,1)"}</Math> of that period&rsquo;s budget. Since the mechanism is uniform pro rata, the adversary&rsquo;s own score enters the denominator too, so they need <Math>{"s_A"}</Math> with <Math>{"s_A/(s_A + S_h) = \\varphi"}</Math>, that is <Math>{"s_A = S_h\\,\\varphi/(1-\\varphi)"}</Math>. Combining with the Proposition:
                    </p>
                    <div className="my-3 overflow-x-auto">
                        <Math display>{"C(\\varphi) \\;=\\; \\gamma\\,S_h\\,\\frac{\\varphi}{1-\\varphi}\\,, \\qquad \\frac{dC}{d\\varphi} \\;=\\; \\frac{\\gamma\\,S_h}{(1-\\varphi)^{2}} \\;>\\; 0."}</Math>
                    </div>
                    <p>
                        The curve is convex and unbounded as <Math>{"\\varphi \\to 1"}</Math>. Three things follow, and they are the substantive security statement of the mechanism. First, honest authors always retain a positive share: no finite capital captures the whole of a period, because the last increment of share costs without limit. Second, the marginal cost of share <em>rises</em> with the share already taken, so an adversary who has diluted honest authors by a tenth pays about 23% more for the next increment than they paid for the first, and one who has taken half pays four times as much &mdash; capture gets harder as it proceeds, which is the opposite of the usual dynamic in a pool that can be drained. Third, the whole statement is denominated in <em>capital committed per unit of dilution achieved</em>, and deliberately not in profit. This mechanism sets no price for the florin and can read none from anything it touches, so any claim of the form &ldquo;the attack is unprofitable below such-and-such a stake&rdquo; would be smuggling in a price forecast this paper has no basis to make. What the mechanism can honestly publish is the cost side, exactly, and let a reader supply their own view of the other side.
                    </p>
                    <PaperRun title="The minimum viable attack, and where the worst case sits.">
                        The floor gives the curve a starting point, and the point is a price rather than a prohibition. A clause or assembly scores zero until <Math>{"d_{\\min}"}</Math> distinct staked sellers have carried it, so the cheapest attack that puts any score on the board at all costs <Math>{"d_{\\min}(\\delta + g)"}</Math> &mdash; three identity-periods and three settled processes at the reference floor &mdash; and buys the smallest score the mechanism will recognize. One actor can pay that, and the paper says so rather than claiming the floor excludes them; what the floor does is set the entry price and keep one- and two-identity noise out of the denominator. The worst case for the mechanism as a whole is the first annual period, where <Math>{"S_h"}</Math> is smallest and each unit of fabricated score therefore buys the largest <Math>{"\\varphi"}</Math>. That is what the rising budget schedule (Section 2) answers: the first period disposes of 7.5% of the reserve &mdash; the smallest slice the schedule ever pays, shared with the second year alone, and barely more than two-thirds of what an equal division across the nine would place there &mdash; while each of the last four disposes of 13.75%. So the period in which a unit of fabricated score buys the largest share is also the period in which the least is at stake, and the largest budgets sit where the denominators are thickest. That alignment is a security property of the schedule, obtained without changing a single counting rule.
                    </PaperRun>
                    <PaperRun title="What the bound prices, and what it does not.">
                        The Proposition prices score on a <em>single</em> registration. An adversary who registers several clauses of their own and commits all of them into the same fabricated agreements replicates that score across each of them: the identity and settlement costs are shared, while each replicate costs its own author-side registration deposit &mdash; which, unlike a seller&rsquo;s, cannot be recycled at all, since a registration binds permanently and its stake must stay live for the clause to earn anything &mdash; plus one further record per process. We state the per-registration bound as the sharp one and do not claim it as a bound over an adversary&rsquo;s whole portfolio of authored clauses and assemblies; the author-side deposit is what prices replication, and it is a parameter chosen at deployment like the others. Nor does the bound price collusion between genuine participants, who are not fabricating identities at all: an adversary who persuades many real staked sellers to carry a junk clause alongside their real work has bought breadth at the price of persuasion, and no counting rule that reads only chain state can tell that apart from adoption. The mechanism&rsquo;s answer to that case is the uniform rule itself &mdash; such a clause is scored on what it demonstrably carried, like every other.
                    </PaperRun>
                </PaperSubsection>
                <PaperSubsection title="7.4 What a reader can recompute, and what the price does not buy">
                    <p>
                        The two deposits, the cooldown and the accrual-period length are deploy-time constants, immutable once chosen, and together with the measured <Math>{"g"}</Math> they pick the point the mechanism occupies on the <Math>{"C(\\varphi)"}</Math> curve. Publishing them alongside the formula for <Math>{"\\gamma"}</Math> is what makes &ldquo;how was the stake sized?&rdquo; a question with an arithmetic answer rather than an appeal to judgment: a reader takes the constants from the deployed contracts, computes <Math>{"\\delta"}</Math> and <Math>{"\\gamma"}</Math>, forms their own estimate of <Math>{"S_h"}</Math> from the period&rsquo;s public accrual, and reads the capital cost of any dilution they care to consider straight off the curve. That is the whole of the sizing argument, and it is checkable by anyone.
                    </p>
                    <p>
                        What that price does not buy is impossibility, and no reading of the arithmetic should suggest otherwise. Above <Math>{"\\delta = 2g"}</Math> the unit cost grows only as <Math>{"\\delta^{2/3}"}</Math>, so the deposit is a diminishing-returns quantity; the floor sets a minimum entry price rather than an exclusion; and the convexity of <Math>{"C(\\varphi)"}</Math> leaves every share short of the whole purchasable at some finite figure. What the mechanism does hold against fabricated adoption is four things at once, each of them structural: the fabrication costs published, recomputable capital per unit of score; that capital must stay committed while the reward it gates is being earned, on both sides and by different clocks; the reserve it competes for is fixed, so a fabricator dilutes a pool it cannot enlarge; and every recording transaction burns a real, non-recoverable base-currency fee, whoever sends it, which is the one cost that scales with fabricated volume and is paid to nobody. Recording pays no entity and asks no one&rsquo;s permission; there is no toll on it and no institution behind it. Those are the terms, and they are stated as terms rather than as reassurance.
                    </p>
                </PaperSubsection>
            </PaperSection>

            <PaperSection title="8. Uniform Pro-Rata Distribution and Author Eligibility">
                <p>
                    A wallet claims a period once, presenting every clause it authored and every assembly it designed in that single call. Each is checked against its own registry &mdash; the clause registry for a clause&rsquo;s author of record, the assembly registry for an assembly&rsquo;s designer of record &mdash; so the list a claimant supplies is a lookup key, never an assertion of ownership. Their scores for the period are summed, and clauses and assemblies merge into one per-wallet quantity. The wallet&rsquo;s share of that period&rsquo;s budget is that quantity over the period&rsquo;s total score, minted straight, with no per-wallet ceiling.
                </p>
                <PaperRun title="Author eligibility: the stake must be live.">
                    A registry check is not merely a lookup of who registered first; it is a check that the registration stake behind the clause or assembly is still <em>live</em>. An author earns for a clause, and a designer for an assembly, only while the base-currency deposit posted at its registration remains un-withdrawn &mdash; and the check runs at both ends: no record naming the registration will land once the deposit is gone (Section 4), and a period claimed after the withdrawal pays nothing at all, including for adoption counted while the stake was live. What is forfeited is not redistributed. The score stays where it accrued, in the period&rsquo;s total, so the share a withdrawing author gives up simply goes unminted, exactly as flooring dust does. This is the author half of the two-sided stake of Section 6, and it closes the register-farm-withdraw path: the capital that makes a registration costly cannot be recovered while the registration still earns. It is also what prices the replication of a fabricated score across several authored clauses (Section 7), since a registration key binds permanently and its deposit may be withdrawn exactly once &mdash; nothing can be re-posted against the same registration, so each replicate costs fresh capital rather than the same capital cycled. Because that stake is exposure to the network&rsquo;s growth rather than a fee, keeping it live is the honest author&rsquo;s default, not a sacrifice the mechanism extracts.
                </PaperRun>
                <PaperRun title="Why there is no cap.">
                    The mechanism places no ceiling on any wallet&rsquo;s share of the payout. A cap clamping each wallet&rsquo;s share at a fixed fraction would defend against a concentration the two-sided stake already prices: a wallet reaches a large share only by carrying a large amount of real, settled, breadth-spanning adoption across live-staked sellers, and fabricating that adoption costs one base-currency deposit per unit of breadth against a fixed reserve it can only dilute &mdash; at the published unit price of Section 7. A cap would add nothing that structure does not already supply, while introducing an arbitrary fraction to defend and leaving the clamped remainder permanently unminted. Uniform pro rata tracks real usage directly: a wallet that genuinely broadened the substrate the most receives the most, which is the outcome the mechanism is for. Integer flooring dust still stays unminted &mdash; a period&rsquo;s budget is a ceiling, not a target, and no mechanism exists, or could be added later, to sweep what a period does not mint.
                </PaperRun>
                <p>
                    Nothing anywhere in this procedure requires knowing who else is claiming. The denominator is a number the counting contract already holds and can no longer change; the numerator is the claimant&rsquo;s own live-staked clauses and assemblies. That is the whole of the allocation.
                </p>
            </PaperSection>

            <PaperSection title="9. Counting Adoption as It Happens">
                <p>
                    Everything above describes an arithmetic. This section describes why that arithmetic can be trusted, and the answer is not that it is proved or challenged or adjudicated: it is that no one ever states it. The mechanism&rsquo;s design problem was never how to check an allocator&rsquo;s claim. It was how to avoid needing an allocator&rsquo;s claim at all.
                </p>
                <PaperRun title="The chain cannot look backwards.">
                    Three properties of the substrate combine into one hard constraint. The settlement kernel is frozen &mdash; it will never be modified to notify anything. It never calls the clause and assembly registries, and must not: coupling settlement to a registry would make the registries load-bearing for trade. And no contract can read an event, because logs are an interface for observers outside the machine, not state inside it. So at the moment a process settles, the fact that it used a particular clause is a fact the chain has recorded and cannot subsequently consult. Any mechanism that wants to pay for adoption must therefore either reconstruct that fact after the event, or capture it at the event. Everything else about the two designs follows from that fork.
                </PaperRun>
                <PaperRun title="Reconstruction forces a chain of consequences.">
                    Take the first branch and the cascade is forced, link by link. Reconstruction happens off chain, since the chain cannot do it; so the answer must be brought back on chain, which means somebody <em>posts</em> it. A posting is an unverified claim about the past, so it must be made costly, which means a <em>bond</em>. A bond is only a deterrent if a false posting can be attacked, which means a <em>challenge</em>. A challenge stakes capital on both sides, and something must decide who keeps it, which means a <em>forum</em> &mdash; and now the allocation mechanism has acquired a dispute layer, an escalation path, a concession deadline, and an outside adjudicator that has to be composed, funded, and trusted to rule. None of that apparatus funds a single public good. All of it exists to make the chain believe a claim about the past.
                </PaperRun>
                <PaperRun title="Capture removes the claim.">
                    Take the second branch and the cascade never starts. A record names a settled order and a clause or assembly, and the recording contract checks both halves itself, against state the chain already holds: it recomputes the order hash from the signed commitment and requires the kernel to report it resolved, and it requires Merkle inclusion of that identifier in the agreement hash that order carries. Neither check consults the caller. Nobody is trusted, so there is nothing to post; nothing is posted, so there is nothing to bond; nothing is bonded, so there is nothing to challenge; nothing is challenged, so there is no forum. The apparatus is not simplified or hardened &mdash; it is unnecessary, and its absence is not a gap in the design but the design.
                </PaperRun>
                <PaperRun title="Periods, not snapshots.">
                    One difficulty survives the move and is worth stating precisely. If a budget paid pro rata out of a total that kept growing, early claimants would take more than their share, and the usual answer is a snapshot &mdash; a checkpoint of every score at a chosen block, walked at claim time. The mechanism does not take one. Accrual buckets instead into fixed periods, set when the counting contract is deployed, and each period&rsquo;s budget pays for that period alone. Claiming requires that period to have ended, and once it has, its counters and its total are immovable: a record that arrives late lands in whatever period is open when it arrives, never in a closed one. So a claimant reads a denominator that no subsequent transaction can change, without a checkpoint array, without a history walk, and without any block-height parameter for anyone to choose. Claims never expire, because a closed period&rsquo;s arithmetic is stable forever.
                </PaperRun>
                <PaperRun title="Crediting an assembly&rsquo;s designer.">
                    Clauses and assemblies are separate families with separate registries, and the count treats them uniformly: what a record proves is that a particular thirty-two-byte identity was committed in the signed agreement. For a clause that identity is the leaf key itself, its registry identifier. For an assembly it is the composition hash under which the designer registered the composition, committed one step differently &mdash; as the content of the provenance clause&rsquo;s own leaf, whose committed bytes are fully determined by the composition hash, so that a wrong hash derives a leaf which is simply not in the tree. An agreement that commits the composition it instantiates therefore credits its designer by an inclusion proof of the same shape that credits a clause author, with no separate linkage table and no inversion step. The provenance clause that carries the credit earns nothing itself: it rides every assembly-composed process, so scoring it would pay its author for the protocol&rsquo;s floor rather than for anyone&rsquo;s adoption, and it is one of the excluded registrations of Section 4. That exclusion is the price of the construction and is stated as such &mdash; one piece of scoring infrastructure kept out of the scoring, named in advance and fixed at deployment alongside the two order-mandatory clauses.
                </PaperRun>
                <PaperRun title="Claiming, and the two budget backstops.">
                    A claim mints directly to the claimant &mdash; there is no intermediate custody, no root to prove against, and nothing that expires. Issuance is bounded twice over: the minter tracks what it has minted per period and refuses any claim that would overspend that period&rsquo;s budget, and the token independently caps what this minter may ever mint at the 600M reserve, a cap fixed when the minter was registered and beyond the reach of the minter or anyone operating it. The second bound holds even if the first were wrong, and no claim, and no sequence of claims, can move either.
                </PaperRun>
                <PaperRun title="The rule is fixed, and it is the code.">
                    The exponents, the minimum-support floor <Math>{"d_{\\min}"}</Math>, the seller-side and author-side live-stake gates, the excluded protocol-floor clauses, the nine period boundaries and the nine per-period budgets are all constants, immutables, or first-write-wins registry state of the deployed contracts. The two schedules cannot even be deployed inconsistently: the minter&rsquo;s constructor rejects a budget list whose length differs from the counter&rsquo;s period count, so a nine-period accrual cannot be paired with an eight-budget reserve by accident. There is no owner, no pause, no upgrade path, and no configuration surface: one uniform rule applies unchanged across all nine periods, and changing any constant means deploying a new token system. This is a stronger guarantee than anchoring a document&rsquo;s hash on chain, because there is no document that could disagree with what executes &mdash; a participant assessing the mechanism reads the constants from the contracts themselves, including the two deposits, the cooldown and the period length that fix the unit price of Section 7.
                </PaperRun>
            </PaperSection>

            <PaperSection title="10. Why Reconstruction-Based Verification Fails">
                <p>
                    Section 9 established a fork: an accounting of past adoption either reconstructs it after the fact or captures it at the event. Reconstruction admits two natural approaches, and neither escapes the fork&rsquo;s consequence &mdash; a bond, a challenge, and a forum are not implementation details of one technique but a structural cost of the branch itself. We work through both, since the case for capture is made by exactly what reconstruction costs.
                </p>
                <PaperRun title="Proof-gated verification.">
                    One approach gates a posted root behind a zero-knowledge proof: a succinct-proof virtual machine runs the canonical aggregator as its guest program and attests that the submitted root is the correct output of applying the frozen formula to a specific event window supplied as input. The proof binds the <em>formula</em> to the <em>inputs</em>: given those events, the root is provably the formula&rsquo;s output, with no deviation, no favoritism, and no off-formula adjustment. What it cannot bind is the <em>inputs</em> to <em>chain history</em>. A submitter who feeds the prover a doctored event stream &mdash; omitting some clauses&rsquo; usage, inventing others &mdash; obtains a valid proof for the wrong allocation, because the proof certifies correct computation over the inputs and says nothing about their provenance. Input provenance remains a trusted-submitter assumption, so this approach pays the full price of proving infrastructure without discharging the fork&rsquo;s cost.
                </PaperRun>
                <PaperRun title="Posted root under a bonded challenge.">
                    A second approach drops the proof and makes the window chain-defined instead: every event up to the block before the posting, the same for every observer, so there is no supplied stream to doctor. It then applies the assertion-stands-unless-contested pattern that optimistic rollups established (Optimism Foundation, 2021) to allocation &mdash; a poster stakes a bond, anyone may stake an equal bond to void the posting, and an unchallenged posting finalizes and pays by Merkle claim. This closes the input-provenance hole the first approach left open, and on its own terms it is sound. Its cost is the cascade itself: a correct allocation must wait on a challenge period whose only function is to give a hypothetical challenger time; the bonds at stake when a challenge lands need a rule, which means an escalation path, a concession deadline, and an external arbitration forum composed into the token system &mdash; a discretionary body inside a mechanism whose entire claim is to have none, even though its rulings only ever move bonds; and safety rests on a liveness assumption, that at least one honest party is watching, recomputing, and willing to bond, at every one of the nine annual postings the schedule would require, spread across nine years.
                </PaperRun>
                <p>
                    Counting adoption as it happens dominates both, and it does so by refusing the premise the whole branch shares. There is no window, because there is no reconstruction. There is no root, because there is no assertion. There is no bond, no challenge period, no forum, and no watcher who must be present for the mechanism to be safe &mdash; a correct allocation is payable the moment its period closes, and an incorrect one cannot be expressed. The proof-gated technique remains the right tool for a different problem, batch settlement, where signatures must be verified in-circuit rather than read from a log; it is the wrong tool for adoption, which the chain can simply be told about at the moment it occurs. The discipline generalizes past this mechanism: when a construction accumulates a bond, a challenge, and a referee, the thing to examine is not the construction but the claim it was built to make believable.
                </p>
            </PaperSection>

            <PaperSection title="11. Scope and Limitations">
                <PaperRun title="Cohort selection is the formula, by construction.">
                    The mechanism deliberately has no cohort-selection policy. The recipient set is the set of clause authors and assembly designers with non-zero <em>eligible</em> adoption in the period &mdash; adoption recorded while the seller&rsquo;s stake and the registration&rsquo;s own stake were live, scoring above the minimum-support floor, and claimed while that registration stake is still live &mdash; and the proportions are the rule&rsquo;s output. There is no list of approved recipients to curate and no committee to convene. This is a feature &mdash; it is what makes the mechanism discretion-free &mdash; but it means the mechanism funds exactly two kinds of contribution (clause authoring and assembly design) and is silent on every other kind of protocol work (client development, documentation, review, operations). Those are funded, if at all, through the separately-held treasury allocation &mdash; a discretionary human-judgment layer that decides what to fund going forward &mdash; not through this rule.
                </PaperRun>
                <PaperRun title="Single denomination per process.">
                    The counting layer reads a process&rsquo;s parties and its resolution from chain state directly; it takes no position on the currency a process settles in, and it compares no values across currencies, because value never enters the score. Settlement binds each process to a single denomination, and that binding belongs to the settlement layer alone: nothing here relies on it, and nothing here could relax it if it wanted to, this mechanism being a reader of the settlement record and never a writer to it (Section 6). What is scored is the shape of a coordination, not the units it moved.
                </PaperRun>
                <PaperRun title="The rule optimizes nothing, and that is the design.">
                    This mechanism has no social-welfare objective, and none is withheld for later. A welfare criterion over authors would rank kinds of contribution; a ranking justifies weights; and a weight is the curatorial judgment Section 6 declines &mdash; privileging a class of work in advance of the evidence. Neutrality here is not achieved by choosing the right objective but by refusing to hold one: the reward is uniform, and the two-sided live stake, not a weighting, carries what the score cannot. The constants are calibrations of that refusal, and are published as such &mdash; the exponents express a judgment about breadth over depth, the minimum-support floor <Math>{"d_{\\min}"}</Math> the number of separately priced identities a registration must gather before it scores at all, and the deposits, the cooldown and the period length a point on the <Math>{"C(\\varphi)"}</Math> curve any reader can recompute.
                </PaperRun>
            </PaperSection>

            <PaperSection title="12. Conclusion">
                <p>
                    Writing clauses and composing assemblies is the public-goods work that grows a permissionless coordination protocol&rsquo;s substrate, and it is uncompensated by the protocol&rsquo;s own operation. The mechanism developed here funds it retroactively, from a fixed 600M florin reserve paid out over nine annual periods on a schedule that rises as the evidence thickens, allocated by a fixed rule that rewards substrate-broadening &mdash; adoption by distinct value-adders in settled processes &mdash; over volume or value, uniformly across every clause and assembly, with no tag, category, or identity privileged, behind counting rules that close the cheap farming vectors, with Sybil resistance carried by a two-sided live stake in the chain&rsquo;s base currency &mdash; the same stake that makes honest contribution the aligned position to hold &mdash; rather than by a weighting scheme or a per-wallet cap.
                </p>
                <p>
                    That resistance is stated as a price rather than a hope, and the statement is what the choice of statistic buys. Because breadth is counted in distinct staked sellers, fabricated score has a flat unit cost in the chain&rsquo;s base currency; because the reward is uniform pro rata over a fixed reserve, the capital required to take a share of a period is convex in that share and unbounded as it approaches the whole; and because a minimum-support floor withholds scoring until several distinct staked sellers stand behind a clause or assembly, even the cheapest entry that scores at all has a price, quoted in those same units. Anyone can recompute the figures from the deployed constants &mdash; the two deposits, the withdrawal cooldown, the period length &mdash; together with a gas measurement taken on the settlement route an adversary would actually use, and the period&rsquo;s own public accrual.
                </p>
                <p>
                    The mechanism&rsquo;s claim to legitimacy rests on four refusals and one substitution. It refuses governance; it refuses human curation, and in particular the badgeholder panel that retroactive-funding practice elsewhere retains; it refuses to couple issuance to gameable per-use events; and it refuses a trusted submitter of the facts it scores. The substitution is the whole of it: rather than reconstructing adoption after the fact and then building the machinery to make that reconstruction believable &mdash; a posting, a bond, a challenge window, a forum &mdash; it has the chain verify each fact at the moment the fact occurs. What remains is arithmetic over numbers that are already final: no allocator, no submitter, no challenger, no referee, and no window anyone must be awake for. The authors and designers who broadened the substrate are paid on the strength of what their clauses and assemblies demonstrably coordinated, and nothing in between has an opinion.
                </p>
            </PaperSection>
        </PaperLayout>
    );
}
