import type { Metadata } from "next";
import { withOg } from "@/lib/shared/pageMetadata";
import {
    PaperLayout,
    PaperSection,
    PaperRun,
    PaperRemark,
} from "@/components/papers/PaperLayout";
import { Math } from "@/components/papers/Math";

export const metadata: Metadata = withOg({
    title: "Self-Authenticating Data Sales — Figaro Protocol",
    description:
        "A dataset sold on ordinary terms suffers Arrow's information paradox: the buyer cannot value the data without seeing it, and having seen it, has no reason to pay. A settlement layer that records trade as merkle-committed, bonded agreements dissolves the paradox economically rather than cryptographically: each delivered record carries an inclusion proof against the on-chain fingerprint of the settled process that produced it, and the licence granting access carries one against the fingerprint of the sale itself, and the doubled bond leaves a seller that ships less than it described out of pocket even after crediting it with everything shipping less lets it keep.",
});

export default function SelfAuthenticatingDataSalesPaper() {
    return (
        <PaperLayout slug="self-authenticating-data-sales"
            title="Self-Authenticating Data Sales"
            subtitle="Dissolving Arrow's Information Paradox Through Bonded Settlement"
            author="Figaro"
            date="August 2026"
            watermark="Figaro Protocol · Preprint"
            abstract={
                <>
                    <p>
                        A dataset sold on ordinary terms suffers Arrow&rsquo;s information paradox: the buyer cannot value the data without seeing it, and having seen it, has no reason to pay. We show that a settlement layer which records trade as merkle-committed, bonded agreements dissolves the paradox <em>as a barrier to trade</em>, economically rather than cryptographically: each delivered record carries an inclusion proof against the on-chain fingerprint of the settled process that produced it, and the licence granting access carries one against the fingerprint of the sale itself, so what is sold arrives self-authenticating &mdash; provably a real record of a real trade, under terms provably agreed &mdash; while the doubled bond leaves a seller that ships less than its licence describes out of pocket even after crediting it with everything shipping less lets it keep. The two claims are not symmetric, and the paper is precise about which is which: the appropriation horn is closed outright, since paying and reclaiming one&rsquo;s own bond are the same act, and the value the buyer has already extracted cancels from the comparison rather than weighing in it; the valuation horn is answered by verified provenance plus a bond that <em>bounds</em> what misdescription can be worth to a seller rather than eliminating the buyer&rsquo;s residual valuation risk. Section 8 states the four limits in full.
                    </p>
                    <p>
                        Disclosure regimes (closed, each-own, open) are composition choices, not platform policy; the same mechanism prices a snapshot or a stream, and the stream is the repeated game that sustains honest data production.
                    </p>
                </>
            }
            references={
                <>
                    <li>Acemoglu, D., Makhdoumi, A., Malekian, A., &amp; Ozdaglar, A. Too Much Data: Prices and Inefficiencies in Data Markets. <em>American Economic Journal: Microeconomics</em>, 14(4):218&ndash;256, 2022.</li>
                    <li>Akerlof, G. A. The Market for Lemons: Quality Uncertainty and the Market Mechanism. <em>Quarterly Journal of Economics</em>, 84(3):488&ndash;500, 1970.</li>
                    <li>Arrow, K. J. Economic Welfare and the Allocation of Resources for Invention. In R. R. Nelson (ed.), <em>The Rate and Direction of Inventive Activity: Economic and Social Factors</em>, pp. 609&ndash;626. Princeton University Press for the National Bureau of Economic Research, Princeton, NJ, 1962.</li>
                    <li>Fudenberg, D. &amp; Maskin, E. The Folk Theorem in Repeated Games with Discounting or with Incomplete Information. <em>Econometrica</em>, 54(3):533&ndash;554, 1986.</li>
                    <li>Klein, B. &amp; Leffler, K. B. The Role of Market Forces in Assuring Contractual Performance. <em>Journal of Political Economy</em>, 89(4):615&ndash;641, 1981.</li>
                    <li>Merkle, R. C. A Digital Signature Based on a Conventional Encryption Function. In <em>Advances in Cryptology &mdash; CRYPTO &rsquo;87</em>, Lecture Notes in Computer Science vol. 293, pp. 369&ndash;378. Springer, Berlin, 1988.</li>
                    <li>Shapiro, C. &amp; Varian, H. R. <em>Information Rules: A Strategic Guide to the Network Economy</em>. Harvard Business School Press, Boston, 1998.</li>
                    <li>Varian, H. R. Buying, Sharing and Renting Information Goods. <em>Journal of Industrial Economics</em>, 48(4):473&ndash;488, 2000.</li>
                    <li>Williamson, O. E. Credible Commitments: Using Hostages to Support Exchange. <em>American Economic Review</em>, 73(4):519&ndash;540, 1983.</li>
                </>
            }
        >
            <PaperSection title="1. The Paradox, Restated">
                <p>
                    Arrow (1962) observed that information behaves unlike an ordinary good at the moment of sale: &ldquo;there is a fundamental paradox in the determination of demand for information; its value for the purchaser is not known until he has the information, but then he has in effect acquired it without cost.&rdquo; A prospective buyer of a dataset, a model, or a research finding cannot rationally price it sight unseen &mdash; the good&rsquo;s value is exactly the thing withheld until sale &mdash; yet a buyer who has been shown enough to price it has, in the same act, been given the thing itself.
                </p>
                <PaperRun title="The valuation horn.">
                    Before disclosure, the buyer has no basis to distinguish a genuine, well-sourced dataset from a fabricated or degraded one, and no way to distinguish a seller&rsquo;s description of what a licensed feed contains from an accurate one. This is Arrow&rsquo;s paradox applied to provenance rather than only to content: the buyer faces the ordinary quality-uncertainty problem Akerlof (1970) formalized for used cars, sharpened by the fact that the only direct test of quality &mdash; inspecting the good &mdash; is also the disclosure that triggers the second horn.
                </PaperRun>
                <PaperRun title="The appropriation horn.">
                    After disclosure, the informational content the buyer wanted has already changed hands. Information is non-rival and, absent an external enforcement mechanism, non-excludable once shown: nothing about having seen a dataset compels a buyer to then pay for it (Shapiro &amp; Varian, 1998). A seller who discloses to let the buyer value the good has, in the same motion, given up the leverage that would have compelled payment.
                </PaperRun>
                <p>
                    Classical partial remedies each answer one horn at the cost of the other. Patents and copyright convert information into excludable property, but require registration, jurisdiction, and litigation to enforce, and do not help an unregistered dataset or a one-off feed. Non-disclosure agreements make the second horn a breach of contract, but a breach discovered only after the buyer has already extracted the value is a recourse, not a deterrent, and it does nothing for the first horn&rsquo;s provenance problem. Reputation sustained by repeated dealing addresses both horns over a relationship&rsquo;s lifetime (see &sect;6), but supplies nothing for a first transaction between strangers. What follows shows a settlement mechanism that dissolves both horns for a single, first-time sale between parties who have no reputational history and share no jurisdiction &mdash; and does so by economic construction rather than by access control. &ldquo;Dissolves&rdquo; is used throughout in the sense of removing the paradox as an obstacle to the trade taking place, not in the sense of eliminating every risk each horn names: the appropriation horn is closed outright, while the valuation horn is answered by verified provenance and by a bond that bounds what misdescription can be worth to a seller, leaving a residual valuation risk the mechanism prices rather than abolishes (&sect;8).
                </p>
            </PaperSection>

            <PaperSection title="2. A Data Sale Is an Ordinary Bonded Order">
                <p>
                    The mechanism is not a purpose-built data-market contract; it is the ordinary settlement kernel that settles any bonded trade, composed with clauses that name the subject matter as data. The kernel is restated here at the depth the argument below actually uses, since the whole of that argument is an application of it.
                </p>
                <PaperRun title="Two calls, two mechanism designs.">
                    <em>Commit</em> forms a bilateral edge: buyer and seller sign one commitment and both post bonds &mdash; the buyer twice the payment <Math>{"P"}</Math>, the seller twice the value the process has accumulated through its own link, <Math>{"G_i = \\sum_{j \\leq i} P_j"}</Math>, its own payment included. That base is not a report either party makes: the accumulator admits exactly one value per commitment &mdash; the payment itself where the commitment opens a process, the standing accumulator plus the new payment where it extends one &mdash; so the seller&rsquo;s bond is fixed by arithmetic on figures both parties signed. A data sale is ordinarily a single-order process, where <Math>{"G = P"}</Math> and the two bonds coincide at twice the payment. <em>Resolve</em> settles the process: only the buyer may call it, and it settles every order at once or none. It is the only terminal move, and the two calls are the whole of the state-changing surface &mdash; no timeout, no administrator, no unilateral exit from the bonded state, and no clock running once the bonds are locked.
                </PaperRun>
                <PaperRun title="The boundary, and what deterrence is computed from.">
                    The data itself, its delivery, and each party&rsquo;s knowledge of what passed between them are off the record and beyond the mechanism&rsquo;s reach. What the mechanism holds is the bonds, the signed accumulator, and the record of commitments &mdash; so the record shows what was undertaken and whether it was closed, and never shows that anyone performed. Deterrence is accordingly computed with credit for what a defector <em>retains</em>, never from locked bonds alone. A seller that keeps what is in its hands is credited that value, at the signed measure at most <Math>{"G"}</Math> at its link, against <Math>{"2G"}</Math> locked: it stands at best at <Math>{"-G"}</Math>, against the <Math>{"+P"}</Math> that performing pays. A buyer that keeps a delivery and never resolves is credited that delivery in full and still stands a whole payment below what closing would give it. Credit each side with everything it keeps and defection is out of pocket on both &mdash; mutual assured destruction with content, the doubling being exactly what stops retention from paying for the taking, since a bond equal to the value at the link would be cancelled outright by the value held.
                </PaperRun>
                <PaperRun title="The equilibrium, and the order it composes in.">
                    The result is stated at a node, and the node is the conditioning: <em>after performance</em>, resolving is unconditionally strictly better for the buyer than never resolving. What &ldquo;unconditionally&rdquo; qualifies is the seller, not the buyer&rsquo;s policy &mdash; at that node the seller&rsquo;s conduct is already fixed, so the comparison needs no assumption whatever about what kind of counterparty the buyer is facing. It is emphatically not a rule of resolving no matter what arrived, and nothing below assumes one: a buyer that resolves without regard to what arrived is admitted by the mechanism and has thereby given up the instrument the mechanism reserves to it, paying the party that disappointed it, and no argument in this paper rests on such a buyer. Given the node result, performance is each seller&rsquo;s strict best response, and the two compose in that order only &mdash; the resolve call&rsquo;s design supplies the buyer&rsquo;s unconditional reason to close once performance has occurred, and only because that is settled is performing better for a seller than holding what it has. The complementary case is what makes the composition bite rather than an exception to it: under-performance never reaches the post-performance node at all. It routes to the standoff, where both positions stay locked and the remedy is negotiated (below), and it is precisely the prospect of standing in that standoff &mdash; credited with everything it keeps and still out of pocket &mdash; that makes performance the seller&rsquo;s strict best response in the first place. The deterrence of &sect;3 and the limits of &sect;8 are read off that branch; the node result is read off the other; neither displaces the other.
                </PaperRun>
                <PaperRun title="Where recourse sits.">
                    None of this leaves a disappointed party without recourse; it locates the recourse <em>before</em> the resolution rather than after it. Where a seller cannot perform, the remedy is arranged between the parties while the process stands open &mdash; concretely, the failing seller sends the buyer the payment it stands to receive, so that at resolution it takes back its bond and the payment, having already paid that payment away: it ends at zero, its failure earning it exactly nothing, and the buyer is whole. Where the parties disagree, an outside forum can be shown the record of what was undertaken and whatever each party brings it about what happened, and can rule while the process is still open; what such a forum cannot do is call resolve, resolution being the buyer&rsquo;s alone. There is no direct enforcement into the mechanism, which is precisely why composing a forum costs the equilibrium nothing. And resolution is terminal acceptance: a buyer resolves when it is satisfied, and nothing is recoverable inside the mechanism afterwards.
                </PaperRun>
                <p>
                    A data sale composes three clauses onto an ordinary order of this kind, and a fourth clause, easily confused with them, does a different job. The <em>commerce</em> clause carries the price, which is the payment the bonds are struck against. The <em>data licence</em> clause carries the terms of this particular sale &mdash; what is licensed (a short editorial name for the dataset, stream, or record family), the permitted purpose, whether access is a one-time <em>snapshot</em> or a continuing <em>stream</em>, whether redistribution is permitted, and, where the licensed content derives from prior settled trade, the identifiers of the settled processes it derives from. The <em>content hand-off</em> clause carries the delivery: whether the artifact or its decryption key travels the per-order encrypted channel, whether the counterparty is granted access at a named repository, or whether the content is published openly and verified by content hash alone.
                </p>
                <p>
                    The fourth clause, <em>data terms</em>, is not part of the sale at all: it is the disclosure <em>regime</em> for a process&rsquo;s own co-produced records &mdash; the signed agreement, the delivery evidence, the books each side keeps of the trade itself. It fixes one of three postures &mdash; <em>closed</em> (neither party discloses beyond the parties), <em>each-own</em> (each party may disclose the copy it holds), <em>open</em> (either party may publish the record) &mdash; and carries the buyer&rsquo;s own per-order choice, permit or withhold, over the half of the record the buyer contributed. It is composed by a designer over any process whose records may later be worth something, which is why it is generic rather than a marker of a data-selling assembly: the process that <em>produces</em> saleable records is typically the one carrying it, and the later sale of those records is a separate process carrying the three clauses above. Sealed per-order fields &mdash; a delivery address, counterparty-private hand-off content &mdash; sit outside every regime by construction, and are not disclosable through this clause whichever posture is chosen. No dedicated market contract exists for any of this: the sale is priced, bonded, and settled by the same kernel that settles any other trade, and the clauses are what make its subject matter legible as data rather than leaving that to prose.
                </p>
            </PaperSection>

            <PaperSection title="3. Self-Authentication Answers the Valuation Horn">
                <p>
                    A signed agreement is a set of clause sections. Each section is hashed, the section hashes are merkle-committed (Merkle, 1988), and the root of that commitment &mdash; the agreement&rsquo;s <em>fingerprint</em> &mdash; is exactly what both parties sign and what the kernel anchors on-chain at commit. How the tree is built is not this paper&rsquo;s business; one property of it is. A party holding any single section of an agreement can disclose that section alone, together with an inclusion proof, and the recipient checks the pair <em>by recomputation</em>: hash the disclosed content, walk the proof, compare the result with the fingerprint the chain recorded when the process committed. Nothing else about the agreement need be disclosed for the check to succeed, and nothing about the discloser need be believed for it to be conclusive &mdash; a single altered character anywhere in the disclosed content produces a different result and the check fails.
                </p>
                <p>
                    This is what makes a licensed record self-authenticating &mdash; and two different artifacts are checked against two different fingerprints, which is worth separating once and then holding to. <em>The delivered records</em> are sections of the agreement of the process that produced them, so each verifies by inclusion proof against <em>that source process&rsquo;s</em> own fingerprint, the one the chain has held since the source process settled. <em>The licence</em> is a section of the agreement of the sale, so it verifies against <em>the sale process&rsquo;s</em> fingerprint, and it reaches the source not by proof but by naming: its own field carries the identifiers of the settled processes whose records it licenses. The first check is the self-authentication claim proper; the second establishes that the licence is genuinely the instrument the two parties agreed, and the field is what joins them.
                </p>
                <p>
                    Both checks are recomputations, and a recipient does neither on the seller&rsquo;s word: it hashes what it was given and compares. Provenance therefore verifies identically for a record produced yesterday and for one bought third-hand, and it verifies against fingerprints no party to the sale controls &mdash; which is the whole of what &ldquo;self-authenticating&rdquo; means here. Notice what it does <em>not</em> mean: a fingerprint attests that a record is the record a named settled process produced, not that the record&rsquo;s contents are true (&sect;8).
                </p>
                <p>
                    Self-authentication answers the provenance half of the valuation horn &mdash; the record is verifiably the thing it claims to be &mdash; but it does not, by itself, price the unseen remainder of a dataset or stream the buyer has not inspected. That is answered by the bond, on exactly the accounting of &sect;2. A seller who ships a licensed feed materially different from what the licence terms describe has not performed, just as a seller of any other bonded good that ships something else has not performed; and what that is worth to it is computed by crediting it with everything shipping less lets it keep &mdash; the records it withheld, the collection it did not do &mdash; at the measure the parties themselves signed. Against that credit stands its own locked bond at twice the value at its link, so through the standoff that follows it is out of pocket by at least the value at the link, against the payment that performing would have earned it. The bond is a credible commitment in Williamson&rsquo;s (1983) sense &mdash; posted by the seller against its own conduct, at a moment when the buyer cannot yet verify what it will receive &mdash; and what makes it credible is not that anyone will consume it, since nothing in the mechanism consumes anything, but that nobody can release it except through a resolution an unsatisfied buyer does not give. That is what lets a buyer price a licence from its description and its verified provenance rather than from a first inspection of the content itself.
                </p>
            </PaperSection>

            <PaperSection title="4. Bonded Resolution Closes the Appropriation Horn">
                <p>
                    The second horn survives self-authentication on its own: nothing about an inclusion proof stops a buyer who has received a licensed record from reading it, copying it, and simply declining to pay. What stops it is the shape of resolution. Write <Math>{"P"}</Math> for the sale&rsquo;s payment and <Math>{"W \\geq 0"}</Math> for whatever the delivered content turns out to be worth to this buyer &mdash; a figure the buyer alone knows, which the mechanism never sees and this paper never estimates. This is deliberately not the assented value the general treatment credits a buyer with holding: that figure is the sum of the payments behind whatever has actually reached the buyer&rsquo;s hands, a quantity both parties signed and which for a single-order sale equals <Math>{"P"}</Math> exactly. <Math>{"W"}</Math> is a different measure entirely &mdash; private, unsigned, and under no constraint to equal <Math>{"P"}</Math> in either direction &mdash; and what the comparison below shows is that the cancellation the general treatment proves for the signed figure holds just as well for this unsigned one. At the buyer&rsquo;s node after delivery the mechanism offers exactly two continuations, there being no third and no exit from the bonded state: resolve, or never resolve.
                </p>
                <p>
                    Resolving returns the locked <Math>{"2P"}</Math> less the <Math>{"P"}</Math> transferred to the seller, and the content stays where it is, so the buyer ends at <Math>{"W - P"}</Math>. Never resolving leaves the bond locked &mdash; no timeout, no recovery path, no third party able to release it &mdash; and the content stays where it is there too, since withholding a resolution un-discloses nothing that has already travelled the hand-off channel: the buyer ends at <Math>{"W - 2P"}</Math>. The comparison is therefore
                </p>
                <div className="my-4 overflow-x-auto">
                    <Math display>{"(W - P) \\;-\\; (W - 2P) \\;=\\; P \\;>\\; 0 \\qquad \\text{for every } W \\geq 0"}</Math>
                </div>
                <p>
                    &mdash; the buyer&rsquo;s valuation cancels. This is the general property of the resolve call read at a data sale: after performance, resolving is unconditionally strictly better for the buyer than never resolving, and the comparison needs no assumption about the seller, whose conduct is already fixed at this node. What the data case adds is the disposal of the objection one would expect it to raise. A buyer of ordinary goods might be thought to close because something further is still owed to it; a buyer of information has already banked everything it came for, so one expects its reason to close to be correspondingly weaker. The arithmetic says the reason is exactly as strong, and for a reason worth stating plainly: what the buyer banked is common to both continuations and drops out, so the mechanism never has to price the very quantity Arrow&rsquo;s paradox says nobody can price before disclosure. The strengthening is real but narrow &mdash; not that the buyer values the data less, but that how much it values it has become irrelevant to the only decision left to it.
                </p>
                <p>
                    This is the sign-flip Arrow&rsquo;s second horn assumes away. The classical paradox treats payment as a free-standing act a buyer can skip once the informational value is in hand, because in an ordinary sale skipping it costs the buyer nothing. Here paying and reclaiming one&rsquo;s own locked capital are the same call, so skipping is not free but the more expensive of the two things the buyer can do; and the buyer closes not because access is withheld pending payment &mdash; it is not, by construction, the content having already travelled the hand-off channel &mdash; but because leaving its own bond locked is worse for it by exactly the payment. The dissolution is economic rather than cryptographic: no encryption, watermark, or access gate polices the buyer&rsquo;s use of the data after receipt; the buyer&rsquo;s own arithmetic does.
                </p>
                <PaperRemark title="What the comparison claims, and what it does not.">
                    Two boundaries keep the result honest. First, it is a comparison at a node and not a ranking of every plan a buyer might adopt: the mechanism also admits a buyer that resolves without regard to what arrived, which is a buyer that has given up the instrument the mechanism reserves to it, and nothing here recommends that. What is unconditional is the narrower statement above &mdash; <em>after</em> delivery, closing beats never closing, whatever the counterparty is like. Second, the direction of the usual telling is reversed here and the reversal costs nothing. In an ordinary trade it is the buyer&rsquo;s willingness to withhold that disciplines a seller who has not performed; in a data sale it is the buyer itself, holding what it came for, that might want to withhold. The arithmetic is indifferent to which party is tempted, because in both readings withholding strands the withholder&rsquo;s own capital and reaches none of the counterparty&rsquo;s.
                </PaperRemark>
            </PaperSection>

            <PaperSection title="5. Disclosure Regimes Are Composition Choices">
                <p>
                    The data-terms clause&rsquo;s three regimes &mdash; closed, each-own, open &mdash; are not settings a platform enforces on a seller&rsquo;s behalf; they are design-time composition choices, and a process instantiated under one regime is a different assembly from the same process instantiated under another, identified by a different composition hash rather than by a version bump on a shared one. Two compositions built from an otherwise identical survey-flight design &mdash; one composing data terms with disclosure fixed to <em>each-own</em>, the other to <em>open</em> &mdash; are two distinct compositions with distinct identities; adopting one commits a buyer and seller to that regime&rsquo;s terms exactly as adopting a different price or a different delivery window would commit them to those. Within whichever regime the assembly composes, the buyer&rsquo;s own consent over the content it contributed is a further, separate, per-order commitment &mdash; permit or withhold &mdash; signed at checkout rather than inferred from the regime, so a buyer who transacts under an each-own regime still explicitly opts in or out of disclosing its own half. Sealed per-order fields are excluded from all three regimes at the clause boundary, not by a policy exception: a delivery address or a counterparty-private hand-off payload is simply never a candidate for disclosure through this mechanism, whatever regime the surrounding process has chosen.
                </p>
            </PaperSection>

            <PaperSection title="6. Pricing a Snapshot or a Stream">
                <p>
                    The same licence clause prices two different products with one field: a <em>snapshot</em>, a one-time delivery of the records as they stand, verified once by content hash; or a <em>stream</em>, continuing access to a growing record, realised as a further bonded order &mdash; or a further delivery under a standing agreement &mdash; each period. The argument of &sect;4 already governs each delivery in a stream on its own, independent of any repetition: every period is its own bonded order, and every period&rsquo;s buyer faces the same comparison, its valuation of that period&rsquo;s content cancelling from it exactly as before. Repetition is therefore not load-bearing for either horn, which is worth stating before saying what it does add, since the classical remedies it resembles are the ones &sect;1 found wanting for a first transaction between strangers.
                </p>
                <p>
                    What repetition adds is a second, weaker discipline on top of a mechanism that does not need it. A seller whose period ships degraded or fabricated has not performed that period, so it stands where &sect;3 leaves it &mdash; credited with what shipping less let it keep and still out of pocket against its own locked bond while the buyer withholds and a remedy is negotiated &mdash; and it also stands to lose the buyer&rsquo;s continuation into the next period, which no bond had to be posted to make costly. A licensee that is found to have redistributed a stream held under a no-redistribution term stands to lose continued access on the same footing. This is the ordinary logic by which a relationship&rsquo;s continuation value disciplines conduct beyond what a single period&rsquo;s stakes would (Klein &amp; Leffler, 1981; Fudenberg &amp; Maskin, 1986), applied to a channel where every period is separately and contemporaneously bonded rather than merely promised &mdash; so the continuation value adds to a floor instead of substituting for one. A snapshot prices a single fact; a stream prices a relationship, whose value to both sides is largest in the case where neither side ever has occasion to run the one-period argument of &sect;4 in anger. That is why the sustainable data product is the stream rather than the snapshot (Varian, 2000): the deceived snapshot buyer has the bonded position of that one order and nothing beyond it, whereas the stream seller has, on top of that same position, a continuation it wants and the buyer alone decides whether to renew.
                </p>
            </PaperSection>

            <PaperSection title="7. A Worked Instance">
                <p>
                    Two independent bonded processes carry the whole cycle, and working them through is the shortest way to see which clause does which job. In the first, a survey operator flies a route for a client under a composition carrying the price, a flight-schedule clause, a route committed at neighbourhood grain, an operator-credential clause, and data terms fixed to the <em>each-own</em> regime; the client separately commits at checkout to permit disclosure of the half of the record it contributed. The order commits, both bonds lock, and the buyer resolves once the flight is complete, which pays the operator and settles the process. Its records &mdash; the signed agreement, the delivery evidence, the books each side keeps of the flight &mdash; are now co-produced records under a regime that lets each party disclose the copy it holds.
                </p>
                <p>
                    In the second process the client is the seller rather than the buyer: it licenses continuing access to the resulting telemetry to a counterparty, under a composition carrying the price, a data-licence clause &mdash; access set to <em>stream</em>, redistribution prohibited, the first process&rsquo;s identifier named as its source &mdash; and a content hand-off clause whose completion evidence is the hash of the access credential delivered over the encrypted channel. Note that the second composition carries no data-terms clause and needs none: the regime governs a process&rsquo;s own records, and the process being sold <em>from</em> is the first one. To the kernel these are two entirely separate linear chains of commits, each against its own accumulator; nothing on-chain records that the second derives from the first.
                </p>
                <p>
                    The link is carried in the licence clause&rsquo;s own field, and the two checks of &sect;3 fall out in their two places. The disclosed <em>licence</em> is a section of the second agreement, so it verifies by recomputation against the <em>second</em> process&rsquo;s committed fingerprint, and the identifier it names is the first process&rsquo;s. The disclosed <em>flight records</em> &mdash; the committed window, the route at neighbourhood grain, the operator&rsquo;s verified credential, each a section of the first agreement &mdash; verify against the <em>first</em> process&rsquo;s fingerprint, which the chain has held since that flight settled, and which nothing about the second sale can touch. So a party holding what it was sold establishes two separate things by two separate recomputations: that this licence is genuinely the instrument the two parties agreed, and that the records it grants access to are genuinely those of a real, bonded, already-settled flight commissioned by the party now selling access to them. The negative case is what gives the positive case its content &mdash; alter one field of either disclosed section and its recomputation fails rather than quietly passing, which is why either check is worth performing at all.
                </p>
            </PaperSection>

            <PaperSection title="8. Scope and Limits">
                <p>
                    The mechanism bounds four risks; it eliminates none of them, and the difference is where a reader should press hardest.
                </p>
                <p>
                    <em>First, the bond bounds misdescription rather than abolishing valuation risk.</em> A seller can ship a feed that is technically consistent with a loosely-worded licence description and still disappoint the buyer who read that description generously. What &sect;3 establishes is that shipping less than the licence describes cannot pay &mdash; credited with everything it keeps, the seller is still out of pocket &mdash; not that the buyer&rsquo;s disappointment is always smaller than what the seller stands in. The precision of the licence text is doing work here that no bond schedule can do for it, and a buyer that accepts a vague description has accepted a correspondingly vague standard of performance.
                </p>
                <p>
                    <em>Second, a no-redistribution term is evidence, not a control.</em> Nothing prevents a licensee from copying data once received; the mechanism has no way to un-disclose what has crossed the hand-off channel, and no term in any clause gives it one. What the term does is leave a timestamped, co-signed statement of what the licensee undertook, which an outside forum &mdash; an arbitration panel, an ordinary court &mdash; can rule on while the process stands open, alongside whatever else the parties bring it. Such a ruling feeds the parties&rsquo; own remedy negotiation and reaches the licensee through its exposure outside the process. It does not and cannot reach into the mechanism: no forum can call resolve in the buyer&rsquo;s place, so there is no direct enforcement here and this paper claims none.
                </p>
                <p>
                    <em>Third, what the chain holds is a fingerprint.</em> The agreement&rsquo;s fingerprint is anchored at commit; the section hashes and inclusion proofs are computed from disclosed content and checked against it, and nothing of them is stored on-chain. The content behind the fingerprint &mdash; the dataset itself, the delivery evidence, the books a process leaves behind &mdash; is never on-chain and stays with whichever party produced it, disclosed only by that party&rsquo;s own choice under whichever regime the process composed. What the mechanism therefore guarantees is referential integrity: that a disclosed record really is the record a named, settled process produced. It does not guarantee substantive accuracy of that record&rsquo;s contents. A drone that reported a position it was not at produces a record that is provably the record of a real settled flight and substantively false, and no property of the settlement layer distinguishes the two &mdash; that judgement belongs to whoever reads the data, which is where this mechanism leaves it.
                </p>
                <p>
                    <em>Fourth, the bound is per-transaction; it prices nothing that never entered the licence.</em> A dataset rarely describes only the party who sold it: records correlate across sellers whenever they share customers, neighbours, or a population, so a sale settled exactly as this paper describes &mdash; self-authenticated, bonded, priced against a precise licence &mdash; can still degrade the privacy, and depress the achievable price, of records some other seller holds and has never offered for sale (Acemoglu, Makhdoumi, Malekian &amp; Ozdaglar, 2022). Self-authentication verifies that a disclosed record is the record a named settled process produced; it says nothing about whom else that record&rsquo;s content implicates, because the check runs against the two parties&rsquo; own fingerprints, not against the population the content describes. The bond, similarly, prices what the seller shipped against what its own licence promised; a fact about a third party that was never named in that licence was never priced by it either. What this mechanism secures is accordingly a claim about the transaction it settles, not about the market of correlated transactions the transaction sits inside, and the efficiency gain &sect;1&ndash;&sect;4 establish should be weighed against that externality rather than read as having already netted it out.
                </p>
            </PaperSection>

            <PaperSection title="9. Conclusion">
                <p>
                    Arrow&rsquo;s paradox has two horns, and the settlement layer described here answers each by a different property of the same mechanism rather than by restricting access to the data itself &mdash; but it answers them to different depths, and the difference is the paper&rsquo;s main claim on a reader&rsquo;s attention. The appropriation horn is closed outright, at the node where the horn arises: once delivery has happened, reclaiming one&rsquo;s own locked capital and paying the seller are the same call, and whatever the buyer has already extracted enters both of its continuations identically and cancels, so a buyer who has read the data closes for a reason that never has to price what reading it was worth. That is a comparison at a node and not a policy of closing regardless &mdash; a delivery that falls short of the licence never reaches that node, routing instead to the standoff and the remedy negotiated within it, which is the same branch on which the seller&rsquo;s deterrent is computed. The valuation horn is answered rather than abolished: a delivered record&rsquo;s provenance is self-authenticating by recomputation against the fingerprint the chain committed when the source process settled, the licence granting access to it verifies the same way against the fingerprint of the sale, and the seller&rsquo;s bond leaves shipping less than the licence describes out of pocket even crediting the seller with everything it keeps &mdash; which bounds what misdescription can be worth without guaranteeing that the bound sits above any given buyer&rsquo;s disappointment. Neither answer depends on restricting what the buyer can do with the data after receipt; both depend entirely on what each party stands to lose by not completing the trade it committed to. Disclosure regimes are composed, not policed, and the clause that prices a single record prices a continuing one &mdash; where the continuation each side wants is what makes the stream, rather than the one-off sale, the form in which honest data production sustains itself.
                </p>
            </PaperSection>
        </PaperLayout>
    );
}
