import type { Metadata } from "next";
import { withOg } from "@/lib/shared/pageMetadata";
import {
    PaperLayout,
    PaperSection,
    PaperSubsection,
    PaperRun,
} from "@/components/papers/PaperLayout";
import { Math } from "@/components/papers/Math";

export const metadata: Metadata = withOg({
    title: "The Wallet Without a Polity — Figaro Protocol",
    description:
        "The kernel's precondition is a cryptographic key, not a recognized civil-legal subjecthood. For the displaced and stateless, it grants not the right to have rights (political) but a capacity to have commerce (structural).",
});

export default function WalletWithoutPolityPaper() {
    return (
        <PaperLayout slug="wallet-without-polity"
            title="The Wallet Without a Polity"
            subtitle="Displaced and Stateless Subjects under the Kernel"
            author="Figaro"
            date="April 2026"
            watermark="Figaro Protocol · Preprint"
            abstract={
                <>
                    <p>
                        The kernel exhibits a property whose consequences are most consequential not for populations conventionally treated by labor or commercial law, but for those who occupy the negative space of those frames: refugees, stateless persons, undocumented migrants, and populations whose residency is beyond the reach of stable banking and enforcement infrastructure. The kernel&rsquo;s precondition is a cryptographic key, not a recognized civil-legal subjecthood. This paper develops the consequence. Of the six elements a binding contract needs, two turn on a polity: capacity, which it confers on the party, and legality, which it confers on the act. The kernel substitutes for the first by two acts that consult no polity &mdash; a wallet signs, and it funds its bond &mdash; and supplies none of the second.
                    </p>
                    <p>
                        The premise is that the kernel collapses the Roman <em>res</em>/<em>persona</em> distinction &mdash; the thing owned versus the party who acts &mdash; so that the productive asset is simultaneously property and party; this paper extends the premise to settings where civil-legal subjecthood is itself absent. Arendt (1951) named the right to have rights as the fundamental human right &mdash; a right whose denial is a civilizational failure rather than an individual misfortune &mdash; and the technological infrastructure considered here cannot grant it. What it grants is narrower, and bounded to those who retain the tokens to fund a bond: a capacity to have commerce, where the capacity to have rights is denied. The two should not be confused. For populations for whom the first is denied and something to bond survives, the second is non-trivial; for populations whose displacement has also stripped them of everything they could bond, the kernel has nothing yet to offer.
                    </p>
                    <p>
                        The argument is positional rather than programmatic and bounded by that funding condition throughout. Real constraints &mdash; key custody, fiat on-ramp, counterparty and currency gatekeeping, the absence of any forum both parties can reach, the legality no kernel supplies, and the funding constraint above all &mdash; are named and not dismissed. The analytical claim is that, for the population able to fund a bond, the kernel moves the humanitarian-economics gap from an architectural impossibility to an operational engineering question, and that this is a consequential move worth scholarship.
                    </p>
                </>
            }
            references={
                <>
                    <li>Allen, C. The Path to Self-Sovereign Identity. Personal blog, April 25, 2016.</li>
                    <li>Arendt, H. <em>The Origins of Totalitarianism</em>. Harcourt, Brace &amp; Co., New York, 1951 (esp. Part II, Ch. 9, &ldquo;The Decline of the Nation-State and the End of the Rights of Man&rdquo;).</li>
                    <li>Arendt, H. <em>The Human Condition</em>. University of Chicago Press, Chicago, 1958.</li>
                    <li>Benhabib, S. <em>The Rights of Others: Aliens, Residents, and Citizens</em>. Cambridge University Press, Cambridge, 2004.</li>
                    <li>Betts, A. &amp; Collier, P. <em>Refuge: Transforming a Broken Refugee System</em>. Penguin, London, 2017.</li>
                    <li>Buterin, V. Why We Need Wide Adoption of Social Recovery Wallets. Personal blog, January 11, 2021.</li>
                    <li>Coppi, G. &amp; Fast, L. Blockchain and Distributed Ledger Technologies in the Humanitarian Sector. Humanitarian Policy Group, Overseas Development Institute, 2019.</li>
                    <li>Gaius. <em>Institutes</em> (c. 161 AD), trans. W. M. Gordon &amp; O. F. Robinson. Duckworth, London, 1988.</li>
                    <li>Goodwin-Gill, G. S. &amp; McAdam, J. <em>The Refugee in International Law</em>, 4th ed. Oxford University Press, Oxford, 2021.</li>
                    <li>Hernandez, K. <em>Blockchain for Development: Hope or Hype?</em> IDS Rapid Response Briefing, Institute of Development Studies, 2017.</li>
                    <li>Kesby, A. <em>The Right to Have Rights: Citizenship, Humanity, and International Law</em>. Oxford University Press, Oxford, 2012.</li>
                    <li>Locke, J. <em>Two Treatises of Government</em>. Awnsham Churchill, London, 1689.</li>
                    <li>Nozick, R. <em>Anarchy, State, and Utopia</em>. Basic Books, New York, 1974.</li>
                    <li>Pritchett, L. <em>Let Their People Come: Breaking the Gridlock on Global Labor Mobility</em>. Center for Global Development, Washington, DC, 2006.</li>
                    <li>Tobin, A. &amp; Reed, D. The Inevitable Rise of Self-Sovereign Identity. Sovrin Foundation White Paper, 2017.</li>
                    <li>UN High Commissioner for Refugees. <em>Global Trends: Forced Displacement in 2023</em>. UNHCR, Geneva, 2024.</li>
                    <li>United Nations. <em>Convention Relating to the Status of Refugees</em>. 189 UNTS 137, 1951; expanded by the 1967 Protocol, 606 UNTS 267.</li>
                    <li>US Department of the Treasury, Office of Foreign Assets Control. Treasury Sanctions Notorious Virtual Currency Mixer Tornado Cash. Press release, August 8, 2022.</li>
                    <li>US Department of the Treasury. Tornado Cash Delisting. Press release, March 21, 2025.</li>
                    <li><em>Van Loon v. Department of the Treasury</em>, 122 F.4th 331 (5th Cir. 2024).</li>
                    <li>Van Valkenburgh, P. Analysis of the Tornado Cash Sanctions: How Far Does Treasury&rsquo;s Authority Reach? Coin Center Report, 2022.</li>
                    <li>W3C. Decentralized Identifiers (DIDs) v1.0: Core Architecture, Data Model, and Representations. W3C Recommendation, July 2022.</li>
                    <li>World Food Programme. <em>Building Blocks: Blockchain for Humanitarian Assistance</em>. WFP (with UNHCR biometric registration), ongoing since 2017.</li>
                </>
            }
        >
            <PaperSection title="1. Introduction">
                <p>
                    The legal infrastructure of commerce presumes a recognized civil subject. Contract law requires parties whose standing the forum will accept; banking access requires identity documents the domestic regime issues; commercial-dispute adjudication requires a court whose jurisdiction reaches both sides. Each of these presumptions is so deeply embedded in the architecture of contemporary trade that its failure mode &mdash; populations for whom the presumptions do not hold &mdash; is treated by the architecture as exception rather than as a system property.
                </p>
                <p>
                    The United Nations Refugee Agency estimated 117.3 million forcibly displaced persons worldwide at the end of 2023, and approximately 4.4 million persons registered as stateless, with a substantially larger estimated population whose statelessness is undocumented (UNHCR, 2024). An overlapping and considerably larger population lacks stable banking and enforcement access for reasons of informal migration status, residence without papers, or residency in jurisdictions whose financial infrastructure does not reach them. Across these categories, the productive capacity of well over a hundred million working-age adults is systematically underused because the legal scaffold for engaging it is absent. The humanitarian-economics literature on refugee economies (Betts &amp; Collier, 2017) and the policy frontier between camp and labor market (Pritchett, 2006) documents the cost of this gap and the existing repertoire of responses.
                </p>
                <p>
                    This paper argues that the kernel changes the architectural posture of the gap. The kernel operates on parties whose existence as parties does not require civil-legal recognition. A wallet can sign; a bonded commitment can resolve; an exchange can complete &mdash; without a host-state court, a domestic bank, or a permission-to-work visa sitting between the parties. The present paper develops the consequence for populations to whom the labor-law debate is a second-order question, because the first-order question is whether they are recognized parties to any contract in any forum at all.
                </p>
                <PaperRun title="What this paper is not.">
                    This paper does not claim that the kernel resolves statelessness. It does not confer citizenship, restore legal recognition, or create enforcement against a state that denies a person&rsquo;s standing. It is not a substitute for the political work that addresses those gaps &mdash; work that remains necessary, that this paper does not duplicate, and that no technological infrastructure can perform. It does not predict adoption rates, endorse any particular humanitarian program, or assess the political consequences of widespread wallet adoption among displaced populations. Its argument is structural: the architectural posture of the commerce-access gap changes once a kernel whose precondition is a cryptographic key exists.
                </PaperRun>
                <PaperRun title="Paper organization.">
                    Section 2 summarizes the kernel in the terms relevant here. Section 3 states the paper&rsquo;s premise: the wallet can be a party where no civil-legal party exists. Section 4 develops self-sovereignty as the cryptographic precondition. Section 5 develops the central claim, leading with the Arendtian analysis of statelessness and the boundary it imposes on the thesis, then the scale of the affected population, the architecture they face, and what the kernel does and does not do. Section 6 names the operational constraints the kernel does not dissolve, foremost among them the funding constraint that bounds Section 5&rsquo;s claim. Section 7 concludes.
                </PaperRun>
            </PaperSection>

            <PaperSection title="2. The Kernel">
                <p>
                    The mechanism is summarized here only as far as the argument needs.
                </p>
                <p>
                    The kernel has two calls, and each carries a mechanism design of its own. <em>Commit</em> forms a bilateral edge under <em>asymmetric bonding</em>: both parties sign the commitment from their own wallets, the buyer locks twice the payment, <Math>{"2P"}</Math>, and the seller locks twice the value the process has accumulated through its own link, <Math>{"2G"}</Math> &mdash; where <Math>{"G"}</Math> counts every payment committed in the process up to and including the seller&rsquo;s own, a figure fixed by arithmetic on the signed accumulator rather than reported by anybody. <em>Resolve</em> closes the process under <em>buyer dominance with atomic resolution</em>: only the buyer may call it, it resolves every active order in the process together or none of them, and it is terminal. There is no platform between the parties, no arbitrator authorized to resolve a process, and no admin key permitting external override.
                </p>
                <p>
                    The two calls compose in a definite order, and that order is the equilibrium. After performance, resolving is unconditionally strictly better for the buyer &mdash; resolving returns its bond less the payment it agreed to make, where withholding leaves the whole bond locked and the payment out of everyone&rsquo;s reach inside it &mdash; and given that, performance is each seller&rsquo;s strict best response. The comparison is made on what a defector would keep as well as on what the mechanism moves: a party that walks off with the value at its link still holds that value, and the doubled bond is what leaves the walking-off costly <em>after</em> crediting the party with everything it retains. The goods and the parties&rsquo; knowledge of them stay off the chain; what the chain holds is the two parties, the denomination, the payment, the bonds, the signed accumulator, and the commitments themselves.
                </p>
                <p>
                    The features that matter for the present paper are three. First, the mechanism does not require either party to be a recognized civil subject; it requires each to control a key that can sign and to fund the bond that key commits. Second, it does not require a forum to enforce the agreement: the bonds are the enforcement, each party&rsquo;s being its own deterrent. Third, it does not route value through a banking intermediary: no institution credits an account; the kernel holds the bonds from commit and transfers to the parties&rsquo; wallets at resolution, atomically. What the bonds discipline is resolution &mdash; whether a party that can perform will. They do not decide the honest disagreement about whether what arrived met the agreement: the mechanism holds no test of performance and decides nothing there, so the parties work it out between themselves while the process stands open, with an outside forum ruling on the open data if the parties have one they can both reach. For the population this paper concerns, that is often precisely what is missing (&sect;5.3), and the architecture does not depend on it: no forum can resolve a process in the buyer&rsquo;s place, so the bonded positions stand, and the buyer&rsquo;s resolution &mdash; terminal acceptance, taken once it is satisfied &mdash; is the only thing that closes them.
                </p>
                <p>
                    For the present paper both mechanisms are load-bearing. Asymmetric bonding removes the trusted enforcer; buyer dominance with atomic resolution removes the trusted clearing house, resolving a whole multi-party process at one signature rather than at an intermediary&rsquo;s ledger entry. The displaced or stateless subject lacks access to either, and the kernel&rsquo;s contribution is to make both unnecessary.
                </p>
            </PaperSection>

            <PaperSection title="3. A Party Where No Civil-Legal Party Exists">
                <p>
                    A binding contract needs six elements &mdash; offer, acceptance, consideration, capacity, legality, mutual assent &mdash; and of the six, two turn on a polity: legality, which it confers on the act and which Section 6 takes up, and capacity, which it confers on the party &mdash; the recognized ability to bind oneself, which contract law withholds from the minor and the incapable. Capacity is distinct from standing, the ability to be heard by a forum; a party may have the first and lack the second, and Section 6 treats the second under adjudication. The kernel has a capacity test of its own, and it is two acts. A wallet signs, and the signature verifies against the key alone; a wallet funds its bond, and the funding is a transfer the kernel pulls from the wallet&rsquo;s balance in the denomination the process uses. The kernel consults no registry of recognized subjects, and nothing else is asked about the party&rsquo;s standing; the denomination&rsquo;s issuer may consult a registry of its own, which is the constraint of Section 6. The premise this paper adopts follows from that test rather than preceding it. Roman law divided its subject matter into persons, things, and actions (Gaius, <em>Institutes</em> 1.8), and the thing owned and the party who acts have been distinct categories since: property is held by a person, and a person is what a polity recognizes. Roman law itself knew the exception that is this paper&rsquo;s structure &mdash; the slave, a thing in law, who transacted on a <em>peculium</em> and bound others by it &mdash; and treated it as an anomaly to be contained rather than a category. A wallet is a key-pair, held and transferable &mdash; a thing; it is also a signer, a bonder, and a receiver of resolution &mdash; a party; and the kernel sees one address doing both, so the productive asset is at once property and party. Where one or both parties lack persona status in the host jurisdiction at all, the wallet provides a party to the transaction whose existence does not depend on the prior existence of a recognized civil subject: the wallet can be a party where no civil-legal party exists.
                </p>
                <p>
                    This is not a claim that the wallet <em>is</em> a civil-legal subject. Civil-legal subjecthood is conferred by polities, and its absence is a political condition. The claim is narrower: a party to a bonded commitment can transact, resolve, and accumulate the data its closed processes leave without first acquiring civil-legal subjecthood, because the kernel does not consult the polity for permission to resolve a bond. One consequence of the wallet being a thing as well as a party must be stated rather than left to be found: the data is the wallet&rsquo;s, never the person&rsquo;s. A key that is sold carries the wallet&rsquo;s history to its buyer, as a business sold with its books does, with one difference a business sale lacks: the sale does not divest the seller, since the kernel authenticates whoever holds the key and knows no title, so the history is portable and copyable at once, and that bounds what the data can evidence about any one person. A key that is lost loses the history outright; the person&rsquo;s claim on that history is possession of the key and nothing else. That is not a paradox in the thesis but a constraint on it, and Section 6 names it under custody.
                </p>
            </PaperSection>

            <PaperSection title="4. Self-Sovereignty: The Cryptographic Key as Precondition">
                <p>
                    The previous section established that the wallet can be a party where no civil-legal party exists. The deeper observation, which the self-sovereign-identity literature has been developing independently of the kernel&rsquo;s context, is that this arrangement is a particular kind of agency that deserves a name distinct from both <em>civil-legal personhood</em> and the older <em>natural personhood</em> the philosophical tradition has analyzed. The name we adopt, following Allen (2016) and the broader self-sovereign-identity literature (Tobin &amp; Reed, 2017; W3C DID, 2022), is <em>self-sovereignty</em>: the condition of an agent whose capacity to bind, transact, and accumulate verifiable history derives from cryptographic self-control rather than from recognition by a polity.
                </p>
                <PaperRun title="Three acts, three preconditions discharged.">
                    A bonded transaction reduces to three acts at the participant&rsquo;s side, and each has historically required a civil-legal precondition the kernel replaces with a cryptographic one. <em>Signing:</em> the act of binding oneself to terms has required a recognized capacity to enter contracts (adulthood, sound mind, jurisdictional standing); under the kernel the capacity to sign is the capacity to control a private key, and the signature verifies against the signing key without consulting any registry of recognized subjects. <em>Bonding:</em> pledging assurance has required a counterparty willing to extend credit, a court willing to enforce a guarantee, or a recognized residency status enabling a banking relationship; under the kernel it is the act of funding a bond in a permissionless token, its refund on cooperation enforced by the kernel, not a court; this is the second half of the capacity test, and the half the objection that a wallet never needed recognition to sign overlooks &mdash; signing was never the barrier, funding a bond that makes the signature credible was. <em>Resolving:</em> receiving consideration has required a banking relationship that can credit the receiving party in the receiving jurisdiction&rsquo;s currency; under the kernel the payment and the refunds are transfers the kernel makes to the parties&rsquo; wallets at resolution, with no account credited in between. The architectural property is unconditional; the operational property in any given denomination is not, since the bond-denomination currency is itself a jurisdictional artifact (USDC is freezable by Circle on Treasury request; ETH is acquired through KYC-gated exchanges) &mdash; the constraint developed in Section 6 below.
                </PaperRun>
                <PaperRun title="What self-sovereignty does and does not mean.">
                    The <em>self-sovereign-identity</em> (SSI) literature (Allen, 2016; Tobin &amp; Reed, 2017) is grounded in identity specifically: the participant holds verifiable credentials about themselves rather than depending on identity providers. Allen&rsquo;s ten principles extend beyond credential-holding into the agency-of-interaction register, and the sense we develop is the commerce-specific narrowing of those agency principles &mdash; applied to the signing, bonding, and resolving acts of bilateral commerce rather than to identity per se. The W3C Decentralized Identifiers specification (2022) formalizes the architectural shape (identifiers controlled by the subject through cryptographic keys, with no central registrar), but SSI in the W3C-DID register is about <em>identity</em>, and the kernel does not implement identity: the kernel knows wallets, not persons. The <em>libertarian / Lockean</em> sense of sovereignty (Locke, 1689; Nozick, 1974) is normative &mdash; natural rights of self-ownership that political arrangements must respect &mdash; and the kernel is silent on it; it provides architecture, not ethics. The sense we adopt is narrower than either: an agent whose commercial agency is operationally constituted by cryptographic self-control rather than by polity recognition &mdash; a structural fact about how the kernel operates, not a normative claim about how it should. The agency applies universally &mdash; any wallet that signs, bonds, and resolves exercises it &mdash; but its marginal value is asymmetric. A participant whose civil-legal subjecthood is already conferred and stable has plenty of paths to express commercial agency; the kernel is one substrate among many. A participant whose subjecthood is denied or unstable does not have those paths, and for them the operational self-sovereignty the kernel supplies <em>is</em> the agency, not an augmentation to it.
                </PaperRun>
            </PaperSection>

            <PaperSection title="5. The Capacity to Have Commerce">
                <PaperSubsection title="5.1 Arendt and the Right to Have Rights">
                    <p>
                        Arendt (1951) observed that the fundamental human right is the right to have rights &mdash; the right to belong to a political community within which one&rsquo;s other rights have standing. Her analysis of statelessness named the condition as a civilizational failure rather than an individual misfortune. The person without a polity is not merely deprived of specific rights; they are deprived of the institutional setting in which having-rights is even a coherent claim. The remedy is political, not technological.
                    </p>
                    <p>
                        The Arendtian objection is sharper than the surface formulation. Part II, Chapter 9 of <em>The Origins of Totalitarianism</em> is not only a diagnosis of statelessness; it is an analysis of a specific kind of <em>worldlessness</em> &mdash; the loss not of particular entitlements but of the standing of the human person within a public world that confers significance on their actions. Arendt&rsquo;s (1958) later distinction between <em>labor</em>, <em>work</em>, and <em>action</em> sharpens this: the world is constituted through action visible to others, in a public space within which the actor is recognized as an actor. The Arendtian objection to a &ldquo;capacity to have commerce&rdquo; framing is therefore not that commerce is unimportant for the displaced; it is that commerce-without-polity &mdash; commerce without recognition by any political community &mdash; may be the deepening of worldlessness rather than its alleviation &mdash; participation in <em>labor</em> (the metabolic necessity of staying alive) without re-entering <em>action</em> (the recognized public act).
                    </p>
                    <p>
                        We take the objection seriously and decline it on these terms. The capacity-to-have-commerce we describe is not a substitute for membership; it is a structural precondition that membership historically subsumed and that, where membership is denied, can be supplied separately. The bonded transaction does include a recognition function in Arendt&rsquo;s sense, on a small scale: the commitment is dual-signed, the performance is attested, the data a closed process leaves is public in aggregate, and the counterparty acknowledges the participant as a party with whom binding agreements can be made. This is not the political recognition Arendt regarded as fundamental &mdash; co-membership in a polity &mdash; but it is not nothing in her register either. The disanalogy must be conceded rather than blurred: bilateral acknowledgment by a counterparty is not plural appearance before a public, and no accumulation of bilateral acknowledgments amounts to the shared world in which Arendtian action appears. What the substrate supplies is narrower &mdash; portable evidence of the participant&rsquo;s performances &mdash; not coextensive with political membership, but filling a gap statelessness has historically left empty.
                    </p>
                    <p>
                        The kernel does not grant the right to have rights; it grants, more narrowly, a capacity to have commerce, and only to those who retain the tokens to fund a bond &mdash; the boundary developed fully in Section 6. The right to have rights is political and is not within the gift of any technology. The capacity to have commerce is structural and becomes operational once the cryptographic infrastructure is in reach and a bond can be funded. For populations for whom the first right is denied but something to bond survives, the second capacity is non-trivial; for populations for whom the first right is granted, the second is largely subsumed by existing institutions. The kernel&rsquo;s leverage is asymmetric: where the conventional infrastructure works, it adds modestly; where recognition fails but something to bond remains, it adds the architectural condition for participation at all.
                    </p>
                    <PaperRun title="The protection-gap residue the substrate cannot reach.">
                        The 1951 Refugee Convention and its 1967 Protocol enumerate rights the host state owes refugees within its territory (<em>non-refoulement</em>, access to courts, identity and travel papers, employment, public education, public relief &mdash; Refugee Convention, 1951; Goodwin-Gill &amp; McAdam, 2021). The right to have rights as Arendt names it is closer to the spirit of the Convention than to any single article; the Convention operationalizes the spirit through specific institutional duties (Kesby, 2012; Benhabib, 2004). The kernel supplies none of these: it cannot prevent <em>refoulement</em>, grant access to courts, or issue identity papers, travel documents, or work permits. The protection gap Goodwin-Gill &amp; McAdam describe is real, vast, and political; the substrate addresses one of its many components (the inability to bind in commerce without a recognized counterparty) and leaves the others where they were. The position we hope to occupy is closer to Benhabib&rsquo;s: the rights-of-others framework identifies layers of moral and legal claim that are differently secured by different institutional arrangements, and the bonded substrate adds one such layer (commerce-binding capacity) without displacing the others.
                    </PaperRun>
                </PaperSubsection>
                <PaperSubsection title="5.2 Scale">
                    <p>
                        Beyond the UNHCR figures cited in the introduction, the relevant population is broader than the forcibly-displaced and stateless categories alone. Undocumented migrants who hold no recognized status in their country of residence, internally displaced persons whose host sub-jurisdiction does not extend banking infrastructure to their location, and populations in failed-state or contested-sovereignty zones whose nominal citizenship is not exercisable for commercial purposes all share the operationally-relevant property: they cannot reliably enter the legal infrastructure of commerce as recognized parties. Estimates of the combined population vary substantially with definition; the order of magnitude is hundreds of millions, not millions. Not all of this population can fund a bond &mdash; the qualification Section 6 develops &mdash; and what fraction can is not known: displacement dispossesses unevenly, and holding something transferable while lacking recognized civil-legal standing is common enough among the categories named above that the fraction is plausibly non-trivial, but no survey this paper can cite measures it, and the thesis&rsquo;s scope is exactly that fraction.
                    </p>
                </PaperSubsection>
                <PaperSubsection title="5.3 The Received Architecture">
                    <p>
                        Labor law, contract law, banking, and commercial-dispute adjudication each presume a recognized legal subject attached to a jurisdiction that enforces their rights. The relevant populations occupy the negative space of that presumption.
                    </p>
                    <ul className="list-disc pl-6 space-y-2">
                        <li>The employment relation is typically unavailable to them formally: permission-to-work requirements gate access to the employee category, and undocumented work, where it occurs, occurs outside legal recognition.</li>
                        <li>The independent-contractor relation is unstable: cannot register a business in many jurisdictions of residence, cannot enforce contracts in local courts that do not recognize the party&rsquo;s standing, cannot reliably serve process across jurisdictional boundaries.</li>
                        <li>Banking access is restricted or absent: opening an account typically requires documents of residency and identity the population does not have in the form the host jurisdiction recognizes.</li>
                        <li>Adjudication has no stable forum: commercial disputes have no local court willing to hear them from a party whose standing is contested.</li>
                    </ul>
                    <p>
                        The humanitarian-economics tradition has documented the cost of this gap. Betts &amp; Collier (2017) argue that displaced populations are systematically prevented from contributing to the economies that host them by an institutional architecture designed for citizens, so the host economy captures little of the productive capacity the displaced bring and the displaced themselves remain dependent on humanitarian transfers when productive participation would be both possible and preferred. Pritchett (2006) makes the broader argument about labor-mobility friction and the welfare cost of the institutional gap between origin and destination labor markets.
                    </p>
                </PaperSubsection>
                <PaperSubsection title="5.4 What the Primitive Does and Does Not Do">
                    <p>
                        Section 1 named what the kernel does not do. What it does is structurally narrower:
                    </p>
                    <ol className="list-[lower-alpha] pl-6 space-y-3">
                        <li>It provides a commerce architecture whose precondition is a cryptographic key rather than a recognized civil-legal subjecthood. A wallet does not require a passport to bond; a bonded commitment does not require a host-state court to enforce; a resolved exchange does not require a domestic bank to clear.</li>
                        <li>It produces verifiable data of what was undertaken, attested, and closed, and that data travels with the wallet across jurisdictional boundaries. A contributor whose civil-legal subjecthood is contested in jurisdiction <Math>{"A"}</Math> accumulates the same on-chain attestation history as one whose status is decided in jurisdiction <Math>{"B"}</Math>. The data is portable in a way that conventional employment or contracting papers are not.</li>
                        <li>It opens a region of productive activity &mdash; bilateral, bonded, resolved directly between parties &mdash; to participants for whom the legal scaffold that conventionally underwrites such activity is unavailable. The set of activities thus opened is bounded by what can be coordinated bilaterally and resolved atomically; the bound is non-trivial but not all of productive activity.</li>
                    </ol>
                    <p>
                        These are descriptive properties of the architecture. They do not depend on any humanitarian program or any particular legal reform; they follow from the construction of the kernel.
                    </p>
                </PaperSubsection>
            </PaperSection>

            <PaperSection title="6. Operational Constraints">
                <p>
                    The kernel moves the commerce-access gap from architectural impossibility to operational engineering question; it does not solve the engineering question. We name the six constraints that remain, and the World Food Programme&rsquo;s <em>Building Blocks</em> pilot (with UNHCR providing biometric registration, deployed in Jordan from 2017 and expanded across several refugee operations) supplies existing evidence for two of them: independent evaluations (Coppi &amp; Fast, 2019; Hernandez, 2017) find the programs deliver real operational improvements in coordination and disbursement, but locate the binding constraint not in on-chain recognition of the participant &mdash; which the architecture supplies straightforwardly &mdash; but in the on-ramp to local purchasing power and in host-state gatekeeping of who may transact with whom, which are the second and third constraints below. The displaced beneficiaries in these pilots do not bond; they receive. The kernel extends the architecture to a use case the pilots have not yet exercised at scale: the displaced participant as <em>counterparty</em> in a productive bilateral exchange rather than as recipient of one-sided disbursement.
                </p>
                <PaperRun title="Access: key custody and the fiat on-ramp.">
                    Two constraints bound the population&rsquo;s practical access to the architecture even where it is legally reachable. Populations with unreliable access to power, devices, and connectivity face usability barriers at the cryptographic layer the kernel does not solve; loss-of-key risk is high in unstable environments, and key-recovery infrastructure for displaced populations is not built. Solutions exist &mdash; a key split into shares that trusted contacts hold and can reassemble, social-recovery accounts where those contacts can collectively replace a lost key (Buterin, 2021), custodial wallets with revocable trust &mdash; but each carries its own threat model and trade-offs the population is poorly positioned to evaluate, and one bound is the kernel&rsquo;s: a commitment is signed by a key, not by an account, so recovery that replaces the key at the account level reaches the buyer&rsquo;s act of resolving but not the signature that commits, and for the signature only key-level recovery serves. Separately, converting wallet-denominated value to local currency still runs through existing rails, which remain gated for the population in question; the kernel operates on a public chain, and the bridge to local purchasing power remains a separate problem with its own gatekeepers, partially closed where local merchants accept stablecoins directly.
                </PaperRun>
                <PaperRun title="Counterparty and currency gatekeeping.">
                    A well-resourced buyer in a recognized jurisdiction may decline to bond with a counterparty whose civil-legal standing is contested &mdash; not because of the kernel, but because of downstream legal exposure in the buyer&rsquo;s home jurisdiction (sanctions screening, anti-money-laundering obligations, forum-of-enforcement concerns). The kernel&rsquo;s effect, where it has one, is to shift this friction from architectural (&ldquo;commerce with the displaced is impossible&rdquo;) to discretionary (&ldquo;some counterparties will, others will not&rdquo;). The same reach extends to the bond&rsquo;s denomination currency, which is itself a jurisdictional artifact: the kernel is denomination-agnostic, but the denominations available in practice are not. The principal US-dollar-pegged stablecoin (USDC) is issued by Circle, a US entity subject to OFAC enforcement and capable of freezing addresses on Treasury request; how far that reach extends is contested rather than settled. The Tornado Cash sanctions of August 2022 designated the mixer and a list of its contract addresses (US Department of the Treasury, 2022), which Van Valkenburgh (2022) read as sanctioning immutable open-source code rather than an entity; the Fifth Circuit then held that the immutable contracts among them are not property a sanctioned person can own and so lie outside the statute (<em>Van Loon v. Department of the Treasury</em>, 2024), and the Treasury delisted the code (US Department of the Treasury, 2025). What the episode leaves standing is the narrower fact that matters here: an issuer can freeze the addresses that hold its token, and a court&rsquo;s narrowing of the state&rsquo;s reach over code does not narrow the issuer&rsquo;s reach over its own ledger. ETH is a neutral substrate at the protocol level but is acquired through exchanges that KYC.
                </PaperRun>
                <PaperRun title="Adjudication: no forum both parties can reach.">
                    The population this paper concerns is the one for which the reachable-forum assumption fails most often. A party whose standing is contested has no local court willing to hear its commercial dispute (&sect;5.3), and a counterparty in a recognized jurisdiction has no forum whose process reaches the other side; where a forum can be named at all, the naming is a privilege of the better-placed party. What this costs is specific, and it is worth stating exactly, because the kernel neither supplies a forum nor depends on one. The honest disagreement over whether what arrived met the agreement is precisely the case the bonds do not decide, so a party without a reachable forum loses the aid that would otherwise inform its remedy negotiation. It does not lose the mechanism&rsquo;s own discipline: no forum can resolve a process in the buyer&rsquo;s place, so a forum&rsquo;s absence subtracts nothing from the bonded positions themselves, which stand with each party&rsquo;s bond exposed for as long as the process is open and close only on the buyer&rsquo;s acceptance. The data, meanwhile, travels with the parties should a forum ever become reachable &mdash; it shows what was undertaken and what was never closed, though never what was performed. Ordinary courts read that data as evidence wherever they sit, and nothing in the mechanism limits recourse to them; what this population lacks before a court is not evidence but standing. The constraint is real and it is bounded: it removes an aid to deciding disagreements, not the deterrent that makes deciding them worthwhile.
                </PaperRun>
                <PaperRun title="Legality: the element the kernel does not supply.">
                    A contract with a party whose presence a polity does not recognize is, in some jurisdictions, not merely unenforceable but void, and in some the act of contracting is itself an offence &mdash; the employment of a person without permission to work being the common case. Legality is the sixth element of a binding contract, and the kernel supplies none of it: a process resolves whether or not the polity would have it resolve, because the kernel consults no polity, and the parties bear whatever exposure the polity attaches to what they did. Downstream legal exposure, above, is therefore the counterparty&rsquo;s reading of this constraint; this is the displaced party&rsquo;s. The kernel makes a promise credible; it does not make a trade lawful, and this paper claims nothing of the second kind.
                </PaperRun>
                <PaperRun title="The funding constraint &mdash; and the boundary of this paper&rsquo;s thesis.">
                    The bond is the party&rsquo;s own deterrent, not an asset it holds or a facility it can draw on. A party with nothing to bond cannot yet bond &mdash; a material reality the mechanism does not paper over with lending instruments: a financed bond is not the party&rsquo;s own skin, and hedging or borrowing the deterrent unwinds the equilibrium it exists to create. The kernel&rsquo;s equilibrium results assume only agency and a funded bond &mdash; that each party can choose its own actions and holds the tokens to fund its bond &mdash; and are otherwise jurisdiction-invariant, invoking no legal freedom, status, or standing. For the present analysis this is not one constraint among several but the constraint that fixes the thesis&rsquo;s scope: displacement and statelessness correlate with asset loss, and for the fraction of the affected population whose displacement has also stripped them of everything they could bond, the kernel has no present contribution to make. This paper&rsquo;s claim &mdash; a capacity to have commerce where the capacity to have rights is denied &mdash; therefore holds only for the population that can still fund a bond despite lacking civil-legal recognition, not for the population that lacks both.
                </PaperRun>
                <p>
                    The cumulative effect of these constraints is that the kernel is not a solved-problem deliverable for displaced populations today. Its present-tense contribution is architectural, and bounded to those who can fund a bond: commerce-without-recognition can be built, and the constraints that remain are engineering problems with engineering solutions rather than structural features of the legal infrastructure.
                </p>
            </PaperSection>

            <PaperSection title="7. Conclusion">
                <p>
                    The kernel changes the architecture of the commerce-access gap that statelessness creates, by replacing the precondition of recognized civil-legal subjecthood with the precondition of a cryptographic key. The change is not in the political condition of the populations under discussion; it is in the institutional architecture they face when they attempt to participate in productive activity across jurisdictional boundaries.
                </p>
                <p>
                    The paper is positional. It identifies a gap, names the architectural change, and acknowledges the operational constraints that remain. The programmatic work &mdash; building key-custody infrastructure for refugee populations, partnering with humanitarian organizations to evaluate where bonded commerce is structurally feasible and where it is not &mdash; is for the practitioners who do that work. The contribution of this paper is to make the architectural change legible to scholarship that has not yet recognized it as available.
                </p>
            </PaperSection>
        </PaperLayout>
    );
}
