// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

/// @title ISP1Verifier — Interface for SP1 on-chain proof verification
/// @custom:audit-status UNAUDITED — This interface has not been reviewed by an independent security auditor.
/// @notice Matches the Succinct SP1 verifier gateway interface.
///         See https://docs.succinct.xyz/docs/onchain-verification
interface ISP1Verifier {
    /// @notice Verify a proof generated by the SP1 zkVM.
    /// @param programVKey The verification key of the proven program (ELF hash).
    /// @param publicValues The ABI-encoded public values committed by the program.
    /// @param proofBytes The serialized proof bytes.
    /// @dev MUST revert if the proof is invalid.
    function verifyProof(bytes32 programVKey, bytes calldata publicValues, bytes calldata proofBytes) external view;
}
