import type { Metadata } from "next";
import { withOg } from "@/lib/shared/pageMetadata";
import {
    PaperLayout,
    PaperSection,
    PaperRun,
    PaperRemark,
} from "@/components/papers/PaperLayout";

export const metadata: Metadata = withOg({
    title: "The Ungoverned Substrate — Figaro Protocol",
    description:
        "The network-state and blockchain-governance programs both assume the alternative to state coordination must itself be a governed entity. The bonded settlement primitive realizes a third option: an invariant, ungoverned substrate on which arbitrary governed entities compose.",
});

export default function UngovernedSubstratePaper() {
    return (
        <PaperLayout slug="ungoverned-substrate"
            title="The Ungoverned Substrate"
            subtitle="Network States, Blockchain Governance, and the Option Both Programs Presuppose Away"
            author="Figaro"
            date="April 2026"
            watermark="Figaro Protocol · Preprint"
            keywords="network state, blockchain governance, lex cryptographica, ungoverned substrate, decentralized autonomous organization, governance at the graph"
            abstract={
                <>
                    <p>
                        Two contemporary research programs have addressed what kind of polity a network-native coordination architecture might support. The first, Srinivasan&rsquo;s (2022) <em>network state</em>, proposes a community that forms online, accumulates cohesion and shared institutions, and ultimately seeks territorial and diplomatic recognition. The second, developed by De Filippi &amp; Wright (2018) and the collaborators around the Coalition of Automated Legal Applications (COALA), examines the legal and governance consequences of running rules through code: <em>lex cryptographica</em>, decentralized autonomous organizations, on-chain governance. The two programs differ in goal &mdash; one constitutional, the other infrastructural &mdash; but share a structural premise: the alternative to state coordination must itself be a <em>governed entity</em>, and governance is a question that arises at the network or protocol layer and must be answered there.
                    </p>
                    <p>
                        This paper observes that the bonded settlement primitive admits a third option neither program names: an <em>ungoverned substrate</em> on which arbitrary governed entities can be constituted, but which itself is not a governed entity at all. The substrate does not vote, does not upgrade, has no constitution, no representatives, no protocol-level discretion. Network states can be constituted on it; so can DAOs, cooperatives, peer networks, sole traders, and agent coalitions. The claim is not that either program is wrong on its own terms &mdash; both are coherent programs addressing real questions &mdash; but that the architectural option they presuppose away is the one the bonded primitive realizes. Recognizing it does not adjudicate among governed arrangements; it relocates the governance question from the substrate, where both programs place it, to the graph, where the substrate admits it to be answered in arbitrarily many ways.
                    </p>
                </>
            }
            references={
                <>
                    <li>Compound Labs. Compound Governor: On-Chain Governance Module. Compound Protocol Documentation, 2020.</li>
                    <li>De Filippi, P. &amp; Hassan, S. Blockchain Technology as a Regulatory Technology: From Code is Law to Law is Code. <em>First Monday</em>, 21(12), 2016.</li>
                    <li>De Filippi, P., Mannan, M., &amp; Reijers, W. Blockchain as a Confidence Machine: The Problem of Trust &amp; Challenges of Governance. <em>Technology in Society</em>, 62:101284, 2020.</li>
                    <li>De Filippi, P. &amp; Wright, A. <em>Blockchain and the Law: The Rule of Code</em>. Harvard University Press, Cambridge, MA, 2018.</li>
                    <li>DeepDAO. DAO Treasury Aggregate Statistics. DeepDAO Analytics Platform, 2024.</li>
                    <li>Hirschman, A. O. <em>Exit, Voice, and Loyalty: Responses to Decline in Firms, Organizations, and States</em>. Harvard University Press, Cambridge, MA, 1970.</li>
                    <li>Lessig, L. <em>Code: Version 2.0</em>. Basic Books, New York, 2006.</li>
                    <li>Messari Research. The Health of DAO Treasuries. Messari, 2022.</li>
                    <li>OpenZeppelin. Governor Contracts: Reference Implementation for On-Chain Governance. OpenZeppelin Contracts Documentation, 2024.</li>
                    <li>Reijers, W. &amp; Coeckelbergh, M. The Blockchain as a Narrative Technology: Investigating the Social Ontology and Normative Configurations of Cryptocurrencies. <em>Philosophy &amp; Technology</em>, 31(1):103&ndash;130, 2018.</li>
                    <li>Sablier Labs. Sablier Protocol: Token Streaming Infrastructure. Sablier Documentation, 2023.</li>
                    <li>Srinivasan, B. <em>The Network State: How to Start a New Country</em>. Self-published, 2022.</li>
                    <li>Walch, A. The Path of the Blockchain Lexicon (and the Law). <em>Boston University Review of Banking and Financial Law</em>, 36:713&ndash;765, 2017.</li>
                    <li>Walch, A. Deconstructing &lsquo;Decentralization&rsquo;: Exploring the Core Claim of Crypto Systems. In C. Brummer (ed.), <em>Cryptoassets: Legal, Regulatory, and Monetary Perspectives</em>. Oxford University Press, New York, 2019a.</li>
                    <li>Walch, A. In Code(rs) We Trust: Software Developers as Fiduciaries in Public Blockchains. In P. Hacker, I. Lianos, G. Dimitropoulos &amp; S. Eich (eds.), <em>Regulating Blockchain: Techno-Social and Legal Challenges</em>. Oxford University Press, Oxford, 2019b.</li>
                    <li>Werbach, K. <em>The Blockchain and the New Architecture of Trust</em>. MIT Press, Cambridge, MA, 2018.</li>
                </>
            }
        >
            <PaperSection title="1. Introduction">
                <p>
                    This paper sits between political philosophy, the literature on blockchain governance, and the analysis of a particular settlement primitive. Its starting point is a question the political philosophy of coercion leaves open: when the state&rsquo;s sovereign-coercive function is partially substituted by bonded pre-commitment in bilateral commerce, what follows for the proposals that have emerged to organize coordination at the network layer?
                </p>
                <p>
                    Two such proposals have organized the recent discussion: the network-state thesis (Srinivasan, 2022), which is normative-prescriptive &mdash; a program for constituting alternative polities &mdash; and the blockchain-governance research program (De Filippi &amp; Wright, 2018, and collaborators around COALA), which is descriptive-analytical &mdash; an account of what blockchain arrangements imply for law and governance. Both share a structural assumption the present paper identifies and argues is not forced.
                </p>
                <p>
                    The shared assumption is that the network-layer alternative to state coordination must itself be a <em>governed entity</em>. The network state requires a constitutional founder, a community self-conception, an explicit governance process, and ultimately sovereign-equivalent diplomatic standing. The blockchain-governance program treats the governance of on-chain arrangements as the central problem of the field: how decisions are made about protocol evolution, who has voting power, what counts as legitimate amendment (De Filippi, Mannan &amp; Reijers, 2020). In both, the substrate of network-native coordination is itself something that must be governed.
                </p>
                <p>
                    The bonded settlement primitive provides a different option: an <em>ungoverned substrate</em>. One term should be fixed before it is used, since two things in the stack have been called by it. Throughout this paper, <em>substrate</em> means the <em>settlement substrate</em> &mdash; the invariant kernel and its two calls, and nothing else. It does not mean the <em>execution layer</em> beneath it, the chain and the services that run and reach it, which is a different object with a governance of its own and which &sect;3 takes up separately. The ungoverned claim is made of the first and not of the second. The kernel is invariant &mdash; no upgrades, no proposals, no votes, no protocol-level discretion. There is no entity of which the kernel is the constitution, because the kernel is not a constitution of anything. It is a small set of rules executed on public infrastructure, on top of which arbitrary governed entities can be composed &mdash; or which bilateral parties can use without constituting any entity at all.
                </p>
                <PaperRun title="The thesis.">
                    (1) Both programs assume the alternative to state coordination must be a governed network entity. (2) The assumption is not architecturally forced: a coordination substrate can be invariant rather than governed, and the decision is a design choice. (3) The ungoverned-substrate option does not abolish governance &mdash; it relocates governance from the substrate layer to the graph layer, where any pattern of governance (or its absence) can be composed. (4) The relocation is the political-architectural content of the substrate change, and it clarifies what each program is actually proposing: the network state is one possible graph, blockchain-governance arrangements are another, and neither is the substrate.
                </PaperRun>
                <PaperRun title="What this paper is and is not.">
                    This is a short essay in the political architecture of network coordination. It does not extend the underlying mechanism, and it takes no position on whether network states are desirable, whether DAOs are well-governed, or whether <em>lex cryptographica</em> should be recognized by conventional jurisdictions. Two disclaimers govern everything that follows. First, the paper is not a critique of either program: both analyses are substantive on their own terms, and the claim is only that the class of governance-rich arrangements they analyze is not the only class &mdash; the substrate the network state needs does not have to be one it governs, and an invariant kernel is a class to which the ongoing-governance concern does not apply. Second, it is not a claim that all protocols should be ungoverned, nor a constitutional proposal, nor a prediction: functions that genuinely require adaptability should have governance, and the substrate admits arbitrary arrangements &mdash; choosing among them is the participants&rsquo; work, and there is more political work to do at the graph layer, not less.
                </PaperRun>
            </PaperSection>

            <PaperSection title="2. The Network-State Program and Its Coordination Gap">
                <p>
                    We begin with the network-state thesis, both because it is the more public of the two programs and because its specific unsolved sub-problem is one the bonded primitive resolves.
                </p>
                <PaperRun title="The thesis as articulated.">
                    Srinivasan (2022) proposes the network state as a sequence: an online community forms around a shared interest, acquires cohesion, develops shared institutions, attains a population and a treasury large enough to act, acquires territorial presence, and ultimately seeks diplomatic recognition. A distinctive feature is the <em>one commandment</em>: the network state is organized around a single moral innovation on which the founding community has already converged. The sequence updates Hirschman&rsquo;s (1970) framework on <em>exit</em>: when voice within incumbent states becomes ineffective, exit becomes the alternative &mdash; but exit requires a destination, and the network state is the destination&rsquo;s design. The thesis takes governance as constitutive: explicit shared institutions, a founder-articulated self-conception, a process for collective decision, internal adjudication, external recognition &mdash; each a governance function the program addresses.
                </PaperRun>
                <PaperRun title="The unsolved sub-problem.">
                    The thesis names an &ldquo;economic engine&rdquo; as a constitutive stage between community formation and recognition, but treats that stage as under-specified: in practice, commerce within network-state communities continues to route through fiat rails, incumbent platforms, and the legal apparatuses of participants&rsquo; physical jurisdictions. The missing economic engine is the substrate gap, and the bonded primitive supplies it. Bilateral commercial coordination between participants, between participants and non-participants, and between two non-participants who happen to share the substrate can be conducted through bonded commitments that depend on no incumbent state apparatus and no network-state-internal governance.
                </PaperRun>
                <PaperRun title="What the thesis does not require.">
                    A subtler observation: the substrate the network-state program needs does not have to be one the network state <em>governs</em>. Treating the substrate as something to constitute under its own governance &mdash; a network-state-native blockchain, a network-state-issued currency, a network-state-operated arbitration system &mdash; recreates within the network state the very substrate-governance problem it was supposed to resolve relative to the incumbent state. The substrate it actually requires is one whose settlement rules no entity governs &mdash; a claim scoped precisely in &sect;3, where the execution layer beneath those rules is given its own account &mdash; which any entity can use, and whose neutrality makes it suitable for cross-affiliation coordination. The bonded primitive supplies a self-enforcing form without supplying any moral content: it produces no commandment of its own, so a network state organized around any one commandment can use it without the substrate constraining what the commandment can be.
                </PaperRun>
                <PaperRemark title="On exit and the missing destination.">
                    Hirschman&rsquo;s analysis assumes exit is meaningful only when it has a destination. The bonded primitive contributes a different observation: exit can be <em>partial</em>. A participant can exit the incumbent state&rsquo;s commercial-coordination apparatus without exiting its other functions &mdash; citizenship, criminal-law protection, public goods, defense. Partial exit was difficult under prior architectures because the commercial-coordination apparatus was bundled with the others; the substrate change unbundles. Whether the participant goes on to constitute a network state is a separate choice the substrate does not make for them.
                </PaperRemark>
            </PaperSection>

            <PaperSection title="3. Blockchain Governance and the Confidence Machine">
                <p>
                    We turn to the blockchain-governance program, which addresses the same substrate question from a different angle and arrives at a more textured account of what governing network-native coordination involves.
                </p>
                <PaperRun title="The program in outline.">
                    De Filippi &amp; Wright (2018) examine the legal consequences of running rules through code: <em>lex cryptographica</em> as an emerging body of computational law, smart contracts as self-executing agreements, DAOs as code-mediated coordination structures, and the hybrid arrangements that emerge when computational rules encounter conventional jurisdictions. The framing extends Lessig&rsquo;s (2006) &ldquo;code is law&rdquo; into a positive program. A consistent thread is that the apparent elimination of governance through code is illusory: rules are written by people, require interpretation when situations arise their authors did not anticipate, require change when conditions shift, and the infrastructure on which they run introduces governance through the back door even when the on-chain protocol claims to have eliminated it.
                </PaperRun>
                <PaperRun title="The hidden-fiduciary critique.">
                    Walch (2017) argues that the field&rsquo;s self-description &mdash; &ldquo;decentralized,&rdquo; &ldquo;trustless,&rdquo; &ldquo;immutable&rdquo; &mdash; functions as a vocabulary that obscures rather than describes, and that the obscuring matters legally, since these are the terms on which the systems are assessed. Walch (2019a) presses the point into a standard: &ldquo;decentralization&rdquo; is too vague to serve as a legal one, bundling distinct and independently-varying domains of power concentration, so that a system can be decentralized in some respects while remaining highly concentrated in others &mdash; among them the small groups whose decisions about the software carry practical weight over everyone who depends on it. Walch (2019b) names the relationship those groups stand in: the people who create, operate, and reshape a public blockchain function much as <em>fiduciaries</em> of those who rely on them, since users extend the leading developers a trust of the extreme kind the fiduciary literature describes &mdash; trust in their competence, and in their loyalty to the users&rsquo; interest over any conflicting one &mdash; while none of the duties such trust ordinarily attracts has been recognized. The present argument needs only the concentration and rests on that alone; the fiduciary characterization is the stronger form of the same concern, and between them they are the strongest available challenge to any assertion that a protocol has eliminated governance. Werbach (2018) arrives at an adjacent point from the trust-theory side: blockchain protocols substitute one <em>architecture of trust</em> for another, and the new architecture has its own institutional preconditions.
                </PaperRun>
                <PaperRun title="The confidence machine.">
                    De Filippi, Mannan &amp; Reijers (2020), building on Reijers &amp; Coeckelbergh (2018) reading blockchain as a narrative technology, frame blockchain as a <em>confidence machine</em>: an architecture that shifts the locus of trust from people and institutions to code and mathematics, but does not eliminate trust or governance. The framing is largely correct for the class it addresses &mdash; <em>governance-rich</em> protocols whose rules evolve, whose parameters are subject to vote, whose treasuries fund development. For such systems, trust shifted from human institutions to code does not arrive at a final resting place; it shifts to the human institutions that govern the code. A complementary thread runs the relation in both directions: De Filippi &amp; Hassan (2016) trace the movement from <em>code is law</em> &mdash; code operating as a regulatory technology in its own right &mdash; to <em>law is code</em>, where legal rules are themselves expressed in software, and treat the two as complementary registers of regulation rather than rivals.
                </PaperRun>
                <PaperRemark title="On the scope of the confidence-machine analysis.">
                    The confidence-machine analysis applies to the class it was developed for: governance-rich protocols whose rules evolve under explicit governance. It is silent on what happens when an architecture is <em>not</em> governance-rich &mdash; when its rules are invariant, no parameter is subject to vote, and no treasury funds its evolution. The present paper does not contradict the analysis; it identifies a class of arrangements outside its scope.
                </PaperRemark>
                <PaperRun title="The settlement substrate and the execution layer beneath it.">
                    Even an invariant kernel runs on infrastructure that is not invariant, and the distinction fixed in &sect;1 is what keeps the claim from overreaching. The <em>settlement substrate</em> is the invariant kernel and its two calls. The <em>execution layer</em> is everything the kernel depends on to run and to be reached: the chain and its validators or sequencers, and alongside them the RPC providers, the exchanges that price the bond currency, and the fiat on-ramps. The execution layer is neither invariant nor ungoverned. Its operators are governed entities, decisions taken there affect what happens at the kernel, and Walch&rsquo;s hidden-fiduciary critique (2019b) is the strongest version of that concern. We accept the critique and locate the kernel relative to it explicitly: the ungoverned claim is a claim about the settlement substrate as a unit of governance, and about nothing else in the stack it sits in. Governance of the execution layer &mdash; of the chain, the validator set, the service providers &mdash; is not eliminated by anything argued here; it is delegated to the chain&rsquo;s own arrangements and inherited whole by whoever chooses that chain. A participant&rsquo;s confidence therefore rests on two distinct surfaces and on nothing between them: the settlement substrate, whose rules are fixed at deployment and can be read once and relied on thereafter, and the execution layer, whose operators must go on executing them faithfully and whose composition changes under governance no participant controls. What a participant relies on in practice is the composition of the two &mdash; a fixed rule, executed by a layer that must keep executing it &mdash; and only the first of them is what the present paper claims is ungoverned.
                </PaperRun>
            </PaperSection>

            <PaperSection title="4. The Common Premise: Governance at the Substrate Layer">
                <p>
                    The network-state program assumes the alternative to state coordination is a network polity that must be governed: a founder, a constitution, a process for collective decision, a treasury, internal adjudication, external standing. The blockchain-governance program assumes the alternative to platform-mediated coordination is an on-chain protocol whose rules and parameters must be governed: a governance token, a voting process, a developer foundation, an upgrade path, external legal scaffolding. In both cases the alternative is itself a governed entity.
                </p>
                <PaperRun title="Why the assumption seems necessary.">
                    The assumption is not arbitrary. Most studied protocols are governance-rich &mdash; their parameters change, their rules admit upgrade paths, their treasuries fund development: Ethereum, Bitcoin (through its informal but real social process), Tezos, Cosmos chains, Optimism, Maker. The assumption that network-native coordination requires governance reflects the architectures the programs were analyzing.
                </PaperRun>
                <PaperRun title="Why the assumption is not architecturally forced.">
                    A protocol&rsquo;s parameters and rules need not evolve. A coordination architecture can be designed so its small invariant kernel is fixed at deployment, with all variability pushed to layers above that the kernel does not constrain. The bonded settlement primitive is such an architecture: no admin, no owner, no upgrade path, no governance token, no treasury, no parameter that can be voted on. Whatever assemblies are constituted on top inherit no governance dependency on the kernel and no obligation to participate in its evolution, because the kernel does not evolve. This is not an attempt to evade governance; it is a demonstration that governance is a substrate-design choice, not a necessity. The choice has consequences &mdash; a governance-rich protocol can adapt and correct errors; an invariant kernel cannot &mdash; but the choice exists, and pretending it does not is the move both programs make when they treat substrate-layer governance as constitutive.
                </PaperRun>
                <PaperRemark title="On governance and adaptability.">
                    The most common defense of substrate-layer governance is that adaptability is required. This is forceful for protocols whose function is itself adaptive (lending markets responding to market conditions, scaling layers responding to throughput, identity systems responding to evolving standards). It is weaker for protocols whose function is structurally invariant. A protocol that does one well-defined thing &mdash; enforce a bonded bilateral commitment &mdash; can be invariant in a way that a protocol doing many things subject to external state cannot. The adaptability defense is specific to function, not generic to protocols.
                </PaperRemark>
            </PaperSection>

            <PaperSection title="5. The Ungoverned Substrate: A Structural Alternative">
                <PaperRun title="What &ldquo;ungoverned&rdquo; means here.">
                    The kernel is governed in no respect the contemporary governance literature would recognize: no proposal process, no voting, no quorum, no veto, no executive, no foundation controlling protocol evolution, no privileged update access, no upgrade path. This is governance designed out of the substrate, not absent through inattention &mdash; and the non-discretion has two architectural sources that foreclose different things. Immutability with no admin surface forecloses <em>evolution</em> governance: the deployed bytecode is invariant, so changing the kernel&rsquo;s behavior requires deploying a <em>different kernel</em> at a different address, constituting a different protocol the existing one has no relationship to. The shape of the kernel&rsquo;s two calls forecloses <em>resolution-time</em> discretion. There are two calls and no others, and each carries a mechanism design of its own. <em>Commit</em> forms a bilateral edge under asymmetric bonding: both parties sign it, the buyer locks twice the payment, and the seller locks twice the value the process has accumulated through its own link &mdash; a figure fixed by arithmetic on the signed accumulator rather than reported by anyone. <em>Resolve</em> settles the process: only the buyer may call it, it settles every active order together or none of them, and it is terminal. The equilibrium the two produce composes in that order &mdash; after performance, resolving is unconditionally strictly better for the buyer, and given that, performance is each seller&rsquo;s strict best response. No third party is in a position to defer, partial-resolve, selectively enforce, or override, and none is needed for the result to hold. Between the invariant bytecode and the two calls there is no decision-position from which governance could be exercised, even if a governance body were stood up adjacent to the kernel.
                </PaperRun>
                <PaperRun title="What this requires of the kernel.">
                    The option is not free. It requires that the kernel&rsquo;s function be specifiable in advance and small enough to be formally specified and verified to a standard that warrants trust without ongoing governance. The ungoverned substrate is purchased by accepting the constraint that its function be amenable to this discipline.
                </PaperRun>
                <PaperRun title="This is not &ldquo;code is law.&rdquo;">
                    Lessig&rsquo;s (2006) &ldquo;code is law&rdquo; has been useful as a slogan and damaging as a method &mdash; useful because it observed that software increasingly performs law&rsquo;s regulatory function, damaging because it obscures the differences between what software and law do (a point both Walch (2017) and De Filippi &amp; Wright (2018) emphasize). The ungoverned-substrate claim does not depend on &ldquo;code is law.&rdquo; It depends on a narrower claim: that the <em>settlement primitive</em> &mdash; a single bilateral function with a deterministic outcome &mdash; is exactly the class for which formal specification, verification, and immutable deployment are appropriate, and that this class is much smaller than &ldquo;everything regulated by software.&rdquo; Law remains where it has always been: in the off-chain forums that adjudicate disputes under conventional doctrines. The kernel is not law; it is settlement infrastructure that produces evidence on which law operates.
                </PaperRun>
                <PaperRun title="What the substrate admits.">
                    A consequence of the ungoverned design is that the substrate admits arbitrary higher-layer arrangements without constraining their <em>form</em>. A community can constitute a network state on top of it, with whatever governance it chooses; a group can constitute a DAO; a cooperative can compose itself; a peer network can operate without constituting any entity; two strangers can transact once and never again. One constraint it does impose should be stated here rather than left to be discovered, because it is real: the substrate constrains the <em>signing interface</em>, not the governance form. A commitment is authenticated by the signature of the key that produced it, so an arrangement that decides collectively must designate a signer to carry its decision to the substrate &mdash; the mechanics are &sect;6&rsquo;s, and every arrangement named above composes upstream of that key. What is not constrained is how the decision behind the signature is reached, by whom, under what rules, or with what recourse. A governance-rich substrate would import its governance into every arrangement constituted on it; an ungoverned substrate imports none &mdash; arrangements owe it the use of its public infrastructure and a key that signs, and are otherwise free to govern (or not govern) themselves however their participants choose.
                </PaperRun>
                <PaperRemark title="The substrate is sub-political, not anti-political.">
                    The ungoverned substrate is not a rejection of politics or governance; it is a layer beneath them. The political question of how a network state should be governed, the institutional question of how a DAO should decide, the legal question of how an arrangement integrates with conventional jurisdictions &mdash; all remain real and unresolved at the layer at which they apply. What the substrate does is make it possible for these questions to be answered <em>differently in different arrangements</em> on the same infrastructure, rather than uniformly across all arrangements that share it.
                </PaperRemark>
            </PaperSection>

            <PaperSection title="6. Where Governance Returns: At the Graph">
                <p>
                    The argument that the substrate is ungoverned is not the argument that everything constituted on it is ungoverned. Most useful arrangements will have governance of some kind. This section identifies where governance returns and what shape it takes.
                </p>
                <PaperRun title="Assemblies as governed entities.">
                    A bonded multi-party process composed at the substrate is an assembly &mdash; a transaction-scoped arrangement of bonded commitments among multiple parties. A simple assembly (two parties, one commitment) requires no governance: the parties agreed, and the substrate enforces. A complex assembly typically does: questions arise the original commitments did not specify, parties join and leave, disputes require resolution beyond what bonding provides. For complex assemblies, governance is real work the participants must do, and the substrate provides no scaffolding for it. This is a feature, not a gap: the substrate&rsquo;s silence lets assemblies choose the form appropriate to their function &mdash; cooperative, corporate, constitutional, or none. The same absence cuts the other way, and the honest statement of it belongs here: concentrations that form at the graph layer &mdash; of retroactive reward accrual, of token holdings, of first-registered names &mdash; meet no governor either, and the design&rsquo;s answer to them is competition and disclosure rather than administration, which is a claim whose test is empirical rather than architectural. Conventional legal personality remains available to assemblies that want it, and for those that do, the relation between an arrangement&rsquo;s coded rules and the legal rules that would govern it (De Filippi &amp; Hassan, 2016) is a live question; taking it up becomes one option among many rather than a precondition.
                </PaperRun>
                <PaperRun title="How DAOs use the substrate without governing it.">
                    A common objection: DAOs need governance, the primitive is meant for DAOs to use, therefore the primitive needs a governance interface. The objection mistakes a substrate property for a runtime requirement. The kernel admits only an address whose own ECDSA key produced the signature &mdash; an externally-owned account (EOA), or an EIP-7702-delegated EOA, but never a contract wallet authenticating by returning a validity answer under ERC-1271. A DAO or multisig authorizes a signer upstream; the kernel sees only that signer&rsquo;s own signature. And because a permanently lost buyer key strands a process&rsquo;s bonds &mdash; there is no timeout and no recovery &mdash; buyer keys are expected to sit under recoverable custody, at the key-custody layer above the kernel.
                </PaperRun>
                <PaperRun title="Governance authorizes the signer.">
                    A DAO whose commitments require formal governance approval &mdash; quadratic-vote, delegation-based, optimistic &mdash; approves the commitment through its process; the authorized commitment is then signed by the account the governance designates (Compound Governor, 2020; OpenZeppelin Governor, 2024). The substrate sees only that signer&rsquo;s signature; it does not see the vote, the proposal text, or the delegation graph. The DAO&rsquo;s governance is real and operates entirely above the substrate; the substrate is invisible to the governance and the governance is invisible to the substrate.
                </PaperRun>
                <PaperRun title="Derivability from chain state.">
                    A DAO&rsquo;s substrate-settled activity is derivable from chain state: for the portion disbursed through the substrate, its disbursement history and commitment portfolio read off the public commit and resolution records without any substrate-specific accommodation. What accounting treatment those records support &mdash; how they map onto a set of books, under what recognition rules, and to whose satisfaction &mdash; is a separate subject on which this paper takes no position.
                </PaperRun>
                <p>
                    The patterns share a structural property: each composes with the substrate by treating it as a <em>signature interface</em>, not a governance interface &mdash; a DAO&rsquo;s disbursement policy, whether voted commitment by commitment or run through a streaming contract upstream of the substrate (Sablier, 2023), never reaches the substrate as a decision. The standard institutional shapes already in use among DAO and treasury operators (Messari, 2022; DeepDAO, 2024) compose with the substrate without modification. A network-state community, likewise, has its governance work fully in front of it: the substrate provides the missing economic engine, but not the constitutional process, the self-conception, the diplomatic framework, or internal adjudication &mdash; those are the network state&rsquo;s to design.
                </p>
                <PaperRemark title="On infrastructural literacy.">
                    The blockchain-governance program&rsquo;s concern that participants generally cannot evaluate the arrangements they operate under applies to the substrate as to any infrastructure. The substrate does not reduce the literacy gap; it does <em>not expand</em> it. A governance-rich protocol&rsquo;s literacy demand grows as its rules and parameters evolve; an invariant kernel&rsquo;s demand is bounded &mdash; the participant must understand the fixed rules once. This does not solve the literacy problem, but it bounds the problem in a way governance-rich protocols structurally cannot.
                </PaperRemark>
            </PaperSection>

            <PaperSection title="7. Conclusion">
                <p>
                    The network-state and blockchain-governance programs share a structural assumption that the alternative to state coordination must itself be a governed network entity. The bonded settlement primitive realizes a third option neither names: an ungoverned substrate, invariant by design, on which arbitrary governed entities can be composed but which itself is not a governed entity at all. Recognizing the option does not adjudicate among governance forms above the substrate; it relocates the governance question from the substrate to the graph.
                </p>
                <p>
                    The substantive observation is that the choice between a governance-rich substrate and an ungoverned one is a real design choice with real consequences: governance-rich substrates provide adaptability at the cost of an ongoing governance-of-the-governance burden; ungoverned substrates provide invariance at the cost of inability to adapt. For substrate functions amenable to fixed specification &mdash; the bonded settlement primitive being one &mdash; the ungoverned option is available, and its availability is what permits the diversity of higher-layer governance forms the substrate admits.
                </p>
                <p>
                    We close with an observation of method: the kernel is ideologically agnostic; the graph is the politics. The present paper has argued one case of that observation and only one &mdash; governance becomes a graph-tier choice when the settlement substrate is invariant. Parallel arguments have been made for two further variables, and this paper adopts them rather than re-deriving them. The first is subordination: no seller on the substrate is directed by any party, each bonding and settling as an independent value-adder, so any hierarchy above that is composed rather than imposed. The second is coercion: settlement within the substrate&rsquo;s domain is discretion-free, bonds settling by rule at the buyer&rsquo;s resolution, so there is no enforcer whose discretion could be leveraged against a party. Neither claim is established here, and neither is needed for the governance result; they are named because the three together make one move, whoever argues it &mdash; a feature prior architectures treated as constitutive of the substrate becomes a graph-tier choice when the substrate is designed to exclude it. The graph is the politics in a strong sense &mdash; the layer at which political-architectural choices are made on infrastructure that makes no political-architectural choices itself &mdash; and the relocation is recursive: future architectures may relocate further substrate variables still.
                </p>
            </PaperSection>
        </PaperLayout>
    );
}
