import type { Metadata } from "next";
import {
    PaperLayout,
    PaperSection,
    PaperSubsection,
    PaperRun,
} from "@/components/papers/PaperLayout";
import { Math } from "@/components/papers/Math";

export const metadata: Metadata = {
    title: "On-Chain Evidence, Off-Chain Adjudication — Figaro Protocol",
    description:
        "Settlement is on-chain by nature, adjudication is off-chain by nature. A layered approach to smart-contract dispute resolution: the protocol produces evidence existing courts already know how to use.",
};

export default function OnChainEvidencePaper() {
    return (
        <PaperLayout slug="on-chain-evidence"
            title="On-Chain Evidence, Off-Chain Adjudication"
            subtitle="A Layered Approach to Smart-Contract Dispute Resolution"
            author="Alessandro Daliana"
            date="April 2026"
            watermark="Figaro Protocol · Preprint"
            keywords="electronic evidence, smart-contract law, dispute resolution, blockchain evidence, eIDAS, UNCITRAL, jurisdictional flexibility"
            abstract={
                <>
                    <p>
                        This paper makes a legal argument about smart-contract dispute resolution. The dominant on-chain dispute-resolution designs &mdash; Kleros&rsquo;s Schelling-jury arbitration, Aragon Court&rsquo;s DAO-governed jury, optimistic-rollup challenge windows &mdash; attempt to perform adjudication on chain. We argue that this is a category error: settlement is on-chain by nature, adjudication is off-chain by nature, and conflating the two re-introduces the discretionary intermediary that smart contracts were supposed to remove.
                    </p>
                    <p>
                        We develop the argument by reference to a bonded settlement primitive &mdash; asymmetric bonding composed with buyer-dominated atomic resolution, on a formally verified kernel &mdash; whose enforcement architecture is a five-layer stack: the underlying chain&rsquo;s consensus security (Layer 0), the bonding game with its co-resident immutable record (Layer 1), the peer-coordination subgame (Layer 2), and the off-chain forums that read the record &mdash; arbitration (Layer 3) and the traditional legal system (Layer 4). The record is produced always, by construction, at the bonding layer; it is not a fallback summoned when the inner layers fail. The contribution of this paper is to develop that evidentiary record and its off-chain use in detail: the evidentiary properties of the on-chain record, the relationship between those properties and existing electronic-evidence law (eIDAS, UCC &sect;1-201, the Singapore Electronic Transactions Act, the UNCITRAL Model Law on Electronic Commerce), and the jurisdictional implications of decoupling settlement from adjudication.
                    </p>
                    <p>
                        The argument is not that smart contracts replace courts. It is that smart contracts can produce a form of evidence that courts already know how to use, and that the cleanest division of labor is one in which the protocol does what it does well (deterministic settlement) and the legal system does what it does well (contextual adjudication). The protocol is silent on what counts as &ldquo;satisfactory performance&rdquo; or &ldquo;material breach&rdquo; &mdash; those are adjudicative determinations &mdash; but loud on the facts that adjudication needs as input.
                    </p>
                </>
            }
            references={
                <>
                    <li>Cuende, L. and Izquierdo, J. Aragon Network: A Decentralized Infrastructure for Value Exchange. Aragon White Paper, 2017.</li>
                    <li>De Filippi, P. and Wright, A. <em>Blockchain and the Law: The Rule of Code</em>. Harvard University Press, Cambridge, MA, 2018.</li>
                    <li>Bloemen, R., Logvinov, L., and Evans, J. EIP-712: Ethereum typed structured data hashing and signing. Ethereum Improvement Proposal, 2017.</li>
                    <li>Ast, F. and Lesaege, C. Kleros: A Protocol for a Decentralized Justice System. Kleros White Paper, 2019.</li>
                    <li>United Nations. <em>Convention on the Recognition and Enforcement of Foreign Arbitral Awards</em> (the New York Convention). 330 U.N.T.S. 38, 1958.</li>
                    <li>Optimism Foundation. Optimistic Rollups. Optimism Technical Documentation, 2021.</li>
                    <li>Ortolani, P. The Impact of Blockchain Technologies and Smart Contracts on Dispute Resolution. <em>Uniform Law Review</em>, 24(2):430&ndash;448, 2019.</li>
                    <li>Rabinovich-Einy, O. and Katsh, E. <em>Digital Justice: Technology and the Internet of Disputes</em>. Oxford University Press, New York, 2017.</li>
                    <li>B2C2 Ltd v Quoine Pte Ltd [2019] SGHC(I) 03 (Singapore International Commercial Court).</li>
                    <li>Quoine Pte Ltd v B2C2 Ltd [2020] SGCA(I) 02 (Singapore Court of Appeal).</li>
                    <li>US Judicial Conference, Advisory Committee on Evidence Rules. Report on Proposed Amendments to FRE 902(13) and 902(14). Effective December 1, 2017.</li>
                    <li>Goode, R. and Gullifer, L. <em>Goode and Gullifer on Legal Problems of Credit and Security</em>, 6th ed. Sweet &amp; Maxwell, London, 2017.</li>
                    <li>Yunus, M. <em>Banker to the Poor: Micro-Lending and the Battle Against World Poverty</em>. PublicAffairs, New York, 1999.</li>
                    <li>Morduch, J. The Microfinance Promise. <em>Journal of Economic Literature</em>, 37(4):1569&ndash;1614, 1999.</li>
                    <li>American Institute of Certified Public Accountants. <em>AU-C Section 315: Understanding the Entity and Its Environment and Assessing the Risks of Material Misstatement</em> (assertion categories). AICPA, 2020.</li>
                    <li>UMA Project. The Optimistic Oracle. UMA Technical Documentation, 2020.</li>
                </>
            }
        >
            <PaperSection title="1. Introduction">
                <p>
                    Smart-contract dispute resolution is currently a contested design space. The dominant architectures attempt to perform adjudication on chain, typically through some variant of token-weighted juror selection or DAO governance. Kleros (2019) uses Schelling-point juror voting; Aragon Court (2017) embeds arbitration in DAO infrastructure; optimistic mechanisms (Optimism, 2021; UMA, 2020) use challenge windows in which assertions stand unless contested. Each of these approaches addresses the dispute-resolution problem by importing the discretionary actor that would otherwise reside in a court: the juror, the DAO voter, the challenger.
                </p>
                <p>
                    This paper argues that the import is a mistake. The claim is not that on-chain juries are bad mechanisms (they are interesting mechanisms with documented properties); it is that they are solving the wrong problem. The right problem is not &ldquo;how do we adjudicate disputes on chain&rdquo; but &ldquo;how do we produce evidence that off-chain forums can use to adjudicate efficiently.&rdquo; The former requires re-creating, in adversarial token-economic settings, the institutional infrastructure (impartial juror selection, jurisdictional fit, due process) that civil legal systems have refined over centuries. The latter requires only that the on-chain artifact meet existing evidentiary standards &mdash; a substantially easier problem, and one for which the legal infrastructure already exists.
                </p>
                <p>
                    We make the argument in the context of Figaro, a bonded settlement primitive whose mechanism is established and whose kernel is formally verified. Figaro explicitly does not attempt on-chain dispute resolution. Its enforcement architecture is a five-layer stack &mdash; the chain&rsquo;s consensus security (Layer 0), the bonding game with its co-resident immutable record (Layer 1), the peer-coordination subgame (Layer 2), and the off-chain arbitration (Layer 3) and legal (Layer 4) forums that read that record. The bonding game and peer coordination are the primary defenses; the immutable record is produced alongside them by construction, and the outer forums adjudicate on it when the inner layers leave a residual. The present paper develops the record and its forum use.
                </p>
                <PaperRun title="What this paper is not.">
                    This paper does not provide legal advice. It does not predict the admissibility of any specific on-chain artifact in any specific jurisdiction, nor does it claim that the on-chain record is itself sufficient for any particular legal claim. It argues for a design discipline (do not perform adjudication on chain) and catalogues the evidentiary properties of the artifact that the discipline produces. Practitioners who wish to rely on those properties in specific proceedings should obtain jurisdiction-specific counsel.
                </PaperRun>
                <PaperRun title="Paper organization.">
                    Section 2 states the layered architecture and walks it through operationally. Section 3 develops the evidentiary properties of the on-chain record and taxonomizes its records into two classes. Section 4 compares those properties to existing electronic-evidence law. Section 5 treats substantive defenses and post-settlement restitution. Section 6 addresses jurisdictional implications and works a cross-border example. Section 7 argues against on-chain adjudication as a category, and Section 8 catalogues composition with dispute systems. Section 9 concludes.
                </PaperRun>
            </PaperSection>

            <PaperSection title="2. The Layered Architecture">
                <p>
                    Figaro&rsquo;s enforcement architecture is layered. The mechanism details &mdash; the bonding equilibrium and the atomic-resolution subgame &mdash; are established results we take as given; we state each layer here from the legal-design perspective and walk it through operationally, because practitioners frequently arrive with the question &ldquo;where does my dispute go?&rdquo;
                </p>
                <PaperSubsection title="Layer 0 — chain security">
                    <p>
                        Beneath every claim in this paper sits the security of the underlying chain: its consensus rules and finality guarantees are what make an on-chain record authentic in the first place. The evidentiary properties developed in Sections 3 and 4 &mdash; that a record at block <Math>{"b"}</Math> is the same record at block <Math>{"b + N"}</Math>, that the &ldquo;reliable method&rdquo; test is discharged by the kernel&rsquo;s bytecode and the consensus rules of the underlying chain &mdash; are inherited from this layer, not asserted by the protocol above it. We name it as a layer rather than assume it silently, because the entire evidentiary argument is only as strong as the chain&rsquo;s resistance to reorganization and censorship.
                    </p>
                </PaperSubsection>
                <PaperSubsection title="Layer 1 — bonding, with its co-resident record">
                    <p>
                        Each party to a transaction locks <Math>{"2\\times"}</Math> the transaction value (asymmetric for <Math>{"N"}</Math>-party processes; the seller&rsquo;s bond scales with upstream value), and the bond returns to its poster only through buyer-initiated atomic resolution. A buyer who has signed a commitment for a payment <Math>{"P"}</Math> and posted a <Math>{"2P"}</Math> bond faces a choice between cooperation (recover the bond minus the net flow <Math>{"P"}</Math>) and defection (forfeit the bond entirely); the cooperation/defection gap is <Math>{"P"}</Math> for the buyer and <Math>{"P + 2G"}</Math> for the seller, where <Math>{"G"}</Math> is the cumulative upstream value. Most participants do not defect, because doing so is locally irrational under the bonded posture; the vast majority of disputes are prevented at this layer.
                    </p>
                    <p>
                        <em>The record is co-resident with the bond, not a fallback.</em> Every commit and every resolve emits an immutable record as a mechanical byproduct &mdash; the commitment digest, the bond deposits, the process&rsquo;s monotonic settlement state, the resolution event with its payout vector. No party can collect a settlement payout without the corresponding events having been emitted (Section 3 develops this as the settlement-byproduct property). The record is therefore produced <em>always, by construction</em>, at the same layer as the bond and in the same act &mdash; not summoned later for the cases the bond failed to prevent. What the outer layers add is not the record but a <em>forum</em> that reads it.
                    </p>
                    <p>
                        <em>What does and does not reach a forum at Layer 1.</em> The clearest case for Layer-1 prevention is the <em>cooperation/defection</em> dispute: a counterparty who would have walked away from a conventional contract because the cost of performance exceeded the cost of breach is, under the bonded posture, prevented from doing so because breach now costs the forfeited bond. Real commerce, however, is dominated by a different class: <em>information-asymmetry</em> disputes about whether the seller&rsquo;s performance conformed to the agreement (did the goods conform? was time of the essence? did the description match?). The bonded posture pressures the seller toward addressing dissatisfaction, because the seller&rsquo;s bond remains locked while the buyer withholds resolution; but it does not by itself resolve the underlying factual question of whether the buyer&rsquo;s dissatisfaction is justified. Information-asymmetry disputes survive Layer 1 by construction and flow to Layer 2 if multi-party, or to the off-chain forums (Layers 3&ndash;4) if the parties cannot converge.
                    </p>
                </PaperSubsection>
                <PaperSubsection title="Layer 2 — peer coordination">
                    <p>
                        Atomic resolution means no co-seller is paid until the buyer resolves the whole process at once. So when one seller in a multi-party process is performing poorly enough to threaten resolution, the co-sellers&rsquo; first response is to <em>remedy</em> the fault, not merely to punish it: their own bonds stay locked until the buyer is satisfied, so each of them has a direct interest of magnitude <Math>{"P_i + 2G_i"}</Math> in helping the faulting party bring performance up to the bar that unlocks the shared resolution. Consider a process with one root buyer and four value-adders &mdash; one upstream and three downstream, co-equal parties to the same buyer, differing only in their position in the value chain. Monitoring and pressure &mdash; phone calls, escalation through the cohort&rsquo;s coordination channels &mdash; are the backing behind that interest; the mechanism itself is that everyone&rsquo;s payout is hostage to the weakest link, so everyone is motivated to strengthen it.
                    </p>
                    <p>
                        The pressure is endogenous to the bonded structure; no governance, no platform, no aggregator, no foundation organizes it. This layer handles disputes that survive Layer 1 by internalizing them as intra-cohort coordination problems.
                    </p>
                    <p>
                        <em>The expected rate.</em> The Grameen joint-liability microfinance literature reports headline default-rate reductions on the order of <Math>{"20\\% \\to 2\\%"}</Math> under peer monitoring (Yunus, 1999) &mdash; figures contested on accounting grounds (Morduch, 1999) &mdash; and we cite the comparison only as a stylized indication of the order of magnitude that joint-liability peer pressure has been claimed to achieve.
                    </p>
                </PaperSubsection>
                <PaperSubsection title="Layers 3–4 — the off-chain forums">
                    <p>
                        The residual that survives Layers 1 and 2 &mdash; a participant acts irrationally, the cohort cannot self-coordinate, external circumstances (regulatory action, force majeure, participant death) prevent normal resolution, or the underlying agreement is contested on substantive grounds (duress, mistake, frustration, illegality, public policy) &mdash; flows to a forum that adjudicates on the record. These forums are ordered outward. <strong>Layer 3</strong> is decentralized or institutional <em>arbitration</em>: a Schelling-jury protocol, or a seated commercial arbitration whose award travels under the New York Convention. <strong>Layer 4</strong> is the <em>traditional legal system</em> &mdash; the courts of the jurisdiction whose law the agreement selects. Recourse to Layers 3 and 4 exists even when the agreement names no dispute clause: the record is admissible on its own terms, and a party may bring it to whatever forum has jurisdiction over the counterparty.
                    </p>
                    <p>
                        <em>The forum the parties chose.</em> Where the parties do name a forum, it is named by their off-chain agreement. Neither Layer 3 nor Layer 4 is imposed by the protocol; the protocol produces the evidentiary record on which the chosen forum operates. Section 8 catalogues the forums most commonly composed with the protocol.
                    </p>
                </PaperSubsection>
                <PaperRun title="What is and is not on chain.">
                    Settlement is on chain. Adjudication is off chain. The split is deliberate. Settlement is deterministic, automated, and public &mdash; all properties that on-chain execution provides natively. Adjudication is contextual, discretionary, and jurisdiction-specific &mdash; all properties that on-chain execution is poorly suited for. The split lets each layer do what it does best and avoids forcing one to imitate the other.
                </PaperRun>
                <PaperRun title="The practical guidance.">
                    Expect Layer 1 to handle the vast majority of cases; Layer 2 the multi-party residual; the off-chain forums (Layers 3&ndash;4) the small residual that survives both. Most operational deployment work goes into the runtime tier&rsquo;s Layer-1 and Layer-2 surfaces, with the forums structurally reachable but rarely invoked. A deployment that finds itself routinely escalating disputes to a forum is typically signaling that the inner layers are mis-configured &mdash; commitments that never entered the bonding game at all, broken attestation flows, mis-specified clauses &mdash; not that the architecture is failing.
                </PaperRun>
            </PaperSection>

            <PaperSection title="3. Evidentiary Properties and the Two Record Classes">
                <p>
                    The on-chain record produced by Figaro has six properties that together constitute its evidentiary value. The record is not a single artifact class, however; after enumerating the properties we taxonomize the protocol&rsquo;s records into two classes, distinguished by how they are produced and what they prove, to which the properties apply differently.
                </p>
                <PaperRun title="(1) Timestamped.">
                    Every state transition is associated with a block timestamp. The timestamp is set by block proposers under consensus rules; it is not subject to retroactive modification. It is not, however, a <em>qualified</em> electronic time stamp in the eIDAS sense: that status is reserved to time stamps signed or sealed by a qualified trust service provider (Regulation (EU) 910/2014, Article 42(1)(c)), and no such provider stands behind a public chain&rsquo;s consensus clock. What the block timestamp has instead is admissibility under the regulation&rsquo;s non-discrimination rule for electronic time stamps &mdash; legal effect and admissibility are not denied solely because a time stamp is electronic or falls short of the qualified requirements (Article 41(1)) &mdash; with weight left to the forum&rsquo;s contextual assessment rather than supplied by the presumption Article 41(2) attaches to qualified time stamps. Section 4 develops the point.
                </PaperRun>
                <PaperRun title="(2) Cryptographically signed.">
                    Every commitment is signed by both parties using EIP-712 typed structured data (Bloemen et al., 2017). The signatures bind the material terms and the agreement hash to the signers&rsquo; private keys. Recovery is deterministic; tampering with any field invalidates the signature.
                </PaperRun>
                <PaperRun title="(3) Content-addressed.">
                    Order identifiers are content-addressed hashes of the commitment. The same commitment content always produces the same identifier; different content always produces different identifiers (collision-resistant under the assumed hash function). This makes the record unforgeable in a specific sense: no second commitment can claim the same identifier.
                </PaperRun>
                <PaperRun title="(4) Immutable.">
                    On a finalized block, the record cannot be modified or deleted. A party seeking to repudiate a commitment cannot purge the chain of the relevant log entries. This is a stronger property than what electronic records normally enjoy.
                </PaperRun>
                <PaperRun title="(5) Publicly verifiable.">
                    Anyone can read the chain and replay the verification logic. The evidence is not held by any single party; it is held by the network. Disputing parties therefore cannot disagree about what the record says &mdash; they can disagree only about what the record <em>means</em>, which is precisely the question adjudication is suited to.
                </PaperRun>
                <PaperRun title="(6) Contains commitment intent.">
                    The signed payload includes a content hash <Math>{"h"}</Math> of the off-chain agreement. The off-chain agreement itself can be anything the parties choose &mdash; a structured contract, a free-text PDF, a clause-typed JSON document. The on-chain record does not interpret the agreement; it commits both parties to a specific document via the hash. A dispute over performance is then a dispute over the referenced document, with the on-chain hash establishing <em>which</em> document is at issue.
                </PaperRun>
                <p>
                    These six properties, combined, produce an artifact that is substantially <em>stronger</em> than the electronic records most courts already accept. Courts admit emails, electronic signatures, and database extracts as evidence subject to authentication challenges; the on-chain record satisfies many authentication requirements at the cryptographic level rather than at the custodial level.
                </p>
                <PaperRun title="Settlement-byproduct records: kernel byproducts.">
                    Settlement-byproduct records are emitted by the kernel itself as a byproduct of commit and resolve. They include the commitment digest, the bond deposits, the process&rsquo;s monotonic settlement state, and the resolution event with its complete payout vector. These are produced as a mechanical side effect of the bonding game: no party can collect the settlement payout without the corresponding on-chain events having been emitted, so their integrity as evidence is underwritten by the game itself. Settlement-byproduct records share four properties. <em>Discretion-free:</em> the kernel emits them without any participant choice. <em>Cryptographically authenticated:</em> each is signed by the parties who participated in the operation that produced it (EIP-712 signatures on commits; the buyer&rsquo;s transaction signature on resolutions), verifiable without consulting any oracle. <em>Append-only:</em> a settlement-byproduct record at block <Math>{"b"}</Math> is the same record at block <Math>{"b + N"}</Math> for any <Math>{"N"}</Math>. <em>Clause-typed at the kernel level:</em> the structure is determined by the kernel&rsquo;s typed events, known in advance and machine-readable.
                </PaperRun>
                <p>
                    The four properties together make settlement-byproduct records <em>strong evidence</em>: an off-chain forum can rely on the record&rsquo;s existence and content with high confidence and minimal expert testimony. The MLETR functional-equivalence analysis (Section 4) applies directly to settlement-byproduct records, with the &ldquo;reliable method&rdquo; test discharged by the kernel&rsquo;s bytecode and the consensus rules of the underlying chain.
                </p>
                <PaperRun title="Discretionary-attestation records.">
                    Discretionary-attestation records are produced by participants through the protocol&rsquo;s attestation path under clause-validation discipline. They include delivery confirmations, emissions disclosures, handoff attestations, custody-of-seal events, lifecycle stage transitions, and the other clause-typed records that operational deployments produce. They are <em>discretionary</em> (a participant chooses whether, when, and what to attest within the clause&rsquo;s content space); <em>cryptographically authenticated plus validation-gated</em> (the participant&rsquo;s EIP-712 signature plus a well-formedness gate, though the content itself is participant-asserted and may be contestable on substantive grounds); <em>append-only</em> (incorrect attestations cannot be retracted, only contextualized by later ones); and <em>clause-typed at the protocol level</em> (structure determined by the registered clause&rsquo;s specification).
                </PaperRun>
                <p>
                    The four properties together make discretionary-attestation records <em>useful but contestable evidence</em>: an off-chain forum can rely on the record&rsquo;s existence (cryptographic), its participant (cryptographic), and its formal correctness under the clause (validation-gated), but the substantive accuracy of what the record asserts (the delivery did happen as the seller stated; the emissions disclosure does reflect reality) raises the questions the audit-assertion framework of AICPA (2020) treats across the assertion categories of existence (did the recorded event happen?) and accuracy (was it recorded at the right amount, timing, and characterization?). A party who selectively attests (silence about underperformance, precise attestation of performance) can produce a discretionary-attestation record that survives authentication but misrepresents reality; adjudication should treat such records under ordinary authentication-and-hearsay doctrine rather than extending the settlement-byproduct class&rsquo;s assurance to them.
                </p>
                <PaperRun title="The MLETR fit by class.">
                    The MLETR analysis applies most directly to settlement-byproduct records, which carry the kernel&rsquo;s structural properties and discharge MLETR Articles 10&ndash;11&rsquo;s control and singularity tests in their own right. Discretionary-attestation records do not generally meet the MLETR test on their own, because they are not transferable records in the Article-10 sense: a delivery confirmation, an emissions disclosure, or a custody-of-seal event is not an instrument of title that participants treat as functionally equivalent to a negotiable paper. They are evidentiary artifacts <em>about</em> the underlying transferable record (the commitment), not separate transferable records. Their evidentiary weight is corroborative, conditional on the clause-validation surface&rsquo;s correctness &mdash; a record filed under an unregistered clause type is rejected before it is recorded. The clause-design discipline is therefore part of the corroborative weight discretionary-attestation records carry, not part of an MLETR transferable-record analysis applied to them directly.
                </PaperRun>
                <PaperRun title="Why the taxonomy matters for forum strategy.">
                    A litigant taking the bonded record to a forum should expect the forum&rsquo;s treatment of settlement-byproduct and discretionary-attestation records to differ in detail even if both are admissible. For settlement-byproduct records, the analysis reduces to authentication (signatures verify; chain matches; expert if needed) then content interpretation (what does the recorded state mean for the parties&rsquo; claims) &mdash; authentication is nearly mechanical, interpretation is the work. For discretionary-attestation records, the analysis expands to include clause-validity (was the record filed under a registered clause type and accepted as well-formed) and <em>substantive truth-of-content</em> (does the attestation reflect the off-chain reality it asserts), engaging the AU-C 315 existence and accuracy assertions at per-attestation granularity. A deployment that relies on discretionary-attestation records for load-bearing factual claims is exposed to a different litigation profile than one that relies on settlement-byproduct records (e.g., the resolution event itself, undeniable on chain). Most deployments use both; understanding the litigation profile of each is part of the runtime tier&rsquo;s design discipline.
                </PaperRun>
            </PaperSection>

            <PaperSection title="4. Legal Fit: Existing Electronic-Evidence Frameworks">
                <p>
                    We sketch how the six properties above interact with four major electronic-evidence frameworks. The treatment is illustrative; a full doctrinal analysis is jurisdiction-by-jurisdiction.
                </p>
                <PaperRun title="eIDAS (EU Regulation 910/2014).">
                    eIDAS distinguishes electronic signatures, advanced electronic signatures (AdES), and qualified electronic signatures (QES). EIP-712 signatures meet the AdES technical requirements (uniquely linked to the signatory; capable of identifying the signatory; created using means under the signatory&rsquo;s sole control; linked to the signed data such that any subsequent change is detectable). They do not by themselves meet the QES requirements (which include a qualified certificate from a trust service provider). However, AdES status is sufficient for most contractual purposes, and eIDAS explicitly provides that the legal effect of an electronic signature shall not be denied solely because it is in electronic form. eIDAS also defines qualified electronic time stamps, and the same structure recurs: a block timestamp on a chain with public consensus rules answers the binding requirement of Article 42(1)(a) well &mdash; date and time are bound to the data such that undetected alteration is impracticable &mdash; answers Article 42(1)(b)&rsquo;s accurate-time-source requirement only approximately, since a proposer sets the value within a consensus tolerance rather than from a traceable reference clock, and does not answer Article 42(1)(c) at all, which requires that the time stamp be &ldquo;signed using an advanced electronic signature or sealed with an advanced electronic seal of the qualified trust service provider, or by some equivalent method.&rdquo; The closing words do not open the door they appear to: what they admit is an equivalent <em>method</em> of a qualified provider, and qualified status is conferred on a supervised provider under the regulation&rsquo;s supervision regime, not earned by a technique &mdash; a permissionless network with no legal person to supervise has nothing to which the status could attach. No such provider stands behind a public chain, so the block timestamp is <em>not</em> a qualified electronic time stamp, and the presumption of accuracy and integrity that Article 41(2) grants qualified time stamps does not attach to it. What attaches instead is Article 41(1): legal effect and admissibility as evidence are not denied solely because a time stamp is in electronic form or does not meet the qualified requirements. The practical effect: the on-chain record is admissible electronic evidence under eIDAS, with weight determined by the court&rsquo;s contextual assessment rather than by a statutory presumption.
                </PaperRun>
                <PaperRun title="UCC &sect;1-201 and the Federal Rules of Evidence (US).">
                    The Uniform Commercial Code defines &ldquo;record&rdquo; as information inscribed on a tangible medium or stored in an electronic medium and retrievable in perceivable form; on-chain log entries satisfy this without ambiguity. UCC &sect;1-201 also defines &ldquo;signature&rdquo; inclusively (any symbol executed or adopted with present intention to adopt or accept a writing); EIP-712 signatures qualify. UETA and the federal E-SIGN Act extend the principle to contracts more broadly. For evidentiary admission, the operative provisions are FRE 901(b)(9), 902(13), and 902(14), with the <em>Daubert</em> standard for any expert testimony required to authenticate the cryptographic process. FRE 901(b)(9) permits authentication by showing that a process or system produces an accurate result; FRE 902(13) (added 2017) permits self-authentication of records generated by an electronic process or system; FRE 902(14) permits self-authentication of data copied from electronic devices through a process producing a digital identifier &mdash; here the cryptographic hash of the record itself (FRE legislative history, 2017). On-chain commitments are records and signatures under US commercial law, admissible through the established electronic-evidence pathway and authenticatable through <em>Daubert</em>-qualified expert testimony where authentication is challenged.
                </PaperRun>
                <PaperRun title="Singapore Electronic Transactions Act (Cap. 88) and MLETR.">
                    Singapore&rsquo;s ETA closely follows the UNCITRAL Model Law and provides functional equivalents for &ldquo;writing,&rdquo; &ldquo;signature,&rdquo; and &ldquo;original&rdquo; in electronic form. The ETA was amended in 2021 to recognize electronic transferable records, implementing MLETR (2017) and extending scope to instruments of title. On-chain records satisfy the writing and signature requirements directly; the transferable-record provisions warrant closer treatment because the doctrinal question they raise is the one most directly relevant to the multi-party structure of Figaro.
                </PaperRun>
                <p>
                    MLETR Article 10 requires functional equivalence with a paper-based transferable document on three dimensions: (i) the information is accessible for subsequent reference; (ii) a reliable method (a) identifies the record as the electronic transferable record, (b) renders it capable of being subject to control from creation until it ceases to have effect, and (c) retains its integrity. Article 11 requires that &ldquo;control&rdquo; be functionally equivalent to possession of a paper instrument: a single identifiable controller, with exclusive capacity to transfer that control, the transfer recorded reliably. The control and singularity tests are load-bearing.
                </p>
                <p>
                    Figaro&rsquo;s on-chain commitment satisfies Articles 10&ndash;11 in the relevant senses. The content-addressed order identifier uniquely identifies the transferable record (Art. 10(2)(a)). The bond mechanics give the bonded party exclusive capacity to act on the record until resolution (Art. 11(1) singularity); the kernel rejects any duplicate or fork of the record (Art. 10(2)(b) non-duplication). Integrity is enforced cryptographically through consensus and EIP-712 verification (Art. 10(2)(c)). Where the right to receive performance moves along a multi-party process, each commitment in the process is itself a transferable record under the same analysis, and the on-chain settlement records the transfer with the reliable method MLETR contemplates. Goode and Gullifer (2017) gives the standard doctrinal framework against which this analysis is run; the on-chain settlement satisfies the framework&rsquo;s tests without controversy.
                </p>
                <PaperRun title="UNCITRAL Model Law on Electronic Commerce.">
                    Adopted in 1996 and supplemented by the 2017 Model Law on Electronic Transferable Records, the UNCITRAL framework articulates the functional-equivalence principle underlying most modern electronic-evidence regimes. Its three core requirements &mdash; accessibility for subsequent reference, integrity of the information, and identifiability of the originator &mdash; are all satisfied by on-chain commitments. Jurisdictions that have adopted UNCITRAL-derived electronic-transactions law (over 80 as of 2024) provide an established framework for treating on-chain commitments as admissible electronic evidence.
                </PaperRun>
                <PaperRun title="The summary picture.">
                    The on-chain record is admissible electronic evidence in every jurisdiction whose electronic-evidence law derives from the UNCITRAL framework or implements equivalent functional principles. What varies is the weight courts assign (a question of judicial practice rather than admissibility) and the further procedural requirements for authenticating the chain itself (typically satisfied by expert testimony or judicial notice of well-known chains). No jurisdiction we are aware of categorically excludes on-chain records from evidentiary consideration.
                </PaperRun>
            </PaperSection>

            <PaperSection title="5. Substantive Defenses and Post-Settlement Restitution">
                <p>
                    A reader sympathetic to the argument so far will raise the sharpest question this paper has to answer. Suppose the on-chain settlement is unimpeachable as evidence; suppose every framework above admits it. What happens when an external court, applying the substantive contract law of its jurisdiction, finds that the underlying agreement was procured under duress, formed under fundamental mistake, frustrated by impossibility, voided by illegality, or unconscionable in its terms? The on-chain settlement has, by hypothesis, already executed. The question is what the court can do with that fact and whether the division between settlement (on-chain) and adjudication (off-chain) is consistent with the substantive-defense jurisprudence the dominant tradition has developed over centuries.
                </p>
                <PaperRun title="Doctrinal inventory.">
                    The defenses that void or rescind a contract <em>ab initio</em>, or that excuse subsequent performance, are doctrinally settled in the major commercial jurisdictions. Common-law systems recognize <em>duress</em> (consent obtained by improper threat); <em>undue influence</em> (abuse of a relationship of trust); <em>misrepresentation</em> (false statements about material facts); <em>fundamental mistake</em> (shared mistake about an essential fact); <em>unconscionability</em> (terms so one-sided that enforcement shocks the conscience); <em>frustration of purpose</em> and <em>impossibility / impracticability</em> (subsequent events render performance fundamentally different or impossible); <em>illegality</em>; and <em>public policy</em>. Civil-law systems recognize closely parallel doctrines (<em>vices du consentement</em>, <em>erreur</em>, <em>circonstances exceptionnelles</em>). The doctrines are substantive: they apply to <em>the agreement</em> the bonded commitment records, not to the bonded commitment as a technological artifact.
                </PaperRun>
                <PaperRun title="Substantive-defenses analysis.">
                    The bonded primitive is silent on every doctrine in the inventory. The kernel does not know whether consent was procured under duress, whether parties were mistaken about a material fact, whether the underlying transaction was illegal, or whether performance has been frustrated. It records what was signed; it makes no representation about the conditions under which signing occurred or the legality of what was signed for. This is by design &mdash; the kernel cannot make substantive-defense determinations without doing the kind of discretionary work the no-escape-hatches design principle rules out &mdash; and it is by design also a <em>feature</em>, because it leaves the substantive-defense apparatus exactly where the dominant tradition has placed it: in courts applying their own constitutional and doctrinal apparatus to the agreement recorded in the bonded commitment. The leading case-law authority is <em>B2C2 Ltd v Quoine Pte Ltd</em> [2019] SGHC(I) 03, affirmed in <em>Quoine Pte Ltd v B2C2 Ltd</em> [2020] SGCA(I) 02, in which the Singapore International Commercial Court and, on appeal, the Court of Appeal worked out how the doctrine of unilateral mistake applies to deterministic algorithmic execution &mdash; locating the relevant knowledge at the time the algorithm was programmed, not at execution. On the facts the mistake defence failed and the trades stood, but the case establishes that smart-contract executions are not beyond the reach of conventional contract doctrine.
                </PaperRun>
                <p>
                    The restitutionary mechanics are where the question becomes operationally sharp. <em>Case 1: court orders specific re-transfer off-chain.</em> Where one party should not have received the payout, the standard remedy is a restitutionary order to transfer the received value back off-chain. This operates on the parties&rsquo; real-world capacity to comply, not on the kernel state; the kernel records show the original settlement unchanged, and the off-chain transfer is recorded separately. This is the most common form and the one for which the existing legal apparatus is best-equipped. <em>Case 2: court orders a fresh bonded counter-process.</em> Where ongoing performance and a counter-flow are appropriate, the parties (or the court via an order on the parties) constitute a fresh Figaro process flowing value in the corrective direction &mdash; using the bonded primitive as the implementation of the remedy rather than an obstacle to it. <em>Case 3: court orders an arrangement the kernel cannot support.</em> The remedy then operates on the parties&rsquo; off-chain assets and obligations through conventional mechanisms (asset seizure, contempt sanctions, criminal liability for non-compliance). The kernel does not obstruct the remedy; it does not implement it either. The substrate is sub-political, not anti-political.
                </p>
                <PaperRun title="Implication for the escape-hatch theorem.">
                    The escape-hatch theorem and its carve-out deserve a precise characterization. The theorem rules out unilateral exit paths internal to the mechanism &mdash; timeouts, arbitrators, governance votes &mdash; because those would weaken the Nash equilibrium. The carve-out admits external legal forums applying duress, frustration, and similar substantive doctrines. The carve-out is sound, but for a more precise reason than &ldquo;external forums are themselves bonded&rdquo;: the substantive-defense jurisprudence operates on the agreement <em>as recorded</em> after the kernel has settled, not on the kernel itself, and produces remedies that reach the parties through their conventional legal exposure rather than through the kernel&rsquo;s bond balance. The kernel&rsquo;s equilibrium is preserved because no remedy can reach into that rule-bound bond balance &mdash; there is no custodian register for a court order to touch; the substantive defenses operate downstream of settlement. The bonded primitive does not displace contract law&rsquo;s substantive doctrines; it produces a settlement under which those doctrines continue to apply in the conventional way.
                </PaperRun>
            </PaperSection>

            <PaperSection title="6. Jurisdictional Implications">
                <p>The decoupling of settlement from adjudication has substantive jurisdictional consequences.</p>
                <PaperRun title="Forum is contractual.">
                    The on-chain commitment includes an off-chain agreement hash <Math>{"h"}</Math>. That off-chain agreement can &mdash; and typically should &mdash; include a forum-selection clause, a choice-of-law clause, and an arbitration clause if the parties prefer arbitration to court. The on-chain record proves what was agreed; the off-chain agreement specifies where and under what law the agreement is adjudicated. Parties who omit a forum clause default to whatever private-international-law analysis the seised forum applies; this is a known regime, not a novel problem.
                </PaperRun>
                <PaperRun title="Forum-shopping is bounded.">
                    A party seeking to forum-shop is bounded by (a) the forum-selection clause in the off-chain agreement, (b) the seising forum&rsquo;s own jurisdictional rules, and (c) the recognition-and-enforcement treaties between the seising forum and any forum where the counterparty&rsquo;s assets reside. None of these constraints is weakened by the on-chain settlement; they all operate on the off-chain agreement and the parties&rsquo; real-world circumstances.
                </PaperRun>
                <PaperRun title="Evidence is jurisdiction-displaced.">
                    The integrity of the on-chain evidence does not depend on the seising forum&rsquo;s recognition of any specific cryptographic standard. The signatures verify, or they do not; the chain hashes match, or they do not. A forum that doubts the cryptographic analysis can engage an expert; a forum that does not is in the position of any forum facing forensic evidence.
                </PaperRun>
                <PaperRun title="Cross-border processes.">
                    A multi-party process can involve parties in multiple jurisdictions simultaneously. The on-chain settlement is jurisdiction-blind: the bond mechanics work identically regardless of where the parties reside. Off-chain disputes arising from such processes are handled by the same private-international-law machinery that already handles cross-border disputes in conventional commerce &mdash; typically with the on-chain record providing substantially more evidentiary clarity than the parties would have produced under conventional bookkeeping.
                </PaperRun>
                <PaperRun title="A worked example: New York forum, cross-border process.">
                    Consider a multi-party process with a buyer in New York and two value-adders &mdash; one in Singapore and one upstream in Argentina, co-equal parties to the same root buyer, differing only in their position in the value chain &mdash; settled in <code>USDC</code> on Ethereum L1. The off-chain agreement specifies New York Supreme Court as the forum and New York law as the governing law. A dispute arises: the Singapore seller claims the buyer never resolved the process despite delivery; the buyer claims the goods did not conform to the agreed specification. Admissibility is settled by the Section 4 framework and needs no re-argument here; what the example adds is the fact-to-forum routing. The seller&rsquo;s claim &mdash; that the buyer never resolved &mdash; is determinable from the chain state directly: the resolution transaction is present or it is absent. The buyer&rsquo;s claim &mdash; that the goods did not conform &mdash; is not determinable from the chain state and requires off-chain evidence: delivery records, photographs, laboratory analyses, and the clause-typed attestations that may already be on chain. The New York court, applying New York contract law (UCC Article 2 for the goods, NY CPLR for procedure, New York&rsquo;s Electronic Signatures and Records Act (State Technology Law art. 3) for electronic signatures), decides the substantive question &mdash; did the goods conform? &mdash; on the off-chain evidence under ordinary contract doctrine; the remedy, if the court finds for the buyer, is restitutionary, operating on the seller&rsquo;s off-chain assets through standard enforcement (US&ndash;Singapore reciprocity, New York Convention, asset attachment). The bonded settlement does not interfere with any of this. It provides the evidentiary record and the bilateral-enforcement backstop that prevents the seller from walking away with the funds before the dispute is heard &mdash; the gap that cross-border commerce has had to manage through letters of credit, escrow agents, and intermediary banks.
                </PaperRun>
            </PaperSection>

            <PaperSection title="7. Why Not On-Chain Adjudication">
                <p>
                    We have argued the positive case for off-chain adjudication. We now argue the negative case against on-chain adjudication. Several patterns occupy this space; we treat each briefly.
                </p>
                <PaperRun title="Schelling-point juror selection (Kleros).">
                    A token-weighted juror panel votes on the disputed question; the plurality wins; jurors who voted with the plurality are rewarded, those against are slashed. The mechanism is elegant in abstraction but has three problems for serious adjudication. First, the panel is not selected for jurisdictional fit &mdash; a juror in jurisdiction <Math>{"A"}</Math> may know nothing of jurisdiction <Math>{"B"}</Math>&rsquo;s law that the parties agreed should govern. Second, the juror&rsquo;s incentive is to vote with the perceived plurality, not the legally correct outcome &mdash; a Schelling point on plurality is structurally distinct from a Schelling point on truth. Third, the slashing mechanism imports a new dispute (was the slashing fair?) that has no terminal forum on chain.
                </PaperRun>
                <PaperRun title="DAO-governed arbitration (Aragon Court).">
                    Aragon Court is structurally similar to Kleros, with juror-selection integrated with DAO governance. This inherits Kleros&rsquo;s problems plus the additional one that DAO voting power is plutocratic in proportion to token holdings; the wealthy juror has structurally more votes than the poor juror. Whether that is desirable is a normative question; that it differs from the &ldquo;one juror, one vote&rdquo; premise of jury trials is a doctrinal question that has not been settled.
                </PaperRun>
                <PaperRun title="Optimistic challenge windows.">
                    Optimistic mechanisms (Optimism, 2021; UMA, 2020) avoid the juror problem by allowing assertions to stand unless challenged within a fixed window. This works for settlement-layer state machines but not for adjudication, because adjudication is precisely the activity of assessing an assertion that has been challenged. An optimistic &ldquo;adjudication&rdquo; is just an assertion with a deadline &mdash; it has no mechanism for resolving the underlying question, only for resolving who blinked first.
                </PaperRun>
                <PaperRun title="The structural objection.">
                    All on-chain adjudication mechanisms share the same flaw. The escape-hatch theorem establishes that any unilateral exit from the bonded state requires either a third-party decision (introducing an unbonded actor whose incentives are not constrained by the bond structure) or a payoff modification that weakens the Nash equilibrium. On-chain adjudication is the third-party-decision case: the juror, the DAO voter, the challenger is the unbonded actor whose decision determines the outcome. Whatever the designer does to constrain that actor (token slashing, Schelling incentives, reputation), the actor is still unbonded and the kernel&rsquo;s self-enforcing property is broken.
                </PaperRun>
                <PaperRun title="The off-chain alternative.">
                    Off-chain adjudication by an existing legal forum has the opposite structure. The forum&rsquo;s incentives are constrained by its institutional context &mdash; judges face appellate review, arbitrators face institutional reputation, both face professional sanction. The forum is not unbonded in the kernel sense; it operates inside a different bond structure (its institutional authority). The off-chain evidence record is therefore consumed by an actor whose incentives are already constrained by a regime refined for centuries. The protocol does not re-implement that regime; it provides input to it.
                </PaperRun>
                <PaperRun title="Forum-agnosticism.">
                    The objection above is to on-chain adjudication <em>at the kernel layer</em>. It is not an objection to Kleros, or any other adjudication mechanism, when the parties&rsquo; agreement designates it as the forum: the kernel does not adjudicate; it produces an evidence record and exports it to whatever forum the parties name &mdash; the Singapore International Arbitration Centre, the New York Supreme Court, or a Schelling-jury system. On our reading, a Schelling-jury decision can itself fall within the New York Convention&rsquo;s definition of an arbitral award where the parties&rsquo; agreement so designates &mdash; reading the Convention&rsquo;s tribunal definition as functional rather than institutional &mdash; though the point is more contested than for institutional arbitration and is more exposed to a public-policy refusal; Section 8 develops the analysis in full alongside the other forum classes.
                </PaperRun>
            </PaperSection>

            <PaperSection title="8. Composition with Dispute Systems">
                <p>
                    A constructive treatment is owed to the practitioner who arrives with the question &ldquo;which forum should I name in my agreement, and how do I compose with it.&rdquo; We catalogue the four classes of forum the protocol composes with in practice.
                </p>
                <PaperSubsection title="State courts">
                    <p>
                        Conventional state courts are the highest-recognition forum available and the appropriate destination for disputes whose substantive resolution requires the full apparatus of contract law (duress, mistake, frustration, illegality, public policy). The off-chain agreement names a specific state court (e.g., New York Supreme Court, Singapore International Commercial Court, English High Court) and a governing law; the clause is a standard contractual provision. The bonded record is admitted under the relevant evidentiary framework (FRE 901(b)(9) / 902(13)&ndash;(14) for US courts, eIDAS AdES recognition for EU courts, Singapore ETA / MLETR for Singapore courts). A judgment is enforceable through standard private-international-law machinery (recognition treaties, the Hague Judgments Convention where in force, domestic enforcement powers); enforcement against on-chain assets requires a court with jurisdiction over the asset-holding party rather than over the bonded primitive itself, which is not a party. State courts are appropriate where the parties need the recognition properties of a state-court judgment, or where the matter touches public policy, sanctions, criminal conduct, or regulatory enforcement.
                    </p>
                </PaperSubsection>
                <PaperSubsection title="International commercial arbitration centers">
                    <p>
                        Centers such as SIAC, the ICC, the LCIA, and the HKIAC are the appropriate destination for cross-border disputes whose parties prefer arbitration to court litigation. The off-chain agreement names the center, the seat, the language, and the procedural rules. Arbitration centers admit electronic evidence broadly with flexible authentication standards; the bonded record satisfies them straightforwardly. The New York Convention (1958, 172 state parties as of 2024) is the canonical recognition framework: an award under SIAC / ICC / LCIA rules is enforceable in any Convention state subject to the Article V grounds for refusal, and the bonded primitive composes with this chain natively because the underlying agreement is a recognized arbitration agreement under Article II. Appropriate where parties want institutional arbitration&rsquo;s combination of expertise, procedural flexibility, and international enforceability.
                    </p>
                </PaperSubsection>
                <PaperSubsection title="Online dispute resolution (ODR) platforms">
                    <p>
                        ODR platforms (eBay&rsquo;s Resolution Center as the volume archetype, Modria, smartsettle, and the broader literature, Rabinovich-Einy and Katsh, 2017) are the appropriate destination for high-volume, low-value disputes where the cost of conventional adjudication exceeds the disputed amount. The off-chain agreement names the platform and accepts its terms-of-service; binding effect is contractual rather than treaty-based. ODR platforms typically accept the bonded record without specialized authentication and use it as the dispositive content for routine disputes. ODR decisions are typically enforced by the platform itself rather than through state machinery. A practitioner pattern of pairing an ODR clause with an arbitration clause that treats unappealed ODR decisions as final is structurally available but doctrinally delicate: many ODR procedures (no live hearing, no discovery, opaque review) fail Article V(1)(b) due-process requirements on standard readings, so the hybrid is a careful drafting matter, not an off-the-shelf composition. Appropriate for routine commercial disputes at operational scale where dispute volume rules out court/arbitration economics.
                    </p>
                </PaperSubsection>
                <PaperSubsection title="Schelling-point juror systems (Kleros and analogues)">
                    <p>
                        Kleros and analogues (2019) occupy a distinctive position: mechanism-based forums where Schelling-point juror selection produces decisions through coordination on the focal answer. The protocol composes with them as the parties&rsquo; chosen forum, but their recognition and enforcement properties are the most contested of the four classes. Our reading of the New York Convention is that a Kleros decision is <em>capable</em> of falling within Article I&rsquo;s definition of an arbitral award where the parties&rsquo; arbitration agreement so designates &mdash; reading the Convention&rsquo;s tribunal definition as functional rather than institutional, and the parties&rsquo; acceptance of the forum&rsquo;s procedural rules as the Article V(1)(d) agreement on composition &mdash; subject to Article V&rsquo;s grounds for refusing recognition; the contrary view (Ortolani, 2019) is defensible, and the question is takable rather than settled. The sharpest ground is Article V(2)(b) public policy: many civil-law jurisdictions treat unreasoned awards as presumptively contrary to public policy, and Kleros decisions are vote tallies, not reasoned awards, so parties intending enforcement in such jurisdictions should pair the clause with a written-opinion supplement or choose a different forum. Appropriate where parties prefer the mechanism&rsquo;s combination of neutrality, speed, and token-economic incentive over conventional recognition properties.
                    </p>
                </PaperSubsection>
                <PaperSubsection title="Composition discipline across the four">
                    <p>
                        Two structural points apply across all four. <em>Forum-clause discipline is the parties&rsquo; choice and responsibility.</em> The bonded primitive does not recommend a forum; the forum is named by the off-chain agreement, and the parties bear the consequences of their choice (recognition properties, enforcement chain, procedural rules, operational cost). The architecture&rsquo;s role is to produce evidence the chosen forum can use, not to constrain the choice. <em>Recognition theory is upstream of forum choice.</em> The parties should name a forum whose decisions they have a clean recognition theory for in the jurisdiction of intended enforcement &mdash; a US-based seller and an EU-based buyer who name SIAC arbitration with Singapore seat have a clean theory through the New York Convention; the same parties naming an ODR platform without arbitration backing do not. <em>The bonded primitive shifts the balance toward weaker forums.</em> Because the bonded posture itself enforces most disputes at Layers 1 and 2, the residual reaching the forums (Layers 3&ndash;4) is small (Section 2); a smaller residual can justify a weaker forum than conventional commerce would choose. This is not the architecture replacing stronger forums; it changes the cost-benefit calculation of which forum is appropriate for what residual.
                    </p>
                </PaperSubsection>
            </PaperSection>

            <PaperSection title="9. Conclusion">
                <p>
                    We have argued for a layered approach to smart-contract dispute resolution, with a deliberately designed evidentiary record bridging deterministic on-chain settlement and contextual off-chain adjudication. The architecture inherits the strengths of each layer without forcing either to imitate the other, and it resolves the structural objection to on-chain adjudication: the unbonded juror does not need to exist because the legally constituted forum already does.
                </p>
                <p>
                    The debate over smart-contract dispute resolution has been dominated by the assumption that on-chain settlement implies on-chain adjudication. The decoupling we propose is a different design posture, and it permits a substantially cleaner alignment with existing electronic-evidence law.
                </p>
            </PaperSection>
        </PaperLayout>
    );
}
