import type { Metadata } from "next";
import { withOg } from "@/lib/shared/pageMetadata";
import {
    PaperLayout,
    PaperSection,
    PaperSubsection,
    PaperRun,
} from "@/components/papers/PaperLayout";
import { Math } from "@/components/papers/Math";

export const metadata: Metadata = withOg({
    title: "On-Chain Evidence, Off-Chain Adjudication — Figaro Protocol",
    description:
        "Settlement is on-chain by nature, adjudication is off-chain by nature. A layered approach to smart-contract dispute resolution: the protocol produces evidence existing courts already know how to use.",
});

export default function OnChainEvidencePaper() {
    return (
        <PaperLayout slug="on-chain-evidence"
            title="On-Chain Evidence, Off-Chain Adjudication"
            subtitle="A Layered Approach to Smart-Contract Dispute Resolution"
            author="Figaro"
            date="April 2026"
            watermark="Figaro Protocol · Preprint"
            keywords="electronic evidence, smart-contract law, dispute resolution, blockchain evidence, eIDAS, UNCITRAL, jurisdictional flexibility"
            abstract={
                <>
                    <p>
                        This paper makes a legal argument about smart-contract dispute resolution. The dominant on-chain dispute-resolution designs &mdash; Kleros&rsquo;s Schelling-jury arbitration, Aragon Court&rsquo;s DAO-governed jury, optimistic-rollup challenge windows &mdash; attempt to perform adjudication on chain. We argue that this is a category error: settlement is on-chain by nature, adjudication is off-chain by nature, and conflating the two re-introduces the discretionary intermediary that smart contracts were supposed to remove.
                    </p>
                    <p>
                        We develop the argument by reference to a bonded settlement primitive &mdash; asymmetric bonding composed with buyer-dominated atomic resolution &mdash; whose enforcement architecture is a five-layer stack: the underlying chain&rsquo;s consensus security (Layer 0), the bonding game with its co-resident immutable record (Layer 1), the peer-coordination subgame (Layer 2), and the off-chain forums that rule on the open process record &mdash; arbitration (Layer 3) and the traditional legal system (Layer 4). The record is produced always, by construction, at the bonding layer; it is not a fallback summoned when the inner layers fail. The contribution of this paper is to develop that evidentiary record and its off-chain use in detail: the evidentiary properties of the on-chain record, the relationship between those properties and existing electronic-evidence law (eIDAS, UCC &sect;1-201, the Singapore Electronic Transactions Act, the UNCITRAL Model Law on Electronic Commerce), and the jurisdictional implications of decoupling settlement from adjudication.
                    </p>
                    <p>
                        The argument is not that smart contracts replace courts. It is that smart contracts can produce a form of evidence that courts already know how to use, and that the cleanest division of labor is one in which the protocol does what it does well (deterministic settlement) and the legal system does what it does well (contextual adjudication). The protocol is silent on what counts as &ldquo;satisfactory performance&rdquo; or &ldquo;material breach&rdquo; &mdash; those are adjudicative determinations &mdash; but loud on the facts that adjudication needs as input.
                    </p>
                </>
            }
            references={
                <>
                    <li>Bloemen, R., Logvinov, L., and Evans, J. EIP-712: Ethereum typed structured data hashing and signing. Ethereum Improvement Proposal, 2017.</li>
                    <li>Cuende, L. and Izquierdo, J. <em>Aragon Network: A Decentralized Infrastructure for Value Exchange</em>. Aragon White Paper, 2017.</li>
                    <li>Katsh, E. and Rabinovich-Einy, O. <em>Digital Justice: Technology and the Internet of Disputes</em>. Oxford University Press, New York, 2017.</li>
                    <li>Lesaege, C., George, W., and Ast, F. <em>Kleros: Long Paper v1.0.0</em>. Kleros, 2019.</li>
                    <li>Optimism Foundation. <em>Optimistic Rollups</em>. Optimism Technical Documentation, 2021.</li>
                    <li>Ortolani, P. The Impact of Blockchain Technologies and Smart Contracts on Dispute Resolution: Arbitration and Court Litigation at the Crossroads. <em>Uniform Law Review</em>, 24(2):430&ndash;448, 2019.</li>
                    <li>UMA Project. <em>The Optimistic Oracle</em>. UMA Technical Documentation, 2020.</li>
                    <li>United Nations. <em>Convention on the Recognition and Enforcement of Foreign Arbitral Awards</em> (the New York Convention). 330 U.N.T.S. 38, 1958.</li>
                    <li>US Judicial Conference, Advisory Committee on Evidence Rules. Report on Proposed Amendments to FRE 902(13) and 902(14). Effective December 1, 2017.</li>
                    <li>B2C2 Ltd v Quoine Pte Ltd [2019] SGHC(I) 03 (Singapore International Commercial Court).</li>
                    <li>Quoine Pte Ltd v B2C2 Ltd [2020] SGCA(I) 02 (Singapore Court of Appeal).</li>
                </>
            }
        >
            <PaperSection title="1. Introduction">
                <p>
                    Smart-contract dispute resolution is currently a contested design space. The dominant architectures attempt to perform adjudication on chain, typically through some variant of token-weighted juror selection or DAO governance. Kleros (Lesaege et al., 2019) uses Schelling-point juror voting; Aragon Court (Cuende and Izquierdo, 2017) embeds arbitration in DAO infrastructure; optimistic mechanisms (Optimism, 2021; UMA, 2020) use challenge windows in which assertions stand unless contested. Each of these approaches addresses the dispute-resolution problem by importing the discretionary actor that would otherwise reside in a court: the juror, the DAO voter, the challenger.
                </p>
                <p>
                    This paper argues that the import is a mistake. The claim is not that on-chain juries are bad mechanisms (they are interesting mechanisms with documented properties); it is that they are solving the wrong problem. The right problem is not &ldquo;how do we adjudicate disputes on chain&rdquo; but &ldquo;how do we produce evidence that off-chain forums can use to adjudicate efficiently.&rdquo; The former requires re-creating, in adversarial token-economic settings, the institutional infrastructure (impartial juror selection, jurisdictional fit, due process) that civil legal systems have refined over centuries. The latter requires only that the on-chain artifact meet existing evidentiary standards &mdash; a substantially easier problem, and one for which the legal infrastructure already exists.
                </p>
                <p>
                    We make the argument in the context of Figaro, a bonded settlement primitive whose mechanism is established and whose kernel is formally verified by its own authors &mdash; a self-performed verification, not an audited one, which is the right weight for a legal reader to give it. Figaro explicitly does not attempt on-chain dispute resolution. Its enforcement architecture is a five-layer stack &mdash; the chain&rsquo;s consensus security (Layer 0), the bonding game with its co-resident immutable record (Layer 1), the peer-coordination subgame (Layer 2), and the off-chain arbitration (Layer 3) and legal (Layer 4) forums that rule on that record. The bonding game and peer coordination are the primary defenses; the immutable record is produced alongside them by construction, and the outer forums rule on it &mdash; while the process stands open, their rulings feeding what the parties settle between themselves &mdash; when the inner layers leave a residual. The present paper develops the record and its forum use.
                </p>
                <PaperRun title="What this paper is not.">
                    This paper does not provide legal advice. It does not predict the admissibility of any specific on-chain artifact in any specific jurisdiction, nor does it claim that the on-chain record is itself sufficient for any particular legal claim. It argues for a design discipline (do not perform adjudication on chain) and catalogues the evidentiary properties of the artifact that the discipline produces. Practitioners who wish to rely on those properties in specific proceedings should obtain jurisdiction-specific counsel.
                </PaperRun>
                <PaperRun title="Paper organization.">
                    Section 2 states the settlement mechanism the argument relies on and walks the layered architecture through operationally. Section 3 develops the evidentiary properties of the on-chain record and taxonomizes its records into two classes. Section 4 compares those properties to existing electronic-evidence law. Section 5 treats the substantive contract defenses and the remedies that follow them. Section 6 addresses jurisdictional implications and works a cross-border example. Section 7 argues against on-chain adjudication as a category, and Section 8 catalogues composition with dispute systems. Section 9 concludes.
                </PaperRun>
            </PaperSection>

            <PaperSection title="2. The Layered Architecture">
                <p>
                    The mechanism whose record this paper is about has two calls, each carrying a mechanism design of its own, and the legal argument below uses both. <em>Commit</em> forms a bilateral edge under <em>asymmetric bonding</em>: the buyer locks twice the payment <Math>{"P"}</Math>, and the seller locks twice <Math>{"G"}</Math>, the value the process has accumulated through that seller&rsquo;s own link, its own payment included &mdash; a figure fixed by arithmetic against a signed monotonic accumulator rather than reported by anyone. <em>Resolve</em> settles the process under <em>buyer dominance with atomic resolution</em>: only the buyer may call it, every order in the process settles together or none does, and it is terminal. Nothing else moves a bonded balance.
                </p>
                <p>
                    The equilibrium the two calls compose should be stated exactly, because several passages below rest on its shape. After performance, resolving is unconditionally strictly better for the buyer &mdash; a comparison that needs no assumption whatever about the seller &mdash; and, given that, performance is each seller&rsquo;s strict best response. The two calls compose in that order. What holds the arrangement in place is that a defecting party keeps what is in its hands and is nonetheless out of pocket: the bond doubles the value at the link precisely so that crediting the defector with everything it retains still leaves defection self-destructive. That is mutual assured destruction with the retained value accounted for, and it never executes &mdash; no operation of the mechanism consumes a bond, an unresolved position is simply held, and the standoff therefore ends in performance rather than in loss.
                </p>
                <p>
                    Two boundaries follow, and both are load-bearing for a legal reader. First, the goods, every passage of value between the parties, and the parties&rsquo; knowledge of both lie outside the mechanism&rsquo;s reach; what it holds is bonds, the accumulator, and a record of commitments. The record therefore shows what was undertaken and what remains unsettled &mdash; never that anyone performed. Second, disagreements are worked out between the parties <em>while the process stands open</em>: a remedy is negotiated before resolution &mdash; concretely, a seller that cannot perform sends the buyer the payment it stands to receive, so that resolution leaves it its bond and nothing more &mdash; and the buyer resolves once satisfied. An external forum rules on that open record and cannot call resolve in the buyer&rsquo;s place. That absence of direct enforcement, rather than any question of timing or of layers stacked above the kernel, is what lets a forum compose without touching the equilibrium; Sections 5 and 7 develop the point.
                </p>
                <p>
                    Around those two calls the enforcement architecture is layered. We state each layer here from the legal-design perspective and walk it through operationally, because practitioners frequently arrive with the question &ldquo;where does my dispute go?&rdquo;
                </p>
                <PaperSubsection title="Layer 0 — chain security">
                    <p>
                        Beneath every claim in this paper sits the security of the underlying chain: its consensus rules and finality guarantees are what make an on-chain record authentic in the first place. The evidentiary properties developed in Sections 3 and 4 &mdash; that a record at block <Math>{"b"}</Math> is the same record at block <Math>{"b + N"}</Math>, that the integrity of an entry is a property of the kernel&rsquo;s bytecode and the chain&rsquo;s consensus rules rather than of any party&rsquo;s custodial practice &mdash; are inherited from this layer, not asserted by the protocol above it. We name it as a layer rather than assume it silently, because the entire evidentiary argument is only as strong as the chain&rsquo;s resistance to reorganization and censorship.
                    </p>
                </PaperSubsection>
                <PaperSubsection title="Layer 1 — bonding, with its co-resident record">
                    <p>
                        Both sides of every commitment are bonded, and no bonded balance returns to its poster except through buyer-initiated atomic resolution. The exposures are not symmetric and the asymmetry is the point: the buyer&rsquo;s scales with the payment it agreed, while the seller&rsquo;s scales with everything the process has accumulated through its own link, so a participant deep in a value-added chain stands in a position considerably larger than what it earns there. On that structure the equilibrium stated above holds at every link &mdash; after performance the buyer strictly prefers to resolve, and given that, performance is each seller&rsquo;s strict best response &mdash; and it holds after crediting a defector with everything it retains. The class of dispute this layer is designed to remove is accordingly removed at the point of bonding rather than adjudicated afterwards.
                    </p>
                    <p>
                        <em>The record is co-resident with the bond, not a fallback.</em> Every commit and every resolve emits an immutable record as a mechanical byproduct &mdash; the commitment digest, the bond deposits, the process&rsquo;s monotonic settlement state, the resolution event with its payout vector. No party can collect a settlement payout without the corresponding events having been emitted (Section 3 develops this as the settlement-byproduct property). The record is therefore produced <em>always, by construction</em>, at the same layer as the bond and in the same act &mdash; not summoned later for the cases the bond failed to prevent. What the outer layers add is not the record but a <em>forum</em> that reads it.
                    </p>
                    <p>
                        <em>What does and does not reach a forum at Layer 1.</em> The clearest case for Layer-1 prevention is the <em>cooperation/defection</em> dispute: a counterparty who would have walked away from a conventional contract because the cost of performance exceeded the cost of breach is, under the bonded posture, walking away from twice the value in its hands &mdash; it keeps what it took and is still out of pocket by at least the value accumulated at its link, against a payment it declined. Real commerce, however, is dominated by a different class: <em>information-asymmetry</em> disputes about whether the seller&rsquo;s performance conformed to the agreement (did the goods conform? was time of the essence? did the description match?). The bonded posture pressures the seller toward addressing dissatisfaction, because the seller&rsquo;s bond remains locked while the buyer withholds resolution; but it does not by itself resolve the underlying factual question of whether the buyer&rsquo;s dissatisfaction is justified. Information-asymmetry disputes survive Layer 1 by construction and flow to Layer 2 if multi-party, or to the off-chain forums (Layers 3&ndash;4) if the parties cannot converge.
                    </p>
                </PaperSubsection>
                <PaperSubsection title="Layer 2 — peer coordination">
                    <p>
                        Atomic resolution means no co-seller is paid until the buyer resolves the whole process at once. So when one seller in a multi-party process has not performed, every other seller&rsquo;s interest runs toward <em>remedying</em> the fault rather than punishing it: their own bonds stay locked until the buyer is satisfied. The magnitude of that interest is readable from the record, writing <Math>{"P_i"}</Math> for the payment on the <Math>{"i"}</Math>-th order of the process and <Math>{"G_i"}</Math> for the value accumulated through that order&rsquo;s link. A co-seller that has already performed stands in exactly <Math>{"P_i + 2G_i"}</Math> &mdash; the payment it forgoes, plus its whole bond locked against a product it has already parted with &mdash; and that figure is computable in advance, its position being fixed. One that has not yet performed stands in at least <Math>{"P_i + G_i"}</Math>, since it still holds what is in its hands; here the record gives the floor and no more, the balance turning on how much of the value at its link that seller could actually retain, which is exactly the sort of quantity the mechanism cannot see. The party most exposed to another&rsquo;s failure is thus the one that has already done its part. What co-sellers <em>do</em> with that interest &mdash; a call, an escalation, a substitution arranged among themselves &mdash; is conduct the mechanism neither prescribes nor derives; what it supplies is the interest, which is what makes any of those responses rational rather than altruistic. This is the coordination-pressure component of joint-liability peer enforcement and only that component: nothing here reproduces peer selection or peer monitoring, which rest on a social substrate the mechanism does not assume.
                    </p>
                    <p>
                        The pressure is endogenous to the bonded structure; no governance, no platform, no aggregator, no foundation organizes it. This layer handles disputes that survive Layer 1 by internalizing them as intra-cohort coordination problems.
                    </p>
                </PaperSubsection>
                <PaperSubsection title="Layers 3–4 — the off-chain forums">
                    <p>
                        The residual that survives Layers 1 and 2 &mdash; a participant acts irrationally, the cohort cannot self-coordinate, external circumstances (regulatory action, force majeure, participant death) prevent normal resolution, or the underlying agreement is contested on substantive grounds (duress, mistake, frustration, illegality, public policy) &mdash; goes to a forum that rules on the record while the process stands open. These forums are ordered outward. <strong>Layer 3</strong> is decentralized or institutional <em>arbitration</em>: a Schelling-jury protocol, or a seated commercial arbitration whose award travels under the New York Convention. <strong>Layer 4</strong> is the <em>traditional legal system</em> &mdash; the courts of the jurisdiction whose law the agreement selects. Recourse to Layers 3 and 4 exists even when the agreement names no dispute clause: the record is admissible on its own terms, and a party may bring it to whatever forum has jurisdiction over the counterparty.
                    </p>
                    <p>
                        <em>What such a forum can and cannot do.</em> It can determine what was undertaken, from the record, and what happened, from what the parties bring it; it can rule, and its ruling can be enforced against the parties in the ordinary way, through their exposure outside the process. What it cannot do is settle the process. Resolution is the buyer&rsquo;s alone, and no ruling gives anyone else the call. A forum&rsquo;s ruling therefore enters the process only by changing what the parties expect from continuing to withhold: it feeds the remedy they negotiate, and the buyer&rsquo;s resolution, once satisfied, records that the matter was settled between them. That resolution is terminal &mdash; acceptance, after which the mechanism holds nothing further for anyone to recover.
                    </p>
                    <p>
                        <em>The forum the parties chose.</em> Where the parties do name a forum, it is named by their off-chain agreement. Neither Layer 3 nor Layer 4 is imposed by the protocol; the protocol produces the evidentiary record on which the chosen forum operates. Section 8 catalogues the classes of forum the protocol composes with.
                    </p>
                </PaperSubsection>
                <PaperRun title="What is and is not on chain.">
                    Settlement is on chain. Adjudication is off chain. The split is deliberate. Settlement is deterministic, automated, and public &mdash; all properties that on-chain execution provides natively. Adjudication is contextual, discretionary, and jurisdiction-specific &mdash; all properties that on-chain execution is poorly suited for. The split lets each layer do what it does best and avoids forcing one to imitate the other.
                </PaperRun>
                <PaperRun title="The practical guidance.">
                    Expect Layer 1 to handle the vast majority of cases; Layer 2 the multi-party residual; the off-chain forums (Layers 3&ndash;4) the small residual that survives both. The allocation is what makes forum choice a real choice rather than a formality, and Section 8 returns to it: a small residual can justify a forum whose recognition properties would be inadequate to carry a larger one.
                </PaperRun>
            </PaperSection>

            <PaperSection title="3. Evidentiary Properties and the Two Record Classes">
                <p>
                    The on-chain record produced by Figaro has six properties that together constitute its evidentiary value. The record is not a single artifact class, however; after enumerating the properties we taxonomize the protocol&rsquo;s records into two classes, distinguished by how they are produced and what they prove, to which the properties apply differently.
                </p>
                <PaperRun title="(1) Timestamped.">
                    Every state transition is associated with a block timestamp. The timestamp is set by block proposers under consensus rules; it is not subject to retroactive modification. It is not a <em>qualified</em> electronic time stamp in the eIDAS sense. What it has instead is the regulation&rsquo;s non-discrimination rule for electronic time stamps, which denies neither legal effect nor admissibility on the ground that a time stamp is electronic or falls short of the qualified requirements, leaving weight to the forum&rsquo;s contextual assessment. Section 4 states the doctrine.
                </PaperRun>
                <PaperRun title="(2) Cryptographically signed.">
                    Every commitment is signed by both parties using EIP-712 typed structured data (Bloemen et al., 2017). The signatures bind the material terms and the agreement hash to the signers&rsquo; private keys. Recovery is deterministic; tampering with any field invalidates the signature. One retrieval detail matters to anyone planning expert testimony: the commitment&rsquo;s terms and its digest replay from the emitted logs, whereas the signatures are neither stored nor logged, so recovering the signers means reading the calldata of the transaction that carried them. Both are on chain and both are permanent; they are not the same act of retrieval.
                </PaperRun>
                <PaperRun title="(3) Content-addressed.">
                    Order identifiers are content-addressed hashes of the commitment. The same commitment content always produces the same identifier; different content always produces different identifiers (collision-resistant under the assumed hash function). This makes the record unforgeable in a specific sense: no second commitment can claim the same identifier.
                </PaperRun>
                <PaperRun title="(4) Immutable.">
                    On a finalized block, the record cannot be modified or deleted. A party seeking to repudiate a commitment cannot purge the chain of the relevant log entries. This is a stronger property than what electronic records normally enjoy.
                </PaperRun>
                <PaperRun title="(5) Publicly verifiable.">
                    Anyone can read the chain and replay the verification logic. The evidence is not held by any single party; it is held by the network. Disputing parties therefore cannot disagree about what the record says &mdash; they can disagree only about what the record <em>means</em>, which is precisely the question adjudication is suited to.
                </PaperRun>
                <PaperRun title="(6) Contains commitment intent.">
                    The signed payload includes a content hash <Math>{"h"}</Math> of the off-chain agreement. The off-chain agreement itself can be anything the parties choose &mdash; a structured contract, a free-text PDF, a clause-typed JSON document. The on-chain record does not interpret the agreement; it commits both parties to a specific document via the hash. A dispute over performance is then a dispute over the referenced document, with the on-chain hash establishing <em>which</em> document is at issue.
                </PaperRun>
                <p>
                    These six properties, combined, produce an artifact that is substantially <em>stronger</em> than the electronic records most courts already accept. Courts admit emails, electronic signatures, and database extracts as evidence subject to authentication challenges; the on-chain record satisfies many authentication requirements at the cryptographic level rather than at the custodial level.
                </p>
                <PaperRun title="Settlement-byproduct records: kernel byproducts.">
                    Settlement-byproduct records are emitted by the kernel itself as a byproduct of commit and resolve. They include the commitment digest, the bond deposits, the process&rsquo;s monotonic settlement state, and the resolution event with its complete payout vector. These are produced as a mechanical side effect of the bonding game: no party can collect the settlement payout without the corresponding on-chain events having been emitted, so their integrity as evidence is underwritten by the game itself. Settlement-byproduct records share four properties. <em>Discretion-free:</em> the kernel emits them without any participant choice. <em>Cryptographically authenticated:</em> each is signed by the parties who participated in the operation that produced it (EIP-712 signatures on commits; the buyer&rsquo;s transaction signature on resolutions), verifiable without consulting any oracle. <em>Append-only:</em> a settlement-byproduct record at block <Math>{"b"}</Math> is the same record at block <Math>{"b + N"}</Math> for any <Math>{"N"}</Math>. <em>Typed at the kernel level:</em> the structure is determined by the kernel&rsquo;s own typed events, known in advance and machine-readable; the kernel is otherwise blind to the parties&rsquo; terms, its only agreement-side field being the opaque fingerprint of their document.
                </PaperRun>
                <p>
                    The four properties together make settlement-byproduct records <em>strong evidence</em>: an off-chain forum can rely on the record&rsquo;s existence and content with high confidence and minimal expert testimony. The functional-equivalence analysis of Section 4 &mdash; writing, signature, original &mdash; applies to them directly, the integrity those standards ask about being supplied by the kernel&rsquo;s bytecode and the consensus rules of the underlying chain rather than by any party&rsquo;s record-keeping.
                </p>
                <PaperRun title="Discretionary-attestation records.">
                    Discretionary-attestation records are filed by participants against an order that is already committed. They include delivery confirmations, emissions disclosures, handoff attestations, custody-of-seal events, lifecycle stage transitions, and the other clause-typed records a running process produces. Five properties characterize the class, and the third is the one a forum should weigh most heavily. <em>Discretionary:</em> a participant chooses whether, when, and what to attest within the space its clause section allows, and this is what separates the class from the first. <em>Role-gated:</em> authority to file comes from the sender&rsquo;s role in the order itself &mdash; the seller of that order, its buyer, or a party whose authority the seller&rsquo;s own composed role-resolution confers &mdash; and not from any further signature; the only EIP-712 signatures in a process are the two on the commitment, and what those bind is the agreement fingerprint. <em>Agreement-bound:</em> an attestation cannot be filed at all except under a clause section the two parties&rsquo; signed agreement already contains. The record names a clause and the fingerprint of the section it is filed under, and both must open under the merkle root committed with the order; a seller who signed an emissions clause naming one standard cannot later attest under a different one, because the inclusion proof does not open and the record is never made. The class is therefore anchored to the undertaking by construction rather than by anyone&rsquo;s diligence. <em>Window-bounded:</em> an attestation is admitted only while its order stands unresolved, so the evidence window closes with the process it belongs to &mdash; the same boundary Section 5 draws for forums. <em>Append-only:</em> an incorrect attestation cannot be retracted, only contextualized by a later one; the correction is itself a record, and what a forum sees is the sequence.
                </PaperRun>
                <p>
                    Together these make discretionary-attestation records <em>useful but contestable evidence</em>. An off-chain forum can rely on the record&rsquo;s existence, on the identity of the party that filed it, and on its place in the agreement the parties signed &mdash; three cryptographic facts, none of which asks it to trust a custodian. What none of them establishes is the substantive accuracy of what the record asserts: that the delivery happened as the seller stated, that the emissions disclosure reflects reality. Two distinct questions survive that verification &mdash; whether the recorded event occurred at all, and whether it was recorded at the right amount, timing, and characterization &mdash; and a party who selectively attests, silent about underperformance and precise about performance, can produce a record impeccable on every count above that still misrepresents reality. Adjudication should treat such records under ordinary authentication-and-hearsay doctrine rather than extending the settlement-byproduct class&rsquo;s assurance to them.
                </p>
                <PaperRun title="What the second class&rsquo;s weight rests on.">
                    Discretionary-attestation records are evidentiary artifacts <em>about</em> the undertaking a process records, not undertakings in their own right: a delivery confirmation, an emissions disclosure, or a custody-of-seal event asserts something concerning the commitment, and derives its significance from that commitment rather than from itself. Their weight is accordingly corroborative &mdash; and what it rests on differs by the path on which the process settles, which is a distinction a litigant should establish before relying on either.
                </PaperRun>
                <p>
                    On the <em>direct</em> path the floor is the agreement binding described above, and it is a binding to the agreement rather than a warrant of content. The chain receives the fingerprint of the attested content and never its preimage; it inspects nothing and validates no shape. Well-formedness under the clause&rsquo;s published specification is an off-chain concern at both ends &mdash; an authoring discipline when the record is written, a reading discipline when a forum or an indexer consumes it. What the direct path establishes is that the record was filed by an authorized party, against a live order, under a section of the agreement both parties signed. It does not establish that the content satisfies the clause it was filed under.
                </p>
                <p>
                    On the <em>batched</em> path the assurance is stronger, and the difference is worth stating precisely, because the stronger form is the one a reader is likely to assume everywhere. There settlement carries a proof, and the proof validates each attestation&rsquo;s content against the clause specification that the public clause registry anchors; a batch whose contents do not satisfy their specifications does not settle. Two rejections accordingly exist on that path and not on the other: a record filed under an unregistered clause type, and a record whose content does not satisfy the registered type&rsquo;s rules. A forum told that an attestation was &ldquo;validated on chain&rdquo; should therefore ask which path settled the process. On the direct path the honest answer is that the record&rsquo;s clause section was validated against the signed agreement and its content was not validated at all &mdash; which is a real assurance, and a narrower one than the phrase suggests. The discipline governing which clause types exist and what each admits is part of the weight such records carry on either path, and a reason to know, before the dispute, under what type the load-bearing attestations were filed.
                </p>
                <PaperRun title="Why the taxonomy matters for forum strategy.">
                    A litigant taking the bonded record to a forum should expect the forum&rsquo;s treatment of settlement-byproduct and discretionary-attestation records to differ in detail even if both are admissible. For settlement-byproduct records, the analysis reduces to authentication (signatures verify; chain matches; expert if needed) then content interpretation (what does the recorded state mean for the parties&rsquo; claims) &mdash; authentication is nearly mechanical, interpretation is the work. For discretionary-attestation records, the analysis expands to include the agreement binding (does the named clause section open under the root the parties signed), whatever content validation the settlement path in fact supplied, and <em>substantive truth-of-content</em> (does the attestation reflect the off-chain reality it asserts), the last contestable at per-attestation granularity. A party whose load-bearing factual claims rest on discretionary-attestation records therefore faces a different litigation profile from one whose claims rest on settlement-byproduct records &mdash; the resolution event itself, say, which is undeniable on chain. Most processes produce both, and the difference is worth knowing when the agreement is drafted rather than when the dispute begins.
                </PaperRun>
            </PaperSection>

            <PaperSection title="4. Legal Fit: Existing Electronic-Evidence Frameworks">
                <p>
                    We sketch how the six properties above interact with four major electronic-evidence frameworks. The treatment is illustrative; a full doctrinal analysis is jurisdiction-by-jurisdiction.
                </p>
                <PaperRun title="eIDAS (EU Regulation 910/2014).">
                    eIDAS distinguishes electronic signatures, advanced electronic signatures (AdES), and qualified electronic signatures (QES). EIP-712 signatures meet the AdES technical requirements (uniquely linked to the signatory; capable of identifying the signatory; created using means under the signatory&rsquo;s sole control; linked to the signed data such that any subsequent change is detectable). They do not by themselves meet the QES requirements (which include a qualified certificate from a trust service provider). However, AdES status is sufficient for most contractual purposes, and eIDAS explicitly provides that the legal effect of an electronic signature shall not be denied solely because it is in electronic form. eIDAS also defines qualified electronic time stamps, and the same structure recurs: a block timestamp on a chain with public consensus rules answers the binding requirement of Article 42(1)(a) well &mdash; date and time are bound to the data such that undetected alteration is impracticable &mdash; answers Article 42(1)(b)&rsquo;s accurate-time-source requirement only approximately, since a proposer sets the value within a consensus tolerance rather than from a traceable reference clock, and does not answer Article 42(1)(c) at all, which requires that the time stamp be &ldquo;signed using an advanced electronic signature or sealed with an advanced electronic seal of the qualified trust service provider, or by some equivalent method.&rdquo; The closing words do not open the door they appear to: what they admit is an equivalent <em>method</em> of a qualified provider, and qualified status is conferred on a supervised provider under the regulation&rsquo;s supervision regime, not earned by a technique &mdash; a permissionless network with no legal person to supervise has nothing to which the status could attach. No such provider stands behind a public chain, so the block timestamp is <em>not</em> a qualified electronic time stamp, and the presumption of accuracy and integrity that Article 41(2) grants qualified time stamps does not attach to it. What attaches instead is Article 41(1): legal effect and admissibility as evidence are not denied solely because a time stamp is in electronic form or does not meet the qualified requirements. The practical effect: the on-chain record is admissible electronic evidence under eIDAS, with weight determined by the court&rsquo;s contextual assessment rather than by a statutory presumption.
                </PaperRun>
                <PaperRun title="UCC &sect;1-201 and the Federal Rules of Evidence (US).">
                    The Uniform Commercial Code defines &ldquo;record&rdquo; as information inscribed on a tangible medium or stored in an electronic medium and retrievable in perceivable form; on-chain log entries satisfy this without ambiguity. UCC &sect;1-201 also defines &ldquo;signature&rdquo; inclusively (any symbol executed or adopted with present intention to adopt or accept a writing); EIP-712 signatures qualify. UETA and the federal E-SIGN Act extend the principle to contracts more broadly. For evidentiary admission, the operative provisions are FRE 901(b)(9), 902(13), and 902(14), with the <em>Daubert</em> standard for any expert testimony required to authenticate the cryptographic process. FRE 901(b)(9) permits authentication by showing that a process or system produces an accurate result; FRE 902(13) (added 2017) permits self-authentication of records generated by an electronic process or system; FRE 902(14) permits self-authentication of data copied from electronic devices through a process producing a digital identifier &mdash; here the cryptographic hash of the record itself (US Judicial Conference, 2017). On-chain commitments are records and signatures under US commercial law, admissible through the established electronic-evidence pathway and authenticatable through <em>Daubert</em>-qualified expert testimony where authentication is challenged.
                </PaperRun>
                <PaperRun title="Singapore Electronic Transactions Act (Cap. 88).">
                    Singapore&rsquo;s ETA closely follows the UNCITRAL Model Law on Electronic Commerce and provides functional equivalents for &ldquo;writing,&rdquo; &ldquo;signature,&rdquo; and &ldquo;original&rdquo; in electronic form. On-chain commitments answer each in turn, and the three answers are worth separating because they are what the argument of this paper actually uses.
                </PaperRun>
                <p>
                    <em>Writing.</em> The functional test is accessibility for subsequent reference; a commitment recorded on a public ledger, readable by anyone at any later time and not held in any party&rsquo;s custody, satisfies it without strain. <em>Signature.</em> The functional test is that the method identify the signatory and indicate that signatory&rsquo;s approval of the information; an EIP-712 signature does both, deterministically and over the exact material terms. <em>Original.</em> The functional test is integrity &mdash; that the information has remained complete and unaltered since it was first generated in its final form &mdash; and this is where the on-chain record is on stronger ground than the electronic records the standard was drafted for. Integrity here is a property of the record&rsquo;s construction rather than of anyone&rsquo;s record-keeping: a finalized entry is the same entry at every later block, and any alteration of a signed field invalidates the signature that binds it. A forum applying the original-form test to an on-chain commitment is not asking whether a custodian kept it faithfully; there is no custodian.
                </p>
                <p>
                    One boundary should be marked rather than crossed. The ETA was amended in 2021 to recognize <em>electronic transferable records</em> &mdash; instruments of title treated as functionally equivalent to negotiable paper &mdash; and whether a bonded commitment, or a right to receive performance moving along a process, can be constituted as a transferable record of that kind is a distinct question from the admissibility question argued here. Nothing below turns on the answer: the evidentiary case for the record, the treatment of substantive defenses, and the forum analysis are all questions of admissibility and weight, not of negotiability. We note the question and do not decide it.
                </p>
                <PaperRun title="UNCITRAL Model Law on Electronic Commerce.">
                    Adopted in 1996, the UNCITRAL Model Law articulates the functional-equivalence principle underlying most modern electronic-evidence regimes. Its three core requirements &mdash; accessibility for subsequent reference, integrity of the information, and identifiability of the originator &mdash; are all satisfied by on-chain commitments, for the reasons just given. Jurisdictions that have adopted UNCITRAL-derived electronic-transactions law (over 80 as of 2024) therefore provide an established framework for treating on-chain commitments as admissible electronic evidence.
                </PaperRun>
                <PaperRun title="The summary picture.">
                    The on-chain record is admissible electronic evidence in every jurisdiction whose electronic-evidence law derives from the UNCITRAL framework or implements equivalent functional principles. What varies is the weight courts assign (a question of judicial practice rather than admissibility) and the further procedural requirements for authenticating the chain itself (typically satisfied by expert testimony or judicial notice of well-known chains). No jurisdiction we are aware of categorically excludes on-chain records from evidentiary consideration.
                </PaperRun>
            </PaperSection>

            <PaperSection title="5. Substantive Defenses and Where Their Remedies Reach">
                <p>
                    A reader sympathetic to the argument so far will raise the sharpest question this paper has to answer. Suppose the on-chain record is unimpeachable as evidence; suppose every framework above admits it. What happens when a court, applying the substantive contract law of its jurisdiction, finds that the underlying agreement was procured under duress, formed under fundamental mistake, frustrated by impossibility, voided by illegality, or unconscionable in its terms? The mechanism admits no operation but commit and resolve, and no forum can call either. The question is therefore what such a court can do, and whether the division between settlement (on-chain) and adjudication (off-chain) is consistent with the substantive-defense jurisprudence the dominant tradition has developed over centuries.
                </p>
                <PaperRun title="Doctrinal inventory.">
                    The defenses that void or rescind a contract <em>ab initio</em>, or that excuse subsequent performance, are doctrinally settled in the major commercial jurisdictions. Common-law systems recognize <em>duress</em> (consent obtained by improper threat); <em>undue influence</em> (abuse of a relationship of trust); <em>misrepresentation</em> (false statements about material facts); <em>fundamental mistake</em> (shared mistake about an essential fact); <em>unconscionability</em> (terms so one-sided that enforcement shocks the conscience); <em>frustration of purpose</em> and <em>impossibility / impracticability</em> (subsequent events render performance fundamentally different or impossible); <em>illegality</em>; and <em>public policy</em>. Civil-law systems recognize closely parallel doctrines (<em>vices du consentement</em>, <em>erreur</em>, <em>circonstances exceptionnelles</em>). The doctrines are substantive: they apply to <em>the agreement</em> the bonded commitment records, not to the bonded commitment as a technological artifact.
                </PaperRun>
                <PaperRun title="Substantive-defenses analysis.">
                    The bonded primitive is silent on every doctrine in the inventory. The kernel does not know whether consent was procured under duress, whether parties were mistaken about a material fact, whether the underlying transaction was illegal, or whether performance has been frustrated. It records what was signed; it makes no representation about the conditions under which signing occurred or the legality of what was signed for. This is by design: a kernel that made such determinations would have to seat them with someone, and seating a decision that releases bonded balances with any party at all is exactly what the mechanism&rsquo;s two-operation surface excludes &mdash; the no-escape-hatch constraint, stated at the end of this section. The silence is also a <em>feature</em>, because it leaves the substantive-defense apparatus exactly where the dominant tradition has placed it: in courts applying their own constitutional and doctrinal apparatus to the agreement recorded in the bonded commitment. The leading case-law authority is <em>B2C2 Ltd v Quoine Pte Ltd</em> [2019] SGHC(I) 03, carried on appeal to <em>Quoine Pte Ltd v B2C2 Ltd</em> [2020] SGCA(I) 02, where the appeal succeeded in part on other grounds and the contract holding stood. Between them the Singapore International Commercial Court and the Court of Appeal worked out how the doctrine of unilateral mistake applies to deterministic algorithmic execution &mdash; locating the relevant knowledge at the time the algorithm was programmed, not at execution. On the facts the mistake defence failed and the trades stood, but the case establishes that smart-contract executions are not beyond the reach of conventional contract doctrine.
                </PaperRun>
                <p>
                    Such a defense is raised in one of two postures, and the mechanism&rsquo;s position is the same in both. The ordinary posture is that the process still stands open: the forum rules on the record and on what the parties bring it, its ruling feeds the remedy the parties negotiate between themselves, and the buyer resolves once satisfied &mdash; or does not, in which case the bonded positions simply stand, since nothing expires and nothing is banked short of resolution. The second posture is that the process has already been resolved. Resolution is terminal acceptance and the mechanism holds nothing afterwards for anyone to recover, so a party with a surviving claim is in the position of any party to a payment that has already cleared: it litigates, and the remedy reaches its counterparty through that counterparty&rsquo;s conventional legal exposure rather than through any balance the mechanism holds.
                </p>
                <p>
                    The remedies themselves take three shapes, and none of the three is novel. <em>Case 1: specific re-transfer between the parties.</em> Where one party holds value it should not, the standard remedy is a restitutionary order to transfer that value back. The order operates on the parties&rsquo; real-world capacity to comply, not on any state the mechanism holds; the record shows the commitments and whatever settlement occurred, unchanged, and the corrective transfer is recorded separately, wherever the parties make it. This is the most common form and the one for which the existing legal apparatus is best-equipped. <em>Case 2: a fresh bonded counter-process.</em> Where ongoing performance and a counter-flow are appropriate, the parties (or the court by an order on the parties) constitute a fresh bonded process flowing value in the corrective direction &mdash; the primitive serving as the implementation of the remedy rather than as an obstacle to it, and each of its edges bonded under the same rule as any other. <em>Case 3: an arrangement the kernel cannot express.</em> The remedy then operates on the parties&rsquo; off-chain assets and obligations through conventional mechanisms (asset seizure, contempt sanctions, criminal liability for non-compliance). The kernel does not obstruct the remedy; it does not implement it either.
                </p>
                <PaperRun title="The no-escape-hatch constraint, and why the external forum is not one.">
                    The constraint and its carve-out both deserve a precise characterization. The constraint is that the mechanism offers exactly two operations and no unilateral exit from the bonded state: any further path out would either seat the release of the bonds with a party the bonds do not constrain &mdash; an arbitrator, a jury, an oracle, an electorate, whose ranking of the alternatives is fixed by nothing the mechanism holds &mdash; or add a third continuation at a node whose two the equilibrium weighed against each other, in which case the guarantees stated in Section 2 are no longer guarantees of the game being played. Timeouts, cancellation paths, and governance votes are all excluded on that ground. The carve-out admits external legal forums applying duress, frustration, and the rest of the inventory above, and it is sound for one reason, which is neither that such forums are themselves bonded nor that they act only once the mechanism has finished: it is that <em>no forum can call resolve</em>. Resolution is the buyer&rsquo;s alone. A ruling therefore never sits on the path by which a bonded balance is released &mdash; there is no custodian register for an order to touch and no discretion for it to redirect &mdash; and it reaches the parties as rulings ordinarily reach parties, through their exposure outside the process, entering the process only by changing what each expects from continuing to withhold. That absence of direct enforcement is what makes the composition free. The bonded primitive does not displace contract law&rsquo;s substantive doctrines; it produces a record under which those doctrines continue to apply in the conventional way, and it leaves their enforcement exactly where it has always been.
                </PaperRun>
            </PaperSection>

            <PaperSection title="6. Jurisdictional Implications">
                <p>The decoupling of settlement from adjudication has substantive jurisdictional consequences.</p>
                <PaperRun title="Forum is contractual.">
                    The on-chain commitment includes an off-chain agreement hash <Math>{"h"}</Math>. That off-chain agreement can &mdash; and typically should &mdash; include a forum-selection clause, a choice-of-law clause, and an arbitration clause if the parties prefer arbitration to court. The on-chain record proves what was agreed; the off-chain agreement specifies where and under what law the agreement is adjudicated. Parties who omit a forum clause default to whatever private-international-law analysis the seised forum applies; this is a known regime, not a novel problem.
                </PaperRun>
                <PaperRun title="Forum-shopping is bounded.">
                    A party seeking to forum-shop is bounded by (a) the forum-selection clause in the off-chain agreement, (b) the seising forum&rsquo;s own jurisdictional rules, and (c) the recognition-and-enforcement treaties between the seising forum and any forum where the counterparty&rsquo;s assets reside. None of these constraints is weakened by the on-chain settlement; they all operate on the off-chain agreement and the parties&rsquo; real-world circumstances.
                </PaperRun>
                <PaperRun title="Evidence is jurisdiction-displaced.">
                    The integrity of the on-chain evidence does not depend on the seising forum&rsquo;s recognition of any specific cryptographic standard. The signatures verify, or they do not; the chain hashes match, or they do not. A forum that doubts the cryptographic analysis can engage an expert; a forum that does not is in the position of any forum facing forensic evidence.
                </PaperRun>
                <PaperRun title="Cross-border processes.">
                    A multi-party process can involve parties in multiple jurisdictions simultaneously. The on-chain settlement is jurisdiction-blind: the bond mechanics work identically regardless of where the parties reside. Off-chain disputes arising from such processes are handled by the same private-international-law machinery that already handles cross-border disputes in conventional commerce &mdash; typically with the on-chain record providing substantially more evidentiary clarity than the parties would have produced under conventional bookkeeping.
                </PaperRun>
                <PaperRun title="A worked example: New York forum, cross-border process.">
                    Consider a multi-party process with a buyer in New York and two value-adders &mdash; one in Singapore and one upstream in Argentina, co-equal parties to the same root buyer, differing only in their position in the value chain &mdash; settled in <code>USDC</code> on Ethereum L1. The off-chain agreement specifies New York Supreme Court as the forum and New York law as the governing law. A dispute arises: the Singapore seller claims the buyer never resolved the process despite delivery; the buyer claims the goods did not conform to the agreed specification. Admissibility is settled by the Section 4 framework and needs no re-argument here; what the example adds is the fact-to-forum routing. The seller&rsquo;s claim &mdash; that the buyer never resolved &mdash; is determinable from the chain state directly: the resolution transaction is present or it is absent. The buyer&rsquo;s claim &mdash; that the goods did not conform &mdash; is not determinable from the chain state and requires off-chain evidence: delivery records, photographs, laboratory analyses, and the clause-typed attestations that may already be on chain. The New York court, applying New York contract law (UCC Article 2 for the goods, NY CPLR for procedure, New York&rsquo;s Electronic Signatures and Records Act (State Technology Law art. 3) for electronic signatures), decides the substantive question &mdash; did the goods conform? &mdash; on the off-chain evidence under ordinary contract doctrine. What its ruling then does is what any ruling does: it reaches the parties through their conventional legal exposure, enforceable in the standard ways (US&ndash;Singapore reciprocity, the New York Convention where the clause is arbitral, asset attachment), and it settles for them the question they could not settle between themselves. The process meanwhile stands open, every bond still locked. If the court finds the goods conformed, the buyer resolves and the sellers are paid; if it finds they did not, the parties negotiate the remedy the ruling implies &mdash; a cure, a substitution, a payment from the seller that makes the buyer whole &mdash; and the buyer resolves once satisfied. What the court cannot do, and does not need to do, is settle the process itself. The bonded structure does not interfere with any of this, and it supplies the thing cross-border commerce has otherwise had to buy from letters of credit, escrow agents, and intermediary banks: neither side can take the other&rsquo;s value and disappear while the question is being decided.
                </PaperRun>
            </PaperSection>

            <PaperSection title="7. Why Not On-Chain Adjudication">
                <p>
                    We have argued the positive case for off-chain adjudication. We now argue the negative case against on-chain adjudication. Several patterns occupy this space; we treat each briefly.
                </p>
                <PaperRun title="Schelling-point juror selection (Kleros).">
                    A token-weighted juror panel votes on the disputed question; the plurality wins; jurors who voted with the plurality are rewarded, those against are slashed. The mechanism is elegant in abstraction but has three problems for serious adjudication. First, the panel is not selected for jurisdictional fit &mdash; a juror in jurisdiction <Math>{"A"}</Math> may know nothing of jurisdiction <Math>{"B"}</Math>&rsquo;s law that the parties agreed should govern. Second, the juror&rsquo;s incentive is to vote with the perceived plurality, not the legally correct outcome &mdash; a Schelling point on plurality is structurally distinct from a Schelling point on truth. Third, the slashing mechanism imports a new dispute (was the slashing fair?) that has no terminal forum on chain.
                </PaperRun>
                <PaperRun title="DAO-governed arbitration (Aragon Court).">
                    Aragon Court is structurally similar to Kleros, with juror-selection integrated with DAO governance. This inherits Kleros&rsquo;s problems plus the additional one that DAO voting power is plutocratic in proportion to token holdings; the wealthy juror has structurally more votes than the poor juror. Whether that is desirable is a normative question; that it differs from the &ldquo;one juror, one vote&rdquo; premise of jury trials is a doctrinal question that has not been settled.
                </PaperRun>
                <PaperRun title="Optimistic challenge windows.">
                    Optimistic mechanisms (Optimism, 2021; UMA, 2020) avoid the juror problem by allowing assertions to stand unless challenged within a fixed window. This works for settlement-layer state machines but not for adjudication, because adjudication is precisely the activity of assessing an assertion that has been challenged. An optimistic &ldquo;adjudication&rdquo; is just an assertion with a deadline &mdash; it has no mechanism for resolving the underlying question, only for resolving who blinked first.
                </PaperRun>
                <PaperRun title="The structural objection.">
                    All on-chain adjudication mechanisms share the same flaw, and the no-escape-hatch constraint of Section 5 names it. Any release of a bonded position other than by the buyer&rsquo;s resolution has to be made available on somebody&rsquo;s decision. Where that somebody is a party other than the two who bonded, the release turns on an agent that deposited nothing into the process, holds nothing of what the process moves, and whose ranking of the alternatives is therefore fixed by nothing the mechanism holds or can offer. On-chain adjudication is exactly that case: the juror, the DAO voter, the challenger is the unbonded actor whose decision determines the outcome. Whatever the designer does to constrain that actor (token slashing, Schelling incentives, reputation), the constraint is imported from outside the mechanism, and what the mechanism guarantees is no longer what it guaranteed.
                </PaperRun>
                <PaperRun title="The off-chain alternative.">
                    Off-chain adjudication by an existing legal forum has the opposite structure, and the difference is not that the forum is better constrained &mdash; though it is constrained, judges facing appellate review and arbitrators institutional reputation, both professional sanction. The difference is that the forum is not on the path at all. It cannot call resolve, so nothing it decides releases a bonded balance; its ruling reaches the parties through their exposure outside the process, in the ordinary way, and touches the process only by changing what the parties expect from continuing to withhold. That is a structural fact about the wiring rather than a judgment about the forum&rsquo;s quality, and it is why the composition costs the equilibrium nothing. The evidence record is meanwhile consumed by an institution whose own constraints a regime refined over centuries already supplies. The protocol does not re-implement that regime; it provides input to it.
                </PaperRun>
                <PaperRun title="Forum-agnosticism.">
                    The objection above is to adjudication <em>at the kernel layer</em> &mdash; to seating a decision that releases bonded balances with anyone other than the buyer. It is not an objection to any particular forum, Kleros included. Where the parties&rsquo; agreement designates a forum, the kernel neither adjudicates nor needs to: it produces an evidence record and exports it to whatever forum the parties name &mdash; the Singapore International Arbitration Centre, the New York Supreme Court, or a Schelling-jury system &mdash; and that forum rules on the record while the process stands open. What differs across those choices is not whether the record serves them but the recognition and enforcement properties of the resulting decision, which Section 8 takes up class by class.
                </PaperRun>
            </PaperSection>

            <PaperSection title="8. Composition with Dispute Systems">
                <p>
                    A constructive treatment is owed to the practitioner who arrives with the question &ldquo;which forum should I name in my agreement, and how do I compose with it.&rdquo; We catalogue the four classes of forum the protocol composes with. In each case the composition has the same shape &mdash; the forum rules on the open process record and on what the parties bring it, and its ruling reaches them through their exposure outside the process &mdash; so what distinguishes the classes is the recognition and enforcement properties of what they produce.
                </p>
                <PaperSubsection title="State courts">
                    <p>
                        Conventional state courts are the highest-recognition forum available and the appropriate destination for disputes whose substantive resolution requires the full apparatus of contract law (duress, mistake, frustration, illegality, public policy). The off-chain agreement names a specific state court (e.g., New York Supreme Court, Singapore International Commercial Court, English High Court) and a governing law; the clause is a standard contractual provision. The bonded record is admitted under the relevant evidentiary framework (FRE 901(b)(9) / 902(13)&ndash;(14) for US courts, eIDAS AdES recognition for EU courts, the Singapore ETA for Singapore courts). A judgment is enforceable through standard private-international-law machinery (recognition treaties, the Hague Judgments Convention where in force, domestic enforcement powers); enforcement against on-chain assets requires a court with jurisdiction over the asset-holding party rather than over the bonded primitive itself, which is not a party. State courts are appropriate where the parties need the recognition properties of a state-court judgment, or where the matter touches public policy, sanctions, criminal conduct, or regulatory enforcement.
                    </p>
                </PaperSubsection>
                <PaperSubsection title="International commercial arbitration centers">
                    <p>
                        Centers such as SIAC, the ICC, the LCIA, and the HKIAC are the appropriate destination for cross-border disputes whose parties prefer arbitration to court litigation. The off-chain agreement names the center, the seat, the language, and the procedural rules. Arbitration centers admit electronic evidence broadly with flexible authentication standards; the bonded record satisfies them straightforwardly. The New York Convention (1958, 172 state parties as of 2024) is the canonical recognition framework: an award under SIAC / ICC / LCIA rules is enforceable in any Convention state subject to the Article V grounds for refusal, and the bonded primitive composes with this chain natively because the underlying agreement is a recognized arbitration agreement under Article II. Appropriate where parties want institutional arbitration&rsquo;s combination of expertise, procedural flexibility, and international enforceability.
                    </p>
                </PaperSubsection>
                <PaperSubsection title="Online dispute resolution (ODR) platforms">
                    <p>
                        ODR platforms (eBay&rsquo;s Resolution Center as the volume archetype, Modria, smartsettle, and the broader literature, Katsh and Rabinovich-Einy, 2017) are the appropriate destination for high-volume, low-value disputes where the cost of conventional adjudication exceeds the disputed amount. The off-chain agreement names the platform and accepts its terms-of-service; binding effect is contractual rather than treaty-based. ODR platforms typically accept the bonded record without specialized authentication and use it as the dispositive content for routine disputes. ODR decisions are typically enforced by the platform itself rather than through state machinery. A practitioner pattern of pairing an ODR clause with an arbitration clause that treats unappealed ODR decisions as final is structurally available but doctrinally delicate: many ODR procedures (no live hearing, no discovery, opaque review) fail Article V(1)(b) due-process requirements on standard readings, so the hybrid is a careful drafting matter, not an off-the-shelf composition. Appropriate for routine commercial disputes at operational scale where dispute volume rules out court/arbitration economics.
                    </p>
                </PaperSubsection>
                <PaperSubsection title="Schelling-point juror systems (Kleros and analogues)">
                    <p>
                        Kleros and analogues (Lesaege et al., 2019) occupy a distinctive position: mechanism-based forums where Schelling-point juror selection produces decisions through coordination on the focal answer. The protocol composes with them as the parties&rsquo; chosen forum, but their recognition and enforcement properties are the most contested of the four classes. Our reading of the New York Convention is that a Kleros decision is <em>capable</em> of falling within Article I&rsquo;s definition of an arbitral award where the parties&rsquo; arbitration agreement so designates &mdash; reading the Convention&rsquo;s tribunal definition as functional rather than institutional, and the parties&rsquo; acceptance of the forum&rsquo;s procedural rules as the Article V(1)(d) agreement on composition &mdash; subject to Article V&rsquo;s grounds for refusing recognition; the contrary view (Ortolani, 2019) is defensible, and the question is takable rather than settled. The sharpest ground is Article V(2)(b) public policy: many civil-law jurisdictions treat unreasoned awards as presumptively contrary to public policy, and Kleros decisions are vote tallies, not reasoned awards, so parties intending enforcement in such jurisdictions should pair the clause with a written-opinion supplement or choose a different forum. Appropriate where parties prefer the mechanism&rsquo;s combination of neutrality, speed, and token-economic incentive over conventional recognition properties.
                    </p>
                </PaperSubsection>
                <PaperSubsection title="Composition discipline across the four">
                    <p>
                        Two structural points apply across all four. <em>Forum-clause discipline is the parties&rsquo; choice and responsibility.</em> The bonded primitive does not recommend a forum; the forum is named by the off-chain agreement, and the parties bear the consequences of their choice (recognition properties, enforcement chain, procedural rules, operational cost). The architecture&rsquo;s role is to produce evidence the chosen forum can use, not to constrain the choice. <em>Recognition theory is upstream of forum choice.</em> The parties should name a forum whose decisions they have a clean recognition theory for in the jurisdiction of intended enforcement &mdash; a US-based seller and an EU-based buyer who name SIAC arbitration with Singapore seat have a clean theory through the New York Convention; the same parties naming an ODR platform without arbitration backing do not. <em>The bonded primitive shifts the balance toward weaker forums.</em> Because the bonded posture absorbs most disputes at Layers 1 and 2, the residual reaching the forums (Layers 3&ndash;4) is small (Section 2); a smaller residual can justify a weaker forum than conventional commerce would choose. This is not the architecture replacing stronger forums; it changes the cost-benefit calculation of which forum is appropriate for what residual.
                    </p>
                </PaperSubsection>
            </PaperSection>

            <PaperSection title="9. Conclusion">
                <p>
                    We have argued for a layered approach to smart-contract dispute resolution, with a deliberately designed evidentiary record bridging deterministic on-chain settlement and contextual off-chain adjudication. The architecture inherits the strengths of each layer without forcing either to imitate the other, and it resolves the structural objection to on-chain adjudication: the unbonded juror does not need to exist because the legally constituted forum already does. What lets that forum compose where the juror cannot is a single structural fact, and it is worth restating as the paper&rsquo;s conclusion rather than as one of its steps &mdash; the forum has no direct enforcement. It rules on the record &mdash; while the process stands open, where the parties still hold their bonded positions and a remedy is still to be negotiated, or as the evidentiary base of ordinary litigation once the process has closed &mdash; and it cannot settle the process either way. Resolution stays with the buyer and is terminal. Everything else in the division of labor follows from that.
                </p>
                <p>
                    The debate over smart-contract dispute resolution has been dominated by the assumption that on-chain settlement implies on-chain adjudication. The decoupling we propose is a different design posture, and it permits a substantially cleaner alignment with existing electronic-evidence law.
                </p>
            </PaperSection>
        </PaperLayout>
    );
}
