import type { Metadata } from "next";
import {
    PaperLayout,
    PaperSection,
    PaperSubsection,
    PaperRun,
    PaperRemark,
} from "@/components/papers/PaperLayout";
import { Math } from "@/components/papers/Math";

export const metadata: Metadata = {
    title: "On-Chain Evidence, Off-Chain Adjudication — Figaro Protocol",
    description:
        "Settlement is on-chain by nature, adjudication is off-chain by nature. A layered approach to smart-contract dispute resolution: the protocol produces evidence existing courts already know how to use.",
};

export default function OnChainEvidencePaper() {
    return (
        <PaperLayout
            title="On-Chain Evidence, Off-Chain Adjudication"
            subtitle="A Layered Approach to Smart-Contract Dispute Resolution"
            author="Alessandro Daliana"
            date="April 2026"
            watermark="Figaro Protocol · Preprint"
            keywords="electronic evidence, smart-contract law, dispute resolution, blockchain evidence, eIDAS, UNCITRAL, jurisdictional flexibility"
            abstract={
                <>
                    <p>
                        This paper makes a focused legal argument about smart-contract dispute resolution. The dominant on-chain dispute-resolution designs &mdash; Kleros&rsquo;s Schelling-jury arbitration, Aragon Court&rsquo;s DAO-governed jury, optimistic-rollup challenge windows &mdash; attempt to perform adjudication on chain. We argue that this is a category error: settlement is on-chain by nature, adjudication is off-chain by nature, and conflating the two re-introduces the discretionary intermediary that smart contracts were supposed to remove.
                    </p>
                    <p>
                        We develop the argument by reference to a bonded settlement primitive &mdash; asymmetric bonding composed with buyer-dominated atomic resolution, on a formally verified kernel &mdash; whose three-layer enforcement architecture explicitly separates the bonding game (Layer 1), the peer-coordination subgame (Layer 2), and the evidentiary record that supports off-chain proceedings when the first two layers fail (Layer 3). The contribution of this paper is to develop Layer 3 in detail: the evidentiary properties of the on-chain record, the relationship between those properties and existing electronic-evidence law (eIDAS, UCC §1-201, the Singapore Electronic Transactions Act, the UNCITRAL Model Law on Electronic Commerce), and the jurisdictional implications of decoupling settlement from adjudication.
                    </p>
                    <p>
                        The argument is not that smart contracts replace courts. It is that smart contracts can produce a form of evidence that courts already know how to use, and that the cleanest division of labor is one in which the protocol does what it does well (deterministic settlement) and the legal system does what it does well (contextual adjudication). The protocol is silent on what counts as &ldquo;satisfactory performance&rdquo; or &ldquo;material breach&rdquo; &mdash; those are adjudicative determinations &mdash; but loud on the facts that adjudication needs as input.
                    </p>
                </>
            }
            references={
                <>
                    <li>Cuende, L. and Izquierdo, J. Aragon Network: A Decentralized Infrastructure for Value Exchange. Aragon White Paper, 2017.</li>
                    <li>De Filippi, P. and Wright, A. <em>Blockchain and the Law: The Rule of Code</em>. Harvard University Press, Cambridge, MA, 2018.</li>
                    <li>Bloemen, R., Logvinov, L., and Evans, J. EIP-712: Ethereum typed structured data hashing and signing. Ethereum Improvement Proposal, 2017.</li>
                    <li>Ast, F. and Lesaege, C. Kleros: A Protocol for a Decentralized Justice System. Kleros White Paper, 2019.</li>
                    <li>United Nations. <em>Convention on the Recognition and Enforcement of Foreign Arbitral Awards</em> (the New York Convention). 330 U.N.T.S. 38, 1958.</li>
                    <li>Optimism Foundation. Optimistic Rollups. Optimism Technical Documentation, 2021.</li>
                    <li>Ortolani, P. The Impact of Blockchain Technologies and Smart Contracts on Dispute Resolution. <em>Uniform Law Review</em>, 24(2):430&ndash;448, 2019.</li>
                    <li>Rabinovich-Einy, O. and Katsh, E. <em>Digital Justice: Technology and the Internet of Disputes</em>. Oxford University Press, New York, 2017.</li>
                    <li>Quoine Pte Ltd v B2C2 Ltd [2019] SGHC(I) 03 (Singapore International Commercial Court).</li>
                    <li>Quoine Pte Ltd v B2C2 Ltd [2020] SGCA(I) 02 (Singapore Court of Appeal).</li>
                    <li>US Judicial Conference, Advisory Committee on Evidence Rules. Report on Proposed Amendments to FRE 902(13) and 902(14). Effective December 1, 2017.</li>
                    <li>Goode, R. and Gullifer, L. <em>Goode and Gullifer on Legal Problems of Credit and Security</em>, 6th ed. Sweet &amp; Maxwell, London, 2017.</li>
                    <li>Yunus, M. <em>Banker to the Poor: Micro-Lending and the Battle Against World Poverty</em>. PublicAffairs, New York, 1999.</li>
                    <li>Morduch, J. The Microfinance Promise. <em>Journal of Economic Literature</em>, 37(4):1569&ndash;1614, 1999.</li>
                    <li>American Institute of Certified Public Accountants. <em>AU-C Section 315: Understanding the Entity and Its Environment and Assessing the Risks of Material Misstatement</em> (assertion categories). AICPA, 2020.</li>
                    <li>UMA Project. The Optimistic Oracle. UMA Technical Documentation, 2020.</li>
                </>
            }
        >
            <PaperSection title="1. Introduction">
                <p>
                    Smart-contract dispute resolution is currently a contested design space. The dominant architectures attempt to perform adjudication on chain, typically through some variant of token-weighted juror selection or DAO governance. Kleros (2019) uses Schelling-point juror voting; Aragon Court (2017) embeds arbitration in DAO infrastructure; optimistic mechanisms (Optimism, 2021; UMA, 2020) use challenge windows in which assertions stand unless contested. Each of these approaches addresses the dispute-resolution problem by importing the discretionary actor that would otherwise reside in a court: the juror, the DAO voter, the challenger.
                </p>
                <p>
                    This paper argues that the import is a mistake. The claim is not that on-chain juries are bad mechanisms (they are interesting mechanisms with documented properties); it is that they are solving the wrong problem. The right problem is not &ldquo;how do we adjudicate disputes on chain&rdquo; but &ldquo;how do we produce evidence that off-chain forums can use to adjudicate efficiently.&rdquo; The former requires re-creating, in adversarial token-economic settings, the institutional infrastructure (impartial juror selection, jurisdictional fit, due process) that civil legal systems have refined over centuries. The latter requires only that the on-chain artifact meet existing evidentiary standards &mdash; a substantially easier problem, and one for which the legal infrastructure already exists.
                </p>
                <p>
                    We make the argument in the context of Figaro, a bonded settlement primitive whose mechanism is established and whose kernel is formally verified. Figaro explicitly does not attempt on-chain dispute resolution. Its three-layer enforcement architecture treats Layer 1 (bonding) and Layer 2 (peer coordination) as the primary defenses, and Layer 3 (immutable evidence) as the residual mechanism for cases where Layers 1 and 2 are insufficient. The present paper develops Layer 3.
                </p>
                <PaperRun title="What this paper is not.">
                    This paper does not provide legal advice. It does not predict the admissibility of any specific on-chain artifact in any specific jurisdiction, nor does it claim that the on-chain record is itself sufficient for any particular legal claim. It argues for a design discipline (do not perform adjudication on chain) and catalogues the evidentiary properties of the artifact that the discipline produces. Practitioners who wish to rely on those properties in specific proceedings should obtain jurisdiction-specific counsel.
                </PaperRun>
                <PaperRun title="Paper organization.">
                    Section 2 states the layered architecture and Section 3 walks it through operationally. Section 4 develops the evidentiary properties of the on-chain record and Section 5 taxonomizes those records into two classes. Section 6 compares the properties to existing electronic-evidence law. Section 7 treats substantive defenses and post-settlement restitution; Section 8 works a cross-border example. Section 9 addresses jurisdictional implications, Section 10 argues against on-chain adjudication as a category, and Section 11 catalogues composition with dispute systems. Section 12 concludes.
                </PaperRun>
            </PaperSection>

            <PaperSection title="2. The Three-Layer Architecture">
                <p>
                    Figaro&rsquo;s enforcement architecture is layered. We summarize it here from the legal-design perspective; the mechanism details are developed elsewhere.
                </p>
                <PaperRun title="Layer 1 — bonding.">
                    Each party to a transaction locks <Math>{"2\\times"}</Math> the transaction value (asymmetric for <Math>{"N"}</Math>-party processes; the seller&rsquo;s bond scales with upstream value). The locked capital is recoverable only through buyer-initiated atomic resolution. Cooperation is the strictly dominant strategy; defection costs the full bond. The vast majority of disputes are prevented at this layer because the incentive to defect is structurally negative.
                </PaperRun>
                <PaperRun title="Layer 2 — peer coordination.">
                    Atomic resolution induces a weakest-link subgame among co-sellers in a multi-party process: any one seller&rsquo;s defection causes all sellers to lose their bonds. Honest sellers therefore have direct economic incentive to monitor and pressure underperforming co-sellers. This layer handles disputes that survive Layer 1 by internalizing them as intra-cohort coordination problems.
                </PaperRun>
                <PaperRun title="Layer 3 — evidence.">
                    The on-chain record. Every commitment, every bond deposit, every resolution (or its absence) is recorded with block timestamps and cryptographic signatures. When Layers 1 and 2 fail &mdash; when a party acts irrationally, when a co-seller cohort cannot self-coordinate, when external circumstances (regulatory action, force majeure, participant death) prevent normal resolution &mdash; Layer 3 produces the artifact that off-chain dispute forums need to adjudicate.
                </PaperRun>
                <PaperRun title="What is and is not on chain.">
                    Settlement is on chain. Adjudication is off chain. The split is deliberate. Settlement is deterministic, automated, and public &mdash; all properties that on-chain execution provides natively. Adjudication is contextual, discretionary, and jurisdiction-specific &mdash; all properties that on-chain execution is poorly suited for. The split lets each layer do what it does best and avoids forcing one to imitate the other.
                </PaperRun>
            </PaperSection>

            <PaperSection title="3. The Three Layers in Operation">
                <p>
                    The previous section states the three-layer architecture abstractly. We walk it through operationally here, both because the layered architecture is the paper&rsquo;s central thesis and because practitioners frequently arrive with the question &ldquo;where does my dispute go?&rdquo; that the abstract treatment does not directly answer.
                </p>
                <PaperSubsection title="What disagreements look like at Layer 1">
                    <p>
                        Layer 1 disagreements are the ones the bonding rule prevents from happening at all. A buyer who has signed a commitment for a payment <Math>{"P"}</Math> and posted a <Math>{"2P"}</Math> bond faces a choice between cooperation (recover the bond minus the net flow <Math>{"P"}</Math>) and defection (forfeit the bond entirely). The cooperation/defection gap is large in absolute terms (<Math>{"P"}</Math> for the buyer; <Math>{"P + 2G"}</Math> for the seller, where <Math>{"G"}</Math> is the cumulative upstream value); the gap is tight in the technical sense (cooperation strictly dominates defection when the counterparty cooperates, and is equivalent when the counterparty defects). Most participants do not defect, because doing so is locally irrational under the bonded posture.
                    </p>
                    <p>
                        <em>What does and does not reach a forum at Layer 1.</em> The clearest case for Layer-1 prevention is the <em>cooperation/defection</em> dispute: a counterparty who would have walked away from a conventional contract because the cost of performance exceeded the cost of breach is, under the bonded posture, prevented from doing so because breach now costs the forfeited bond. This class of dispute is what the bonding rule forecloses, and it is plausibly the largest class in volume. Real commerce, however, is dominated by a different class: <em>information-asymmetry</em> disputes about whether the seller&rsquo;s performance conformed to the agreement (did the goods conform? was time of the essence? did the description match?). The bonded posture pressures the seller toward addressing dissatisfaction, because the seller&rsquo;s bond remains locked while the buyer withholds resolution; but it does not by itself resolve the underlying factual question of whether the buyer&rsquo;s dissatisfaction is justified. Information-asymmetry disputes survive Layer 1 by construction and flow to Layer 2 if multi-party, or to Layer 3 if the parties cannot converge. The buyer-dominance option (do not call <code>resolveProcess</code> until dissatisfaction is addressed) is the principal bonded-architecture mechanism for Layer-1 mediation of information-asymmetry disputes; whether it suffices is a function of the dispute&rsquo;s specifics.
                    </p>
                </PaperSubsection>
                <PaperSubsection title="What disagreements look like at Layer 2">
                    <p>
                        Layer 2 disagreements are multi-party coordination disputes that the weakest-link subgame internalizes among the seller cohort. Consider a multi-party process with a buyer, a primary seller, and three sub-sellers, where one sub-seller is performing poorly enough to threaten the parent process&rsquo;s resolution. Each of the three other sellers (the primary seller and two competent sub-sellers) faces a bond loss of <Math>{"P_i + 2G_i"}</Math> if the underperformer&rsquo;s performance causes the buyer to refuse resolution. They have direct economic incentive to apply pressure on the underperformer: phone calls, replacement-bond financing, escalation through the cohort&rsquo;s coordination channels.
                    </p>
                    <p>
                        <em>What this looks like operationally.</em> The pressure is endogenous to the bonded structure; no governance, no platform, no aggregator, no foundation organizes it. The result has a formal counterpart in the endogenous-coordination-pressure proposition; from a practical standpoint, the cohort&rsquo;s behavior is its operational form.
                    </p>
                    <p>
                        <em>Replacement-bond patterns under exploration.</em> Several runtime-tier composition patterns have been proposed for operationalizing Layer 2 mediation but should be understood as exploratory rather than as established mechanisms. <em>Seller substitution</em> (the buyer commits a replacement order with a new seller before resolution; the underperforming seller&rsquo;s bond forfeits at non-resolution) is the cleanest pattern, since each commitment remains bilateral and bonded. <em>Assembly-aggregated bonding</em> (the cohort posts a shared bond pool against cohort performance) shifts coordination from per-seller to per-cohort and raises a distinct set of incentive-compatibility questions the kernel&rsquo;s bonding analysis does not directly address. <em>Sponsor-of-bond patterns</em> (a financially-strong party posts bond on behalf of an under-capitalized cohort member) shade into unbonded-actor territory the no-escape-hatches discipline rules out unless the sponsor&rsquo;s own bond is posted alongside, and the sponsor relationship is itself a bonded commitment. Each pattern is a runtime-tier composition above the kernel; the present paper notes them as patterns under exploration and defers full incentive analysis.
                    </p>
                </PaperSubsection>
                <PaperSubsection title="What disagreements look like at Layer 3">
                    <p>
                        Layer 3 disagreements are the residual cases that survive Layers 1 and 2: a participant acts irrationally, the cohort cannot self-coordinate, external circumstances prevent normal resolution, or the underlying agreement is contested on substantive grounds (duress, mistake, frustration, illegality, public policy). The participants take the bonded record to an off-chain forum and the forum adjudicates on the evidence.
                    </p>
                    <p>
                        <em>The expected rate.</em> The Grameen joint-liability microfinance literature reports headline default-rate reductions on the order of magnitude of <Math>{"20\\% \\to 2\\%"}</Math> under joint-liability arrangements with peer monitoring (Yunus, 1999); Morduch (1999) contests the headline figures on accounting grounds (loan rescheduling, definition-of-default ambiguity, selection effects). We do not treat the <Math>{"2\\%"}</Math> figure as a peer-reviewed empirical estimate; we treat the <Math>{"20\\% \\to 2\\%"}</Math> comparison as a stylized indication of the order of magnitude joint-liability peer pressure has been claimed to achieve, recognizing that the headline figure is contested. The bonded primitive&rsquo;s peer-monitoring effect is structurally stronger than Grameen&rsquo;s on three margins (the externality magnitude scales with chain depth; the punishment technology is mechanical rather than social; information availability is on chain), and the on-chain default-and-resolution event log is not subject to the accounting ambiguities Morduch identifies in Grameen&rsquo;s self-reporting. Detailed development of the benchmark is a behavioral-game-theory question; we do not commit to a specific rate prediction.
                    </p>
                    <p>
                        <em>The forum the parties chose.</em> The forum is named by the parties&rsquo; off-chain agreement. Layer 3 does not impose a forum; it produces the evidentiary record on which the chosen forum operates. The composition-with-dispute-systems section (Section 11) below catalogues the forums most commonly composed with the protocol.
                    </p>
                </PaperSubsection>
                <PaperSubsection title="The walkthrough as practical guidance">
                    <p>
                        The three-layer architecture&rsquo;s practical guidance is therefore: expect Layer 1 to handle the vast majority of cases; expect Layer 2 to handle the multi-party residual; expect Layer 3 to handle the small residual that survives both. Plan infrastructure accordingly: most operational deployment work goes into the runtime tier&rsquo;s Layer-1 and Layer-2 surfaces (cart UX, attestation flows, replacement-bond composition, dispute-staging runtime affordances), with Layer 3 being structurally reachable but rarely invoked. A deployment that finds itself routinely escalating disputes to Layer 3 is typically signaling that the upstream layers are mis-configured (insufficient bonding, broken attestation flows, mis-specified clauses), not that the architecture is failing in the way conventional dispute-rich commerce systems would manifest.
                    </p>
                </PaperSubsection>
            </PaperSection>

            <PaperSection title="4. Evidentiary Properties of the On-Chain Record">
                <p>
                    Before enumerating the evidentiary properties of the on-chain record, we draw a distinction the remainder of this section relies on. The &ldquo;on-chain record&rdquo; is not a single artifact class; it is two artifact classes with substantially different evidentiary character.
                </p>
                <PaperRun title="Class A: settlement byproduct.">
                    Commitment payloads, bond deposits, and resolution calls. These are produced as a mechanical side effect of the bonding game: no party can collect the settlement payout without the corresponding on-chain events having been emitted. Their integrity as evidence is underwritten by the game itself &mdash; an actor cannot opt out of producing them without opting out of settlement.
                </PaperRun>
                <PaperRun title="Class B: discretionary attestation.">
                    Clause-typed lifecycle events, disclosure records, proximity witnesses, and other party-generated attestations emitted by the attestation coordinator. These are voluntary: a party chooses whether to attest, when to attest, and what content to place in the attestation. The clause validator ensures the content is well-formed; it does not and cannot ensure the content is accurate. A party who selectively attests (silence about underperformance, precise attestation of performance) can produce a Class B record that survives authentication but misrepresents reality.
                </PaperRun>
                <p>
                    The six properties enumerated below apply <em>unconditionally</em> to Class A and <em>conditionally</em> to Class B: each Class B attestation carries the integrity of the signature and timestamp (Class A characteristics), but the accuracy of its content depends on the attestor&rsquo;s incentive structure at the moment of attestation. A cryptoeconomics reader will recognize Class B as subject to the same self-reporting incentive problems that attach to every voluntary disclosure; adjudication should treat Class B under ordinary authentication-and-hearsay doctrine rather than extending Class A&rsquo;s byproduct assurance to it. An attestation-bond layer (stake posted per attestation, slashable on proven falsity) is a plausible Class B strengthening but lies outside the kernel and is not yet developed in the protocol.
                </p>
                <PaperRun title="Evidentiary completeness and constitutive primacy.">
                    A further distinction matters for certain downstream uses: the on-chain record is not merely <em>admissible</em> as evidence but <em>constitutive</em> of the accounting record of the process. A Figaro process is a self-closing ledger period in the precise accounting sense &mdash; the custodial balance of the contract is the balance-sheet position; commit and resolve events are journal and closing entries; the process closes when resolution discharges all custodial liabilities. For disputes whose subject matter is the accounting record of economic activity settled through the protocol, the on-chain record is not corroborating evidence for a party-held book; the chain is the book, and any party-held document is a summary or translation of it. The admissibility analysis of the present section applies to the record&rsquo;s evidentiary weight in proceedings; the constitutive analysis applies to the record&rsquo;s primacy within the economic activity it documents.
                </PaperRun>
                <p>The on-chain record produced by Figaro has six properties that together constitute its evidentiary value.</p>
                <PaperRun title="(1) Timestamped.">
                    Every state transition is associated with a block timestamp. The timestamp is set by block proposers under consensus rules; it is not subject to retroactive modification. For practical purposes, the timestamp on a finalized block is a qualified time stamp in the eIDAS sense.
                </PaperRun>
                <PaperRun title="(2) Cryptographically signed.">
                    Every commitment is signed by both parties using EIP-712 typed structured data (EIP-712, 2017). The signatures bind the commitment content (payment, parties, denomination, agreement hash, deadline) to the signers&rsquo; private keys. Recovery is deterministic; tampering with any field invalidates the signature.
                </PaperRun>
                <PaperRun title="(3) Content-addressed.">
                    Order identifiers are content hashes (<Math>{"\\text{orderHash} = \\mathrm{keccak256}(\\text{processId} \\,\\Vert\\, \\text{structHash})"}</Math>). The same commitment content always produces the same identifier; different content always produces different identifiers (collision-resistant under the assumed hash function). This makes the record unforgeable in a specific sense: no second commitment can claim the same identifier.
                </PaperRun>
                <PaperRun title="(4) Immutable.">
                    On a finalized block, the record cannot be modified or deleted. A party seeking to repudiate a commitment cannot purge the chain of the relevant log entries. This is a stronger property than what electronic records normally enjoy.
                </PaperRun>
                <PaperRun title="(5) Publicly verifiable.">
                    Anyone can read the chain and replay the verification logic. The evidence is not held by any single party; it is held by the network. Disputing parties therefore cannot disagree about what the record says &mdash; they can disagree only about what the record <em>means</em>, which is precisely the question adjudication is suited to.
                </PaperRun>
                <PaperRun title="(6) Contains commitment intent.">
                    The signed payload includes a content hash <Math>{"h"}</Math> of the off-chain agreement. The off-chain agreement itself can be anything the parties choose &mdash; a structured contract, a free-text PDF, a clause-typed JSON document. The on-chain record does not interpret the agreement; it commits both parties to a specific document via the hash. A dispute over performance is then a dispute over the referenced document, with the on-chain hash establishing <em>which</em> document is at issue.
                </PaperRun>
                <p>
                    These six properties, combined, produce an artifact that is substantially <em>stronger</em> than the electronic records most courts already accept. Courts admit emails, electronic signatures, and database extracts as evidence subject to authentication challenges; the on-chain record satisfies many authentication requirements at the cryptographic level rather than at the custodial level.
                </p>
            </PaperSection>

            <PaperSection title="5. Class A and Class B Records: A Taxonomy">
                <p>
                    The on-chain record&rsquo;s evidentiary use turns on a distinction that we have used inline in earlier sections and that deserves explicit treatment. We taxonomize the protocol&rsquo;s records into two classes distinguished by how they are produced and what they prove.
                </p>
                <PaperRun title="Class A: kernel byproducts.">
                    Class A records are emitted by the kernel itself as a byproduct of <code>commit</code> and <code>resolveProcess</code>. They include the commitment digest (the EIP-712 hash of the typed agreement struct), the bond deposits, the cumulative-value accumulator state, the order status transitions, and the resolution event with its complete payout vector. Class A records share four properties. <em>Discretion-free:</em> the kernel emits them without any participant choice. <em>Cryptographically authenticated:</em> each is signed by the parties who participated in the operation that produced it (EIP-712 signatures on commits; the buyer&rsquo;s transaction signature on resolutions), verifiable without consulting any oracle. <em>Append-only:</em> a Class A record at block <Math>{"b"}</Math> is the same record at block <Math>{"b + N"}</Math> for any <Math>{"N"}</Math>. <em>Clause-typed at the kernel level:</em> the structure is determined by the kernel&rsquo;s typed events, known in advance and machine-readable.
                </PaperRun>
                <p>
                    The four properties together make Class A records <em>strong evidence</em>: an off-chain forum can rely on the record&rsquo;s existence and content with high confidence and minimal expert testimony. The MLETR functional-equivalence analysis (Section 6) applies directly to Class A records, with the &ldquo;reliable method&rdquo; test discharged by the kernel&rsquo;s bytecode and the consensus rules of the underlying chain.
                </p>
                <PaperRun title="Class B: discretionary attestations.">
                    Class B records are produced by participants through the <code>AttestationCoordinator</code> contract under clause-validation discipline. They include delivery confirmations, GHG disclosures, handoff attestations, custody-of-seal events, lifecycle stage transitions, and the other clause-typed records that operational deployments produce. They are <em>discretionary</em> (a participant chooses whether, when, and what to attest within the clause&rsquo;s content space); <em>cryptographically authenticated plus validator-gated</em> (the participant&rsquo;s EIP-712 signature plus the clause-validator&rsquo;s well-formedness gate, though the content itself is participant-asserted and may be contestable on substantive grounds); <em>append-only</em> (incorrect attestations cannot be retracted, only contextualized by later ones); and <em>clause-typed at the protocol level</em> (structure determined by the registered clause&rsquo;s specification, ABI-encoded for on-chain validation, rendered for off-chain inspection by the runtime tier).
                </PaperRun>
                <p>
                    The four properties together make Class B records <em>useful but contestable evidence</em>: an off-chain forum can rely on the record&rsquo;s existence (cryptographic), its participant (cryptographic), and its formal correctness under the clause (validator-gated), but the substantive accuracy of what the record asserts (the delivery did happen as the seller stated; the GHG disclosure does reflect reality) raises questions the audit-assertion framework of AICPA (2020) treats across the assertion categories of existence (did the recorded event happen?) and accuracy (was it recorded at the right amount, timing, and characterization?). For Class B records both assertions are at stake; we use &ldquo;existence-and-accuracy&rdquo; as shorthand for the wider AU-C 315 assertion taxonomy (existence, completeness, accuracy/valuation, cutoff, classification, occurrence, rights/obligations).
                </p>
                <PaperRun title="The MLETR fit by class.">
                    The MLETR analysis applies most directly to Class A records, which carry the kernel&rsquo;s structural properties (singularity through the cumulative-value accumulator; control through buyer-dominance; integrity through the chain&rsquo;s consensus) and discharge MLETR Articles 10&ndash;11&rsquo;s control and singularity tests in their own right. Class B records do not generally meet the MLETR test on their own, because they are not transferable records in the Article-10 sense: a delivery confirmation, a GHG disclosure, or a custody-of-seal event is not an instrument of title that participants treat as functionally equivalent to a negotiable paper. They are evidentiary artifacts <em>about</em> the underlying transferable record (the commitment), not separate transferable records. Their evidentiary weight is corroborative, conditional on the clause-validation surface&rsquo;s correctness (a Class B record under a clauseId without a registered validator does not get filed in the first place; the validator-gate at the <code>AttestationCoordinator</code> reverts). The clause-design discipline is therefore part of the corroborative weight Class B records carry, not part of an MLETR transferable-record analysis applied to them directly.
                </PaperRun>
                <PaperRun title="Why the taxonomy matters for forum strategy.">
                    A litigant taking the bonded record to a forum should expect the forum&rsquo;s treatment of Class A and Class B records to differ in detail even if both are admissible. For Class A, the analysis reduces to authentication (signatures verify; chain matches; expert if needed) then content interpretation (what does the recorded state mean for the parties&rsquo; claims) &mdash; authentication is nearly mechanical, interpretation is the work. For Class B, the analysis expands to include clause-validity (was the record filed under a registered clauseId; did it pass the validator) and <em>substantive truth-of-content</em> (does the attestation reflect the off-chain reality it asserts), engaging the AU-C 315 existence and accuracy assertions at per-attestation granularity. A deployment that relies on Class B records for load-bearing factual claims is exposed to a different litigation profile than one that relies on Class A records (e.g., the resolution event itself, undeniable on chain). Most deployments use both; understanding the litigation profile of each is part of the runtime tier&rsquo;s design discipline.
                </PaperRun>
            </PaperSection>

            <PaperSection title="6. Legal Fit: Existing Electronic-Evidence Frameworks">
                <p>
                    We sketch how the six properties above interact with four major electronic-evidence frameworks. The treatment is illustrative; a full doctrinal analysis is jurisdiction-by-jurisdiction.
                </p>
                <PaperRun title="eIDAS (EU Regulation 910/2014).">
                    eIDAS distinguishes electronic signatures, advanced electronic signatures (AdES), and qualified electronic signatures (QES). EIP-712 signatures meet the AdES technical requirements (uniquely linked to the signatory; capable of identifying the signatory; created using means under the signatory&rsquo;s sole control; linked to the signed data such that any subsequent change is detectable). They do not by themselves meet the QES requirements (which include a qualified certificate from a trust service provider). However, AdES status is sufficient for most contractual purposes, and eIDAS explicitly provides that the legal effect of an electronic signature shall not be denied solely because it is in electronic form. eIDAS also defines qualified electronic time stamps; block timestamps on chains with public consensus rules satisfy the technical requirements but typically not the trust-service-provider designation. The practical effect: the on-chain record is admissible electronic evidence under eIDAS, with weight determined by the court&rsquo;s contextual assessment.
                </PaperRun>
                <PaperRun title="UCC §1-201 and the Federal Rules of Evidence (US).">
                    The Uniform Commercial Code defines &ldquo;record&rdquo; as information inscribed on a tangible medium or stored in an electronic medium and retrievable in perceivable form; on-chain log entries satisfy this without ambiguity. UCC §1-201 also defines &ldquo;signature&rdquo; inclusively (any symbol executed or adopted with present intention to adopt or accept a writing); EIP-712 signatures qualify. UETA and the federal E-SIGN Act extend the principle to contracts more broadly. For evidentiary admission, the operative provisions are FRE 901(b)(9), 902(13), and 902(14), with the <em>Daubert</em> standard for any expert testimony required to authenticate the cryptographic process. FRE 901(b)(9) permits authentication by showing that a process or system produces an accurate result; FRE 902(13) (added 2017) permits self-authentication of records generated by an electronic process or system; FRE 902(14) permits self-authentication of data copied from electronic devices through a process producing a digital identifier &mdash; here the cryptographic hash of the record itself (FRE legislative history, 2017). On-chain commitments are records and signatures under US commercial law, admissible through the established electronic-evidence pathway and authenticatable through <em>Daubert</em>-qualified expert testimony where authentication is challenged.
                </PaperRun>
                <PaperRun title="Singapore Electronic Transactions Act (Cap. 88) and MLETR.">
                    Singapore&rsquo;s ETA closely follows the UNCITRAL Model Law and provides functional equivalents for &ldquo;writing,&rdquo; &ldquo;signature,&rdquo; and &ldquo;original&rdquo; in electronic form. The ETA was amended in 2021 to recognize electronic transferable records, implementing MLETR (2017) and extending scope to instruments of title. On-chain records satisfy the writing and signature requirements directly; the transferable-record provisions warrant closer treatment because the doctrinal question they raise is the one most directly relevant to the multi-party structure of Figaro.
                </PaperRun>
                <p>
                    MLETR Article 10 requires functional equivalence with a paper-based transferable document on three dimensions: (i) the information is accessible for subsequent reference; (ii) a reliable method (a) identifies the record as the electronic transferable record, (b) renders it capable of being subject to control from creation until it ceases to have effect, and (c) retains its integrity. Article 11 requires that &ldquo;control&rdquo; be functionally equivalent to possession of a paper instrument: a single identifiable controller, with exclusive capacity to transfer that control, the transfer recorded reliably. The control and singularity tests are load-bearing.
                </p>
                <p>
                    Figaro&rsquo;s on-chain commitment satisfies Articles 10&ndash;11 in the relevant senses. The orderHash uniquely identifies the transferable record (Art. 10(2)(a)). The bond mechanics give the bonded party exclusive capacity to act on the record until resolution (Art. 11(1) singularity); the cumulative-value accumulator ensures the record cannot be duplicated or forked without the chain rejecting the duplicate (Art. 10(2)(b) non-duplication). Integrity is enforced cryptographically through consensus and EIP-712 verification (Art. 10(2)(c)). Where the right to receive performance moves along a multi-party process, each sub-order is itself a transferable record under the same analysis, and the on-chain settlement records the transfer with the reliable method MLETR contemplates. Goode and Gullifer (2017) gives the standard doctrinal framework against which this analysis is run; the on-chain settlement satisfies the framework&rsquo;s tests without controversy. For Class A artifacts the MLETR fit is direct; for Class B artifacts additional functional-equivalence analysis applies, which we do not extend here.
                </p>
                <PaperRun title="UNCITRAL Model Law on Electronic Commerce.">
                    Adopted in 1996 and supplemented by the 2017 Model Law on Electronic Transferable Records, the UNCITRAL framework articulates the functional-equivalence principle underlying most modern electronic-evidence regimes. Its three core requirements &mdash; accessibility for subsequent reference, integrity of the information, and identifiability of the originator &mdash; are all satisfied by on-chain commitments. Jurisdictions that have adopted UNCITRAL-derived electronic-transactions law (over 80 as of 2024) provide an established framework for treating on-chain commitments as admissible electronic evidence.
                </PaperRun>
                <PaperRun title="The summary picture.">
                    The on-chain record is admissible electronic evidence in every jurisdiction whose electronic-evidence law derives from the UNCITRAL framework or implements equivalent functional principles. What varies is the weight courts assign (a question of judicial practice rather than admissibility) and the further procedural requirements for authenticating the chain itself (typically satisfied by expert testimony or judicial notice of well-known chains). No jurisdiction we are aware of categorically excludes on-chain records from evidentiary consideration.
                </PaperRun>
            </PaperSection>

            <PaperSection title="7. Substantive Defenses and Post-Settlement Restitution">
                <p>
                    A reader sympathetic to the argument so far will raise the sharpest question this paper has to answer. Suppose the on-chain settlement is unimpeachable as evidence; suppose every framework above admits it. What happens when an external court, applying the substantive contract law of its jurisdiction, finds that the underlying agreement was procured under duress, formed under fundamental mistake, frustrated by impossibility, voided by illegality, or unconscionable in its terms? The on-chain settlement has, by hypothesis, already executed. The question is what the court can do with that fact and whether the substitution between settlement (on-chain) and adjudication (off-chain) the present paper has defended is consistent with the substantive-defense jurisprudence the dominant tradition has developed over centuries.
                </p>
                <PaperRun title="Doctrinal inventory.">
                    The defenses that void or rescind a contract <em>ab initio</em>, or that excuse subsequent performance, are doctrinally settled in the major commercial jurisdictions. Common-law systems recognize <em>duress</em> (consent obtained by improper threat); <em>undue influence</em> (abuse of a relationship of trust); <em>misrepresentation</em> (false statements about material facts); <em>fundamental mistake</em> (shared mistake about an essential fact); <em>unconscionability</em> (terms so one-sided that enforcement shocks the conscience); <em>frustration of purpose</em> and <em>impossibility / impracticability</em> (subsequent events render performance fundamentally different or impossible); <em>illegality</em>; and <em>public policy</em>. Civil-law systems recognize closely parallel doctrines (<em>vices du consentement</em>, <em>erreur</em>, <em>circonstances exceptionnelles</em>). The doctrines are substantive: they apply to <em>the agreement</em> the bonded commitment records, not to the bonded commitment as a technological artifact.
                </PaperRun>
                <PaperRun title="Substantive-defenses analysis.">
                    The bonded primitive is silent on every doctrine in the inventory. The kernel does not know whether consent was procured under duress, whether parties were mistaken about a material fact, whether the underlying transaction was illegal, or whether performance has been frustrated. It records what was signed; it makes no representation about the conditions under which signing occurred or the legality of what was signed for. This is by design &mdash; the kernel cannot make substantive-defense determinations without doing the kind of discretionary work the no-escape-hatches design principle rules out &mdash; and it is by design also a <em>feature</em>, because it leaves the substantive-defense apparatus exactly where the dominant tradition has placed it: in courts applying their own constitutional and doctrinal apparatus to the agreement recorded in the bonded commitment. The leading case-law authority is <em>Quoine Pte Ltd v B2C2 Ltd</em> (2019; 2020), in which the Singapore International Commercial Court and, on appeal, the Court of Appeal worked out how the doctrine of unilateral mistake applies to deterministic algorithmic execution &mdash; locating the relevant knowledge at the time the algorithm was programmed, not at execution. On the facts the mistake defence failed and the trades stood, but the case establishes that smart-contract executions are not beyond the reach of conventional contract doctrine.
                </PaperRun>
                <p>
                    The restitutionary mechanics are where the question becomes operationally sharp. <em>Case 1: court orders specific re-transfer off-chain.</em> Where one party should not have received the payout, the standard remedy is a restitutionary order to transfer the received value back off-chain. This operates on the parties&rsquo; real-world capacity to comply, not on the kernel state; the kernel records show the original settlement unchanged, and the off-chain transfer is recorded separately. This is the most common form and the one for which the existing legal apparatus is best-equipped. <em>Case 2: court orders a replacement-bonded counter-process.</em> Where ongoing performance and a counter-flow are appropriate, the parties (or the court via an order on the parties) constitute a fresh Figaro process flowing value in the corrective direction &mdash; using the bonded primitive as the implementation of the remedy rather than an obstacle to it. <em>Case 3: court orders an arrangement the kernel cannot support.</em> The remedy then operates on the parties&rsquo; off-chain assets and obligations through conventional mechanisms (asset seizure, contempt sanctions, criminal liability for non-compliance). The kernel does not obstruct the remedy; it does not implement it either. The substrate is sub-political, not anti-political.
                </p>
                <PaperRun title="Implication for the escape-hatch theorem.">
                    The escape-hatch theorem and its carve-out deserve a precise characterization. The theorem rules out unilateral exit paths internal to the mechanism &mdash; timeouts, arbitrators, governance votes &mdash; because those would weaken the Nash equilibrium. The carve-out admits external legal forums applying duress, frustration, and similar substantive doctrines. The carve-out is sound, but for a more precise reason than &ldquo;external forums are themselves bonded&rdquo;: the substantive-defense jurisprudence operates on the agreement <em>as recorded</em> after the kernel has settled, not on the kernel itself, and produces remedies that reach the parties through their conventional legal exposure rather than through the bonded escrow. The kernel&rsquo;s equilibrium is preserved because no remedy can reach into the discharged escrow; the substantive defenses operate downstream of settlement. Both the on-chain enforcement and the off-chain doctrinal review apply; they are not in competition because they reach different aspects of the same arrangement. The bonded primitive does not displace contract law&rsquo;s substantive doctrines; it produces a settlement under which those doctrines continue to apply in the conventional way.
                </PaperRun>
            </PaperSection>

            <PaperSection title="8. A Worked Example: New York Forum, Cross-Border Process">
                <p>
                    Consider a multi-party process with a buyer in New York, a primary seller in Singapore, and a sub-seller in Argentina, settled in <code>USDC</code> on Ethereum L1. The off-chain agreement specifies New York Supreme Court as the forum and New York law as the governing law. A dispute arises: the primary seller claims the buyer never resolved the process despite delivery; the buyer claims the goods did not conform to the agreed specification.
                </p>
                <p>
                    The on-chain record establishes: the commitment hash matching the off-chain agreement (UCC §1-201 record; FRE 902(13) self-authenticating); the buyer&rsquo;s and seller&rsquo;s signatures on the EIP-712 typed commitment (UCC §1-201 signature; AdES under eIDAS; signature under E-SIGN/UETA); the cumulative-value accumulator&rsquo;s monotonic state through every commit and resolve operation; and the absence (or presence) of a <code>resolveProcess</code> transaction. The seller&rsquo;s claim &mdash; that the buyer never resolved &mdash; is determinable from the chain state directly. The buyer&rsquo;s claim &mdash; that the goods did not conform &mdash; is not determinable from the chain state and requires off-chain evidence: delivery records, photographs, laboratory analyses, and the clause-typed attestations that may already be on chain.
                </p>
                <p>
                    The New York court, applying New York contract law (UCC Article 2 for the goods, NY CPLR for procedure, NY GBL §75-a for electronic signatures), proceeds: admissibility is established under the FRE pathway above; the substantive question &mdash; did the goods conform? &mdash; is decided on the off-chain evidence under ordinary contract doctrine; the remedy, if the court finds for the buyer, is restitutionary, operating on the seller&rsquo;s off-chain assets through standard enforcement (US&ndash;Singapore reciprocity, New York Convention, asset attachment). The bonded settlement does not interfere with any of this. It provides the evidentiary record and the bilateral-enforcement backstop that prevents the seller from walking away with the funds before the dispute is heard &mdash; the usual gap that cross-border commerce has had to manage through letters of credit, escrow agents, and intermediary banks. The primitive supplies that function more cleanly, leaving the substantive doctrine of the New York court untouched, and it is no less well-positioned in cross-border settings than in domestic ones because the evidentiary properties are the same in either case.
                </p>
            </PaperSection>

            <PaperSection title="9. Jurisdictional Implications">
                <p>The decoupling of settlement from adjudication has substantive jurisdictional consequences.</p>
                <PaperRun title="Forum is contractual.">
                    The on-chain commitment includes an off-chain agreement hash <Math>{"h"}</Math>. That off-chain agreement can &mdash; and typically should &mdash; include a forum-selection clause, a choice-of-law clause, and an arbitration clause if the parties prefer arbitration to court. The on-chain record proves what was agreed; the off-chain agreement specifies where and under what law the agreement is adjudicated. Parties who omit a forum clause default to whatever private-international-law analysis the seised forum applies; this is a known regime, not a novel problem.
                </PaperRun>
                <PaperRun title="Forum-shopping is bounded.">
                    A party seeking to forum-shop is bounded by (a) the forum-selection clause in the off-chain agreement, (b) the seising forum&rsquo;s own jurisdictional rules, and (c) the recognition-and-enforcement treaties between the seising forum and any forum where the counterparty&rsquo;s assets reside. None of these constraints is weakened by the on-chain settlement; they all operate on the off-chain agreement and the parties&rsquo; real-world circumstances.
                </PaperRun>
                <PaperRun title="Evidence is jurisdiction-displaced.">
                    The integrity of the on-chain evidence does not depend on the seising forum&rsquo;s recognition of any specific cryptographic standard. The signatures verify, or they do not; the chain hashes match, or they do not. A forum that doubts the cryptographic analysis can engage an expert; a forum that does not is in the position of any forum facing forensic evidence.
                </PaperRun>
                <PaperRun title="Cross-border processes.">
                    A multi-party process can involve parties in multiple jurisdictions simultaneously. The on-chain settlement is jurisdiction-blind: the bond mechanics work identically regardless of where the parties reside. Off-chain disputes arising from such processes are handled by the same private-international-law machinery that already handles cross-border disputes in conventional commerce &mdash; typically with the on-chain record providing substantially more evidentiary clarity than the parties would have produced under conventional bookkeeping.
                </PaperRun>
            </PaperSection>

            <PaperSection title="10. Why Not On-Chain Adjudication">
                <p>
                    We have argued the positive case for off-chain adjudication. We now argue the negative case against on-chain adjudication. Several patterns occupy this space; we treat each briefly.
                </p>
                <PaperRun title="Schelling-point juror selection (Kleros).">
                    A token-weighted juror panel votes on the disputed question; the plurality wins; jurors who voted with the plurality are rewarded, those against are slashed. The mechanism is elegant in abstraction but has three problems for serious adjudication. First, the panel is not selected for jurisdictional fit &mdash; a juror in jurisdiction <Math>{"A"}</Math> may know nothing of jurisdiction <Math>{"B"}</Math>&rsquo;s law that the parties agreed should govern. Second, the juror&rsquo;s incentive is to vote with the perceived plurality, not the legally correct outcome &mdash; a Schelling point on plurality is structurally distinct from a Schelling point on truth. Third, the slashing mechanism imports a new dispute (was the slashing fair?) that has no terminal forum on chain.
                </PaperRun>
                <PaperRun title="DAO-governed arbitration (Aragon Court).">
                    Aragon Court is structurally similar to Kleros, with juror-selection integrated with DAO governance. This inherits Kleros&rsquo;s problems plus the additional one that DAO voting power is plutocratic in proportion to token holdings; the wealthy juror has structurally more votes than the poor juror. Whether that is desirable is a normative question; that it differs from the &ldquo;one juror, one vote&rdquo; premise of jury trials is a doctrinal question that has not been settled.
                </PaperRun>
                <PaperRun title="Optimistic challenge windows.">
                    Optimistic mechanisms (Optimism, 2021; UMA, 2020) avoid the juror problem by allowing assertions to stand unless challenged within a fixed window. This works for settlement-layer state machines but not for adjudication, because adjudication is precisely the activity of assessing an assertion that has been challenged. An optimistic &ldquo;adjudication&rdquo; is just an assertion with a deadline &mdash; it has no mechanism for resolving the underlying question, only for resolving who blinked first.
                </PaperRun>
                <PaperRun title="The structural objection.">
                    All on-chain adjudication mechanisms share the same flaw. The escape-hatch theorem establishes that any unilateral exit from the bonded state requires either a third-party decision (introducing an unbonded actor whose incentives are not constrained by the bond structure) or a payoff modification that weakens the Nash equilibrium. On-chain adjudication is the third-party-decision case: the juror, the DAO voter, the challenger is the unbonded actor whose decision determines the outcome. Whatever the designer does to constrain that actor (token slashing, Schelling incentives, reputation), the actor is still unbonded and the kernel&rsquo;s self-enforcing property is broken.
                </PaperRun>
                <PaperRun title="The off-chain alternative.">
                    Off-chain adjudication by an existing legal forum has the opposite structure. The forum&rsquo;s incentives are constrained by its institutional context &mdash; judges face appellate review, arbitrators face institutional reputation, both face professional sanction. The forum is not unbonded in the kernel sense; it operates inside a different bond structure (its institutional authority). The off-chain evidence record is therefore consumed by an actor whose incentives are already constrained by a regime refined for centuries. The protocol does not re-implement that regime; it provides input to it.
                </PaperRun>
                <PaperRun title="Composition with Kleros as forum, not as kernel adjudicator.">
                    The objection above is to on-chain adjudication <em>at the kernel layer</em>. It is not an objection to Kleros, or any other adjudication mechanism, when the parties&rsquo; agreement designates it as the forum. Figaro&rsquo;s kernel is forum-agnostic: it does not adjudicate; it produces an evidence record. If two parties sign an off-chain agreement whose arbitration clause names Kleros as the forum, the evidence record produced by their commitments is exported to Kleros and the dispute is adjudicated there &mdash; in the same sense that the Singapore International Arbitration Centre or the New York Supreme Court can be the forum the parties choose. The structural critique is not an endorsement of some forums over others; any forum the parties name is theirs to choose, and Figaro composes with it by exporting evidence to it.
                </PaperRun>
                <PaperRun title="The New York Convention question.">
                    The Kleros recognition question deserves a committed answer. Our reading of Article I of the New York Convention is that a Kleros decision is capable of falling within the Convention&rsquo;s definition of an arbitral award where the parties&rsquo; arbitration agreement so designates, subject to Article V&rsquo;s grounds for refusing recognition (most relevantly the public-policy ground of Article V(2)(b) and the proper-law analysis under Article V(1)(a)). The recognition is not automatic and is jurisdictionally sensitive. Our view is that Kleros decisions <em>can</em> be arbitral awards under the Convention, conditional on competent drafting and on the seising court reading the Convention&rsquo;s &ldquo;arbitral tribunal&rdquo; definition broadly enough to include the juror-selection mechanism. The contrary view (Ortolani, 2019) is defensible and turns on the same Article I and Article V considerations. We do not treat the question as settled, but as takable, and we have written the architecture to be neutral on the choice of forum, with the evidence record exported to either. The recognition-and-enforcement question is, in our reading, the binding legal-doctrinal question; the layered architecture mitigates it, because the on-chain record is admissible electronic evidence regardless of how the consuming forum is constituted, and forum-clause discipline lets the parties name a forum whose decisions they have a clean recognition theory for.
                </PaperRun>
            </PaperSection>

            <PaperSection title="11. Composition with Dispute Systems">
                <p>
                    A constructive treatment is owed to the practitioner who arrives with the question &ldquo;which forum should I name in my agreement, and how do I compose with it.&rdquo; We catalogue the four classes of forum the protocol composes with in practice.
                </p>
                <PaperSubsection title="State courts">
                    <p>
                        Conventional state courts are the highest-recognition forum available and the appropriate destination for disputes whose substantive resolution requires the full apparatus of contract law (duress, mistake, frustration, illegality, public policy). The off-chain agreement names a specific state court (e.g., New York Supreme Court, Singapore International Commercial Court, English High Court) and a governing law; the clause is a standard contractual provision. The bonded record is admitted under the relevant evidentiary framework (FRE 901(b)(9) / 902(13)&ndash;(14) for US courts, eIDAS AdES recognition for EU courts, Singapore ETA / MLETR for Singapore courts). A judgment is enforceable through standard private-international-law machinery (recognition treaties, the Hague Judgments Convention where in force, domestic enforcement powers); enforcement against on-chain assets requires a court with jurisdiction over the asset-holding party rather than over the bonded primitive itself, which is not a party. State courts are appropriate where the parties need the recognition properties of a state-court judgment, or where the matter touches public policy, sanctions, criminal conduct, or regulatory enforcement.
                    </p>
                </PaperSubsection>
                <PaperSubsection title="International commercial arbitration centers">
                    <p>
                        Centers such as SIAC, the ICC, the LCIA, and the HKIAC are the appropriate destination for cross-border disputes whose parties prefer arbitration to court litigation. The off-chain agreement names the center, the seat, the language, and the procedural rules. Arbitration centers admit electronic evidence broadly with flexible authentication standards; the bonded record satisfies them straightforwardly. The New York Convention (1958, 172 state parties as of 2024) is the canonical recognition framework: an award under SIAC / ICC / LCIA rules is enforceable in any Convention state subject to the Article V grounds for refusal, and the bonded primitive composes with this chain natively because the underlying agreement is a recognized arbitration agreement under Article II. Appropriate where parties want institutional arbitration&rsquo;s combination of expertise, procedural flexibility, and international enforceability.
                    </p>
                </PaperSubsection>
                <PaperSubsection title="Online dispute resolution (ODR) platforms">
                    <p>
                        ODR platforms (eBay&rsquo;s Resolution Center as the volume archetype, Modria, smartsettle, and the broader literature, Rabinovich-Einy and Katsh, 2017) are the appropriate destination for high-volume, low-value disputes where the cost of conventional adjudication exceeds the disputed amount. The off-chain agreement names the platform and accepts its terms-of-service; binding effect is contractual rather than treaty-based. ODR platforms typically accept the bonded record without specialized authentication and use it as the dispositive content for routine disputes. ODR decisions are typically enforced by the platform itself rather than through state machinery. A practitioner pattern of pairing an ODR clause with an arbitration clause that treats unappealed ODR decisions as final is structurally available but doctrinally delicate: many ODR procedures (no live hearing, no discovery, opaque review) fail Article V(1)(b) due-process requirements on standard readings, so the hybrid is a careful drafting matter, not an off-the-shelf composition. Appropriate for routine commercial disputes at operational scale where dispute volume rules out court/arbitration economics.
                    </p>
                </PaperSubsection>
                <PaperSubsection title="Schelling-point juror systems (Kleros and analogues)">
                    <p>
                        Kleros and analogues (2019) occupy a distinctive position: not state courts, not traditional arbitration centers, not conventional ODR. They are mechanism-based forums where Schelling-point juror selection produces decisions through coordination on the focal answer. The protocol composes with them as the parties&rsquo; chosen forum, but their recognition and enforcement properties are the most contested of the four classes. The committed view above holds: a Kleros decision is <em>capable</em> of falling within the New York Convention&rsquo;s definition of an arbitral award where the agreement so designates, subject to Article V. Ortolani (2019) raises three objections the committed view must engage. First, Article I requires an identifiable &ldquo;tribunal,&rdquo; and Kleros jurors are anonymized, rotating, and token-incentivized; the committed view contests this on the ground that the Convention&rsquo;s tribunal definition is functional rather than institutional. Second, Article V(1)(d) requires that the composition of the arbitral authority accord with the parties&rsquo; agreement; the committed view reads the parties&rsquo; acceptance of the Kleros court&rsquo;s procedural rules as constituting that agreement. Third, Article V(2)(b) permits refusal on public-policy grounds, and many civil-law jurisdictions treat unreasoned awards as presumptively contrary to public policy &mdash; Kleros decisions are vote tallies, not reasoned awards. <em>The committed view concedes this objection in civil-law jurisdictions whose public policy requires reasoned awards;</em> parties enforcing there should pair the Kleros clause with a written-opinion supplement or choose a different forum. Appropriate where parties prefer the mechanism&rsquo;s combination of neutrality, speed, and token-economic incentive over conventional recognition properties; unsuitable for deployments whose intended enforcement jurisdictions require reasoned awards.
                    </p>
                </PaperSubsection>
                <PaperSubsection title="Composition discipline across the four">
                    <p>
                        Two structural points apply across all four. <em>Forum-clause discipline is the parties&rsquo; choice and responsibility.</em> The bonded primitive does not recommend a forum; the forum is named by the off-chain agreement, and the parties bear the consequences of their choice (recognition properties, enforcement chain, procedural rules, operational cost). The architecture&rsquo;s role is to produce evidence the chosen forum can use, not to constrain the choice. <em>Recognition theory is upstream of forum choice.</em> The parties should name a forum whose decisions they have a clean recognition theory for in the jurisdiction of intended enforcement &mdash; a US-based seller and an EU-based buyer who name SIAC arbitration with Singapore seat have a clean theory through the New York Convention; the same parties naming an ODR platform without arbitration backing do not. <em>The bonded primitive shifts the balance toward weaker forums.</em> Because the bonded posture itself enforces most disputes at Layers 1 and 2, the residual reaching Layer 3 is small (Section 3); a smaller residual can justify a weaker forum than conventional commerce would choose. This is not the architecture replacing stronger forums; it changes the cost-benefit calculation of which forum is appropriate for what residual.
                    </p>
                </PaperSubsection>
            </PaperSection>

            <PaperSection title="12. Conclusion">
                <p>
                    We have argued for a layered approach to smart-contract dispute resolution: settlement on chain, adjudication off chain, with a deliberately designed evidentiary record that bridges the two. The architecture inherits the strengths of each layer (chain determinism for settlement, legal-system contextual judgment for adjudication) without forcing either to imitate the other. It also resolves the structural objection to on-chain adjudication: the unbonded juror does not need to exist because the legally constituted forum already does.
                </p>
                <p>
                    The contribution is modest but, we believe, important. The debate over smart-contract dispute resolution has been dominated by the assumption that on-chain settlement implies on-chain adjudication. The decoupling we propose is a different design posture, and it permits a substantially cleaner alignment with existing electronic-evidence law.
                </p>
            </PaperSection>
        </PaperLayout>
    );
}
