import type { Metadata } from "next";
import { withOg } from "@/lib/shared/pageMetadata";
import {
    PaperLayout,
    PaperSection,
    PaperRun,
} from "@/components/papers/PaperLayout";
import { Math } from "@/components/papers/Math";

export const metadata: Metadata = withOg({
    title: "Behavioral Game Theory of the Two-Mechanism Bonded Commitment — Figaro Protocol",
    description:
        "How the bonded primitive's equilibrium fares once participants are real: each node a comparison of two certain amounts straddling the prospect-theoretic reference point, so loss aversion weights the defecting branch instead of cancelling; why the Van Huyck coordination failure loses the finality it runs on; atomic resolution as activated peer pressure; and incentive legibility as one comparison per node in a public order.",
});

export default function BehavioralGameTheoryPaper() {
    return (
        <PaperLayout slug="behavioral-game-theory"
            title="Behavioral Game Theory of the Two-Mechanism Bonded Commitment"
            subtitle="Loss Aversion, Coordination, Peer Pressure, and Incentive Legibility"
            author="Figaro"
            date="May 2026"
            watermark="Figaro Protocol · Preprint"
            abstract={
                <>
                    <p>
                        The bonded settlement primitive carries an equilibrium argument of a particular shape: at each decision node a party compares two certain amounts, and the nodes are ordered &mdash; after performance the buyer strictly prefers to resolve, a comparison that needs no assumption whatever about the seller, and only once that is settled is performance each seller&rsquo;s strict best response. This paper asks how an argument of that shape fares when the participants are the ones the experimental literature has spent forty years describing: loss-averse, boundedly reasoning, pessimistic about strangers, and moved by motives no payoff records.
                    </p>
                    <p>
                        Four claims follow. First, the payoffs at each node straddle the prospect-theoretic reference point rather than lying on one side of it, because a defector is credited with what it retains: the buyer compares a break-even against a loss, the seller a gain against a loss. Loss aversion therefore weights the defecting branch alone and does not cancel out of either comparison &mdash; and where a defector books its retained value and its locked bond separately, as the natural framing invites, the retention is credited at gain-domain weight against a bond charged at loss-domain weight, so retention pays less behaviorally than it pays arithmetically. Second, the Van Huyck&ndash;Battalio&ndash;Beil coordination-failure result addresses a structural condition this setting has, and we concede it: where a co-seller has held out, holding out is strictly better for a seller than performing. What the setting lacks is the finality that experimental convergence runs on &mdash; no profile is ever banked, so the belief-updating engine driving the laboratory result has no realized history to work from; each seller&rsquo;s own exposure is a figure read off the record rather than a belief about strangers; and every party in a standoff strictly prefers the cooperative close to the position it is holding. Third, the externality structure of atomic resolution produces peer pressure that is economically real and behaviorally activated, though the record makes the stake public and leaves the fault local. Fourth, the architecture&rsquo;s <em>incentive legibility</em> &mdash; one comparison of two certain amounts per node, in an order whose first step is belief-free &mdash; asks for exactly the reasoning the level-<Math>{"k"}</Math> literature finds participants reliably perform.
                    </p>
                    <p>
                        All four are hypotheses rather than findings, and the paper is written as such throughout. No play by independent participants has been observed &mdash; the processes settled on its public record are the authoring project&rsquo;s own exercises of it &mdash; and no laboratory replication of the bonded game has been run; every argument below is a transfer from the experimental record on adjacent games to a payoff structure that differs from all of them in the respect the argument turns on.
                    </p>
                </>
            }
            references={
                <>
                    <li>Bolton, G. E. &amp; Ockenfels, A. ERC: A Theory of Equity, Reciprocity, and Competition. <em>American Economic Review</em>, 90(1):166&ndash;193, 2000.</li>
                    <li>Camerer, C. F. <em>Behavioral Game Theory: Experiments in Strategic Interaction</em>. Princeton University Press, Princeton, NJ, 2003.</li>
                    <li>Cialdini, R. B. &amp; Goldstein, N. J. Social Influence: Compliance and Conformity. <em>Annual Review of Psychology</em>, 55:591&ndash;621, 2004.</li>
                    <li>Costa-Gomes, M., Crawford, V. P., &amp; Broseta, B. Cognition and Behavior in Normal-Form Games: An Experimental Study. <em>Econometrica</em>, 69(5):1193&ndash;1235, 2001.</li>
                    <li>Fehr, E. &amp; G&auml;chter, S. Cooperation and Punishment in Public Goods Experiments. <em>American Economic Review</em>, 90(4):980&ndash;994, 2000.</li>
                    <li>Fehr, E. &amp; Schmidt, K. M. A Theory of Fairness, Competition, and Cooperation. <em>Quarterly Journal of Economics</em>, 114(3):817&ndash;868, 1999.</li>
                    <li>Ghatak, M. Group Lending, Local Information and Peer Selection. <em>Journal of Development Economics</em>, 60(1):27&ndash;50, 1999.</li>
                    <li>Hirshleifer, J. From Weakest-Link to Best-Shot: The Voluntary Provision of Public Goods. <em>Public Choice</em>, 41(3):371&ndash;386, 1983.</li>
                    <li>Kahneman, D. &amp; Tversky, A. Prospect Theory: An Analysis of Decision under Risk. <em>Econometrica</em>, 47(2):263&ndash;291, 1979.</li>
                    <li>Morduch, J. The Microfinance Promise. <em>Journal of Economic Literature</em>, 37(4):1569&ndash;1614, 1999.</li>
                    <li>Schelling, T. C. <em>The Strategy of Conflict</em>. Harvard University Press, Cambridge, MA, 1960.</li>
                    <li>Stahl, D. O. &amp; Wilson, P. W. On Players&rsquo; Models of Other Players: Theory and Experimental Evidence. <em>Games and Economic Behavior</em>, 10(1):218&ndash;254, 1995.</li>
                    <li>Stiglitz, J. E. Peer Monitoring and Credit Markets. <em>World Bank Economic Review</em>, 4(3):351&ndash;366, 1990.</li>
                    <li>Sugden, R. A Theory of Focal Points. <em>Economic Journal</em>, 105(430):533&ndash;550, 1995.</li>
                    <li>Thaler, R. H. Mental Accounting and Consumer Choice. <em>Marketing Science</em>, 4(3):199&ndash;214, 1985.</li>
                    <li>Tversky, A. &amp; Kahneman, D. Advances in Prospect Theory: Cumulative Representation of Uncertainty. <em>Journal of Risk and Uncertainty</em>, 5(4):297&ndash;323, 1992.</li>
                    <li>Van Huyck, J. B., Battalio, R. C., &amp; Beil, R. O. Tacit Coordination Games, Strategic Uncertainty, and Coordination Failure. <em>American Economic Review</em>, 80(1):234&ndash;248, 1990.</li>
                    <li>Yunus, M. <em>Banker to the Poor: Micro-Lending and the Battle Against World Poverty</em>. PublicAffairs, New York, 1999.</li>
                </>
            }
        >
            <PaperSection title="1. Introduction">
                <p>
                    Behavioral game theory (Camerer, 2003) is the empirical correction to mechanism design&rsquo;s full-rationality assumptions. Forty years of experimental work has documented systematic departures from the rational-choice baseline: loss aversion (Kahneman &amp; Tversky, 1979; Tversky &amp; Kahneman, 1992), framing effects, mental accounting (Thaler, 1985), fairness preferences (Fehr &amp; Schmidt, 1999; Bolton &amp; Ockenfels, 2000), bounded depth of strategic reasoning (Stahl &amp; Wilson, 1995; Costa-Gomes, Crawford, &amp; Broseta, 2001), and coordination failure under pessimistic beliefs about co-players (Van Huyck, Battalio, &amp; Beil, 1990). A mechanism designed under the rational-choice assumption is robust to these departures only if the departures preserve its load-bearing equilibrium properties; many mechanisms do not survive the test.
                </p>
                <p>
                    The mechanism treated here is a bonded settlement primitive with two calls. Its equilibrium argument has a shape that matters for everything below, and the shape is worth naming before the behavioral analysis reads it. The argument does not proceed by eliminating strategies in successive rounds, and it does not establish that either party&rsquo;s cooperative conduct is better whatever the other does. It proceeds node by node: after performance, resolving is unconditionally strictly better for the buyer, a comparison that needs no assumption whatever about the seller; given that, performance is each seller&rsquo;s strict best response. Each of those steps is a comparison between two certain amounts. The dependence between them runs one way and is three steps deep, and its first step is belief-free. Section 2 states the mechanism and the payoffs in full, and every quantity used below is defined there; the present section names only what the behavioral claims turn on.
                </p>
                <p>
                    One feature of the payoff convention should be flagged here because a behavioral reader reaches for a production-cost term by reflex and will look for one. There is none at the node. Effort, inputs, and time are the participant&rsquo;s own outlays, made on its own account, and they are not terms in the comparison the mechanism puts in front of it &mdash; a point Section 6 turns into an argument, since a comparison of two certain amounts is a cheaper cognitive object than any private accounting weighed against a bar.
                </p>
                <PaperRun title="The four claims.">
                    The paper develops four claims about the behavioral robustness of the bonded architecture.
                </PaperRun>
                <p>
                    First, the comparison at each node straddles the prospect-theoretic reference point. Because a defector is credited with what it retains &mdash; the seller with the product in its hands, the buyer with the delivery it received &mdash; the defecting branch is a loss while the cooperative branch is a gain for the seller and a break-even for the buyer. Loss aversion accordingly weights one branch and not the other, so it enters the comparison rather than cancelling out of it. Section 3 works this out at both nodes separately, since they differ, and adds the mental-accounting consequence: the retained value and the locked bond sit on opposite sides of the reference point, so a defector that books them apart feels its position more heavily than the netted figure.
                </p>
                <p>
                    Second, the Van Huyck&ndash;Battalio&ndash;Beil (1990) coordination-failure finding addresses a structural condition this setting has. Where a co-seller has held out, a seller&rsquo;s own holding out is strictly better than performing, and no bond schedule could make it otherwise: handing goods to a process that will not pay is not something a schedule can render attractive. Section 4 concedes the condition and answers on other ground &mdash; that the pessimistic-belief channel has no terminal outcome to converge on.
                </p>
                <p>
                    Third, the weakest-link structure the mechanism induces among sellers is both economically real and behaviorally activated. A co-seller that has performed is exposed to a peer&rsquo;s fault by <Math>{"P_i + 2G_i"}</Math>, and one that has not yet performed by at least <Math>{"P_i + G_i"}</Math>; the experimental literature on social-pressure activation operates far below any stake a commercial process would set. Section 5 develops the pressure and scopes the microfinance comparison honestly, including the margin it withdraws.
                </p>
                <p>
                    Fourth, the architecture exhibits <em>incentive legibility</em>: assessing the equilibrium takes one comparison of two certain amounts per node, in an order whose first step depends on nobody. Section 6 argues that this is well within what the level-<Math>{"k"}</Math> literature finds participants reliably do, and that an argument proceeding instead by eliminating strategies in successive rounds would have asked for precisely the reasoning that literature finds they do not.
                </p>
                <PaperRun title="What the paper is not.">
                    Every claim below is a prediction, not a finding. The mechanism analyzed here is built, machine-checked by its own authors with no external audit of those checks yet performed, and settling processes on a public record; but every process settled there is one the authoring project committed and resolved itself, so no play by independent participants has been observed, and no laboratory replication of the bonded game has been run. The behavioral arguments are therefore transfers from the experimental record on adjacent games &mdash; minimum-effort coordination, public-goods punishment, prospect-theoretic valuation of mixed outcomes &mdash; to a payoff structure that differs from all of them in the respect the arguments turn on. A reader should treat them as hypotheses with stated structural grounds and an obvious experimental programme, not as results about how participants in this mechanism behave.
                </PaperRun>
                <PaperRun title="Paper organization.">
                    Section 2 states the settlement primitive, its payoff convention, and the results the behavioral analysis reads. Section 3 works out the prospect-theoretic reading of each node. Section 4 takes up the Van Huyck concern. Section 5 treats the externality structure of atomic resolution as behavioral peer pressure. Section 6 develops incentive legibility and the interface cognition through which participants meet it. Section 7 concludes.
                </PaperRun>
            </PaperSection>

            <PaperSection title="2. The Settlement Primitive and Its Payoffs">
                <p>
                    The mechanism has two calls, each carrying a mechanism design of its own, and nothing else. This section states what the behavioral analysis uses, in the register the rest of the paper works in.
                </p>
                <PaperRun title="Commit: asymmetric bonding.">
                    A commitment is signed by both parties and locks two deposits. For an order with payment <Math>{"P_i > 0"}</Math>, the buyer locks <Math>{"2P_i"}</Math> and the seller locks <Math>{"2G_i"}</Math>, where <Math>{"G_i = \\sum_{j \\leq i} P_j"}</Math> is the value the process has accumulated through that seller&rsquo;s own link &mdash; inclusive of the order&rsquo;s own payment, so <Math>{"G_i \\geq P_i"}</Math> with equality only at the root. The base is not reported by anyone: the accumulator admits exactly one value per commitment, the standing total plus the new payment, and any other declaration is refused. The schedule is constitutive &mdash; one rule applied to every order at every position, twice the payment from the buyer and twice the value accumulated at the link from the seller.
                </PaperRun>
                <PaperRun title="Resolve: buyer dominance with atomic resolution.">
                    Only the buyer may resolve, and resolution settles every active order in the process at once or none. It is the only terminal event: a resolved order cannot be re-opened, while an unresolved one stays live indefinitely with no clock running against it. Resolution <em>is</em> the buyer&rsquo;s acceptance &mdash; the mechanism holds no test of performance of its own, admits no report of delivery, and offers no party a way to certify performance to it.
                </PaperRun>
                <PaperRun title="The boundary, and what a payoff contains.">
                    The goods, every passage of value along the chain, performance itself, and the parties&rsquo; knowledge of all of it are off the record and beyond the mechanism&rsquo;s reach. What the mechanism holds is the bonds, the signed accumulator, and the record of what was committed to; that record shows commitments and non-resolution, and never shows performance. A payoff accordingly has two parts: what the mechanism moves &mdash; the deposit pulled at commit, the payout made at resolution &mdash; and a <em>credit</em> for whatever off-chain value the party ends up holding, valued at the figure the parties themselves signed. The credit is never a debit: a party is counted for what is in its hands and never charged for what is not. Off the cooperative path this credits a defector with its <em>retention</em>, and the retention is real &mdash; a seller that has not passed the product along still has it, and no operation of the mechanism can reach it. Deterrence claims below are therefore always net of retention, never computed from locked bonds alone.
                </PaperRun>
                <p>
                    At a single edge the mechanism produces four outcomes, and the two that involve no resolution are positions held rather than endings.
                </p>
                <div className="my-4 overflow-x-auto">
                    <table className="text-sm border-collapse">
                        <thead>
                            <tr>
                                <th className="border border-default px-3 py-1.5 text-left text-ink-muted font-normal"><Math>{"(u_b, u_s)"}</Math></th>
                                <th className="border border-default px-3 py-1.5 font-semibold text-ink-heading">resolution occurs</th>
                                <th className="border border-default px-3 py-1.5 font-semibold text-ink-heading">no resolution</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td className="border border-default px-3 py-1.5 font-semibold text-ink-heading">performance occurs</td>
                                <td className="border border-default px-3 py-1.5"><Math>{"(0,\\; +P)"}</Math></td>
                                <td className="border border-default px-3 py-1.5"><Math>{"(-P,\\; -2G)"}</Math></td>
                            </tr>
                            <tr>
                                <td className="border border-default px-3 py-1.5 font-semibold text-ink-heading">no performance</td>
                                <td className="border border-default px-3 py-1.5"><Math>{"(-P,\\; \\leq P + G)"}</Math></td>
                                <td className="border border-default px-3 py-1.5"><Math>{"(-2P,\\; \\leq -G)"}</Math></td>
                            </tr>
                        </tbody>
                    </table>
                    <p className="text-xs text-ink-muted mt-2">The four <em>outcomes</em> at one edge &mdash; not a strategic form, and no plan is excluded by it: rows record whether the seller ever performs, columns whether the buyer ever resolves, and every plan either party may adopt terminates in one of the four. Each cell is the pair <Math>{"(u_b, u_s)"}</Math> of the convention above: locked positions, plus the assented value of what each party holds. The seller&rsquo;s entries are bounds because what it retains is at most the value accumulated at its link and may be less. The right-hand column holds no settlements: those are open positions, and with no clock running from the bonded state they persist rather than mature.</p>
                </div>
                <PaperRun title="The equilibrium, and the order of its steps.">
                    Reading the table at the decision nodes gives the result the behavioral analysis reads. After performance the buyer compares <Math>{"0"}</Math> against <Math>{"-P"}</Math>: it holds the delivery either way, so the two branches differ only in what the mechanism moves, and the payment it withholds is not kept by it but frozen inside its own bond. Resolving is therefore strictly better, and the comparison needs no assumption whatever about the seller. Given that, the seller compares <Math>{"+P"}</Math> for performing against at best <Math>{"-G"}</Math> for holding out &mdash; the product in its hands credited at most at <Math>{"G"}</Math>, against <Math>{"2G"}</Math> locked &mdash; and performs, strictly, by at least <Math>{"P + G"}</Math>. Given that in turn, a buyer at a node before performance keeps the process open rather than resolving into a terminal <Math>{"-P"}</Math>. Each comparison is made at the node where the choice falls rather than over a plan fixed at the outset, which is what makes the cooperative profile at a single edge a subgame-perfect equilibrium rather than merely a Nash equilibrium of the same game: a buyer plan carrying a threat never to resolve does not survive the first comparison, which holds after any performance whatever preceded it. The two calls compose in that order, and neither result stands alone: a buyer that resolves without regard to performance is not protected by any of this, and what it loses is bounded by exactly what it agreed to pay.
                </PaperRun>
                <PaperRun title="The multi-party extension, and what it does not establish.">
                    With <Math>{"n"}</Math> sellers under one buyer the same comparisons recur at every position. Where the co-sellers perform, seller <Math>{"S_i"}</Math>&rsquo;s gap between performing and holding out is <Math>{"\\Delta_i = P_i + G_i \\geq 2P_i"}</Math>, with equality only at the root and growing with every payment accumulated ahead of it. Where some co-seller has <em>not</em> performed, the comparison inverts: performing costs <Math>{"S_i"}</Math> its bond and its product together, <Math>{"-2G_i"}</Math>, against at best <Math>{"-G_i"}</Math> for keeping what it holds, so holding out is then strictly better. The sellers&rsquo; side is accordingly not solvable by elimination on its own; what recommends the cooperative profile to a seller is that it is strictly better <em>provided the others perform</em>. Section 4 takes up what that concession costs and what answers it.
                </PaperRun>
                <PaperRun title="The externality, and who carries most of it.">
                    Atomicity couples the sellers. Under a buyer that resolves only against universal performance, the holding out of a seller <Math>{"S_k"}</Math> costs a co-seller <Math>{"S_i"}</Math> (<Math>{"i \\neq k"}</Math>) that has already performed the amount <Math>{"\\varepsilon_{k \\to i} = P_i + 2G_i"}</Math>: it has parted with the product and stands in its whole bond. For a co-seller that has not yet performed the figure is at least <Math>{"P_i + G_i"}</Math>, since it still holds what is in its hands, and the balance turns on how much of the accumulated value it can actually retain &mdash; which the record does not show. Either way it is positive, and the party most exposed to a failure is the one that has already done its part. This satisfies the defining properties of a weakest-link structure (Hirshleifer, 1983).
                </PaperRun>
                <PaperRun title="Failure, remedy, and forums.">
                    A seller&rsquo;s inability to perform is an external event the parties handle between themselves <em>before</em> any resolution, and the concrete transfer is simple: the failing seller sends the buyer the payment it stands to receive, and returns or makes good whatever of the buyer&rsquo;s the failure left in its hands, so that at resolution it nets its bond and nothing else &mdash; its failure earning it exactly zero &mdash; while the buyer is made whole. The second half of that is not a nicety of the telling: a seller that sent the payment on but kept what was in its hands would net what it retained, and the buyer would stay short by the same amount. Where the parties disagree, an external forum may rule on what the open record shows and on what the parties bring it, and its ruling feeds their negotiation; it cannot resolve the process, resolution being the buyer&rsquo;s alone, so it has no direct enforcement of any kind. Resolution is terminal acceptance: a buyer resolves when it is satisfied, and there is no recourse inside the mechanism afterwards.
                </PaperRun>
            </PaperSection>

            <PaperSection title="3. Prospect Theory at the Two Nodes">
                <p>
                    Prospect theory (Kahneman &amp; Tversky, 1979; Tversky &amp; Kahneman, 1992) values outcomes as deviations from a reference point, with a value function steeper below it than above: the disutility of a loss <Math>{"x > 0"}</Math> is approximately <Math>{"\\lambda x^{\\alpha}"}</Math> against a utility <Math>{"x^{\\alpha}"}</Math> for a gain of the same size, where <Math>{"\\lambda"}</Math> is the loss-aversion ratio, empirically in the range 1.5 to 2.5, and <Math>{"\\alpha \\approx 0.88"}</Math> the curvature parameter. The theory leaves the reference point under-determined, and the analysis below takes the conservative one throughout: pre-commitment wealth, which is also the point the payoff convention of Section 2 already measures from.
                </p>
                <p>
                    The consequential fact is where the two branches of each comparison fall relative to that point &mdash; relative, that is, to the kink where the value function changes slope &mdash; and retention is what decides it. A defector is credited with what it keeps, so its position is a mixed one &mdash; a locked bond below the reference point, a retained value above it &mdash; while the cooperative branch is a clean gain for the seller and a clean break-even for the buyer. The two nodes therefore have different structures and are worked separately. Nothing here is asked to establish the direction of either comparison: those hold under any strictly monotone transformation of the payoffs, loss-averse specifications included. What the reading below settles is the felt margin.
                </p>
                <PaperRun title="First, the sizes, which are three different quantities.">
                    Precision about magnitudes matters before any weighting is applied to them, because three quantities are easily run together. The <em>bond</em> is <Math>{"2P"}</Math> from the buyer and <Math>{"2G_i"}</Math> from the seller. The <em>gap</em> at a node is neither: at the buyer&rsquo;s node after performance it is <Math>{"P"}</Math>, the payment and not the bond, and at the seller&rsquo;s node with co-sellers performing it is <Math>{"\\Delta_i = P_i + G_i"}</Math>. The <em>externality</em> a performed co-seller carries from someone else&rsquo;s fault is a third figure, <Math>{"P_i + 2G_i"}</Math>. That the buyer&rsquo;s gap is <Math>{"P"}</Math> rather than <Math>{"2P"}</Math> is not a weakness of the schedule but the whole of what its second half buys: a bond equal to the payment would be exactly offset by the delivery the buyer holds, leaving it indifferent between resolving and withholding, and it is the second <Math>{"P"}</Math> that puts withholding below closing at all.
                </PaperRun>
                <PaperRun title="The buyer&rsquo;s node: a break-even against a loss.">
                    After performance the buyer&rsquo;s branches are <Math>{"0"}</Math> for resolving and <Math>{"-P"}</Math> for never resolving. The first sits exactly at the reference point and the second below it, so in prospect-theoretic terms the comparison is <Math>{"v(0) = 0"}</Math> against <Math>{"v(-P) = -\\lambda P^{\\alpha}"}</Math>: the loss-aversion ratio multiplies the entire gap rather than dropping out of it. This is a consequence of retention accounting and would not arise without it. Read the same node with the delivery uncounted &mdash; the buyer at <Math>{"-P"}</Math> for resolving and <Math>{"-2P"}</Math> for withholding &mdash; and both branches lie in the loss domain, <Math>{"\\lambda"}</Math> multiplies both alike, and the comparison retains only the loss-domain curvature, a factor <Math>{"2^{\\alpha} \\approx 1.84"}</Math>. Crediting the buyer with what it actually holds moves loss aversion from neutral to load-bearing at this node.
                </PaperRun>
                <PaperRun title="The seller&rsquo;s node: a gain against a loss.">
                    Where the co-sellers perform, the seller&rsquo;s branches are <Math>{"+P_i"}</Math> for performing and at best <Math>{"-G_i"}</Math> for holding out. These straddle the reference point in the other configuration &mdash; a gain against a loss &mdash; so <Math>{"\\lambda"}</Math> weights the holding-out branch alone and the felt gap is <Math>{"P_i^{\\alpha} + \\lambda G_i^{\\alpha}"}</Math>. No cancellation arises here either, and none ever could: the cancellation is a feature of comparisons whose branches lie on the same side of the reference point, and this comparison has never had that form. Stating the two nodes separately is not pedantry. They differ in which branch carries the weight and in what a smaller bond would have done to them, and an analysis that derives the cancellation at one node and generalizes it to &ldquo;participants&rdquo; gets the seller&rsquo;s side wrong.
                </PaperRun>
                <PaperRun title="Retention and bond fall on opposite sides, and the editing question is live.">
                    The defecting branch is a mixed position, and prospect theory&rsquo;s editing phase does not settle whether a participant evaluates the netted figure or its components. Mental accounting (Thaler, 1985) makes the question live rather than academic here, because the two components sit in different places and different books: the retained product is in the defector&rsquo;s own custody, and the locked bond is on the record. The two readings bracket the felt position of a seller holding out at maximal retention. Integrated, it evaluates the net: <Math>{"v(-G_i) = -\\lambda G_i^{\\alpha}"}</Math>. Segregated, it books a gain of at most <Math>{"G_i"}</Math> for the product against a loss of the whole <Math>{"2G_i"}</Math>: <Math>{"G_i^{\\alpha} - \\lambda 2^{\\alpha} G_i^{\\alpha} = (1 - \\lambda 2^{\\alpha}) G_i^{\\alpha}"}</Math>.
                </PaperRun>
                <p>
                    At the Tversky&ndash;Kahneman (1992) estimates <Math>{"\\lambda = 2.25"}</Math> and <Math>{"\\alpha = 0.88"}</Math>, the integrated reading gives <Math>{"-2.25\\,G_i^{\\alpha}"}</Math> and the segregated one <Math>{"-3.14\\,G_i^{\\alpha}"}</Math>: segregation makes the holdout position about 1.4 times heavier, and across the documented range <Math>{"\\lambda \\in [1.5, 2.5]"}</Math> the factor runs from roughly 1.17 to 1.44. The direction is the point. Segregation credits the retained value at gain-domain weight while charging the whole locked bond at loss-domain weight, so the more separately a defector books the two, the less its retention pays. This is the behavioral counterpart of the arithmetic the schedule is built on &mdash; the doubling exists because a defector keeps what is in its hands, and the participant who keeps the clearest accounts of what it kept feels the bond most heavily against it.
                </p>
                <p>
                    The same structure at the buyer&rsquo;s node runs the other way by a little, and the honest statement includes it. An extracting buyer&rsquo;s withholding branch segregates into a delivery worth <Math>{"P"}</Math> against <Math>{"2P"}</Math> locked, at <Math>{"(1 - \\lambda 2^{\\alpha})P^{\\alpha}"}</Math>; but its resolving branch is a mixed position too &mdash; a payment made against a delivery received &mdash; and segregated it is felt at <Math>{"(1 - \\lambda)P^{\\alpha}"}</Math> rather than at zero. The gap under segregation is then <Math>{"\\lambda(2^{\\alpha} - 1)P^{\\alpha}"}</Math> against <Math>{"\\lambda P^{\\alpha}"}</Math> under integration, narrower by the factor <Math>{"2^{\\alpha} - 1 \\approx 0.84"}</Math> and positive for every <Math>{"\\lambda > 0"}</Math>. So the editing convention widens the seller&rsquo;s margin and narrows the buyer&rsquo;s by about a sixth, with no reading of it approaching a reversal at either node. Both nodes survive both conventions, which is the claim worth making; the asymmetry between them is worth recording rather than smoothing.
                </p>
                <PaperRun title="No node is flat.">
                    A payoff structure in which some node presents a participant with two branches of equal value gives non-pecuniary motives a free ride there: whatever the participant does costs it nothing, so spite, fatigue, or indifference decides. Retention accounting leaves the mechanism with no such node on the path a participant actually walks. At its own performance decision with the process live, a seller compares <Math>{"+P_i"}</Math> against at best <Math>{"-G_i"}</Math>; where the process has already failed it compares <Math>{"-2G_i"}</Math> against at best <Math>{"-G_i"}</Math>; and the buyer&rsquo;s branches differ strictly at each of its own nodes. The single exception is exact and instructive: a seller that can retain nothing at all &mdash; whose contribution is a service not yet rendered and which holds none of what came before it &mdash; is indifferent between holding out and performing in the states where the process has already failed, since with nothing in its hands to keep the two branches coincide there. At its own live decision, with the co-sellers ready, that same seller faces the widest comparison of anyone: <Math>{"+P_i"}</Math> against a locked <Math>{"2G_i"}</Math> with no credit at all against it. Everywhere else, indulging a non-pecuniary motive has a price, and the price is quoted in the currency the parties signed.
                </PaperRun>
                <PaperRun title="Non-pecuniary preferences.">
                    The equilibrium argument prices pecuniary payoffs only, and the experimental literature documents substantial preferences it does not price: fairness (Fehr &amp; Schmidt, 1999; Bolton &amp; Ockenfels, 2000), reciprocity, spite, intrinsic motivation. Three observations bound the concern. First, inequity aversion has its bite at entry rather than at performance. The schedule is symmetric at the root, where <Math>{"G = P"}</Math> and both parties bond <Math>{"2P"}</Math>, and asymmetric below it, where the seller&rsquo;s exposure exceeds the buyer&rsquo;s; a participant averse to that asymmetry declines to commit rather than holding out after committing, so the correction shows up as slower process formation and not as a different equilibrium of play. Second, spite must now be paid for at the node where it would do its damage. Under a reading in which a participant facing a failed process is indifferent, spite is free and the mechanism has nothing to say; under retention accounting the seller&rsquo;s live decision, with the co-sellers ready, is a strict comparison for any retention whatever, so a spiteful seller that holds out to punish a buyer pays at least <Math>{"G_i"}</Math> for it, and pays in the loss domain where the weighting is steepest. The carve-out of the previous run travels with this one and costs it nothing: the participant that retains nothing is the one whose branches can coincide, and it coincides only in the states where the process has already failed &mdash; never at the decision that fails it. Third, intrinsic motivation to perform &mdash; a craft-based or honor-based preference for delivering the agreed work regardless of incentive &mdash; runs with the schedule rather than against it: the pecuniary incentive points the same way, so the two add instead of competing.
                </PaperRun>
            </PaperSection>

            <PaperSection title="4. Pessimistic Beliefs and the Van Huyck Concern">
                <p>
                    The classical experimental literature on weakest-link coordination, beginning with Van Huyck, Battalio, &amp; Beil (1990), documents a robust finding: in groups larger than two, minimum-effort games converge to the Pareto-inferior equilibrium through pessimistic beliefs about co-players. Since the mechanism induces a weakest-link structure among sellers, the finding is a direct challenge to the multi-party reading, and it is the challenge this section owes an answer to. The answer is not that the structure is absent. It is present, and the section begins by conceding it.
                </p>
                <PaperRun title="The experimental result and the condition it needs.">
                    In the Van Huyck&ndash;Battalio&ndash;Beil design each of 14 to 16 players chooses an effort level from <Math>{"\\{1, \\ldots, 7\\}"}</Math>; a player&rsquo;s payoff rises with the group minimum and falls with its own effort. Every common effort level is a Nash equilibrium, and they are Pareto-ranked, with 7 best for everyone. The structural condition that makes the failure possible is that <em>individual cooperation is not dominated</em>: a player who chooses 7 against a co-player who chooses 1 pays a private cost and produces no joint benefit, so choosing high is rational only conditional on others choosing high, and pessimism about others rationalizes choosing low. The empirical result is then dynamic. The game is played in rounds, the minimum is announced after each, and the announced minimum ratchets downward as players update on what they have just seen; large groups reach the floor within a few rounds, while pairs coordinate on the efficient level.
                </PaperRun>
                <PaperRun title="The condition is present here, and we do not claim otherwise.">
                    A seller facing a process in which some co-seller has held out compares <Math>{"-2G_i"}</Math> for performing &mdash; bond locked, product passed on, nothing paid &mdash; against at best <Math>{"-G_i"}</Math> for keeping what it holds. Holding out is strictly better, and the sellers&rsquo; side is therefore not solvable by elimination. This is not a defect the schedule could repair: no arrangement of bonds makes it attractive to hand goods to a party that will not pay for them, and a claim that the bonded setting forecloses the pessimistic-belief channel by dominance would be false. The response has to come from somewhere else, and three features of the setting supply it. None of them is a dominance argument.
                </PaperRun>
                <PaperRun title="First: nothing is ever banked, so the updating engine has no history.">
                    The Van Huyck convergence is produced by realization. Each round ends, the minimum is computed, payoffs are paid, and the realized profile becomes the datum from which the next round&rsquo;s belief is formed &mdash; and because the datum is a fact about what actually happened, low play confirms low play and the ratchet runs one way. The bonded process has no round. Resolution is the only terminal event, only the buyer can call it, and it is acceptance rather than a scheduled settlement; short of it nothing computes, nothing pays, and nothing enters a history. A standoff is a position held, not an outcome taken. So the mechanism that drives the laboratory result &mdash; belief-updating over realized profiles &mdash; has no realized profile to update from, and the profile it would update toward is not sticky: a cascade of holdouts is a function of the current state and reverses the moment the blocked party stands ready to perform, since each remaining seller&rsquo;s comparison flips back to <Math>{"+P_i"}</Math> against at best <Math>{"-G_i"}</Math> the instant the others do. What the bonded setting removes is not the coordination problem but the finality that makes coordination failure terminal in the experiments.
                </PaperRun>
                <PaperRun title="Second: each seller&rsquo;s own exposure is a figure, not a belief.">
                    A Van Huyck player&rsquo;s reason to choose high effort turns entirely on an unobservable &mdash; what fifteen strangers will do &mdash; estimated from priors and announced history and nothing else. Pessimism is exactly a distribution over that unobservable, and the level-<Math>{"k"}</Math> literature finds wide heterogeneity in the sophistication players attribute to one another. Here the quantity governing a seller&rsquo;s own stake is of a different kind. Its exposure to a peer&rsquo;s fault is computed from the signed accumulator: exactly <Math>{"P_i + 2G_i"}</Math> once it has performed, and at least <Math>{"P_i + G_i"}</Math> before. Pessimism can attach to whether the others will perform; it cannot attach to what a failure would cost, which is arithmetic on public figures and requires no information about anyone. One scope line belongs with this and is not a small one: what the record does not give is <em>which</em> seller failed. Performances are off the record exactly as the value is, so the stake is readable and the fault is not &mdash; identifying the party that did not deliver is knowledge the parties hold and the accumulator does not.
                </PaperRun>
                <PaperRun title="Third: every party in a standoff strictly prefers the close to its position.">
                    The Van Huyck floor is a rest point. Nobody in the all-low profile can improve by moving alone, so pessimism, once settled into, is comfortable to hold. The bonded analogue is not a profile anyone rests in. It is a set of open positions, and each holder would strictly rather the process closed cooperatively than hold what it holds: the buyer stands at <Math>{"-2P"}</Math> against the <Math>{"0"}</Math> that closing would give it, and each seller at best at <Math>{"-G_i"}</Math> against <Math>{"+P_i"}</Math>. The pessimism that would have to be maintained is therefore one that every party is paying to maintain, at every node, with no clock ending the payment and no event improving the position. That is a materially different behavioral object from a rest point, and the difference is not one the laboratory games can exhibit, since their pessimism is discharged at the end of each round.
                </PaperRun>
                <PaperRun title="Group size, and what pessimism buys.">
                    One channel from the experiments does transfer. Coordination fails in large Van Huyck groups and succeeds in pairs because the chance that <em>someone</em> plays low rises with the number of players, and the same is true of the chance that some seller in a long chain holds out. What differs is the consequence. Each seller&rsquo;s own quantities are fixed by its own commitment and do not move with <Math>{"n"}</Math>: its gap is <Math>{"P_i + G_i"}</Math> and its exposure <Math>{"P_i + 2G_i"}</Math> whatever the chain&rsquo;s length. What grows with <Math>{"n"}</Math> is only the number of parties the proviso ranges over. So pessimism in a long chain buys duration rather than an outcome &mdash; a process that stays open longer, not a worse settlement, there being no settlement short of the buyer&rsquo;s acceptance.
                </PaperRun>
                <PaperRun title="Scope of the claim.">
                    The argument is structural, and its conclusion is correspondingly narrow: the negative finding from the weakest-link experiments does not transfer, because the finality it runs on is absent. It establishes no positive finding for the bonded setting. The failure mode that survives is persistence &mdash; a process that stays open a long time, its parties each holding a position they would rather close &mdash; and this paper does not predict how long, nor has any laboratory replication of the bonded game been run. What answers persistence is not a belief correction but a standing exposure that does not decay, together with the route out that stays open to every party at every moment: perform, or make the buyer whole before resolution. Hirshleifer&rsquo;s (1983) characterization of the weakest-link payoff form continues to apply to the structure; the experimental literature&rsquo;s convergence result does not follow it here.
                </PaperRun>
            </PaperSection>

            <PaperSection title="5. Atomic Resolution as Peer Pressure">
                <p>
                    The externality structure of Section 2 is <em>economic</em>: it operates on each seller&rsquo;s own bonded position. The behavioral question is whether participants also experience it as peer pressure &mdash; whether the coupling activates the social channel the experimental literature documents, rather than functioning only as arithmetic. We argue it does, and then bound what that licenses.
                </p>
                <PaperRun title="The activation threshold sits far below the stake.">
                    The experimental literature on social-pressure activation (Cialdini &amp; Goldstein, 2004; Fehr &amp; G&auml;chter, 2000) finds that participants modify their behavior in response to peer monitoring at stakes small relative to their own wealth, and that the response strengthens with the stakes faced by the monitor as well as by the monitored. The Fehr&ndash;G&auml;chter result on punishment in public-goods games is the sharpest form of the finding: participants pay private costs to punish free-riders where no monetary return is available at all, which establishes that the channel activates without an expected-value rationale to carry it. In the bonded setting there is an expected-value rationale as well, and it is not small. A co-seller that has performed carries <Math>{"P_i + 2G_i"}</Math> from any other seller&rsquo;s fault; with equal payments <Math>{"p"}</Math> per link that is <Math>{"(2i+1)p"}</Math> at link <Math>{"i"}</Math> &mdash; eleven times the local payment at the fifth link, twenty-one times at the tenth &mdash; while a seller that has not yet performed carries at least <Math>{"(i+1)p"}</Math>. Whether the channel activates at such stakes is not in doubt on the experimental record. How intensely it does, we do not predict.
                </PaperRun>
                <PaperRun title="The inversion worth naming.">
                    One feature of the externality is behaviorally unusual and should be stated rather than left in the algebra. Exposure to a peer&rsquo;s fault is <em>largest</em> for the seller that has already performed, because that seller has parted with the product and stands in its whole bond with nothing in hand to credit against it. The participant who has behaved exactly as the mechanism intends is the one with most to lose from someone else&rsquo;s failure, and is therefore the one with the strongest reason to press for a cure. Whether co-sellers press, wait, substitute, or arrange a remedy privately is conduct this paper does not model; what the structure supplies is a bonded, computable interest in the same outcome, which is what makes any of those responses rational rather than altruistic.
                </PaperRun>
                <PaperRun title="The joint-liability comparison, and the number we do not carry.">
                    Joint-liability microfinance (Ghatak, 1999; Stiglitz, 1990) obtains peer enforcement through joint-liability contracting plus a social substrate &mdash; repeated interaction, local information, exogenous social sanction &mdash; and the default-rate figure usually quoted for the Grameen model from the lender&rsquo;s own reporting (Yunus, 1999) is contested on accounting grounds by Morduch (1999) with no independently reconciled replacement since, so we carry no number into the argument at any point. That the bonded mechanism reproduces the coordination-pressure component of that equilibrium without the social substrate is a structural fact this paper takes as given rather than one it re-derives here; what it asks is a different question &mdash; whether pressure produced that way, with no village and no relationship behind it, is one a participant actually feels.
                </PaperRun>
                <p>
                    The behavioral reading of that reduction is that the pressure is constituted by the two calls rather than mediated through a social substrate, and the labour divides between them: the bond fixes the magnitude each seller carries at its own link, while it is atomic resolution that couples the sellers at all, since each bond is posted individually against its own accumulator snapshot and nothing in the schedule ties one seller to another. What a co-seller stands to lose from another&rsquo;s failure is accordingly its own locked position, held there by an all-or-nothing settlement rather than imposed by anyone, so the channel exists among strangers who have never met and will not deal again. Three margins set the comparison, and the third runs against the mechanism, which is why it is given here rather than omitted.
                </p>
                <ol className="space-y-2 list-decimal pl-6 text-sm">
                    <li><em>The stake scales with the link.</em> A co-seller&rsquo;s exposure grows with the value the process has accumulated at its own link, so a participant deep in a chain has a larger interest in its peers&rsquo; performance than a shallow one. Joint liability as Ghatak (1999) and Stiglitz (1990) specify it has no counterpart to this: a member&rsquo;s liability for a peer&rsquo;s default does not vary with its position in the group.</li>
                    <li><em>The punishment technology is the schedule.</em> Nothing has to be organized, threatened, or socially administered for the pressure to exist; the participant&rsquo;s own bond does the work that a village&rsquo;s sanctioning capacity does in the joint-liability models, and it does it from the first commitment rather than after a relationship has formed.</li>
                    <li><em>The information margin runs one way only, and we withdraw the half of it usually claimed.</em> Each seller&rsquo;s own bonded exposure is public arithmetic where a village lender&rsquo;s borrowers had to infer one another&rsquo;s positions, and that half of the margin holds. But <em>which</em> seller failed is local knowledge here exactly as it is there: performances are off the record, and the accumulator cannot show what it never saw. So the pressure&rsquo;s existence and magnitude come free of local information, while applying it to a particular failure still takes what the parties know and the record does not.</li>
                </ol>
                <p>
                    A fourth asymmetry cuts against the mechanism on the behavioral side specifically, and completes the honest accounting. The joint-liability groups selected themselves, so their pressure arrived bundled with a prior relationship, and several of the psychological mechanisms the literature invokes &mdash; conformity, standing among acquaintances, anticipated future dealings &mdash; need that relationship to operate. The bonded setting supplies none of it. What transfers cleanly is the economic channel and the monitoring incentive it creates; the acquaintance-mediated channels do not transfer, and a prediction that the bonded setting reproduces the microfinance literature&rsquo;s <em>outcomes</em> would be relying on exactly the part that does not. The claim we make is the narrow one: the peer-pressure channel is present here on structural grounds that do not require a social substrate, and it should be expected to activate. We predict no rate.
                </p>
            </PaperSection>

            <PaperSection title="6. Incentive Legibility and Interface Cognition">
                <p>
                    The behavioral robustness argued above rests on a property we call <em>incentive legibility</em>: what a participant must do to assess the equilibrium is one comparison of two certain amounts at its own node, and the dependence between nodes is short, one-directional, and public.
                </p>
                <PaperRun title="The cognitive demand of an elimination argument.">
                    An equilibrium argument that proceeds by eliminating strategies in successive rounds asks a participant for as many steps of &ldquo;I know that it knows that I know&rdquo; as the elimination has rounds, plus the common knowledge of rationality that licenses carrying the reasoning through them. The level-<Math>{"k"}</Math> literature (Stahl &amp; Wilson, 1995; Costa-Gomes, Crawford, &amp; Broseta, 2001) finds most participants reasoning at one or two steps, not the unbounded depth such an argument presumes. A mechanism whose equilibrium properties are established that way is therefore asking for precisely the reasoning the behavioral evidence says is not reliably available &mdash; and a legibility thesis resting on such an argument would be in tension with itself.
                </PaperRun>
                <p>
                    The argument this mechanism carries does not run that way, and the difference is favorable in a way worth stating directly rather than defensively. Its steps are node comparisons, not eliminations, and the order in which they compose is what does the work: the buyer&rsquo;s comparison after performance &mdash; <Math>{"0"}</Math> against <Math>{"-P"}</Math> &mdash; needs no assumption whatever about the seller, so it is settled without any belief about anyone at all. The seller&rsquo;s comparison then best-responds to it, and the depth of reasoning that takes is one step. The level-<Math>{"k"}</Math> vocabulary is worth invoking carefully here, because the seller&rsquo;s position is better than that vocabulary describes rather than an instance of it. A level-1 player best-responds to a level-0 anchor, and a level-0 anchor is by construction nonstrategic &mdash; conventionally a uniform-random placeholder, whose action the level-1 player has no particular reason to think correct. The seller is not doing that. It is best-responding to a payoff-maximizing counterparty, it predicts that counterparty&rsquo;s action correctly, and it does so without modeling the counterparty&rsquo;s beliefs at all, because the buyer&rsquo;s comparison after performance is settled by two certain amounts and conditions on nothing the seller does. The seller therefore obtains the accuracy that ordinarily takes reasoning about a counterparty&rsquo;s reasoning, at the price that ordinarily buys only a placeholder. That combination is what the two calls composing in this order produce, and it is the whole of the legibility claim.
                </p>
                <PaperRun title="What the comparison at a node contains.">
                    The strength of the legibility claim is the shortness of the list, so it is worth stating what a participant is and is not holding. The seller&rsquo;s node holds <Math>{"+P_i"}</Math> against at best <Math>{"-G_i"}</Math>; the buyer&rsquo;s node after delivery holds <Math>{"0"}</Math> against <Math>{"-P"}</Math>. Both amounts at each node are certain, both are readable off the commitment before it is signed, and both are produced by arithmetic the mechanism executes rather than by anyone&rsquo;s report &mdash; the seller&rsquo;s bond base is fixed by the accumulator and cannot be declared otherwise, so the participant is not asked to assess anybody&rsquo;s honesty about the figures either. No probability enters: neither branch is weighted by how likely the counterparty is to act one way, so there is no estimate to form and no threshold to clear. No private accounting enters: what performing consumes in effort, inputs, or time is an outlay on the participant&rsquo;s own account and not a term at the node, so nobody is asked to price their own performance before they can tell which branch is better. And no model of the counterparty&rsquo;s reasoning enters &mdash; only the mechanism&rsquo;s arithmetic, which is public. A comparison of two certain quantities is the cheapest cognitive object a mechanism can put in front of a participant, and this one presents the same object at every position of the chain with only the magnitudes changing.
                </PaperRun>
                <PaperRun title="The Schelling-focal-point comparison.">
                    Focal-point coordination (Schelling, 1960; Sugden, 1995) also resolves at a shallow depth of reasoning: the participant identifies the salient solution and chooses it, expecting the counterparty to do the same. The bonded comparison is not simpler than that in the sense of removing the dependence &mdash; the seller&rsquo;s choice does depend on the buyer&rsquo;s, and Section 2 says so &mdash; but it is simpler in what the dependence is made of. Focal-point reasoning depends on salience, which is framing-dependent, attention-dependent, and contestable between two parties who see the situation differently. The bonded dependence is on a comparison of two certain amounts that either party can carry out and both will get the same answer to. Salience is replaced by arithmetic, and the participant does not have to guess which solution looks obvious to a stranger.
                </PaperRun>
                <PaperRun title="Interface cognition.">
                    Legibility must survive the interfaces through which participants meet the mechanism. At the moment of commitment a participant attends to four things: the goods or services being exchanged, the price, the bond posture &mdash; mechanically determined by the price and the value accumulated at the link &mdash; and the resolution path, which is the buyer&rsquo;s signature plus whatever terms the parties have composed. The invariants are not left to the participant&rsquo;s verification: the schedule produces <Math>{"2P"}</Math> and <Math>{"2G_i"}</Math> without being asked, only the buyer can resolve, and resolution takes the whole process or none of it. So the cognitive task reduces to the substantive commercial decision &mdash; is this exchange worth this price? &mdash; plus the bond-feasibility decision, whether the deposit is within what the wallet can post. Both are routine commercial judgements.
                </PaperRun>
                <p>
                    A participant in a platform-mediated arrangement is asked, in addition, to attend to the platform&rsquo;s terms of service, its complaint process, its reputation system, its payment timing, and its jurisdictional coverage &mdash; infrastructural verifications the platform delegates to the participant, with correspondingly higher load. The bonded architecture&rsquo;s load is structurally lower because its properties are enforced rather than verified: the mechanism&rsquo;s behavior is its terms, and it cannot depart from terms that are fixed and self-enforcing. The load shifts from infrastructural verification to substantive commercial decision-making, which is the right direction for a coordination architecture.
                </p>
                <PaperRun title="The runtime caveat.">
                    The counter-argument is that participants unfamiliar with key management, transaction submission, and fee estimation may be over-loaded by concerns belonging to the substrate the mechanism runs on rather than to the mechanism itself. The concern is real and the distinction is the answer to it: the comparison at a node is legible, and whether the interface presenting that node is legible is a separate question about the wallet, signing, and onboarding surfaces around it. The mechanism&rsquo;s legibility is a property of its payoffs; it is a necessary condition for a legible experience and not a sufficient one, and the surfaces are where the behavioral promises are kept or broken in practice.
                </PaperRun>
                <PaperRun title="Implications for adoption.">
                    A mechanism&rsquo;s adoption in a population is partly a function of how well that population can verify its equilibrium properties. An argument the participant cannot follow cannot be rationally trusted, however correct it is, so opacity costs adoption independently of soundness. The bonded mechanism&rsquo;s legibility is therefore not only behavioral robustness but adoption advantage: the participant can check the argument with the cognitive operations it performs routinely, on figures it can read before it signs.
                </PaperRun>
            </PaperSection>

            <PaperSection title="7. Conclusion">
                <p>
                    The mechanism&rsquo;s equilibrium argument survives its behavioral reading, and in two places the reading strengthens it. Because a defector is credited with what it retains, each node&rsquo;s two branches straddle the prospect-theoretic reference point instead of lying on one side of it: the buyer weighs a break-even against a loss and the seller a gain against a loss, so loss aversion weights the defecting branch alone rather than cancelling out of the comparison &mdash; and where a defector books its retained value and its locked bond apart, as their different locations invite, the retention is credited at gain-domain weight against a bond charged at loss-domain weight, and pays less than the netted figure suggests. The Van Huyck coordination failure addresses a condition this setting has, which we concede: where a co-seller has held out, holding out is strictly better than performing. What the setting lacks is the finality the experimental convergence runs on. Nothing is banked, so the belief-updating engine has no realized history and the cascaded profile reverses on the state rather than persisting on a belief; each seller&rsquo;s own exposure is arithmetic on public figures rather than a distribution over strangers; and every party in a standoff is paying, continuously and with no clock ending the payment, to hold a position it would rather close. The atomic-resolution externality gives every seller a computable interest in every other&rsquo;s performance, largest for the participant that has already performed, at stakes far above where the experimental literature finds social pressure activating &mdash; though the record makes the stake public and leaves the fault local, so applying the pressure to a particular failure still takes what the parties know. And the whole argument is checkable by a participant with one comparison of two certain amounts at its own node, in an order whose first step depends on nobody.
                </p>
                <p>
                    That last property deserves the final word, because the shape of the argument and its behavioral standing are the same fact. An equilibrium established by eliminating strategies in successive rounds would have rested on the depth of iterated reasoning the level-<Math>{"k"}</Math> literature finds participants do not reach; an equilibrium established by ordered node comparisons rests on the one step they reliably do. The mechanism is not optimal in any technical sense, and this paper makes no claim that it is. It is robust in the behavioral sense that it does not ask participants to do cognitive work they cannot reliably do, and it is legible in the sense that a participant can check for itself, on figures fixed before it signs, that the branch the mechanism wants it to take is the branch it wants to take. For any mechanism that aspires to operate among real participants at scale, those are the properties that decide the matter.
                </p>
            </PaperSection>
        </PaperLayout>
    );
}
