[package]
name = "figaro-prove-test"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "prove"
path = "src/main.rs"

[dependencies]
figaro-kernel = { path = "../lib" }
sp1-sdk = "6.0"
serde_json = "1"
alloy-primitives = { version = "0.8", features = ["serde"] }
k256 = { version = "0.13", features = ["ecdsa", "arithmetic"] }
tokio = { version = "1", features = ["full"] }

[build-dependencies]
sp1-build = "6.0"
