import type { Metadata } from "next";
import {
    PaperLayout,
    PaperSection,
    PaperSubsection,
    PaperRun,
} from "@/components/papers/PaperLayout";

export const metadata: Metadata = {
    title: "The Wallet as Legal Subject — Figaro Protocol",
    description:
        "Labor law classifies along one axis — subordination. A bonded settlement primitive makes subordination architecturally optional in a region of transactions, and there the classification problem loses its subject. The wallet collapses the Roman res/persona distinction.",
};

export default function WalletLegalSubjectPaper() {
    return (
        <PaperLayout slug="wallet-legal-subject"
            title="The Wallet as Legal Subject"
            subtitle="Subordination, Property, and the Dissolution of the Employee–Contractor Line"
            author="Figaro"
            date="April 2026"
            watermark="Figaro Protocol · Preprint"
            keywords="labor law, employee classification, gig economy, private government, subordination, legal subject, self-sovereign identity"
            abstract={
                <>
                    <p>
                        Labor law distinguishes employees from independent contractors along a single doctrinal axis: the degree of subordination the employer exercises over how the worker conducts themselves within the employer&rsquo;s system of processes and values. The axis is a continuum, the classification is a threshold placed somewhere on it, and the threshold is the perpetual subject of legislative and judicial contest &mdash; AB5 and Proposition 22 in California, <em>Uber BV v Aslam</em> in the United Kingdom, the 2024 EU Platform Work Directive. The cases are all the same case, relitigated in each jurisdiction against each new technology.
                    </p>
                    <p>
                        This paper argues that the bonded settlement primitive changes the doctrinal terrain by making subordination architecturally optional in a region of transactions. Within that region, the parties are bonded counterparties; there is no employment relation to classify. The wallet collapses a distinction the Roman legal tradition kept separate: <em>res</em> (property) and <em>persona</em> (legal party). Every productive asset is simultaneously property and party &mdash; self-owned rather than owned or rented. The claim is about necessity rather than possibility: where a relation remains employment-shaped in substance, or where a surrounding layer of discovery, dispatch, and reputation reproduces a platform&rsquo;s position over bonded counterparties, the existing doctrines reach it in the ordinary way.
                    </p>
                    <p>
                        We develop the argument in four moves. First, we locate subordination as the doctrinal variable in the long-running labor-classification debate, drawing on Anderson&rsquo;s analysis of the firm as private government (2017), Ellerman&rsquo;s argument that the employment contract renews the master&ndash;servant relation in softer form (1992), and Taleb&rsquo;s compressed version of the same point in <em>Skin in the Game</em> (2018). Second, we develop the paper&rsquo;s central legal move: the wallet as a legal subject whose Hohfeldian incidents (1913) are held together by a private key, which collapses the <em>res</em>/<em>persona</em> partition that the personhood literature after Naffine (2009) has kept separate. Third, we show that the gig-economy case law is a classification dispute whose ground narrows once subordination ceases to be architecturally required. Fourth, we name the trade-off: Figaro is a leveller on the subordination axis but simultaneously a privatizer of employment-attached protections (unemployment insurance, healthcare, pensions, collective bargaining). The levelling claim carries a limit we state here rather than at the end, because it bounds everything above it: bonding requires a stake, so the primitive levels only those who have one. A worker with no capital to bond is not freed by the substrate; what constrains them is not directional control but unequal access to the stake &mdash; a different asymmetry, which the primitive neither creates nor relieves &mdash; and how that access is distributed is, in our view, the most important policy question the primitive raises.
                    </p>
                </>
            }
            references={
                <>
                    <li>California State Legislature. Assembly Bill No. 5, Ch. 296, Stats. 2019 (codifying the ABC test for employee classification).</li>
                    <li>Anderson, E. <em>Private Government: How Employers Rule Our Lives (and Why We Don&rsquo;t Talk About It)</em>. Princeton University Press, 2017.</li>
                    <li><em>Autoclenz Ltd v Belcher</em>, [2011] UKSC 41.</li>
                    <li><em>Dynamex Operations West, Inc. v Superior Court</em>, 4 Cal.5th 903 (2018).</li>
                    <li>Ellerman, D. P. <em>Property and Contract in Economics: The Case for Economic Democracy</em>. Blackwell, Cambridge, MA, 1992.</li>
                    <li>European Parliament and Council. Directive (EU) 2024/2831 of 23 October 2024 on improving working conditions in platform work. <em>Official Journal of the European Union</em>, 2024.</li>
                    <li>California Proposition 22 (2020), codified at Cal. Bus. &amp; Prof. Code §§ 7448&ndash;7467.</li>
                    <li>Taleb, N. N. <em>Skin in the Game: Hidden Asymmetries in Daily Life</em>. Random House, New York, 2018 (Book 4, &ldquo;Wolves Among Dogs,&rdquo; Ch. 3, &ldquo;How to Legally Own Another Person&rdquo;).</li>
                    <li>Collins, H. Market Power, Bureaucratic Power, and the Contract of Employment. <em>Industrial Law Journal</em>, 15(1):1&ndash;14, 1986.</li>
                    <li>Deakin, S. The Changing Concept of the &lsquo;Employer&rsquo; in Labour Law. <em>Industrial Law Journal</em>, 30(1):72&ndash;84, 2001.</li>
                    <li>Deakin, S. &amp; Morris, G. S. <em>Labour Law</em>, 6th ed. Hart Publishing, Oxford, 2012.</li>
                    <li>Freedland, M. &amp; Kountouris, N. <em>The Legal Construction of Personal Work Relations</em>. Oxford University Press, 2011.</li>
                    <li>Fudge, J. The Legal Boundaries of the Employer, Precarious Workers, and Labour Protection. In G. Davidov &amp; B. Langille (eds.), <em>Boundaries and Frontiers of Labour Law</em>. Hart Publishing, Oxford, 2006.</li>
                    <li>Veitch, S. <em>Obligations: New Trajectories in Law</em>. Routledge, Abingdon, 2021.</li>
                    <li>Hohfeld, W. N. Some Fundamental Legal Conceptions as Applied in Judicial Reasoning. <em>Yale Law Journal</em>, 23(1):16&ndash;59, 1913.</li>
                    <li>Naffine, N. <em>Law&rsquo;s Meaning of Life: Philosophy, Religion, Darwin and the Legal Person</em>. Hart Publishing, Oxford, 2009.</li>
                    <li>Bayern, S. Of Bitcoins, Independently Wealthy Software, and the Zero-Member LLC. <em>Northwestern University Law Review</em>, 108:1485&ndash;1500, 2014.</li>
                    <li>LoPucki, L. M. Algorithmic Entities. <em>Washington University Law Review</em>, 95:887&ndash;953, 2018.</li>
                    <li>Fairfield, J. A. T. <em>Owned: Property, Privacy, and the New Digital Serfdom</em>. Cambridge University Press, 2017.</li>
                    <li>Pasquale, F. <em>The Black Box Society: The Secret Algorithms That Control Money and Information</em>. Harvard University Press, Cambridge, MA, 2015.</li>
                    <li><em>Uber BV and others v Aslam and others</em>, [2021] UKSC 5.</li>
                </>
            }
        >
            <PaperSection title="1. Introduction">
                <p>
                    Labor law, across every jurisdiction that has one, answers a recurring question: is this person an employee or an independent contractor? The answer matters because the two categories attract radically different legal consequences &mdash; minimum wage, overtime, unemployment insurance, employer health-insurance obligations, workers&rsquo; compensation, collective-bargaining rights, anti-discrimination protections, tax treatment, pension eligibility. The classification test varies by jurisdiction, but all tests converge on a common underlying variable: the degree to which the putative employer directs and controls the putative employee&rsquo;s work &mdash; their schedule, their tools, their processes, their supervision, their ability to work for others.
                </p>
                <p>
                    We will call this variable <em>subordination</em>, following the usage common in Continental labor-law scholarship and in the political-economy tradition we return to in Section 2. Subordination is a continuum; the employee&ndash;contractor line is a threshold placed somewhere on it; and the location of the threshold is the perpetual subject of doctrinal and political contest.
                </p>
                <p>
                    The gig economy made the contest legible. Drivers, couriers, and platform freelancers occupy a region of the subordination continuum the existing legal categories were not designed for: loosely supervised by algorithm, nominally free to refuse work, economically dependent on the platform nonetheless. Jurisdictions have responded with increasingly granular tests. California&rsquo;s Assembly Bill 5 (2019) codified the ABC test, pushing many gig workers toward employee status; Proposition 22 (2020) carved out an exception for app-based rideshare and delivery drivers. The UK Supreme Court in <em>Uber BV v Aslam</em> (2021) classified drivers as &ldquo;workers&rdquo; &mdash; a third category intermediate between employee and contractor &mdash; on subordination grounds. The EU Platform Work Directive (Directive (EU) 2024/2831) established a presumption of employment for platform workers meeting specified control indicators.
                </p>
                <p>
                    Each of these cases and statutes is, at root, an attempt to draw the same line differently. The line itself is what the cases cannot dispense with.
                </p>
                <PaperRun title="The argument of this paper.">
                    We argue that the bonded settlement primitive changes the question. When every party to a productive exchange is a bonded counterparty &mdash; signing commitments under their own key, posting a bond against their own performance, receiving settlement directly to their own wallet &mdash; there is no employment relation to classify. In the region of transactions where that structure is available and chosen, the classification problem has no subject: the employee&ndash;contractor line is not redrawn; it finds no relation to draw.
                </PaperRun>
                <PaperRun title="What this paper is not.">
                    This paper does not provide legal advice. It does not argue that labor law should be abolished. It does not argue that employment-attached protections are undesirable. It does not predict that the bonded primitive will displace employment as the dominant coordination form, and does not endorse any particular outcome of the classification it dissolves. Its argument is diagnostic: the primitive changes the doctrinal terrain, and legal scholarship should understand that change independently of any normative conclusion one might draw from it.
                </PaperRun>
                <PaperRun title="Paper organization.">
                    Section 2 develops subordination as the labor-law variable, drawing on Anderson, Ellerman, and Taleb. Section 3 summarizes the settlement primitive in the terms relevant here. Section 4 develops the central legal move: the wallet as a legal subject that collapses the classical <em>res</em>/<em>persona</em> distinction. Section 5 re-reads the gig-economy case law through that lens. Section 6 names the leveller/privatizer trade-off. Section 7 concludes.
                </PaperRun>
            </PaperSection>

            <PaperSection title="2. Subordination as the Labor-Law Variable">
                <PaperSubsection title="2.1 The Doctrinal Test">
                    <p>Every mature labor-law regime operationalizes the employee&ndash;contractor distinction through a control-flavored test. The details vary:</p>
                    <ul className="list-disc pl-6 space-y-2">
                        <li>The IRS twenty-factor test in the United States examines behavioral control, financial control, and the nature of the relationship.</li>
                        <li>California&rsquo;s ABC test, codified in AB5, places the burden on the hiring entity to show that the worker (A) is free from control and direction, (B) performs work outside the hiring entity&rsquo;s usual business, and (C) is customarily engaged in an independently established trade.</li>
                        <li>UK jurisprudence, following <em>Autoclenz</em> (2011) and refined in <em>Aslam</em>, examines the reality of the working arrangement rather than its contractual label, focusing on personal service, mutuality of obligation, and control.</li>
                        <li>Continental systems (France, Germany, Italy) distinguish <em>travail salarié</em>, <em>abhängige Arbeit</em>, <em>lavoro subordinato</em> respectively, anchoring the status on <em>subordination juridique</em> &mdash; the juridical subordination of the worker to the employer&rsquo;s directive power.</li>
                    </ul>
                    <p>
                        The tests differ in which facts they weight and in whether the burden sits on the worker or the employer. They agree on what the variable is. Control, direction, supervision, integration into the employer&rsquo;s processes &mdash; these are all labels for the same underlying relationship: subordination of the worker&rsquo;s conduct to the employer&rsquo;s authority, in exchange for a wage.
                    </p>
                    <PaperRun title="Where the labor-law literature has located subordination.">
                        The point is not original to the present paper. Collins (1986) argued that the contract of employment is a legal construction that aligns ordinary contract principles with the operational reality of subordinated work, and that the construction is contingent on the firm-shaped container within which most employment historically takes place. Deakin (2001; Deakin &amp; Morris, 2012) traces the contract of employment as a legal construct that emerged in response to nineteenth-century factory production, with subordination as its constitutive marker rather than its incidental feature. Freedland &amp; Kountouris (2011) extend the analysis with their <em>personal work nexus</em> framework, which treats personal-service relationships as a continuous category that the employee/contractor binary partitions imperfectly. Fudge (2006) examines the boundary problem from the labor-protection side: as platform work and other &ldquo;new forms of personal work&rdquo; proliferate, the binary partition produces increasing classification arbitrariness, and the response of regulators has been to extend protections by status (presumption rules, minimum-protection floors) rather than to revise the partition itself. Veitch (2021) takes the political-philosophical step further: subordination is itself a relation of asymmetric obligation that requires its own justification, and the consent supplied by the employment contract is conditioned on the absence of viable alternatives that could supply equivalent income without the subordination overlay.
                    </PaperRun>
                    <p>
                        The present argument enters this literature with a structural move it has not had occasion to make: it asks what the doctrinal test does when the firm-shaped container itself becomes economically optional in a region of transactions. The answer below is that the test does not so much fail as run out of applicants: it asks a question that has no party to be its subject when the parties to a transaction are bonded counterparties rather than employer and employee.
                    </p>
                </PaperSubsection>
                <PaperSubsection title="2.2 The Philosophical Position">
                    <p>
                        A scholarly tradition with roots in classical liberalism and in Marx, refreshed more recently by legal and political philosophers, reads the employment relationship as lying on the same continuum as older forms of property-in-persons. We summarize three representative positions.
                    </p>
                    <PaperRun title="Ellerman: the firm as rent-a-person.">
                        Ellerman (1992) argues that the employment contract is not merely economically one-sided but ontologically incoherent: it attempts to rent <em>persona</em> (the worker as legal party) on the same terms as <em>res</em> (the worker&rsquo;s labor power as object). In ordinary jurisprudence, persons cannot be rented &mdash; a doctrine that predates and survived the legal abolition of chattel slavery. The employment contract, Ellerman argues, honors the formal doctrine by contracting for labor power rather than the person, but the substance of the relation (subordination of the worker&rsquo;s conduct to another&rsquo;s authority for a defined period) exercises the same operative control. The argument is philosophical rather than legal, but it names a tension that labor law operationalizes as the employee/contractor test.
                    </PaperRun>
                    <PaperRun title="Anderson: the firm as private government.">
                        Anderson (2017) makes the complementary argument at the level of political theory. Firms exercise governmental powers over employees &mdash; mandatory schedules, speech restrictions, body surveillance, drug testing, arbitrary dismissal &mdash; that are constitutionally proscribed when exercised by the state. American political vocabulary, Anderson argues, has no term for this because the liberal tradition&rsquo;s attention to state power left the authoritarian structure of the workplace unanalyzed. The firm is a private government, and the employment relation is the governance relation within it.
                    </PaperRun>
                    <p>
                        The structural observation common to Ellerman and Anderson &mdash; that the employment relation places one party&rsquo;s conduct under another party&rsquo;s authority along an axis whose endpoints touch historical arrangements of chattel and serfdom &mdash; has currency outside academic labor philosophy as well: Taleb (2018), in the chapter &ldquo;How to Legally Own Another Person,&rdquo; makes the same point in blunter terms, describing the ordinary employment relation as a modern, softened descendant of outright ownership of a person&rsquo;s labor. The observation, however framed, is that the axis is subordination; the differences between historical arrangements at different points on it are quantitative.
                    </p>
                    <PaperRun title="Subordination in two registers.">
                        The doctrinal test and the philosophical treatment just given describe the same relationship from two disciplinary vantages. The doctrinal register is direction-and-control: does the putative employer specify schedule, tools, processes, supervision, ability to work for others? The register Ellerman and Anderson supply is property-in-persons: does the arrangement place the worker&rsquo;s conduct at another party&rsquo;s disposal for a period, so that what is contracted for is handled as a thing hired rather than as a party dealt with? These are not competing definitions. The direction-and-control test is the <em>operational</em> face of subordination &mdash; what a court observes when assessing the relation. Property-in-persons is its <em>structural</em> face &mdash; what the arrangement does to the worker&rsquo;s standing as a party while it runs. The two converge: a relation with high directional control is one in which the worker&rsquo;s conduct has been placed at another&rsquo;s disposal, and a relation in which it has not is one of low directional control. The primitive reaches both faces at once because they are faces of the same thing, and Section 4 says why: it removes the construct by which one party&rsquo;s conduct is placed at another&rsquo;s disposal at all.
                    </PaperRun>
                </PaperSubsection>
                <PaperSubsection title="2.3 Why the Threshold Keeps Moving">
                    <p>
                        Once subordination is recognized as the variable and the employee&ndash;contractor line as a threshold placed on it, the perpetual legal contest becomes explicable. The threshold has no principled location. Any specific test produces a bright line through a continuum, and whichever side of the line a given working arrangement falls on becomes the object of rent-seeking effort by the party for whom that side is cheaper.
                    </p>
                    <ul className="list-disc pl-6 space-y-2">
                        <li>Employers push the threshold upward: reclassifying employees as contractors reduces payroll taxes, avoids benefits-attachment, eliminates collective-bargaining obligations, and removes discrimination-law exposure. Every major gig-economy platform has been the subject of litigation on this point.</li>
                        <li>Workers with bargaining power push the threshold downward: reclassification as employees unlocks minimum-wage protections, overtime, employer-funded health insurance, unemployment eligibility, and union rights. Much of AB5 was a legislative response to this pressure.</li>
                    </ul>
                    <p>
                        The threshold is not &ldquo;wrong&rdquo;; it is <em>under-specified</em>. The underlying continuum has no natural joint. As technologies of remote direction (apps, algorithms, performance dashboards) evolve, the reality of the control relation changes faster than the law can locate the threshold, which is why gig-economy cases recur across jurisdictions with broadly similar facts and broadly divergent outcomes.
                    </p>
                </PaperSubsection>
            </PaperSection>

            <PaperSection title="3. The Settlement Primitive">
                <p>
                    We treat the settlement primitive as a black box and summarize only the features the legal argument uses.
                </p>
                <p>
                    The primitive has two calls, and each carries a mechanism design of its own. <em>Commit</em> forms a bilateral edge between the buyer and one seller under <em>asymmetric bonding</em>: both parties sign, and each locks a bond against its own performance &mdash; the buyer twice the payment it has promised, the seller twice the value the process has accumulated through its own link, that seller&rsquo;s own payment included. The accumulated figure is fixed by arithmetic on the signed record rather than reported by anyone. <em>Resolve</em> closes the process under <em>buyer dominance with atomic resolution</em>: only the buyer may call it, it settles every active order at once or none, and it is terminal. The two calls compose in a definite order, and the equilibrium is read in that order. After performance, resolving is unconditionally strictly better for the buyer than never resolving &mdash; a comparison that needs no assumption whatever about the seller, since the payment a withholding buyer keeps back sits frozen inside its own bond and buys it nothing. Given that, performance is each seller&rsquo;s strict best response: performing and being settled returns its bond along with its payment, whereas holding out leaves it credited with everything it retains and still out of pocket by the value at its link.
                </p>
                <PaperRun title="What the primitive holds, and what it cannot see.">
                    The work, the goods, every passage of value between the parties, and the parties&rsquo; own knowledge of all of it happen off the record, where the mechanism can neither observe them nor undo them. What the mechanism holds is the bonds, the signed accumulator, and the record of what was committed to: it shows what was undertaken and what remains unsettled, and never that anyone performed. The deterrent is stated on that boundary rather than across it. A party that defects does not walk away empty &mdash; it walks away holding the value at its link &mdash; and the schedule answers by locking twice that value, so that crediting the defector with everything it keeps still leaves the defection self-destructive. That is mutual assured destruction with content, and it is why nothing in the mechanism ever needs to execute it: no operation consumes a bond, and the standoff a defection would create is one both parties strictly prefer to end by completing the exchange.
                </PaperRun>
                <PaperRun title="Bonded counterparties.">
                    A transaction between two parties is consummated by commitments cryptographically signed by both, each party signing from its own wallet. There is no platform between the parties, no arbitrator authorized to release a bonded position, and no admin key permitting external override. Three features of that arrangement carry the argument below. First, no party&rsquo;s conduct is directed by any other: the mechanism reads a signature and a balance, and knows nothing else about who signed. Second, buyer dominance is a <em>right of resolution</em>, not a directive authority &mdash; the buyer decides whether the process closes, and decides nothing about how anybody performs. Third, a many-party workflow clears from that single signature rather than from an organizing nucleus that must hold the parties together, because each seller&rsquo;s bond is keyed to the value accumulated at its own link and no seller is paid until the buyer&rsquo;s one all-or-nothing resolution &mdash; which a buyer resolving only when satisfied withholds until every seller has performed. The first of those is the mechanism&rsquo;s own rule; the second is what a rational buyer does with it, and the distinction matters because the mechanism knows nothing of performance and gates nothing on it. The labor-law argument depends on all three: without the bonding schedule the counterparties would need an enforcer, and without the resolution rule the multi-party workflow would still need a nucleus to clear all parties simultaneously &mdash; a nucleus that would inherit the subordination apparatus the primitive is supposed to retire.
                </PaperRun>
                <PaperRun title="Where disagreements go.">
                    The mechanism holds no test of performance and admits no report of one; the buyer&rsquo;s resolution <em>is</em> its acceptance. Where the parties disagree about whether performance met the agreement, they negotiate a remedy while the process stands open &mdash; concretely, a seller that cannot perform sends the buyer the payment it stands to receive, so that resolution leaves it holding its bond and nothing else, and the buyer whole &mdash; and the buyer resolves once satisfied. An external forum may rule on the open record and on whatever the parties bring it, and its ruling feeds their negotiation; what it cannot do is call resolve in the buyer&rsquo;s place. It is that absence of direct enforcement, rather than any question of timing, that keeps a forum off the path by which bonds are released. Resolution is terminal acceptance: once the buyer resolves, the mechanism holds nothing further for anyone to recover.
                </PaperRun>
                <PaperRun title="What the primitive does not require.">
                    No employment relation, no subcontractor hierarchy, no master&ndash;servant agreement, no W-9 or W-2, no 1099 or P-60, no PAYE code, no <em>contrat de travail</em>. The primitive operates on parties as parties: each is a wallet address bonded against performance for a specified exchange. The direction-and-control relation that labor-law categories turn on does not exist at the primitive layer; it is replaced by the direction given by the off-chain agreement both parties sign and the bond that backs their mutual performance.
                </PaperRun>
            </PaperSection>

            <PaperSection title="4. The Wallet as Legal Subject">
                <p>
                    Roman private law distinguished <em>res</em> (things, property, objects that can be owned and alienated) from <em>persona</em> (persons, parties, subjects capable of acting legally). The distinction survived and structures modern private law: physical assets are <em>res</em>; natural persons and recognized legal persons (corporations, states, partnerships) are <em>personae</em>; the two interact through contracts of sale, lease, license, and labor.
                </p>
                <p>
                    The employment contract sits awkwardly in this structure. A worker is unambiguously a <em>persona</em>, but the employment contract treats the worker&rsquo;s labor power as <em>res</em> &mdash; a resource rented from the worker for a specified period, under the employer&rsquo;s direction. Ellerman&rsquo;s argument is that this treatment is operationally coherent only because the legal tradition has learned to overlook the <em>persona</em>/<em>res</em> boundary in this one setting. Every labor-law test for employee status is implicitly an attempt to police that boundary without naming it.
                </p>
                <PaperRun title="The wallet as collapse.">
                    A wallet in the Figaro architecture is a legal artifact that does not fit the classical categories. It is a property &mdash; a cryptographic key-pair that its holder owns and can transfer or abandon. It is simultaneously a party &mdash; it signs commitments, posts bonds, receives settlements, accrues an attestation history, and generates an evidence record that off-chain adjudication can consume. The wallet is the productive asset acting in its own legal name. The collapse is not metaphorical. When the party to a commitment is the wallet itself (whether operated by a natural person, a software agent, or an organizational treasury), the classical <em>persona</em>/<em>res</em> partition no longer partitions. The wallet is what it controls and it controls what it is.
                </PaperRun>
                <PaperRun title="The Hohfeldian reading.">
                    The collapse is easier to see in Hohfeldian than in Roman terms. Hohfeld (1913) disaggregated the omnibus concept of a &ldquo;right&rdquo; into four jural correlatives: right/duty, privilege/no-right, power/liability, and immunity/disability. Ownership in the property-rights tradition is a bundle of Hohfeldian incidents allocated by some legal arrangement. What the wallet in the bonded primitive holds is precisely a Hohfeldian bundle keyed to its private key: the power to enter signed commitments (with the correlative liability of the counterparty&rsquo;s settlement obligation), the right to receive its settlement payoff on resolution, the privilege of not committing, and the immunity from external override (no third party can rewrite an executed resolution; this is a Hohfeldian immunity in the strong sense). The Roman <em>persona</em>/<em>res</em> distinction is doing rough work that the Hohfeldian apparatus sharpens: the wallet is not a <em>persona</em> acting on <em>res</em>, but a Hohfeldian <em>position</em> whose incidents are held together by the cryptographic key.
                </PaperRun>
                <p>
                    The personhood literature tracks the move. Naffine (2009) taxonomizes legal personhood into three registers (P1: capacity to bear rights; P2: rational agency; P3: moral personhood); the wallet sits unambiguously in P1, contingently in P2 (depending on whether a human, an agent, or a treasury operates it), and is silent on P3 (which the primitive does not address and the off-chain forum inherits). Bayern (2014) and LoPucki (2018) have argued separately that algorithmic entities can be made to fit existing personhood doctrine through LLC-style legal scaffolding, and Fairfield (2017) has examined property-in-data and property-in-code as a related doctrinal frontier; Pasquale (2015) treats algorithmic personhood from the opacity-and-accountability side. The wallet collapses the constructs the personhood literature has been keeping separate &mdash; it is a P1 holder of Hohfeldian incidents whose operator may or may not be a P2 agent and whose moral status is a separate question.
                </p>
                <PaperRun title="Four consequences.">
                    These follow from the architecture of dual-signed bonded commitments settled directly between parties:
                </PaperRun>
                <ol className="list-[lower-alpha] pl-6 space-y-3">
                    <li><strong>Self-control is the default.</strong> A wallet cannot be <em>owned</em> by another wallet the way a <em>res</em> can be owned by a <em>persona</em>. What passes on a transfer is the key, and the key holds the Hohfeldian bundle together: the power to commit, the right to the settlement payoff, and the immunity from override move as one, to one holder. There is accordingly no arrangement in which one party retains the incidents of ownership while another supplies the conduct &mdash; which is precisely the arrangement the labor-law test was built to police.</li>
                    <li><strong>No rental of persona.</strong> A commitment between two wallets bonds each wallet&rsquo;s performance directly. There is no construct in which one wallet&rsquo;s persona is rented to another for a defined period; each party signs for themselves, commitment-by-commitment.</li>
                    <li><strong>Attestation is self-attached.</strong> Attestations and profile records attach to the wallet itself, and richer deeds and attestations can be layered on top. A worker&rsquo;s skills, certifications, and performance history travel with the wallet, not with the employer. The resume becomes the wallet; the reference becomes an attestation.</li>
                    <li><strong>No employer-held record.</strong> The record of what the wallet undertook, what it settled, and what it was paid is constituted by the protocol rather than kept by an employer, so the informational asymmetry that employer-held personnel and payroll records create has no place to live.</li>
                </ol>
            </PaperSection>

            <PaperSection title="5. The Gig-Economy Cases, Re-read">
                <p>
                    The gig-economy case law can be read as a series of attempts to place the employee&ndash;contractor threshold in the face of a technology (the platform) that had engineered a new position on the subordination continuum. Re-read through the primitive&rsquo;s lens, four landmark measures share a fate within the region where a bonded relation is genuinely, not merely nominally, structured as one: each one&rsquo;s operative test loses its subject. The qualification is not decorative &mdash; a bonded counterparty who in substance still works a single schedule for a single buyer under buyer-dictated flow control remains reachable by the corresponding doctrine, for the reasons given after the list.
                </p>
                <ul className="list-disc pl-6 space-y-2">
                    <li><strong>California AB5 (2019)</strong>, codifying the ABC test from <em>Dynamex Operations West v Superior Court</em> (2018): none of the three prongs is well-posed for a bonded relation that is substantively, not just formally, bonded. There is no hiring entity to direct and control (prong A has no subject), no usual course of business for the bonded counterparty relation (prong B presupposes a firm), and the bonded party is by construction independently established (prong C is satisfied by default).</li>
                    <li><strong>Proposition 22 (2020)</strong>: the statutory carve-out for app-based drivers is unnecessary because the category it carves out of does not apply. The question it tries to answer &mdash; minimum earnings and healthcare outside the employment relation &mdash; is the leveller/privatizer trade-off of Section 6.</li>
                    <li><strong><em>Uber BV v Aslam</em> (UKSC 2021)</strong>: the substance-over-label examination that classified drivers as <em>workers</em> has no entity whose substance can be examined when the substance itself has changed &mdash; when settlement runs commitment-by-commitment to a wallet the worker controls rather than through a rating-and-algorithmic-direction apparatus. Where that apparatus is reproduced in a surrounding layer built on top of the primitive (see below), the <em>Aslam</em> analysis regains its subject and reaches it in the ordinary way.</li>
                    <li><strong>EU Platform Work Directive (2024)</strong>, the most sophisticated of the four, with a presumption of employment rather than a bright-line test: the presumption criteria (algorithmic management, supervision of work, restrictions on working for others) have no referent at the settlement layer itself &mdash; there is no platform between the bonded parties whose algorithmic management would trigger the presumption, though an intermediary reintroducing that management above the settlement layer remains squarely within the Directive&rsquo;s presumption.</li>
                </ul>
                <PaperRun title="Scope of the re-reading.">
                    Two qualifications bound all four readings, and we state them together rather than as sequential retreats. First, the doctrines above were built to reach behind contractual labels to operational reality, and they still do: a bonded counterparty who performs forty hours a week for a single buyer on a buyer-dictated schedule, with rating-driven flow control producing economic dependence, is not rescued from substance-over-form analysis merely because the commitments are denominated as bonded orders rather than as an employment contract. What the primitive changes is the choice set available to structure a productive relationship, not the doctrine&rsquo;s reach within any relationship that remains, in substance, employment-shaped. Second, the settlement layer&rsquo;s freedom from direction-and-control does not extend automatically to the layers built on top of it &mdash; discoverability, dispatch, reputation aggregation, credit provision, identity vouching, key custody. An intermediary supplying those layers at scale can recreate a platform&rsquo;s economic position relative to the bonded counterparties beneath it, and the substance-over-form doctrines will have exactly the purchase against that intermediary that they have against existing platforms today. The architectural claim is therefore narrower than &ldquo;subordination is impossible&rdquo;: subordination is no longer architecturally required at settlement, and where it reappears it appears as a choice made in a surrounding layer the existing labor-law apparatus is well-equipped to evaluate.
                </PaperRun>
            </PaperSection>

            <PaperSection title="6. Leveller and Privatizer">
                <p>
                    The primitive is, in one register, a leveller. It eliminates a structural asymmetry in labor markets: the subordination gradient between employer and employee. The bond schedule is asymmetric in <em>magnitude</em> &mdash; a seller bonds against the value the process has accumulated at its link, the buyer against the payment it owes &mdash; and symmetric in <em>kind</em>: every party bonds against its own performance and none against another&rsquo;s, every party signs from its own wallet, and no party is rented as <em>persona</em>. It is the symmetry of kind that does the levelling, and the two senses should not be run together.
                </p>
                <p>
                    The primitive is, in another register, a privatizer. The protections labor law built around the employment relation &mdash; employer-funded healthcare, employer-paid payroll taxes feeding unemployment insurance, employer pension contributions, workplace-safety inspections tied to employer status, collective bargaining structured around bargaining units within firms &mdash; are all attached to the category that the primitive removes. When employment is not the container, employment-attached protections are not delivered.
                </p>
                <p>
                    One scope condition is adopted rather than argued here: the argument presumes transactions of low asset specificity, for which a bonded bilateral relation is an adequate substitute for standing hierarchical coordination &mdash; the institutional-economics threshold analysis behind that presumption is another treatment&rsquo;s subject, and this paper takes only its conclusion.
                </p>
                <PaperRun title="Four options for the political response.">
                    We name them so the trade-off is legible:
                </PaperRun>
                <ol className="list-[lower-roman] pl-6 space-y-3">
                    <li><strong>Attach protections to the wallet.</strong> Health insurance, pension contributions, income protection become benefits that the wallet itself purchases from portable providers, priced per unit of bonded activity. This is the direction Prop 22 gestured at, without the AB5 backdrop making it necessary.</li>
                    <li><strong>Attach protections to citizenship.</strong> Universal basic income, single-payer healthcare, state-funded unemployment assistance &mdash; all decouple protection from employment and re-couple it to polity membership. The social-democratic tradition has advocated this independently of Figaro; the primitive removes one historical argument against the decoupling (that employment was the natural locus because that is where most people spend most of their time).</li>
                    <li><strong>Preserve the employment option.</strong> Nothing in the primitive prevents the employment relation from continuing to exist. Firms can hire employees, employees can bargain collectively, labor law can continue to regulate the subordination region. The primitive coexists with the employment relation rather than abolishing it. The question is what fraction of productive activity moves out of that region, and at what rate.</li>
                    <li><strong>Treat employment as the residual.</strong> Employment continues to apply wherever hierarchical coordination retains its advantage, and labor-law protections continue to attach to that residual domain; the primitive competes only where employment was a response to the cost of enforcing agreements rather than to the demands of the activity itself.</li>
                </ol>
                <p>
                    The trade-off is real: each of (i)&ndash;(iv) has different distributive consequences, and the fight over which one dominates will occupy the political economy of the next several decades regardless of how the primitive diffuses. What the primitive changes is that the fight becomes explicit: the attachment of protections to employment was a historical contingency that looked like a natural fact; once the category is removable, the attachment becomes a policy choice.
                </p>
                <PaperRun title="Voluntary participation as a scope condition.">
                    The mechanism&rsquo;s equilibrium results hold on the assumption of agency and a stake alone &mdash; that each party can choose its own actions and controls a stake sufficient to post the bond. The results are jurisdiction-invariant: they invoke no legal freedom, status, or standing, only the ability to sign and to bond. For a labor-law analysis the stake half of that assumption is load-bearing in a way it is not for the mechanism analysis itself. A worker whose only realistic income path runs through bonded assemblies, and who lacks access to a stake, faces a choice set that is not substantively voluntary in the sense the equilibrium argument presupposes. Such a worker is not freed by the substrate change. What constrains them is not subordination in the doctrinal sense this paper has used throughout &mdash; nobody is directing their conduct &mdash; but a different asymmetry entirely: unequal access to the stake, which the primitive neither creates nor relieves. Levelling the first asymmetry does nothing to the second, and equal terms of participation are not equal ability to participate.
                </PaperRun>
                <p>
                    The leveller register therefore applies fully only to the participants for whom the bonding option is substantively available &mdash; and how that availability is itself distributed is, in our view, the most important policy question the primitive raises. Of the four options above, (ii) addresses the access asymmetry directly by uncoupling productive participation from social-protection access; (i) and (iii) leave the asymmetry where the historical employment relation left it and propose that the bonded counterparty purchase protections from earnings; (iv) treats the region where hierarchy retains its advantage as the residual-employment region and lets the protections follow it. The choice among them is the question on which the leveller-versus-privatizer reading ultimately turns.
                </p>
            </PaperSection>

            <PaperSection title="7. Conclusion">
                <p>
                    Labor law has treated subordination as an axis on which to place threshold after threshold, in each jurisdiction against each technology. The bonded settlement primitive does not move the threshold; it makes subordination architecturally optional in a region of transactions. Within that region, the employee&ndash;contractor line, the platform-worker line, the <em>worker</em> category, the <em>subordonné</em> test &mdash; all of which presuppose a directional control relation between two parties &mdash; find no relation to classify. The classification problem has lost its subject. The qualification travels with the claim, and it is a qualification about necessity rather than possibility: where a relation remains employment-shaped in substance, or where a surrounding layer of discovery, dispatch, reputation, or key custody reproduces a platform&rsquo;s position over the bonded counterparties beneath it, the substance-over-form doctrines reach it exactly as they reach existing platforms. And the levelling extends only to those who control a stake; unequal access to that stake is an asymmetry of a different kind, which the primitive leaves untouched.
                </p>
                <PaperRun title="A note on vocabulary.">
                    The vocabulary of &ldquo;subordination&rdquo; and &ldquo;slavery,&rdquo; borrowed from Anderson and Ellerman, is structural rather than moral: modern labor law has developed substantial protections that distinguish the employee from the serf and the serf from the slave, and the primitive removes the arrangement, not the moral progress the arrangement&rsquo;s softening represented. Whether the removal is desirable is the policy question named in Section 6; whether it is happening is an engineering one; the two should not be conflated. Legal scholarship will be better served by engaging the primitive on its own terms than by treating it as one more gig-economy platform to be reclassified under the existing test.
                </PaperRun>
            </PaperSection>
        </PaperLayout>
    );
}
