import type { Metadata } from "next";
import { withOg } from "@/lib/shared/pageMetadata";
import {
    PaperLayout,
    PaperSection,
    PaperSubsection,
    PaperRun,
    PaperRemark,
} from "@/components/papers/PaperLayout";
import { Math } from "@/components/papers/Math";

export const metadata: Metadata = withOg({
    title: "External Events and the Settlement Frame — Figaro Protocol",
    description:
        "Everything the world does between a process's commit calls and its buyer's resolve call — a cargo resold in transit, a partial loss, a seller that cannot perform, a forum's ruling, a change of mind — meets one rule: the parties square it before the terminal call. A netting-completeness result makes the rule exact: a fixed settlement schedule plus free pre-resolve transfers among the parties reaches any reallocation of the committed value, self-enforcing up to each party's own standing exposure, because the bonds stay deposited throughout the negotiation. The frame is deterministic and keeps exactly one discretionary act.",
});

function FormalBlock({ label, children }: { label: string; children: React.ReactNode }) {
    return (
        <div className="border-l-2 border-default pl-6 my-3 space-y-3">
            <p className="text-sm font-semibold text-ink-heading">{label}</p>
            {children}
        </div>
    );
}

function Proof({ children }: { children: React.ReactNode }) {
    return (
        <div className="my-3 space-y-3 text-ink-body">
            <p>
                <span className="italic text-ink-muted">Proof. </span>
                {children}
            </p>
        </div>
    );
}

export default function ExternalEventsPaper() {
    return (
        <PaperLayout slug="external-events"
            title="External Events and the Settlement Frame"
            subtitle="One Rule for Everything the World Does Between the Two Calls"
            author="Figaro"
            date="September 2026"
            watermark="Figaro Protocol · Preprint"
            abstract={
                <>
                    <p>
                        A bonded settlement mechanism has two calls, and they bracket an open interval. <em>Commit</em> freezes a deterministic settlement schedule: every amount the mechanism will ever move is fixed by the signatures, and no elapsed time changes any of them. <em>Resolve</em> is one named party&rsquo;s discretionary terminal acceptance, available at any moment and compelled at none. Between the two, the world goes on. A cargo is resold in transit; part of a shipment is damaged; a seller finds it cannot perform; a forum rules on an open disagreement; the parties simply change their minds. We call any such occurrence an <em>external event</em>, defined not by what it is but by what it does &mdash; it changes what the parties want the settlement of this process to be. The mechanism&rsquo;s answer to every one of them is a single sentence: the parties square it before the terminal call.
                    </p>
                    <p>
                        We make that sentence exact. The committed schedule is a point; the transfers the parties may make among themselves while the process stands open are free; and the reachable set is the whole zero-sum hyperplane through that point, attained with at most one transfer per order (Proposition 1). No transfer touches a bond, an accumulator, or the schedule, and any transfer already made is common to both branches of the buyer&rsquo;s terminal comparison, so resolving remains strictly better after performance whatever the parties have moved between them (Proposition 2). What makes the renegotiated allocation credible is the posture that made the original one credible: every bond stays deposited throughout the negotiation, so a seller executes an agreed transfer up to its own standing exposure, below <Math>{"P_i + 2G_i - r_i"}</Math> with record-computable floor <Math>{"\\Delta_i = P_i + G_i"}</Math> (Proposition 3). That result has one side, and we say so. A buyer holding performance may refuse a transfer and resolve anyway, so the frame secures the seller-outbound transfers &mdash; the ones a remedy from the party at fault is made of &mdash; and leaves the buyer&rsquo;s part to the ordinary commercial reason for making it and to the recourse that reaches any party through its exposure outside the process; the asymmetry is the mechanism&rsquo;s own shape rather than a gap in it. What the frame does price on the buyer&rsquo;s side is the terminal call itself: a buyer that never makes it does not keep the payments it withholds &mdash; they sit inside its own bond at <Math>{"-\\sum_i P_i"}</Math>, where neither it nor any seller nor any forum can reach them. The bounds are equally exact: one denomination, the parties only, balances actually held, and &mdash; the load-bearing one &mdash; the frame can execute any agreement and produce none. Agreement is the parties&rsquo; discretion, and the frame never absorbs it.
                    </p>
                    <p>
                        Cargo resale in transit is the worked instance: title moves under an instrument the mechanism has never heard of, no position is transferred and no party substituted, the sellers whose legs are paid outside return their committed payments before the terminal call, one resolution settles the schedule atomically, and the pre-paid legs net to zero inside it. Two consequences close the argument. The designer&rsquo;s choice of order granularity fixes the exposure topology under which every such negotiation happens, and is therefore a design variable of the bargaining and not only of the work. And a substrate that adjudicated events instead would need an event taxonomy and a decision procedure per entry &mdash; a small world in Savage&rsquo;s sense, whose pruned branches the decision-science record says are not recovered by its catch-all. A frame that freezes the arithmetic and keeps one discretionary act absorbs events it has never heard of, which is the only class large enough to matter.
                    </p>
                </>
            }
            references={
                <>
                    <li>Bernstein, L. Opting Out of the Legal System: Extralegal Contractual Relations in the Diamond Industry. <em>Journal of Legal Studies</em>, 21(1):115&ndash;157, 1992.</li>
                    <li>Coase, R. H. The Problem of Social Cost. <em>Journal of Law and Economics</em>, 3:1&ndash;44, 1960.</li>
                    <li>Ellickson, R. C. <em>Order Without Law: How Neighbors Settle Disputes</em>. Harvard University Press, Cambridge, MA, 1991.</li>
                    <li>Fischhoff, B., Slovic, P., &amp; Lichtenstein, S. Fault Trees: Sensitivity of Estimated Failure Probabilities to Problem Representation. <em>Journal of Experimental Psychology: Human Perception and Performance</em>, 4(2):330&ndash;344, 1978.</li>
                    <li>Hart, O. &amp; Moore, J. Incomplete Contracts and Renegotiation. <em>Econometrica</em>, 56(4):755&ndash;785, 1988.</li>
                    <li>Knight, F. H. <em>Risk, Uncertainty and Profit</em>. Houghton Mifflin, Boston, 1921.</li>
                    <li>Kreps, D. M. A Representation Theorem for &ldquo;Preference for Flexibility&rdquo;. <em>Econometrica</em>, 47(3):565&ndash;577, 1979.</li>
                    <li>Macaulay, S. Non-Contractual Relations in Business: A Preliminary Study. <em>American Sociological Review</em>, 28(1):55&ndash;67, 1963.</li>
                    <li>Maskin, E. &amp; Tirole, J. Unforeseen Contingencies and Incomplete Contracts. <em>Review of Economic Studies</em>, 66(1):83&ndash;114, 1999.</li>
                    <li>Milgrom, P. R., North, D. C., &amp; Weingast, B. R. The Role of Institutions in the Revival of Trade: The Law Merchant, Private Judges, and the Champagne Fairs. <em>Economics &amp; Politics</em>, 2(1):1&ndash;23, 1990.</li>
                    <li>Savage, L. J. <em>The Foundations of Statistics</em>. John Wiley &amp; Sons, New York, 1954.</li>
                    <li>Simon, H. A. A Behavioral Model of Rational Choice. <em>Quarterly Journal of Economics</em>, 69(1):99&ndash;118, 1955.</li>
                    <li>Tversky, A. &amp; Koehler, D. J. Support Theory: A Nonextensional Representation of Subjective Probability. <em>Psychological Review</em>, 101(4):547&ndash;567, 1994.</li>
                </>
            }
        >
            <PaperSection title="1. The Window Between the Two Calls">
                <p>
                    A bonded settlement mechanism of the kind treated here exposes two state-changing operations and nothing else. <em>Commit</em> takes a commitment signed by a buyer and a seller and locks two deposits against it: twice the payment from the buyer, and twice the value the process has accumulated through that seller&rsquo;s own order &mdash; its own payment included &mdash; from the seller. It raises a monotonic accumulator by exactly the new payment, admits no other declared figure, and writes the order into the process. <em>Resolve</em> takes a process and the complete list of its live orders, may be called only by the buyer that opened the process, and settles every one of those orders at once or none: each seller is paid its payment and refunded its bond whole, and the buyer is refunded its bond less the payments it carried.
                </p>
                <p>
                    Between the two calls there is an interval, and it is genuinely open. No clock runs from the bonded state. Nothing matures, nothing expires, no position deepens with time and none improves. A bonded position is a position held rather than a loss taken, and it is held until the buyer decides otherwise. That is a design property with an ordinary consequence: the interval is a place where things happen. Goods travel through it, work is performed in it, and the world does not pause because two parties have signed.
                </p>
                <PaperRun title="External events.">
                    We use the term for any occurrence, after the signatures that open or extend a process and before its terminal call, that changes what the parties want the settlement of that process to be. The definition is deliberately about effect rather than about nature, and the reason is the paper&rsquo;s thesis in miniature: the mechanism has no representation of an occurrence, so a taxonomy of kinds would be a taxonomy of things it cannot see. What it can see is a schedule and a set of positions, and what an event does to those is change which allocation of the committed value the parties now want. A cargo resold in transit, a pallet crushed in a warehouse, a courier that cannot reach the address, a forum&rsquo;s ruling on a disputed delivery, a change of commercial mind, a currency movement that makes one party regret its price: these differ in every respect that matters commercially and in none that matters to the frame.
                </PaperRun>
                <p>
                    Most readers arrive with a settled expectation about what happens next, and it is worth naming because everything below is a departure from it. The expectation is that trust between strangers is repaired <em>afterwards</em>, by someone with the authority to decide: an escrow agent who inspects and releases, a card network that reverses a charge on complaint, an arbitrator, a court. On that model an event is an input to a decision procedure, and a decision procedure must be able to recognize its inputs &mdash; so the mechanism needs a list of what can happen and a rule for each entry. The institution is old and it works: the private judges of the medieval fairs kept exactly such a procedure, and their authority rested on a record of who had been found in default (Milgrom, North, &amp; Weingast, 1990). It is also expensive in a way the present setting cannot pay, and it seats a decision with a party whose own capital is not at stake.
                </p>
                <p>
                    The thesis of this paper is that a mechanism which recognizes nothing does better. Commit freezes an arithmetic; resolve is the one discretionary act left inside the frame; and every external event, of whatever kind, meets the same rule &mdash; <em>the parties square it before the terminal call</em>. Section 2 sets out the two axes that make the rule statable: when a decision is made, and whether it is executed deterministically or exercised by a named party. Section 3 states formally what commit creates. Section 4 proves the central proposition: the fixed schedule constrains the arithmetic, not the allocation, and the reallocation is credible for the same reason the schedule was. Section 5 gives the general rule and the instances that fall under it. Section 6 works the cargo-resale case end to end. Section 7 shows that the designer, in choosing how finely to cut a process into orders, is choosing the exposure topology under which all of this negotiation happens. Section 8 states what the design buys.
                </p>
            </PaperSection>

            <PaperSection title="2. Discretionary and Deterministic">
                <p>
                    Two questions separate every decision that bears on a settlement, and confusing them is the source of most misreadings of mechanisms of this kind. The first is <em>when</em>: is the decision made before both parties have signed, or after? The second is <em>how</em>: is it executed deterministically from what was signed, or is it exercised by a named party at its own discretion? The pivot for the first question is the signature pair, which is where the parties&rsquo; assent is complete and after which the terms stand as signed. Crossing the two questions gives four positions, and all four are occupied.
                </p>
                <div className="my-4 overflow-x-auto">
                    <table className="text-sm border-collapse">
                        <thead>
                            <tr>
                                <th className="border border-default px-3 py-1.5 text-left text-ink-muted font-normal"> </th>
                                <th className="border border-default px-3 py-1.5 font-semibold text-ink-heading">Deterministic</th>
                                <th className="border border-default px-3 py-1.5 font-semibold text-ink-heading">Discretionary</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td className="border border-default px-3 py-1.5 font-semibold text-ink-heading">Before the signatures</td>
                                <td className="border border-default px-3 py-1.5">the bond schedule applied to the signed figures; the accumulator check; the hashing of what was assented to</td>
                                <td className="border border-default px-3 py-1.5">what to offer, whom to bind, which terms to compose, what price to accept &mdash; where all meaning enters</td>
                            </tr>
                            <tr>
                                <td className="border border-default px-3 py-1.5 font-semibold text-ink-heading">After the signatures</td>
                                <td className="border border-default px-3 py-1.5">the settlement schedule&rsquo;s execution; the record of what was undertaken</td>
                                <td className="border border-default px-3 py-1.5">the buyer&rsquo;s decision to resolve; the remedies the parties agree beforehand; a forum&rsquo;s ruling on the open process</td>
                            </tr>
                        </tbody>
                    </table>
                    <p className="text-xs text-ink-muted mt-2">The lower-right cell holds exactly one act that the mechanism itself executes &mdash; the buyer&rsquo;s resolution. The remedies and the ruling are the parties&rsquo; and a forum&rsquo;s, and reach the mechanism only through what the parties do with them.</p>
                </div>
                <PaperRun title="One discretionary act, and what it does.">
                    After the signatures, everything the mechanism does is fixed by them: the amounts, the recipients, the refunds. The single thing not fixed is whether and when the buyer calls the terminal operation, and that act is discretionary in the strong sense &mdash; the mechanism holds no test of performance of its own, admits no report of delivery, and offers no party any way to certify performance to it. Resolution <em>is</em> the buyer&rsquo;s acceptance; there is nothing else it could be. And because that one act is atomic across the process, its force is not confined to the buyer&rsquo;s own order. Nobody is paid until it is called, so every seller holds a live interest in every other seller&rsquo;s performance: a seller that has already performed is exposed to a co-seller&rsquo;s fault by <Math>{"P_i + 2G_i"}</Math> &mdash; it has parted with its work and stands in its whole bond &mdash; and one that has not yet performed by at least <Math>{"P_i + G_i"}</Math>, since it still holds what is in its hands. Both figures are arithmetic on the signed accumulator. That is the pressure under which any negotiation over an external event actually takes place, and it is why the co-sellers of a process are participants in that negotiation rather than spectators of it.
                </PaperRun>
                <p>
                    External events force discretion. The world does not arrive with an answer to who should bear a loss, and no arithmetic derives one: whether the seller that could not deliver should send back the payment, or half of it, or make good in kind, or be forgiven because the failure was nobody&rsquo;s doing, is a question about what these parties think fair and expedient between them. It is a question of the kind Knight (1921) separated from measurable risk &mdash; not a draw from a distribution the parties could have written down, but an occurrence whose very description was unavailable when they signed. A mechanism can meet such a question in one of two ways. It can try to absorb the discretion, which means enumerating the events and appointing someone to decide each; or it can decline to absorb it, hold the arithmetic still, and let the parties decide. This one declines. The settlement frame of Section 3 is the deterministic half of the picture, and its whole virtue is that it never reaches into the other half.
                </p>
                <PaperRemark title="Scope.">
                    The comparison drawn above is used only to name the reader&rsquo;s prior, and it stops there. A comparative analysis of enforcement contingent on events after the fact, across the substrates on which trade between strangers can be made safe, is another treatment&rsquo;s subject and carries an apparatus this paper does not import. Nothing below rests on how the four positions in the table are occupied by any arrangement other than the one it analyzes.
                </PaperRemark>
            </PaperSection>

            <PaperSection title="3. The Settlement Frame">
                <p>
                    This section states what commit creates, in the form the argument uses. Consider a process opened by a buyer <Math>{"B"}</Math> and extended by orders <Math>{"i = 1, \\ldots, n"}</Math>, order <Math>{"i"}</Math> carrying a payment <Math>{"P_i > 0"}</Math> and a seller <Math>{"S_i"}</Math>. Write <Math>{"G_i = \\sum_{j \\leq i} P_j"}</Math> for the value the process has accumulated through order <Math>{"i"}</Math>, its own payment included, so <Math>{"G_i \\geq P_i"}</Math> with equality only at the root. Every order shares one denomination, and the parties hold balances sufficient to bond. A party may hold more than one order; positions of a repeated party add, and nothing below turns on the sellers being distinct.
                </p>
                <FormalBlock label="Definition 1 (The committed schedule).">
                    <p>At commit, order <Math>{"i"}</Math> deposits <Math>{"2P_i"}</Math> from <Math>{"B"}</Math> and <Math>{"2G_i"}</Math> from <Math>{"S_i"}</Math>. At resolution it pays <Math>{"2G_i + P_i"}</Math> to <Math>{"S_i"}</Math> and <Math>{"P_i"}</Math> to <Math>{"B"}</Math>, which exhausts what was deposited. The <em>committed schedule</em> of a process is the vector of net movements the schedule effects across the two calls,</p>
                    <p><Math display>{"\\sigma = \\bigl(\\sigma_B;\\, \\sigma_1, \\ldots, \\sigma_n\\bigr), \\qquad \\sigma_B = -\\sum_{i} P_i, \\qquad \\sigma_i = +P_i,"}</Math></p>
                    <p>so that <Math>{"\\sum_j \\sigma_j = 0"}</Math>: every deposited unit leaves to one of the parties, the mechanism retains nothing, and there is no third recipient. Each seller&rsquo;s bond is refunded whole; the buyer&rsquo;s is refunded less the payments it carried. The schedule is fixed by the signatures and by the accumulator&rsquo;s arithmetic at the moment of each commit, and no later occurrence of any kind alters a term of it.</p>
                </FormalBlock>
                <FormalBlock label="Definition 2 (Closure of the frame).">
                    <p>The frame created by commit has five closure properties, and the argument uses all of them.</p>
                    <p>(i) <em>No position transfer.</em> A party&rsquo;s place in a process is not an instrument. It is not assignable, not transferable, and not represented by any object the mechanism issues; there is nothing to sell, endorse, or pledge.</p>
                    <p>(ii) <em>No party substitution.</em> An order names its two parties in what they signed. No operation replaces one of them, and a party that has not signed and bonded is not in the process on any terms.</p>
                    <p>(iii) <em>No partial resolution.</em> The terminal call takes the complete list of live orders and settles all of them or reverts. There is no per-order settlement path.</p>
                    <p>(iv) <em>No third-party call.</em> Only the buyer that opened the process may make the terminal call. No seller, no forum, no administrator, and no governance body can make it or compel it.</p>
                    <p>(v) <em>No other path to a bond.</em> The terminal call is the only operation that moves a deposited unit. There is no timeout, no cancellation, no unilateral exit, and no operation that returns part of a bond on any terms but resolution.</p>
                </FormalBlock>
                <PaperSubsection title="3.1 The results the frame carries">
                    <p>
                        Three results about this frame are used below, and are restated here in the form and at the size the argument needs &mdash; no more of them than it uses. They concern the order in which the two calls compose, what a third path out of the bonded state would do to that order, and where remedies and outside rulings sit relative to the terminal call.
                    </p>
                    <PaperRun title="The two calls compose in a definite order.">
                        At any buyer node <em>after performance</em>, resolving is strictly better for the buyer than never resolving. It holds the delivery either way, so the branches differ only in what the mechanism moves: resolving refunds the bond less the payments, leaving it at zero once the delivery is credited at the value it signed, while never resolving leaves it at <Math>{"-\\sum_i P_i"}</Math> &mdash; the withheld payments are not kept by the buyer but sit inside its own deposited bond, out of reach of everyone. That comparison assumes nothing whatever about any seller. Given it, performance is each seller&rsquo;s strict best response where its co-sellers perform: <Math>{"+P_i"}</Math> against at best <Math>{"-G_i"}</Math>, the value in its hands credited at most at <Math>{"G_i"}</Math> against a deposited <Math>{"2G_i"}</Math>, a margin of at least <Math>{"\\Delta_i = P_i + G_i"}</Math>. The doubling is what makes the taking cost: a bond equal to the value at the link would be exactly offset by the retention, and the second half is the whole of the deterrent.
                    </PaperRun>
                    <PaperRun title="A third path out is not a neutral addition.">
                        The results above are derived for a game with exactly the two operations, and any further path out of the bonded state changes the game rather than extending it. Either the new path seats a decision with a party whose own capital the bonds do not constrain &mdash; and that party then sits on the path by which bonds are refunded &mdash; or it puts a third continuation at a node whose two the analysis weighed against each other, so the comparison the party actually faces differs from the comparison the result was proved for. This is why Definition 2(v) is a security property and not an economy of implementation, and it is the standard against which every proposal in Section 5 is measured.
                    </PaperRun>
                    <PaperRun title="Remedies precede the terminal call, and forums do not make it.">
                        Where a seller cannot perform, the move that ends its exposure is a remedy agreed with the buyer <em>before</em> resolution. Where the parties disagree about whether what arrived met what was agreed, an outside forum &mdash; named in the composed terms, or the one that would have heard them anyway &mdash; may rule on the open process: on the record for what was undertaken and what remains unsettled, and on what the parties bring it for what happened, since performance occurred where the mechanism cannot look. Its ruling feeds the parties&rsquo; negotiation. It cannot make the terminal call, resolution being the buyer&rsquo;s alone, so it never sits on the path by which bonds are refunded &mdash; which is precisely why composing a forum leaves the equilibrium untouched. There is no direct enforcement of any kind, and the corollary on the other side is equally sharp: resolution is terminal acceptance. Once the buyer resolves, the transfers are made and the mechanism holds nothing further for anyone to recover, so a buyer with a live complaint resolves after the complaint is answered and not before.
                    </PaperRun>
                    <PaperRemark title="What &ldquo;deterministic&rdquo; means here, exactly.">
                        Given the commits, every quantity the terminal call moves is determined: the recipients, the amounts, and the accounting identity that exhausts the deposits. The only thing not determined is whether the call is made, and by whom it is made there is no question at all. A frame with that shape can be reasoned about by any party from public figures alone, and Section 4 is nothing but that reasoning carried out.
                    </PaperRemark>
                </PaperSubsection>
            </PaperSection>

            <PaperSection title="4. Netting Completeness">
                <p>
                    The apparent objection to a frozen schedule is obvious and is worth stating in its strongest form. If commit fixes who receives what, and no operation can alter a term of it, then the parties have bound themselves to an allocation chosen before the world had finished happening. A shipment resold, a partial loss, a failure nobody is to blame for &mdash; each of these makes the signed allocation the wrong one, and the frame appears to have no answer but to execute it anyway. The answer is that the schedule fixes the arithmetic and not the allocation, because the parties may move value between themselves while the process stands open, and those movements are unconstrained.
                </p>
                <PaperRun title="Positions and transfers.">
                    Write <Math>{"x_j"}</Math> for the final net position of party <Math>{"j"}</Math> in the process&rsquo;s denomination: what the mechanism moves to or from it under the schedule, plus what it has received from other parties, less what it has sent to them. A <em>transfer</em> is a movement of value from one party of the process to another, made before the terminal call, out of the sender&rsquo;s own balance. A transfer is not an operation of the mechanism: it touches no bond, no accumulator, no order, and no term of any commitment. It is what two parties who can pay each other do when they agree on something.
                </PaperRun>
                <FormalBlock label="Proposition 1 (Netting completeness).">
                    <p>Let a process carry the committed schedule <Math>{"\\sigma"}</Math> of Definition 1 and let its parties hold sufficient balances. The set of final net positions reachable by executing the schedule together with transfers among the parties before the terminal call is exactly</p>
                    <p><Math display>{"\\mathcal{X} \\;=\\; \\Bigl\\{\\, x \\in \\mathbb{R}^{\\,n+1} \\;:\\; \\textstyle\\sum_j x_j = 0 \\,\\Bigr\\},"}</Math></p>
                    <p>and every point of <Math>{"\\mathcal{X}"}</Math> is reached with at most <Math>{"n"}</Math> transfers.</p>
                </FormalBlock>
                <Proof>
                    <em>Necessity.</em> A transfer of <Math>{"t"}</Math> from <Math>{"j"}</Math> to <Math>{"k"}</Math> adds <Math>{"-t"}</Math> to one coordinate and <Math>{"+t"}</Math> to another, so it preserves the coordinate sum; and <Math>{"\\sum_j \\sigma_j = 0"}</Math> by Definition 1. Every reachable position therefore lies in <Math>{"\\mathcal{X}"}</Math>. <em>Sufficiency.</em> Fix a target <Math>{"x \\in \\mathcal{X}"}</Math> and let <Math>{"d = x - \\sigma"}</Math>, so <Math>{"\\sum_j d_j = 0"}</Math>. If <Math>{"d = 0"}</Math> the schedule alone reaches <Math>{"x"}</Math>. Otherwise the sets <Math>{"D^- = \\{ j : d_j < 0 \\}"}</Math> and <Math>{"D^+ = \\{ j : d_j > 0 \\}"}</Math> are both non-empty; pick <Math>{"j \\in D^-"}</Math> and <Math>{"k \\in D^+"}</Math> and transfer <Math>{"\\min\\{-d_j,\\, d_k\\}"}</Math> from <Math>{"j"}</Math> to <Math>{"k"}</Math>. The step zeroes at least one of the two coordinates and leaves the residual vector summing to zero, so it may be repeated; since the last coordinate is zeroed by the sum, at most <Math>{"n"}</Math> transfers are needed for <Math>{"n+1"}</Math> parties. Ordering the sequence so that each sender holds the amount it sends is always possible when balances suffice, which is the standing assumption. <Math>{"\\square"}</Math>
                </Proof>
                <PaperRemark title="The schedule is an origin, not a constraint.">
                    Proposition 1 says the committed schedule is a point of <Math>{"\\mathcal{X}"}</Math> and the parties may stand anywhere else in it. The only thing conserved is the sum, which is conserved by arithmetic rather than by policy: value is not created inside a process, and nothing the parties do among themselves creates any either. This is also why the reachable set is not bounded by the committed total. A reallocation in which one party ends further below <Math>{"-P_i"}</Math> than any payment in the process is on the hyperplane like any other &mdash; it is funded from that party&rsquo;s own balance rather than from the schedule &mdash; and the question it raises is not reachability but credibility, which Proposition 3 answers on the seller&rsquo;s side and declines to answer on the buyer&rsquo;s.
                </PaperRemark>
                <FormalBlock label="Proposition 2 (Posture invariance).">
                    <p>Transfers among the parties leave the frame exactly as they found it, in two senses.</p>
                    <p>(a) <em>Structural.</em> No transfer alters a bond, the accumulator, the live-order count, the identity of any party, or any term of <Math>{"\\sigma"}</Math>. The deterrent that stood before the negotiation stands during and after it, unchanged in every magnitude.</p>
                    <p>(b) <em>Strategic.</em> Let <Math>{"T"}</Math> be the buyer&rsquo;s net position from transfers already made and received. At a buyer node after performance, resolving yields <Math>{"0 + T"}</Math> and never resolving yields <Math>{"-\\sum_i P_i + T"}</Math>. The term <Math>{"T"}</Math> is common to both branches and cancels, so the gap is <Math>{"\\sum_i P_i"}</Math> &mdash; exactly the gap before any negotiation took place. Resolving is therefore strictly better for the buyer once the agreed transfers are collected, and it is strictly better whatever those transfers were.</p>
                </FormalBlock>
                <Proof>
                    (a) is Definition 2: the operations that write those quantities are commit and resolve, and a transfer is neither. (b) A transfer already made or received is a constant added to every continuation available at the node, and a constant common to two branches drops out of their comparison; the branches then differ only by what the schedule moves, which is the comparison of Section 3.1. <Math>{"\\square"}</Math>
                </Proof>
                <p>
                    Proposition 2(b) is the reason a party may negotiate freely without endangering the close. A concern one might reasonably carry into this section is that side payments distort the incentive to settle &mdash; that a buyer paid something extra, or a seller that has paid something away, now faces a different decision at the terminal node. It does not. The mechanism&rsquo;s comparison at that node is between two futures that share the whole past, and the past includes every transfer either party has made. What the transfers change is where the parties stand; what they cannot change is which branch the buyer prefers.
                </p>
                <FormalBlock label="Proposition 3 (The self-enforcing range, and the side it has).">
                    <p>An agreed reallocation must still be executed, and a party asked to send its part may refuse. What refusing leaves it holding differs in kind between the two sides, because only one of them can close the process.</p>
                    <p>(a) <em>Sellers.</em> A seller cannot make the terminal call, so refusing to send leaves its position standing. Seller <Math>{"S_i"}</Math> therefore sends an agreed amount <Math>{"\\tau"}</Math> when <Math>{"P_i - \\tau"}</Math> exceeds its standing position <Math>{"-2G_i + r_i"}</Math>, where <Math>{"r_i \\leq G_i"}</Math> is what it can actually retain off the record. Hence it executes for every</p>
                    <p><Math display>{"\\tau \\;<\\; P_i + 2G_i - r_i,"}</Math></p>
                    <p>which is exactly <Math>{"P_i + 2G_i"}</Math> for a seller that has already performed and retains nothing, and has the record-computable floor <Math>{"\\Delta_i = P_i + G_i \\geq 2P_i"}</Math> at maximal retention.</p>
                    <p>(b) <em>The buyer, and the asymmetry the frame does not repair.</em> No such bound exists on the buyer&rsquo;s side once it holds what it contracted for, and Proposition 2(b) is the reason. Refusing does not leave the buyer&rsquo;s position standing, because the close is the buyer&rsquo;s own act: it may refuse <em>and resolve</em>, ending at <Math>{"0"}</Math>, which is strictly better than the <Math>{"-\\tau"}</Math> it ends at by sending and resolving, for every <Math>{"\\tau > 0"}</Math>. The self-enforcing range for a buyer-outbound transfer at that node is therefore empty, and no arrangement of deposits could make it otherwise: the act that makes the schedule executable at all is the same act that leaves the buyer&rsquo;s part of a reallocation unpriced by the frame. What secures a buyer-outbound transfer is what secures ordinary commerce &mdash; the buyer sends because it wants the performance it is still buying, and the seller&rsquo;s security is its option to withhold that performance and take a remedy instead. Where the transfer is asked for performance already rendered, the frame prices nothing at all, and the parties are in the channels the world supplies.</p>
                    <p>(c) <em>Consequently</em> the reallocations the frame itself makes self-enforcing are the seller-outbound ones, bounded coordinate by coordinate by (a); the buyer&rsquo;s part of any reallocation rests on the ordinary commercial reason for making it. The shape is half-open rather than a box, and this is not a gap discovered in the frame but the frame&rsquo;s own asymmetry showing through: the one discretionary act sits with the buyer, and a party holding the act that ends the process cannot be held to anything by the position it is standing in. Two things follow, and both are load-bearing. The bounds in (a) are the quantities of the original equilibrium, not new ones &mdash; no instrument is added, no assumption introduced, and nothing about the frame differs during a renegotiation from before it, the bonds that made the first allocation credible being the bonds that make the second one credible because they never moved. And the class (a) covers is exactly the class of transfers the frame prices: a remedy owed by the party that failed runs towards the buyer, and (a) bounds every such transfer coordinate by coordinate. Where what a party is owed runs the other way, the frame prices nothing and says so, and the recourse is the one that reaches any party through its exposure outside the process; the buyer&rsquo;s own reason to close is settled by Proposition 2(b) without any transfer being asked of it.</p>
                </FormalBlock>
                <Proof>
                    Each comparison is between two certain amounts under the payoff convention of Section 3.1, in which a party is credited with the off-chain value in its hands at the assented measure and never charged for what is not. (a) Sending and closing pays <Math>{"S_i"}</Math> its payment and refunds its bond, net <Math>{"+P_i"}</Math>, less the transfer <Math>{"\\tau"}</Math>; refusing leaves <Math>{"2G_i"}</Math> deposited against a credit of at most <Math>{"r_i"}</Math>, and no move of <Math>{"S_i"}</Math>&rsquo;s ends that position. Rearranging <Math>{"P_i - \\tau > -2G_i + r_i"}</Math> gives the bound, and <Math>{"r_i \\leq G_i"}</Math> gives the floor. (b) At a node after performance the buyer&rsquo;s continuations include resolving, and by Proposition 2(b) resolving is available and strictly preferred whatever has passed between the parties. Its two relevant continuations are therefore sending and resolving, worth <Math>{"-\\tau"}</Math> with the delivery credited, and refusing and resolving, worth <Math>{"0"}</Math>; the second strictly exceeds the first for every <Math>{"\\tau > 0"}</Math>, so no positive <Math>{"\\tau"}</Math> is executed on the frame&rsquo;s own reasons. <Math>{"\\square"}</Math>
                </Proof>
                <PaperRemark title="What the bound is conditional on, stated plainly.">
                    The comparison in Proposition 3(a) is taken at the seller&rsquo;s own node <em>given that the agreed reallocation closes the process</em>. A seller that does not believe the others will do their parts compares its standing position against itself and learns nothing, and the frame supplies nothing further &mdash; the same conditionality the seller&rsquo;s side of the original equilibrium carries, and for the same reason: no schedule of deposits can make it attractive to pay into a process that is not going to close. What the frame does supply, and it is not small, is that no failed negotiation is ever banked. Nothing terminates but resolution, so a refused proposal leaves every party exactly where it was, free to propose again, with every exposure intact. And nothing in (b) restricts what a buyer <em>may</em> send: Proposition 1&rsquo;s reachability is untouched, since a party that wants to make a transfer is never prevented from making one. What (b) withholds is the frame&rsquo;s guarantee that it will.
                </PaperRemark>
                <PaperSubsection title="4.1 The bounds of the result">
                    <p>
                        Four limits belong with Proposition 1, and the fourth is the one the rest of the paper turns on.
                    </p>
                    <ol className="space-y-2 list-decimal pl-6 text-sm">
                        <li><em>One denomination.</em> The proposition is stated in the process&rsquo;s single unit of account, and the netting is exact only there. Parties are free to transfer value in anything they like, but a transfer in another unit nets against the schedule only at a rate somebody has to supply, and the frame supplies none: it compares magnitudes and does not convert them.</li>
                        <li><em>The parties only.</em> The coordinates of <Math>{"\\mathcal{X}"}</Math> are the parties of the process. Someone outside it holds no position the schedule reaches, so a transfer to a non-party is not a reallocation of the committed value but a party&rsquo;s own disposal of what it ends up with &mdash; and it is neither secured by the frame nor visible to it. A party that wants a non-party held to something must have that party sign and bond, which is a decision taken before the signatures and not a move available after them.</li>
                        <li><em>Balances actually held.</em> Reachability assumes each sender holds what it sends when the sequence reaches it. This is the same assumption commit makes and no stronger, and the constructive proof needs at most one sending step per order.</li>
                        <li><em>The frame executes agreements and produces none.</em> Nothing above says which point of <Math>{"\\mathcal{X}"}</Math> the parties will choose, and nothing in the mechanism has an opinion. Whether the failing seller should return the whole payment or part of it, whether a damaged consignment is worth accepting at a discount, whether a resale should leave the original buyer whole or better than whole &mdash; these are decided by the parties, before the terminal call, in whatever way parties decide things. The frame&rsquo;s completeness is a statement about what can be executed. It is not a statement about what will be agreed, and the two must not be run together.</li>
                    </ol>
                    <PaperRun title="The familiar shape, and where it differs.">
                        The reader will recognize the form of Proposition 1: a fixed initial assignment plus unrestricted bargaining reaches any allocation, which is the shape of the argument Coase (1960) made about the assignment of rights. Three differences are worth being exact about, because they are what makes the present statement a mechanism result rather than a restatement. First, the assignment here is not a right conferred by an outside authority; it is arithmetic the parties themselves signed, computed from an accumulator that admits exactly one value per commitment. Second, the bargaining is not assumed costless &mdash; the parties bear whatever it costs them to reach agreement, and Section 7 shows that the designer&rsquo;s own choices move that cost. Third, and most consequentially, the <em>execution</em> of the bargain is not assumed. Coase&rsquo;s frictionless world takes it for granted that an agreed reallocation is carried out; here the seller-outbound part of one is carried out because that seller&rsquo;s bond is deposited while the negotiation runs, and Proposition 3(a) gives the range over which that is enough &mdash; the buyer&rsquo;s part being carried out for the reason it always was, which Proposition 3(b) declines to dress up as a mechanism result. The bonded frame is thus one setting in which the bargaining half of that classical argument is supplied with an enforcement half of its own, and the enforcement half is the same one that secured the original exchange.
                    </PaperRun>
                    <PaperRun title="Renegotiation as the normal life of the arrangement.">
                        The incomplete-contracting literature treats renegotiation as the characteristic event of a contract whose terms cannot cover every state, and as something a mechanism must be robust to, since parties who can renegotiate will (Hart &amp; Moore, 1988). The frame here is not robust to renegotiation in that defensive sense; it is built out of it. It writes down only what it can compute, leaves every substantive contingency to be settled between the parties, and holds each of them to the table with its own deposited capital while they settle it. That is close to the observation that indescribability need not be fatal when the payoff-relevant consequences can be settled between the parties afterwards (Maskin &amp; Tirole, 1999), stated here as a settlement rule rather than as a message game: the parties do not report anything to the mechanism, and the mechanism asks them nothing.
                    </PaperRun>
                    <PaperRemark title="What the world calls a refund.">
                        A bond is <em>refunded</em> &mdash; returned to the party that deposited it, at resolution, each seller&rsquo;s whole and the buyer&rsquo;s less the payments it carried. Nothing is reversed by that, since the deposit was always the depositor&rsquo;s own. The reversal of a payment, which commerce calls by the same word, has no path in this frame at all: no operation returns a payment, and none could without becoming the third path Section 3.1 excludes. What a party asks for when it asks for its money back is, inside the frame, a transfer that the parties agree and execute before the terminal call &mdash; a point of <Math>{"\\mathcal{X}"}</Math> reached by Proposition 1 and, that transfer running from the seller, credible by Proposition 3(a). The word survives; the mechanism it names does not, and the substitute is strictly more general, since the parties may agree the whole payment, part of it, or something else entirely.
                    </PaperRemark>
                </PaperSubsection>
            </PaperSection>

            <PaperSection title="5. The General Rule">
                <p>
                    The rule can now be stated in the form it is used: <em>every external event is squared between the parties before the terminal call</em>. Squaring has three components, and separating them is what makes the rule operable rather than merely tidy.
                </p>
                <ol className="space-y-2 list-decimal pl-6 text-sm">
                    <li><strong>Agree the reallocation.</strong> The parties decide which point of <Math>{"\\mathcal{X}"}</Math> they now want. This is discretionary, it is theirs, and no part of it happens inside the mechanism. A forum&rsquo;s ruling may inform it; a co-seller&rsquo;s exposure may press it; nothing decides it but the parties.</li>
                    <li><strong>Execute the transfers.</strong> The parties move value between themselves, and the buyer makes the terminal call. This is deterministic: Proposition 1 says the point is reachable, Proposition 2 says reaching it disturbs nothing, and Proposition 3(a) says a seller&rsquo;s own deposited position makes its part of the movement worth making &mdash; while Proposition 3(b) says the buyer&rsquo;s part rests on its wanting what it is still buying, which the frame does not price and does not pretend to.</li>
                    <li><strong>Attest what happened.</strong> Each party may sign a statement about the order it concerns while the process stands open &mdash; declared under a clause the order&rsquo;s own signed agreement already carries, since the record stays open while the process does but the clause set was fixed at signing &mdash; so that the record carries not only the schedule but the variation the parties agreed. The record shows undertakings and attestations; it never shows performance, which happened where the mechanism cannot look.</li>
                </ol>
                <p>
                    Why every event receives the same treatment is a matter of arithmetic rather than of policy. The mechanism has no representation of an occurrence &mdash; not of a resale, not of a loss, not of a delay &mdash; so an event cannot present itself to the frame at all. What it does is change which point of <Math>{"\\mathcal{X}"}</Math> the parties want, and <Math>{"\\mathcal{X}"}</Math> is the same set whatever changed it. The instances below are therefore organized by what an event <em>demands</em>, which is a fact about the parties, and not by what an event <em>is</em>, which is a fact about the world the frame never learns.
                </p>
                <PaperRun title="A remedy transfer.">
                    Non-performance, partial loss, a delivery that arrived late or short. One party is out of pocket relative to what it agreed, and the reallocation moves value from the party at fault to the party that bore it. The concrete transfer where a seller cannot perform is the sharpest case: the failing seller sends the buyer the payment it stands to receive and makes good whatever of the buyer&rsquo;s its failure left in its hands. At resolution its bond is refunded and it is paid the payment it has already paid away, so it ends at exactly zero &mdash; its failure earning it nothing, and zero better by the whole value through its order than the standing position of at best <Math>{"-G_i"}</Math>. The buyer, made whole, resolves because resolving is its better branch. Both halves of that transfer matter: a seller that sent the payment on but kept what was in its hands would end holding its retention, and the buyer would stay short by the same amount.
                </PaperRun>
                <PaperRun title="A full reallocation.">
                    Nobody is at fault and the commercial facts have changed: the goods are resold, a party takes over what another was to bear, the price the parties would now sign is not the price they did sign. The reallocation may move any amount among any of them, and Proposition 1 places no ceiling on it. Section 6 works this case in detail, because it is the one where the temptation to reach for machinery &mdash; an assignable position, a substituted party, a settlement of one leg alone &mdash; is strongest, and where the frame&rsquo;s refusal costs the parties nothing.
                </PaperRun>
                <PaperRun title="A ruling that feeds the negotiation.">
                    The parties disagree in good faith about whether what arrived met what was agreed. Here the event is a disagreement rather than an occurrence, and what it demands is a judgement the parties cannot supply between them. An outside forum can be shown the open process for what was undertaken, and whatever each party brings it for what happened; its ruling changes what the parties expect from continuing to hold their positions, and they then agree a point of <Math>{"\\mathcal{X}"}</Math> in its light. The forum cannot make the terminal call. That is not a limitation grudgingly conceded but the exact reason the composition is safe: a body that could make the call would be a party the bonds do not constrain, standing on the path by which they are refunded, and Section 3.1 says what that does to the results. Enforcement of the ruling, where a party resists it, runs through the party&rsquo;s exposure outside the process, as rulings ordinarily reach parties.
                </PaperRun>
                <PaperRun title="Nothing at all.">
                    The largest class in practice, and the easiest to overlook. A vast number of things happen during any commercial process that change nobody&rsquo;s mind about the settlement: a truck takes a different route, a subcontractor is swapped out, a warehouse reorganizes its bays, an exchange rate moves against a party that priced in the process&rsquo;s unit anyway. A frame with an event taxonomy would have to decide whether each of these is an entry in it. This frame does not notice them, and its not noticing is not neglect &mdash; there is nothing to notice, because the parties still want the settlement they signed.
                </PaperRun>
                <PaperRun title="The standing lock: the boundary observation.">
                    One case is not squared, and honesty about the frame requires stating it exactly rather than smoothing it. A party may simply not act &mdash; a seller that neither performs, nor remedies, nor answers a ruling; a buyer that neither agrees a variation nor makes the terminal call &mdash; and the position then stands as it was: every bond deposited, the accumulator where the commits left it, the record carrying an undertaking never closed. It stands against whoever is in it, and the two sides of it are both priced. A seller in that position is at best at <Math>{"-G_i"}</Math> and worse wherever it retains less. A buyer in it is at <Math>{"-\\sum_i P_i"}</Math>: the payments it withholds are not kept by it but sit inside its own bond, which by Definition 2(v) only the terminal call moves. Nothing in the mechanism consumes either bond, and nothing matures. The lock is therefore not an instrument either party holds over the other; it is the deterrent working in both directions, and what a deterrent prices is a grudge &mdash; what it cannot do is prevent a party from paying that price. It is not solved by having a buyer accept a settlement it does not want, and it is not solved by having a seller that delivered write off what it delivered. The frame advises neither.
                </PaperRun>
                <PaperRun title="When performance is delivered and the terminal call does not come.">
                    Take the direction that is easiest to misread. A seller has performed and the buyer has not resolved. What that seller does is what any party in this frame does, and it does it before the terminal call. It offers a remedy &mdash; the variation that would make the buyer willing to close, at whatever figure the two of them reach, which Proposition 1 places on the hyperplane like any other point and Proposition 2 says costs the close nothing. It attests, signing against its own order under a clause that order&rsquo;s signed agreement already carries, so that the open record holds its account of what it undertook and what it did alongside the schedule. And it brings the disagreement to the forum the agreement names, or to the one that would have heard these parties anyway. That forum can be shown the open process &mdash; the undertakings, the accumulator, the attestations, the same record both sides hold &mdash; and can rule on what each party brings it for what happened; where a party resists the ruling, enforcement runs through that party&rsquo;s exposure outside the process, as rulings ordinarily reach parties. What it cannot do is make the terminal call or reach a bond, and that limit is not a shortfall the delivering seller absorbs: a body that could do either would be a party the bonds do not constrain, standing on the path by which they are refunded, and the results of Section 3.1 would then be results about a different arrangement.
                </PaperRun>
                <PaperRun title="What never resolving costs the buyer.">
                    A buyer that does not close is not waiting comfortably while that runs. Never resolving leaves it at <Math>{"-\\sum_i P_i"}</Math>, and by Proposition 2(b) that holds whatever has passed between the parties: transfers already made and received are common to both branches and cancel, so at every node after performance the gap between resolving and not is exactly <Math>{"\\sum_i P_i"}</Math>, and no elapsed time narrows it. The withheld payments reach nobody. They sit inside the buyer&rsquo;s own bond, out of reach of everyone &mdash; of the sellers, of any forum, and of the buyer itself &mdash; so the party refusing the close is the party whose value is frozen by the refusal. Nor is the delivering seller alone in pressing for it: resolution is atomic, every bond in the process is refunded in that one call, and a co-seller that has already performed stands in <Math>{"P_i + 2G_i"}</Math> on it. The branch out of a standing position therefore stays open at every moment to the party whose conduct holds it there, on both sides: perform or make the counterparty whole, on the terms Proposition 3(a) prices; agree the variation and make the terminal call, on the terms Proposition 2(b) prices. Nobody can close either branch to the party that holds it, and nothing accrues to anyone while it stays unopened.
                </PaperRun>
                <PaperRemark title="The rule asks the parties for nothing unfamiliar.">
                    The empirical record on how firms actually behave under contract is that they square things between themselves and reach for adjudication rarely: the businesses Macaulay (1963) interviewed adjusted and settled by negotiation and regarded litigation as a last resort that damaged the relationship; the diamond traders Bernstein (1992) studied opted out of the legal system almost entirely; the ranchers Ellickson (1991) observed settled damage among themselves under norms that ignored the applicable law. The rule stated here does not ask parties to do something new. It asks them to do what the record says they already do, and supplies the part they otherwise had to trust &mdash; that the arrangement will not settle out from under them while they do it, and that the value each of them stands to recover is held where the other cannot take it.
                </PaperRemark>
            </PaperSection>

            <PaperSection title="6. Worked Instance: Cargo Resale in Transit">
                <p>
                    Take a shipper as root buyer, moving a consignment under three orders: a haulier for the inland leg at <Math>{"P_1 = 10"}</Math>, an ocean carrier at <Math>{"P_2 = 30"}</Math>, and a warehouse at destination at <Math>{"P_3 = 5"}</Math>, all in the process&rsquo;s single unit. The accumulator gives <Math>{"G_1 = 10"}</Math>, <Math>{"G_2 = 40"}</Math>, <Math>{"G_3 = 45"}</Math>, so the sellers stand in <Math>{"20"}</Math>, <Math>{"80"}</Math>, and <Math>{"90"}</Math>, and the buyer in <Math>{"2 \\times 45 = 90"}</Math> across its three orders. The committed schedule is <Math>{"\\sigma = (-45;\\, +10,\\, +30,\\, +5)"}</Math>.
                </p>
                <p>
                    Mid-voyage the shipper sells the consignment to a new owner. Title moves under whatever instrument the trade uses for that &mdash; an endorsement, a contract of sale, a warehouse receipt &mdash; and the instrument is entirely outside the protocol. It names no order, moves no bond, and its own performance is not something the frame can see or secure. The commercial question is then the ordinary one: who ends up paying for the movement, and how.
                </p>
                <PaperRun title="What does not happen.">
                    The shipper&rsquo;s place in the process is not sold with the cargo, because there is nothing to sell: no position is transferable, and no object representing one is issued by anything (Definition 2(i)). The new owner does not step into the process, because a party that has not signed and bonded is not in it (Definition 2(ii)). The warehouse leg is not settled on its own so that the remainder can be handled separately, because the terminal call takes the whole process or none of it (Definition 2(iii)). And nothing about the sale reaches the frame in any other way: no operation exists through which it could. Every one of those refusals looks like a missing feature and each of them is the frame holding still while the world moves.
                </PaperRun>
                <PaperRun title="What happens instead.">
                    The parties square it. In the simplest arrangement the new owner pays the shipper the sale price together with the freight the shipper has committed; the shipper resolves at the end of the movement; each seller is paid its payment and refunded its bond; the shipper&rsquo;s bond is refunded less the payments it carried, which the sale has already reimbursed. The frame did nothing at all, and that is the correct outcome: a change of ownership that leaves the settlement the parties signed still the settlement they want is an event of the fourth class in Section 5.
                </PaperRun>
                <p>
                    The instructive variant is the one in which the new owner wants to pay the remaining sellers directly &mdash; its own carriers, its own credit terms, its own accounting &mdash; and those sellers are willing. Under an adjudicating substrate this is where machinery appears: a novation, an assignment, a substitution of parties, a partial settlement of the legs already performed. Here it is a reallocation, and Proposition 1 reaches it with transfers.
                </p>
                <ol className="space-y-2 list-decimal pl-6 text-sm">
                    <li>Each seller that will be paid outside agrees with the new owner, on its own terms, for the leg it is to perform. That agreement is theirs; the frame is not party to it and does not price it.</li>
                    <li>Before the terminal call, each such seller transfers to the shipper the payment amount it is due under the schedule &mdash; <Math>{"30"}</Math> from the carrier, say, and <Math>{"5"}</Math> from the warehouse. These are transfers in the sense of Section 4: they touch no bond, no accumulator, and no term of any commitment.</li>
                    <li>Each party attests the variation against the order it concerns, under a clause that order&rsquo;s signed agreement already carries, so that the record holds the agreed change alongside the schedule.</li>
                    <li>The shipper makes one terminal call. The schedule executes unchanged: the carrier receives <Math>{"80 + 30"}</Math>, the warehouse <Math>{"90 + 5"}</Math>, the haulier <Math>{"20 + 10"}</Math>, and the shipper <Math>{"45"}</Math>. Every bond is refunded to the party that deposited it.</li>
                </ol>
                <p>
                    The netting is exact. The carrier&rsquo;s position inside the process is <Math>{"+30 - 30 = 0"}</Math>, and what it keeps for the leg is what the new owner paid it; the warehouse&rsquo;s is likewise zero; the haulier, whose leg was performed and paid for on the original terms, keeps its <Math>{"+10"}</Math>. The shipper stands at <Math>{"-45 + 35 = -10"}</Math>, which is the inland leg it always intended to bear. The final position vector is <Math>{"(-10;\\, +10,\\, 0,\\, 0)"}</Math>, it sums to zero as Proposition 1 requires, and it was reached with two transfers &mdash; well inside the bound of one per order. Each transfer is far below the sender&rsquo;s own standing exposure: the carrier sent <Math>{"30"}</Math> against a position of <Math>{"80"}</Math> deposited, and Proposition 3(a) puts its execution bound no lower than <Math>{"\\Delta_2 = P_2 + G_2 = 70"}</Math>. Neither seller needed persuading by anything but its own arithmetic.
                </p>
                <PaperRun title="What the record ends up holding, and what it does not.">
                    It holds the three commitments, the accumulator they built, the attested variation, and one atomic resolution. It does not hold the sale. The frame never saw the instrument by which title moved, cannot verify that it was valid, and makes no representation about it &mdash; and this is not a gap to be closed but the same boundary the whole design rests on: performance and the passage of goods happen where the mechanism cannot look, and a change of ownership is exactly such a passage. The sale stands on its own instrument, before whatever forum that instrument answers to, and the process stands on its own record. That the two never touch is why the sale needed no permission from the process and the process needed no knowledge of the sale.
                </PaperRun>
                <PaperRun title="The exposure topology never moved.">
                    Through all of it each seller&rsquo;s bond stayed at twice the value accumulated through its own order, the accumulator stayed where the commits left it, and the terminal call stayed the buyer&rsquo;s alone. The deterrent that secured the movement therefore secured the remainder of the movement too &mdash; including the part performed for a new owner the frame has never heard of, under an arrangement it cannot read, paid for with value that never passed through it. The carrier that completes the voyage after the resale is deterred by exactly the <Math>{"80"}</Math> it deposited before there was any resale to speak of.
                </PaperRun>
                <PaperRemark title="Scope of the instance.">
                    The case above is worked, not observed: it is an illustration of the rule and of the propositions, with figures chosen for legibility. No play by independent participants has been observed in any process of this kind, and nothing in this paper is offered as a report of one. Note also what the frame does not promise. If the carrier declines to deal with the new owner, or declines to send back what it is due, nothing is broken and nothing is stuck: the schedule stands, the shipper is left where the schedule put it &mdash; having sold a consignment whose freight it has already committed &mdash; and each party holds the position it agreed to hold. The frame guarantees that the schedule executes on the buyer&rsquo;s acceptance. It does not guarantee that a better bargain is available, and no mechanism can.
                </PaperRemark>
            </PaperSection>

            <PaperSection title="7. Designing the Negotiation: Granularity and the Exposure Topology">
                <p>
                    Every negotiation in Sections 5 and 6 takes place among parties whose exposures were fixed before any of them knew there would be something to negotiate. The bond each seller stands in, the gap it weighs against leaving its position open, and the amount it will transfer rather than hold out are all determined by where its order sits in the accumulator &mdash; which is a choice made when the process was designed, not when the event occurred. Granularity is therefore a design variable of the bargaining and not only of the work, and a designer who cuts a process into orders is laying down the topology under which every later reallocation will be reached.
                </p>
                <PaperRun title="Depth decides how much a link can absorb.">
                    <Math>{"G_i"}</Math> is non-decreasing along the process, so a seller further along stands in more and has more to gain from the process closing. Proposition 3(a) turns that into a figure: the amount seller <Math>{"S_i"}</Math> will transfer out of its own pocket rather than leave its position standing is at least <Math>{"\\Delta_i = P_i + G_i"}</Math> and as much as <Math>{"P_i + 2G_i"}</Math> where it has performed and retains nothing. Two links carrying the same payment therefore absorb different amounts of reallocation according to where they sit, and a designer that places a thinly-paid step late in a process has created a party with a small payment and a large reason to settle. The converse is also true and less comfortable: a step placed early carries the least, and where the parties need someone to absorb a shock, the shallow link is the one least able to.
                </PaperRun>
                <PaperRun title="Splitting a link changes the capital, not the exposure through it.">
                    Suppose a designer divides one order of payment <Math>{"P_i"}</Math> into two consecutive orders of <Math>{"a"}</Math> and <Math>{"b"}</Math> with <Math>{"a + b = P_i"}</Math>, held by the same party. The bonds become <Math>{"2(G_{i-1} + a)"}</Math> and <Math>{"2(G_{i-1} + a + b) = 2G_i"}</Math>. The exposure through the later position is exactly what it was, since the schedule is keyed to the accumulator and not to the local payment; what changes is that the party now stands in the sum of the two, and that the reallocation can address the halves separately. Fine granularity thus buys explicitness &mdash; more positions to negotiate over, more attested detail in the record, a shock that can be settled against the step it struck &mdash; and pays for it in aggregate deposited capital and in the number of agreements that must be reached.
                </PaperRun>
                <PaperRun title="Every party is a party to the reallocation.">
                    Proposition 1&rsquo;s coordinates are the parties, so reaching a point of <Math>{"\\mathcal{X}"}</Math> requires the assent of everyone whose position moves. A coarse process concentrates the bargaining in few hands and settles quickly, at the price that one seller absorbs internally &mdash; on its own books, invisibly to the record and unsecured by any bond &mdash; whatever the frame would otherwise have made explicit. A fine process makes the structure visible and secures each part of it, at the price of more parties to convene. Neither is right in general; the trade-off is the designer&rsquo;s, and it is the substance of what a designer decides. And what the designer is allocating runs one way, by Proposition 3: it is the sellers&rsquo; standing positions that make their parts of a future reallocation executable, the buyer&rsquo;s part resting on its wanting the performance it is still buying. Cutting a process into orders is therefore also deciding how much of a settlement nobody has yet had reason to negotiate the frame itself will secure.
                </PaperRun>
                <p>
                    One further consequence deserves stating because inherited habits conceal it. Coordination that would traditionally be split across separate arrangements &mdash; a haulage contract here, a carriage contract there, a storage agreement with a third party, each with its own settlement and its own recourse, reconciled afterwards by somebody&rsquo;s accounts department &mdash; composes inside one process at this level. The process the mechanism sees is a linear sequence of commits extending one accumulator, and its length is bounded only by what a single transaction can execute. Everything inside that boundary shares one terminal call, one atomic settlement, and one hyperplane of reachable allocations, which is why the reallocation of Section 6 needed no reconciliation of any kind: the legs that were paid outside netted to zero against the schedule in the same call that paid the leg that was not.
                </p>
                <PaperRemark title="Where the topology itself lives.">
                    The order of the sellers, the fan-in and fan-out of a process, and who stands before whom are terms of what the parties signed rather than facts the mechanism stores. What it stores is an accumulator and a count. The consequence for this section is that a designer&rsquo;s granularity choice is expressed in the agreement, is read from there by anyone reconstructing the process, and binds the parties in the only way anything binds them here &mdash; through the figures each of them signed and the deposits those figures fixed.
                </PaperRemark>
            </PaperSection>

            <PaperSection title="8. Discretion as the Design">
                <p>
                    Set the two designs side by side. A substrate that undertook to adjudicate events would need two things it cannot get cheaply. It would need an <em>event taxonomy</em> &mdash; a list of what can happen, complete enough that a case arriving from the world can be recognized as an instance of an entry. And it would need a <em>decision procedure per entry</em>: someone or something empowered to say, for each recognized kind, what now follows. Both are costs, and the decision-science record is unusually specific about what they cost.
                </p>
                <PaperRun title="A taxonomy is a small world.">
                    Savage (1954) built his framework on a state space in which every relevant contingency is already enumerated, and was explicit that the framework is a small-world construction whose application depends on the enumeration being adequate. The experimental record says the enumeration is not adequate and, worse, that its inadequacy is invisible from inside. Shown a fault tree with whole branches pruned away, participants did not compensate by inflating the residual &ldquo;all other causes&rdquo; category; they judged the pruned tree much as they judged the complete one, so the omitted branches drew no compensating weight anywhere (Fischhoff, Slovic, &amp; Lichtenstein, 1978). Support theory generalizes the finding: an implicit disjunction is judged less likely than the sum of its explicit components, so a catch-all category is systematically underweighted precisely because its contents are unnamed (Tversky &amp; Koehler, 1994). A taxonomy is written by a designer of bounded rationality, satisficing over the cases it can bring to mind (Simon, 1955), and the cases it cannot bring to mind do not announce themselves. The class of events a mechanism has never heard of is thus both the largest class and the one its designers will judge smallest.
                </PaperRun>
                <PaperRun title="A judge per entry is a party the bonds do not constrain.">
                    The second cost is structural rather than cognitive, and Section 3.1 has already priced it. Every decision procedure seated inside the substrate is a discretionary act added after the signatures, and whoever exercises it stands on the path by which deposits are refunded without having deposited anything. That is not an argument that adjudication is bad &mdash; the parties may want a forum and often should &mdash; but an argument about <em>where</em> it may sit. A forum that rules on an open process changes what the parties expect and leaves every comparison in the mechanism exactly as it found it. A forum that could release a deposit would replace those comparisons with different ones, and the results would have to be established again for the arrangement that resulted, if they could be.
                </PaperRun>
                <p>
                    The design taken here is the other one. Freeze the arithmetic at the signatures; keep exactly one discretionary act after them; put every substantive decision either before the signatures, where the parties are composing terms and choosing counterparties, or in the interval, where the parties negotiate under deposits that make their agreements executable. The frame is then complete in the only sense that matters against an open world: not that it can name what may happen, but that whatever happens, the reallocation the parties then want is reachable (Proposition 1), reaching it disturbs nothing (Proposition 2), and each seller&rsquo;s own position makes its part of it worth executing (Proposition 3), the buyer&rsquo;s part resting where commerce has always rested it. There is a well-understood reason to keep an option open rather than to specify in advance what will be done with it &mdash; a decision-maker who cannot foresee the menu values the flexibility itself (Kreps, 1979) &mdash; and this design keeps exactly one, holds it with the party whose acceptance the whole exchange is for, and leaves the substance to the parties who know what happened.
                </p>
                <p>
                    That is the whole claim, and it is worth stating in the plainest form available. A mechanism that adjudicates can absorb the events it has heard of. A mechanism that freezes a deterministic schedule and keeps a single discretionary act absorbs the events it has never heard of, which is the class that actually turns up: a cargo resold in transit under an instrument written for a trade the designer never considered, a loss the parties settle at a figure no rule would have produced, a change of mind that is nobody&rsquo;s failure. The frame does not know any of it happened. It holds the arithmetic still while the parties decide, and then it executes what they decided.
                </p>
                <PaperRun title="Two boundaries this paper does not cross.">
                    What an open process&rsquo;s record can be shown to an outside forum, and what it can never show &mdash; it holds undertakings and attestations, and performance happened where the mechanism cannot look &mdash; is an evidentiary subject with an apparatus of its own; nothing above uses more of it than the two facts already stated, that a ruling feeds the parties&rsquo; negotiation and that no ruling makes the terminal call. And whether an arrangement that assembles the parties a transaction needs, holds them by their own deposited capital while it stands, and dissolves at its settlement, displaces the durable institutions that have done that work &mdash; in which trades, and under what conditions on the costs of transacting &mdash; is a question of institutional economics carrying its own apparatus. This paper raises neither, and no result above rests on an answer to either.
                </PaperRun>
            </PaperSection>
        </PaperLayout>
    );
}
