import type { Metadata } from "next";
import {
    PaperLayout,
    PaperSection,
    PaperRun,
} from "@/components/papers/PaperLayout";
import { Math } from "@/components/papers/Math";

export const metadata: Metadata = {
    title: "The Florin: A Schelling-Point Token — Figaro Protocol",
    description:
        "The florin is a pure focal-point token: its value is its focality, not yield, governance, fees, or activity-driven supply. No settlement operation mints, consults, or denominates in it, and the one coupling that exists runs one way — the distribution layer reads what settlement has already recorded, and nothing the florin does reaches back into a bonded process. It is situated among the four things that meet in one bonded process — three kinds of token (coordination, utility, community) and the signal a denomination emits, which is not a token at all — and the design is defined by what it refuses to do: each exclusion removes a reason to hold florins that is not alignment-signaling.",
};

export default function FlorinSchellingPointTokenPaper() {
    return (
        <PaperLayout slug="florin-schelling-point-token"
            title="The Florin: A Schelling-Point Token"
            subtitle="for the Figaro Coordination Ecosystem"
            author="Figaro"
            date="April 2026"
            watermark="Figaro Protocol · Preprint"
            keywords="cryptoeconomics, Schelling point, focal-point coordination, token design, coordination token, utility token, community token, denomination, supply integrity, fixed supply schedule, retroactive distribution"
            abstract={
                <>
                    <p>
                        We describe the florin, the coordination unit that ships alongside the Figaro settlement primitive. The florin is designed as a <em>Schelling-point token</em> in the sense of Schelling (1960): a focal point around which participants in the Figaro ecosystem can coordinate without central authority or explicit agreement. Its value as a coordination instrument derives from its focality, not from any on-chain utility function, yield stream, governance claim, or fee path.
                    </p>
                    <p>
                        This framing inverts the usual design question for a new token. Rather than asking &ldquo;what does the florin <em>do</em>?&rdquo; we ask &ldquo;what would the florin have to <em>not</em> do in order to remain a credible focal point?&rdquo; The answer produces a catalogue of design exclusions, each of which removes a class of holding motivation that would dilute the purity of the florin&rsquo;s signaling value. The florin is not governance, not yield-bearing, not a fee path, not privileged as the denomination of any bonded process, not founder-vested, and not a token whose supply any amount of trade can raise above its fixed schedule or bring forward within it. One relation to settlement does exist, and the paper holds a single position on it throughout: no settlement operation mints, consults, or denominates in the florin; the coupling runs one way &mdash; the distribution layer reads what settlement has already recorded, and nothing the florin does can reach back into a bonded process.
                    </p>
                    <p>
                        The positive design content is modest and targeted: a fixed one-billion-unit cap enforced by two complementary supply-integrity mechanisms, a one-way deployer-renouncement latch that freezes the allocation plan at deployment, and a single staged distribution of 60% of supply over nine annual periods whose budgets are fixed at deployment on a rising schedule. Each instalment is divided pro rata among the authors and designers of record of the clauses and assemblies real trade used &mdash; on identical terms, by one uniform rule with no category, no editorial weight, and no per-wallet cap &mdash; and any share of an instalment nobody claims is never minted at all. We lay this design out in detail and close with an honest analysis of how the florin can lose its focal-point status and what the design does and does not defend against.
                    </p>
                    <p>
                        The paper sits within a lineage, and the disanalogy matters as much as the analogy. Nakamoto (2008) demonstrated that money could be a protocol rather than an institution, with BTC as the focal Schelling point for a peer-to-peer cash system. Buterin (2014) demonstrated that contracts could be composable, with ETH as the focal point for programmable settlement. The present work extends the lineage one step in <em>what becomes composable</em> &mdash; <em>institutions</em> themselves, through the Figaro primitive &mdash; and the florin is the focal point for participants who coordinate around that composition. What it does not extend is the ladder of monetary function that ties BTC and ETH to a mechanism that requires the unit. The settlement primitive requires <em>a</em> single unit per process and no particular one: its comparisons set a bond against a value, and a comparison of magnitudes needs both quoted in the same unit, which is all the constraint amounts to. Every result the primitive rests on is stated in the process&rsquo;s own unit and names no token, so no settlement operation denominates in the florin and none requires it (Section 3).
                    </p>
                </>
            }
            references={
                <>
                    <li>Bacharach, M. <em>Beyond Individual Choice: Teams and Frames in Game Theory</em>, edited by N. Gold and R. Sugden. Princeton University Press, Princeton, NJ, 2006.</li>
                    <li>Buterin, V. Ethereum: A Next-Generation Smart Contract and Decentralized Application Platform. White paper, 2014.</li>
                    <li>Buterin, V. Credible Neutrality As A Guiding Principle. nakamoto.com, 2020.</li>
                    <li>European Parliament and Council of the European Union. Regulation (EU) 2023/1114 of 31 May 2023 on Markets in Crypto-Assets, and amending Regulations (EU) No 1093/2010 and (EU) No 1095/2010 and Directives 2013/36/EU and (EU) 2019/1937. <em>Official Journal of the European Union</em>, L 150, 9 June 2023, pp. 40&ndash;205.</li>
                    <li>Hayek, F. A. The Use of Knowledge in Society. <em>American Economic Review</em>, 35(4):519&ndash;530, 1945.</li>
                    <li>Markey-Towler, B. Anarchy, Blockchain and Utopia: A Theory of Political-Socioeconomic Systems Organised Using Blockchain. <em>Journal of the British Blockchain Association</em>, 1(1):1&ndash;14, 2018.</li>
                    <li>Mehta, J., Starmer, C., &amp; Sugden, R. The Nature of Salience: An Experimental Investigation of Pure Coordination Games. <em>American Economic Review</em>, 84(3):658&ndash;673, 1994.</li>
                    <li>Nakamoto, S. Bitcoin: A Peer-to-Peer Electronic Cash System. White paper, 2008.</li>
                    <li>Schelling, T. C. <em>The Strategy of Conflict</em>. Harvard University Press, Cambridge, MA, 1960.</li>
                    <li><em>SEC v. W. J. Howey Co.</em>, 328 U.S. 293 (1946).</li>
                    <li>Securities and Exchange Commission (US). <em>Framework for &ldquo;Investment Contract&rdquo; Analysis of Digital Assets</em>. Strategic Hub for Innovation and Financial Technology, April 3, 2019.</li>
                    <li>Selgin, G. A. <em>The Theory of Free Banking: Money Supply Under Competitive Note Issue</em>. Rowman &amp; Littlefield, Totowa, NJ, 1988.</li>
                    <li>Sugden, R. A Theory of Focal Points. <em>Economic Journal</em>, 105(430):533&ndash;550, 1995.</li>
                </>
            }
        >
            <PaperSection title="1. Introduction">
                <p>
                    The florin is the native token that ships alongside the Figaro settlement primitive. The name is borrowed from the coin Florence struck for the trade of its day, and the borrowing is for salience, not for lineage of function: that florin was a circulating coin with a metal content, while this one is required by no operation of the protocol &mdash; no fee is paid in it, no bond need be posted in it, and nothing on chain depends on holding it. What survives the borrowing is the property that made the historical unit useful &mdash; that everyone knew which unit everyone else meant &mdash; which is focality, and focality is the whole of what the design pursues. This paper describes that design and defends a specific framing of what it is. The framing is the substantive contribution; the supply-integrity and distribution mechanics follow from it.
                </p>
                <p>
                    The framing: <em>the florin is a Schelling-point token for the Figaro ecosystem.</em> Its value to participants is not a claim on protocol revenue (there is no protocol fee), not a governance vote (the settlement mechanism has no governance), not a yield stream (no activity-coupled supply), not a utility token purchasable for on-chain services (there are no protocol-layer services that require it), and not bond collateral (the settlement mechanism is token-agnostic). Its value is its focality: in the sense of Schelling (1960), the florin is the focal point that Figaro-aligned participants converge on when they want to signal alignment without coordinating through a central authority.
                </p>
                <PaperRun title="A lineage note.">
                    The <em>design pattern</em> has precedent &mdash; the pattern being focality, and only focality; a reader who carries the monetary function of the precedents across to the florin has imported precisely what this section is written to exclude. Nakamoto&rsquo;s (2008) Bitcoin is, in retrospect, the clearest example of a Schelling-point token at the money layer: its value as a store of value derives from holders converging on it as <em>the</em> answer to the question &ldquo;what digital bearer asset are we coordinating around?&rdquo; The proof-of-work mechanism secures Bitcoin&rsquo;s ledger, but it does not manufacture Bitcoin&rsquo;s Schelling-point status &mdash; that emerged from participant convergence under conditions in which Bitcoin&rsquo;s design made convergence viable (fixed supply, open participation, no issuer). Buterin&rsquo;s (2014) Ethereum moved the logic up one layer: ETH became the focal point for programmable settlement, with composable contracts as the substrate. The present work moves it up again: with Figaro, institutions themselves are composable, and the florin is the focal point for aligned participation in that composition. What each layer&rsquo;s native token shares is the <em>coordination</em> role &mdash; a focal anchor that needs no central issuer and no governance apparatus, and that a general-purpose token cannot replicate, because the signal is specifically about alignment with that particular ecosystem. What they do not share is the structural position beneath that role: BTC and ETH each sit under a mechanism that requires the unit, and their focality rides on top of that requirement, whereas the florin sits under no such requirement at all. The lineage is therefore real and the homology is not; Section 3 states the difference precisely, and a reader who carries the monetary function of the precedents across to the florin has imported exactly what this paper is written to exclude.
                </PaperRun>
                <PaperRun title="Paper organization.">
                    Section 2 introduces Schelling-point tokens as a design category and locates the florin within it. Section 3 argues why the Figaro ecosystem is well-suited to a focal-point native token rather than a utility-coupled one. Section 4 articulates design rules that support focal-point emergence and resist focality-dilution. Section 5 develops supply integrity. Section 6 develops allocation. Section 7 develops the staged distribution, the counted adoption it divides by, and the one direction in which that counting couples to settlement. Section 8 situates the florin among the four things that meet in a single bonded process &mdash; three kinds of token, and the signal a denomination emits, which is not one. Section 9 catalogues the design exclusions and ties each to the focality property it preserves. Section 10 treats bootstrap and attack surface. Section 11 separates what is true of the settlement primitive from what is true of this particular unit&rsquo;s distribution. Section 12 treats regulatory framing. Section 13 concludes.
                </PaperRun>
            </PaperSection>

            <PaperSection title="2. Schelling-Point Tokens as a Design Category">
                <p>
                    Schelling (1960) identified <em>focal points</em> (what later came to be called Schelling points) as solutions that parties tend to choose in the absence of explicit communication, because some feature of the solution makes it stand out as the natural coordination target. Schelling&rsquo;s canonical example: if two parties are told to meet in New York City without being able to communicate, a disproportionate fraction converge on Grand Central at noon. Neither the location nor the time is more rational than any other; what makes them focal is a shared cultural salience that each party correctly expects the other to recognize.
                </p>
                <PaperRun title="The focal-point literature, briefly.">
                    The conceptual machinery is older and more developed than the crypto-token literature usually engages. Schelling (1960) introduced focal points as a coordination phenomenon and observed the empirical fact that humans converge on salient solutions without communication. Sugden (1995) formalized the phenomenon as <em>salience theory</em>: parties pick the option that stands out by some shared frame of reference, and the salience is itself constructed through repeated coordination on similar problems. Mehta, Starmer, &amp; Sugden (1994) produced the canonical experimental confirmation that focal-point convergence operates robustly across populations on a wide range of pure-coordination problems. Bacharach&rsquo;s (2006) <em>team reasoning</em> formalized the further step that focal points operate not because each party reasons about the other&rsquo;s reasoning but because both parties shift to a we-frame in which the salient solution is the team-rational choice. The combined apparatus gives a precise account of what makes a token focal: it is not the token&rsquo;s properties in isolation but the token&rsquo;s properties as picked out by a shared frame within which holding the token is recognizable as a coordination act. The cryptoeconomic literature has applied this apparatus repeatedly without always citing it: Markey-Towler (2018) examines tokens as Schelling points in a behavioral-economics register, and Buterin (2020) on <em>credible neutrality</em> articulates the design discipline for tokens whose focality is to be sustained over time; the classical antecedents worth naming are Hayek (1945) on the distributed-coordination role of prices and Selgin (1988) on the emergence of focal monetary instruments without central authority.
                </PaperRun>
                <PaperRun title="Crypto and Schelling points.">
                    The structure has been rediscovered repeatedly in crypto design. Nakamoto (2008) did not use the word &ldquo;Schelling,&rdquo; but Bitcoin&rsquo;s emergence as a store of value followed the logic precisely: a fixed-supply, non-upgradable, issuer-less digital bearer asset with a peer-to-peer monetary intent. No mechanism guarantees Bitcoin&rsquo;s store-of-value status; it emerged because the design made focal convergence viable and participants converged. Buterin (2014) extended the logic up a layer: ETH became the focal settlement unit for programmable contracts, for the same reason &mdash; the design made convergence viable (gas-required, ubiquitous across contracts, issuer-less at the base layer). Similar focal patterns have emerged for subsidiary positions within crypto: Uniswap as the focal automated market maker, Aave as the focal lending protocol, Lido as the focal liquid-staking wrapper. In each case the token has some utility, but a substantial fraction of its holding behavior is Schelling convergence on &ldquo;the token that represents alignment with this particular primitive.&rdquo;
                </PaperRun>
                <PaperRun title="Schelling tokens vs. utility tokens.">
                    A pure utility token is valued for the services a holder can purchase with it (gas, access, data). A pure governance token is valued for the votes it conveys. A pure yield-bearing token is valued for the cash flows it represents. A Schelling-point token is valued for something different: its <em>focality</em>, which is a coordination property, not a cash-flow property or a rights property. A participant holds a Schelling-point token because holding it makes them legible to other aligned participants and because the shared holding constitutes the coordination itself.
                </PaperRun>
                <p>
                    Pure Schelling-point tokens are rare because most token designs add utility or governance features to create additional demand drivers. Each such addition, however, introduces holders whose reason for holding is <em>not</em> focal alignment &mdash; governance speculators, yield farmers, utility arbitrageurs &mdash; and these holders&rsquo; presence dilutes the focality signal. Bitcoin&rsquo;s focality is durable partly because of a refusal of the same shape: no governance, no yield, no utility features bolted onto the base-layer payment rail. What Bitcoin demonstrates is therefore the <em>discipline</em>, and it is worth being exact about how far the demonstration reaches. Bitcoin is not a pure Schelling point in the strict sense this paper reserves for the florin: its issuance consumes real factors and its own transactions require the unit, so a mechanical floor sits beneath the focal convergence and a share of the holding it attracts answers to that floor rather than to alignment. Purity in the strict sense means focality with nothing beneath it at all &mdash; a stronger and more exposed condition, and the one Section 3 argues the florin occupies.
                </p>
                <PaperRun title="The florin&rsquo;s design category.">
                    The florin is designed to sit in the pure-Schelling-point category. The design is committed to refusing utility couplings, governance rights, yield streams, and fee paths. The rest of this paper develops what that refusal looks like in practice.
                </PaperRun>
            </PaperSection>

            <PaperSection title="3. Why the Figaro Ecosystem Is Well-Suited to a Focal-Point Token">
                <PaperRun title="What underpins the florin&rsquo;s value, said honestly.">
                    A Schelling-point token requires focal convergence, and focal convergence is itself a value-formation mechanism in the strict sense: a holder values the token because other aligned holders value it for the same reason, and the shared recognition is what gives the token its content. Care is needed here, because the adjacent crypto literature broadly invites a misreading that conflates focal convergence with mechanism-coupled token demand. The two are different and should be kept apart.
                </PaperRun>
                <p>
                    The standard lineage &mdash; Bitcoin underpinned by the cost of proof-of-work, Ethereum underpinned by gas demand, the florin underpinned by trade &mdash; is rhetorically tidy and mechanically misleading. Bitcoin and Ethereum each have a <em>mechanism-coupled</em> demand source: Bitcoin&rsquo;s proof-of-work issuance consumes real factors and puts a marginal-cost floor under issuance; Ethereum&rsquo;s gas requirement makes ETH necessary for any transaction on the Ethereum L1, with EIP-1559 burn reinforcing the floor. The florin has neither. The Figaro settlement primitive takes any standard, non-rebasing ERC-20 as the bond and payment currency of a process &mdash; the one requirement being that a transfer deliver exactly the amount requested, which rules out fee-on-transfer and rebasing designs and nothing else; a participant who settles every bonded commitment in <code>USDC</code> pays zero florins, contributes zero florin-denominated demand, and the primitive is indifferent to the choice. Saying the florin is &ldquo;underpinned by trade&rdquo; in the way Bitcoin is underpinned by proof-of-work elides this asymmetry and overstates the case.
                </p>
                <p>
                    The florin is a <em>pure focal-point token</em> in the sense Section 2 defined: its value derives from focal convergence alone &mdash; aligned holders recognize the florin as the coordination anchor for the Figaro-ecosystem question, and the coordination is itself the token&rsquo;s content. No settlement creates florin demand, no gas requirement does, no fee path routes ecosystem activity through florin-denominated demand, and the design rules of Section 4 forbid introducing one. One relation to settlement does exist and it creates no demand for the unit: the distribution of Section 7 reads adoption the record already holds, in order to divide instalments whose sizes were fixed before any of that adoption happened. It is a read, it runs one way, and Section 9 states it in that form. The florin therefore occupies a different category from Bitcoin and Ethereum rather than a homologous position in the same one: their mechanism-couplings happen to support focal convergence on top, whereas the florin&rsquo;s focal convergence <em>is</em> the mechanism, with no <em>mechanical</em> coupling beneath it. That is not no coupling at all. The florin is a scarce unit whose focality is expressed only through use and alignment, and the trade-volume of the ecosystem is a public signal a holder may correctly expect to correlate with the maintenance of focal alignment &mdash; but the correlation is reflexive (held together by participant belief) rather than mechanical (held together by required token-flow). Reflexive value is real and durable when the focality is durable; it is not the same thing as cost-floor or fee-floor value. Whether such a category can sustain value is uncertain in the way any pure coordination phenomenon is uncertain, and the design discipline below is the work of keeping the convergence intact.
                </p>
                <PaperRun title="Why a general-purpose token cannot carry this signal.">
                    The settlement primitive is token-agnostic in a specific and checkable sense. A bonded process fixes one unit of account at its first signature, and every link committed under it settles in that same unit &mdash; a constraint the primitive does impose, because it sets bonds against values and two magnitudes are comparable only when quoted alike. Which unit it is, the primitive neither knows nor cares. The buyer bonds twice the payment; each seller bonds twice the value the chain has accumulated through its own link; and every comparison that makes performance each party&rsquo;s best course is stated in those quantities and in nothing else. No operation mints, consults, or denominates in the florin, and no result about the mechanism would change if the florin had never been deployed. Why, then, have a native token at all?
                </PaperRun>
                <p>
                    The answer is that multi-party coordination in an ecosystem without central authority requires a coordination signal that does not depend on any central authority, and no general-purpose token provides that signal. Participants bond in <code>USDC</code> when they want legal-system alignment; in a DAO governance token when they want community membership in that DAO; in <code>ETH</code> when they want to denominate in the base settlement unit; in a commodity-backed token when they want value anchoring. None of these signals <em>Figaro-ecosystem alignment specifically</em>. A general-purpose token carries many reasons to hold it at once, so a <em>balance</em> in one distinguishes nothing about why it is held.
                </p>
                <p>
                    A recorded <em>use</em> is a different object, and the distinction matters because Section 8 turns on it. The denomination of every commitment is on the public record, so which unit a party was willing to accept in a particular deal is checkable by anyone; that is a fact about a deal, it is available for any unit whatever, and it says nothing about the rest of a party&rsquo;s balance sheet. What no general-purpose unit can supply is the other reading: a holding that admits one interpretation. The florin&rsquo;s design is an attempt to supply exactly that, and the two readings are complementary rather than in competition &mdash; the record shows what a party did with a unit, the florin balance shows which ecosystem a party has declared for.
                </p>
                <p>
                    A focal-point token that signals Figaro alignment <em>only</em>, and whose design forbids any other reading of the holder&rsquo;s motivation, provides a coordination instrument the ecosystem does not otherwise have. This instrument is useful in two distinct settings.
                </p>
                <PaperRun title="Finding aligned counterparties.">
                    A participant designing a new Figaro assembly (a bonded workflow composed from protocol components) wants to find counterparties who understand the protocol, operate in its idiom, and will engage constructively with its equilibrium discipline. Searching for such counterparties by settlement history is possible but expensive &mdash; one must read the chain. Searching by florin holding is cheaper: a participant who holds florins has declared alignment through the specific act of acquiring a unit whose only plausible reason to acquire is alignment.
                </PaperRun>
                <PaperRun title="Signaling alignment in contested contexts.">
                    Participants who want to declare Figaro-aligned participation in adjacent debates &mdash; regulatory, academic, industry &mdash; benefit from a token whose holding is unambiguous. A founder who accepts florins in lieu of other compensation signals more than a founder who accepts <code>USDC</code>. Not every participant needs this signal; those who do benefit from the existence of a focal coordination anchor that has no financial pretext.
                </PaperRun>
                <p>
                    These use cases are modest. We do not claim the florin is indispensable or that the ecosystem fails without it. We claim only that a focal-point token has a coordination function unavailable to general-purpose tokens, and that some participants will find the function useful.
                </p>
            </PaperSection>

            <PaperSection title="4. Design Rules for a Focal-Point Token">
                <p>
                    Supporting focal-point emergence is not the same as manufacturing it. A designer cannot declare that a token is a Schelling point; focality emerges from participant convergence or it does not. What the designer can do is remove features that would make convergence implausible or fragile, and add features that make convergence stable once it starts. We articulate four design rules.
                </p>
                <PaperRun title="Rule 1: Pure signaling.">
                    The token must carry <em>one</em> unambiguous reason to hold it. Holders should be alignment-signalers, not yield-chasers, governance-speculators, utility-arbitrageurs, or fee-path-optimizers. Features that would introduce non-alignment holders are forbidden. This is the most restrictive rule and generates most of the florin&rsquo;s catalogue of exclusions (Section 9).
                </PaperRun>
                <PaperRun title="Rule 2: Predictable supply.">
                    Focality is fragile under surprise inflation. A holder who believes supply is fixed may exit on learning it is not. The florin&rsquo;s supply schedule is committed at deployment and cannot be modified: 1B hard cap, staged distribution with immutable per-period budgets and immutable calendar boundaries, one-way deployer-renouncement as the last act of the genesis sequence. There are no surprise-inflation paths available to any actor once that sequence is complete.
                </PaperRun>
                <PaperRun title="Rule 3: Clean distribution.">
                    Focality is fragile under highly concentrated ownership, and it is worth being exact about which fragility is meant, since it is not the obvious one. A focal point is a claim about <em>who holds and why</em>: a participant assessing the florin reads the holder population and asks whether holding it is recognizably an act of alignment. Concentration attacks that reading directly. Where a large share sits in a few hands whose reason for holding is something other than alignment &mdash; an allocation received rather than chosen, a treasury holding for its mandate &mdash; the distribution supports no inference either way, and the signal is weak before any market opens. What a large holder&rsquo;s sale would cost is of the same kind: it is a public declaration of non-alignment by a party the distribution itself named, which is a fact about the holder population and not about the price. The price consequence is a separate matter, and Section 10 explains why a pure focal-point design neither defends it nor needs to. The florin&rsquo;s allocation is 60% to the authors and designers of record &mdash; clause authors and assembly designers &mdash; by the staged distribution, 30% to a treasury with an ecosystem mandate (the DAO), 7% to the founder, and 3% to early supporters (friends and family) carved out of the founder cut. The concentration is higher than ideal for focality &mdash; 40% is held outside the staged distribution &mdash; which we address honestly in Section 10 and in the distributional-silhouette concession in Section 11. It divides, though, into a covered part and an uncovered one, and the division is the operative fact for a rule about who can make a declaration. The token itself carries, permanently and in its own text, a stated market stance: neither the founder nor the DAO treasury will ever sell, buy, or provide liquidity for the florin on any market, the first price being a stranger&rsquo;s to name. That covers 37 of the 40 points. It is a commitment and not a mechanism &mdash; nothing on chain enforces it, and this paper does not present it as enforced &mdash; but it is a commitment made in advance, in public, in the artifact a reader inspects, which is the form of thing Rule 3 is about: it removes the two largest holders from the population of parties who could declare non-alignment by selling, and it does so at the cost of their being able to deny having said it. The remaining three points are the supporters&rsquo; allocation, which carries no such stance, and they are the uncovered holding the analysis of Section 10 turns on. On that reading the carve-out is still not a mitigation, and is if anything the reverse: re-labeling three points of the founder&rsquo;s cut as friends-and-family moved exactly those points out of the class the stance covers.
                </PaperRun>
                <PaperRun title="Rule 4: No activity may move the supply schedule.">
                    Focality requires that participants hold for alignment reasons, and a supply that responds to protocol activity destroys that requirement by paying for the activity: holders then acquire the unit by doing things that are not alignment &mdash; riding an emission curve, manufacturing volume &mdash; and a wallet balance comes to mean two things at once, &ldquo;holder by alignment choice&rdquo; and &ldquo;holder because activity happened to print me some.&rdquo; A token that means two things at once is not a Schelling point. The rule states the exclusion precisely, because a weaker or a vaguer form of it will not survive contact with Section 7. <em>No activity of any kind, at any volume, raises the florin&rsquo;s supply above the schedule fixed at deployment, and none brings any part of that schedule forward.</em> The nine instalments are fixed in size and in date before the first commitment is ever signed. Counted adoption enters only as the divisor of an instalment already fixed: it decides <em>shares</em>, never quantity, and it can only divide &mdash; and, where a share goes unclaimed, shrink &mdash; what the schedule had already set. The fastest-growing network imaginable mints not one florin more than the slowest, and not one florin sooner.
                </PaperRun>
            </PaperSection>

            <PaperSection title="5. Supply Integrity">
                <p>
                    The florin has a fixed maximum supply of <Math>{"10^9"}</Math> units (one billion). The supply ceiling is enforced by two distinct mechanisms operating at different times.
                </p>
                <PaperRun title="Per-mint enforcement (run-time).">
                    Every individual mint is checked at the moment it executes: a mint that would carry total supply above the one-billion ceiling is rejected atomically.
                </PaperRun>
                <PaperRun title="Pre-registration enforcement (deploy-time).">
                    Beyond the per-mint check, the design maintains an aggregate registered cap &mdash; the sum of the mint allowances granted to every authorized minter. A new minter cannot be registered if doing so would push the aggregate registered cap above the one-billion ceiling. The entire allocation plan is therefore committed to the <Math>{"10^9"}</Math> ceiling <em>before any token is minted</em>.
                </PaperRun>
                <p>
                    The pair (per-mint + pre-registration) is stronger than either alone in the focality frame: per-mint enforcement catches cap overruns that survive bugs; pre-registration enforcement puts the allocation plan on chain where a focality-assessing participant can read it directly rather than relying on off-chain narrative.
                </p>
                <p>
                    <span className="font-semibold text-ink-heading">The renouncement latch. </span>
                    The florin carries a one-way renouncement latch &mdash; a flag the original deployer can set exactly once, irreversibly. Once renouncement is set, no further minter can be registered and the deployer&rsquo;s own mint authority is extinguished. The genesis is a sequence of ordinary transactions, not one atomic act: the token is created, two minters are registered &mdash; the deployer wallet (cap <Math>{"4 \\times 10^8"}</Math>, for the genesis mint) and the distribution mechanism that pays the accrual periods (cap <Math>{"6 \\times 10^8"}</Math>) &mdash; the three genesis allocations are minted, and the latch is tripped last. The token offers no constructor-time registration and no batch entry, so the sequence is what it is, and the guarantee does not rest on its being indivisible. It rests on two facts that hold at every point in the sequence and after it: the aggregate registered cap can never exceed the one-billion ceiling, so once the two registrations sum to the whole billion any further minter with a positive cap is refused; and the latch, once set, cannot be unset. Once the renouncing transaction is final:
                </p>
                <ul className="space-y-1 list-disc pl-6 text-sm">
                    <li>the aggregate registered cap equals <Math>{"10^9"}</Math> exactly;</li>
                    <li>the deployer has minted exactly <Math>{"4 \\times 10^8"}</Math> to the designated founder, supporters, and DAO wallets;</li>
                    <li>only the distribution mechanism retains residual mint authority, capped at <Math>{"6 \\times 10^8"}</Math>;</li>
                    <li>no path exists to register additional minters.</li>
                </ul>
                <p>
                    The supply schedule is therefore frozen by the last of those transactions, and the contract has no further &ldquo;governance moments&rdquo; available to anyone &mdash; not to the deployer, not to the DAO, not to any future upgrade proposal. In focality terms: a participant assessing the florin at time <Math>{"t > t_{\\text{deploy}}"}</Math> can verify on chain that no further minting will occur beyond the nine period budgets. Focal convergence is not destabilized by uncertainty about supply.
                </p>
                <PaperRun title="The supply-integrity guarantees, verified.">
                    These properties &mdash; the fixed ceiling, the monotone aggregate registered cap, the immutability of each minter&rsquo;s cap, and the one-way renouncement latch &mdash; are established by formal verification rather than asserted in prose, so a focal-point participant can rely on them independently of anything the settlement primitive does. The verification is the authoring project&rsquo;s own machine checking, and no external audit of it has been performed; a participant weighing the supply guarantees should read them as claims the design makes checkable rather than as claims a third party has certified, and the properties are stated here precisely so that check is available to anyone who wants to run it. The guarantee they combine into: from the moment deployer-mint renouncement is included in a finalized transaction, total supply is bounded above by <Math>{"10^9"}</Math>, no new minters can be registered, and the only remaining mint authority is the distribution mechanism, whose period boundaries and per-period budgets are themselves frozen at deployment. What the adoption counted in a period determines is not how much that period mints but how its fixed budget divides among the claimants &mdash; and a share of the budget nobody claims is simply never minted, so the schedule is a ceiling on each period as it is on the whole. Every quantity entering that division is maintained by the chain itself, frozen when the period closes, and readable directly from on-chain state.
                </PaperRun>
            </PaperSection>

            <PaperSection title="6. Allocation: 7 / 3 / 30 / 60">
                <p>The total supply is split:</p>
                <ul className="space-y-1 list-disc pl-6 text-sm">
                    <li><strong>Founder</strong> &mdash; 7% (70M) &mdash; genesis mint, no vesting, no unlock.</li>
                    <li><strong>Supporters</strong> &mdash; 3% (30M) &mdash; friends and family / early supporters, carved out of the founder cut, genesis mint, no vesting, no unlock.</li>
                    <li><strong>DAO</strong> &mdash; 30% (300M) &mdash; genesis mint, no vesting, no unlock.</li>
                    <li><strong>Clause authors and assembly designers</strong> &mdash; 60% (600M) &mdash; claimed pro rata over nine annual accrual periods, ending at years 1 through 9, each period&rsquo;s budget fixed at deployment and grouped into three rising tranches (15% / 30% / 55%); a share of a budget nobody claims is never minted.</li>
                </ul>
                <PaperRun title="Founder allocation (7%).">
                    A modest founder share, by contemporary norms. The non-vesting choice is deliberate: a vesting cliff is a tacit promise of future voting alignment or schedule-driven holding, both of which would be reasons to hold florins other than alignment signaling. The structural observation is that an unvested founder forgoes an asymmetric option (sell into early demand if it materializes; ride out the vesting if it does not) that a vested founder retains, and we have chosen to forgo the option &mdash; twice over, since the standing market stance below gives up the sale itself and not merely its scheduling. The 3% supporter allocation &mdash; friends and family and early supporters, carved out of the founder&rsquo;s cut rather than the DAO&rsquo;s &mdash; is held on identical <em>vesting</em> terms and on no market stance at all: genesis mint, unvested, and exposed at genesis to whatever consequences attach to sale, for the same reason (a vesting cliff on supporters would recruit exactly the schedule-driven, non-alignment holders the non-vesting choice is designed to exclude). The prior question &mdash; whether founder and supporter allocation at this magnitude is the right allocation at all &mdash; is a political-economy question we do not attempt to answer in a cryptoeconomic paper.
                </PaperRun>
                <PaperRun title="The bootstrap-dump scenario.">
                    A fair objection to the no-vesting choice is the bootstrap-dump scenario: between genesis (year 0) and the first annual claim at year 1, the genesis allocations are the whole of the circulating supply and are liquid on identical terms, while focal convergence has not yet had time to establish the stickiness that makes a later sale survivable. The damage in question is the one Rule 3 names, not a price move: an insider sale in this window is a public declaration of non-alignment by a party the distribution itself named, made at the moment when the holder population is small enough for one declaration to characterize it. A prospective aligned holder reads the population and finds the people who launched the unit leaving it, which is how emergence gets foreclosed. What the objection reaches, given the stated stance, is 3% and not 10%: the founder&rsquo;s 7% and the treasury&rsquo;s 30% are covered by a commitment made before any of this and readable in the token itself, and the supporters&rsquo; 30M is the position no stance covers. Section 10 treats sales against an established focal point, where the reading is far more robust; the bootstrap window is the case where it is weakest, and it is treated here.
                </PaperRun>
                <p>
                    The answer, for the covered part, is that the risk is met by a declaration rather than by a schedule, and for the uncovered part that it is accepted. Two reasons for the shape of that. First, vesting would import the same focality-dilution problem the non-vesting choice was designed to avoid: a founder who must vest will be a holder for schedule-driven reasons that are not alignment, and the schedule itself becomes a Schelling object that competes with the underlying alignment signal. Second, the risk is a risk about a declaration, so the instrument that answers it is a declaration &mdash; and the declaration has been made. The token states permanently, in its own text, that neither the founder nor the DAO treasury will ever sell, buy, or provide liquidity for the florin on any market; the first price is a stranger&rsquo;s to name. That is not a window and not a cliff but a standing position, it addresses the actual harm where a vesting schedule would only postpone the moment of it, and it is what a reader sent to the contract by Section 5 will find written there. Its register should be stated exactly: it is a commitment, enforced by nothing on chain, and a party that broke it would find the breach permanently legible next to the words &mdash; which is the whole of its force, and is a different kind of thing from the supply guarantees, which are enforced by code. The supporters&rsquo; 3% carries no such stance; that holding is exposed as any holding is, and we do not dress the absence as a mitigation.
                </p>
                <PaperRun title="DAO allocation (30%).">
                    A treasury share, available immediately at genesis. The DAO is not a governance body over the settlement mechanism &mdash; there is no such governance to be done &mdash; but a coordination treasury for ecosystem activity (grants, public goods, reference implementations). Releasing the DAO allocation at genesis means the treasury is operational from day one. A fair objection: doesn&rsquo;t a liquid 30% treasury with an ecosystem-grants mandate create exactly the reflexivity that activity-coupled supply would (Rule 4), and doesn&rsquo;t it dilute the florin&rsquo;s focal-point purity (Rule 1)? We concede the objection in its general form. The defense is narrower than the objection implies, and it turns on what Rule 4 actually forbids. What that rule excludes is any function from activity to the <em>quantity</em> minted &mdash; a deterministic path by which doing more trade puts more florins into existence, or puts them there sooner. The treasury creates no such path: its 300M was minted at genesis and no amount of trade adds a unit to it. What it does create is a <em>policy-level</em> coupling &mdash; a human-discretionary function from treasury governance to disbursement &mdash; and that is a real cost to Rule 1 rather than a violation of Rule 4, attenuated by two layers of friction (off-chain discretion, revocable grants) and by the fact that a grant recipient&rsquo;s holding is legible as what it is. The distinction is principled but not absolute: a sufficiently mechanical grant policy, paying out as a function of measured activity, would manufacture at policy level the coupling the schedule forbids at mechanism level, which is why the DAO&rsquo;s operating procedures are themselves a design object rather than a silent assumption.
                </PaperRun>
                <p>
                    A reader who has followed the paper&rsquo;s repeated claim that the settlement mechanism is ungoverned &mdash; no admin, no owner, no vote can move a bonded commitment or alter any parameter of it, ever &mdash; may see a tension in a DAO that governs a 300M-token treasury by discretionary decision. There is none, because the two are different objects at different tiers. That absence of governance is a property of the settlement mechanism itself: nothing the DAO does, votes on, or spends can touch how a bonded commitment resolves, because the DAO holds no key or role in that mechanism at all. What the DAO governs is its own treasury &mdash; which public goods to fund, which programs to stand up, who gets paid &mdash; the ordinary discretion any treasury-holding body exercises over its own assets. A vote of the DAO can redirect the 300M; no vote, by the DAO or anyone else, can redirect a single bonded commitment.
                </p>
                <PaperRun title="Author-and-designer allocation (60%).">
                    The majority share, allocated over a calendar window in nine annual instalments of rising size. The structure is designed to (a) reach the two recipient classes on identical terms &mdash; the clause authors of record and the assembly designers of record, each credited by their own registry and each scored by the same rule &mdash; (b) reward sustained contribution, since a contributor whose work is still being adopted in year seven is paid for that year as fully as for their first, and (c) avoid the &ldquo;dump-on-launch&rdquo; dynamic of a single distribution event by spreading the emission over a nine-year horizon.
                </PaperRun>
                <p>
                    What divides an instalment is counted usage and nothing else. For each clause and each assembly, a period holds two quantities, both accumulated by the chain as trade settles: how many settled processes carried it, and how many <em>distinct</em> sellers of record carried it while holding a live registration stake. One fixed function of those two numbers is the entry&rsquo;s score for that period &mdash; the same function for every entry, weighted so that reaching more distinct counterparties counts for more than repeating with the same one &mdash; and the period&rsquo;s fixed budget divides pro rata across the scores. Settlement reaches the chain by more than one route, and the function is applied to each route&rsquo;s counts separately and the results summed, rather than the counts being pooled first; since the same counterparty may appear on both routes and the chain cannot tell, summing scores can understate an entry&rsquo;s breadth and can never overstate it, which is the direction to err in. There is no category, no tag, no editorial weight, no per-wallet cap, and no matching round: an entry&rsquo;s score is its real usage, and the score of a clause that coordinates something the designers consider important is computed exactly as the score of one they do not. Two refinements apply, both structural and both uniform. A floor: an entry scores nothing at all in a period until some small fixed number of distinct staked sellers have used it, which is the smallest count at which a solo or paired arrangement cannot reach the scoreboard by transacting with itself. And an exclusion, fixed at deployment: three registrations that ride every agreement or nearly every one &mdash; the generic commerce clause, the topology clause, and the clause by which an agreement names the assembly it was composed from &mdash; earn nothing at recording time, since scoring the floor everyone must carry would pay its author for the protocol&rsquo;s own mandatory carriage rather than for adoption anybody chose. That is a statement about what carriage is, not a judgment of merit, and with those three set aside the uniformity claim holds of everything that scores.
                </p>
                <p>
                    Neutrality here is carried by the stake rather than by any weighting, and the two are alternatives. A weighted formula would have the designers deciding whose contribution matters, which is precisely the discretion the uniform rule exists to avoid; what stands in its place is a live stake in the network&rsquo;s base currency on both sides of the count &mdash; a seller&rsquo;s usage counts only while that seller&rsquo;s own stake is live, and an author or designer earns only while the stake behind their registration is live. That stake is not a fee and is paid to nobody: it is returnable, it is held in the currency the network&rsquo;s own gas is paid in, and holding it is exposure to the growth the holder&rsquo;s own work produces. What it prices is the fabrication of identities, which is the only lever by which counted usage can be manufactured; and it is honest to record that this aligns the participants who stay rather than deterring every possible fabricator. Nothing here is granted to a participant for participating: a wallet that trades heavily, and is the author or designer of record of nothing, receives nothing from this share.
                </p>
                <p>
                    The nine annual budgets group into three rising tranches: 15% of the reserve across years 1&ndash;2, 30% across years 3&ndash;5, and 55% across years 6&ndash;9, split equally within each group, so the instalments are 45M, 45M, 60M, 60M, 60M, and 82.5M four times over. The schedule rises rather than front-loads or declines. The reason is that each instalment is divided by measured adoption, and the measurement is thinnest exactly when the network is youngest: an early year is both the least informative reading of what was actually adopted and the most manipulable, since a small honest denominator is a cheap one to dilute. Putting the largest budgets where the evidence is best aligns the size of each instalment with the quality of the division it will be subject to. The early-years bootstrap need that motivated front-loading is real, and it is met by a different instrument &mdash; the DAO&rsquo;s 30% treasury, which funds work by human judgment before the evidence exists and is designed for exactly the case where no measurement is yet available.
                </p>
                <PaperRun title="A note on the specific percentages.">
                    The 7/3/30/60 split and the internal 15/30/55 grouping of the distribution reflect a design judgment rather than a first-principles derivation. Any rising schedule of comparable shape would satisfy the measurement argument above, and the specific weights are a calibration we do not attempt to justify beyond &ldquo;plausible under the stated principles.&rdquo; What is not a free calibration is the direction: a schedule that pays most where the denominator is thinnest maximizes exposure at the point of least evidence, and no choice of weights repairs that.
                </PaperRun>
            </PaperSection>

            <PaperSection title="7. Staged Distribution over Counted Adoption">
                <p>
                    The 600M share is realized by a single minter holding one budget per accrual period, all nine fixed at deployment, with no privileged path to add a period, extend the schedule, resize a budget, or alter who is eligible. Adoption is counted on chain at the moment it happens, by a recording call anyone may make: it verifies for itself, from state the chain already holds, that the order settled and that the clause or assembly was named in the agreement the parties signed, and on that verification it increments the two counts of Section 6. Everything a period&rsquo;s division needs is therefore already final when the period closes, and a claim is arithmetic over it &mdash; minted straight to the claimant, at the claimant&rsquo;s own initiative, in one call.
                </p>
                <p>
                    That is the entire relation between settlement and the florin, and the paper holds one position on it, stated here and carried everywhere else: <em>no settlement operation mints, consults, or denominates in the florin; the coupling runs one way &mdash; the distribution layer reads what settlement has already recorded, and nothing the florin does can reach back into a bonded process.</em> Both halves need saying, because each is misleading alone. There <em>is</em> a path from settled trade to a florin mint, and this section is that path: an order settles, a recording call verifies the settlement and credits the clause or assembly the parties named, and at the period&rsquo;s close that credit is part of the divisor by which a fixed instalment is shared out. Denying the path would be false, and the design does not depend on denying it.
                </p>
                <p>
                    What the design does depend on is the direction, and the direction holds in three separable senses. <em>The reading cannot write.</em> No florin balance, mint, claim, schedule, or period boundary alters a bond, a payout, a resolution, or any term of a commitment; a process settles identically whether or not anyone ever records it, and a party who never hears of the florin transacts on exactly the terms of one who holds a great many. <em>The reading cannot pay.</em> The recording call moves no value to any party and confers no advantage inside the process it read; whoever pays the gas to make it is doing so for a credit that accrues to an author or a designer, not to the trade. <em>And the reading cannot expand.</em> Counting divides an instalment and never adds to one, so the most a settlement can do to the florin&rsquo;s supply is change <em>who</em> receives a quantity that was already going to exist &mdash; or, where a share goes unclaimed, ensure that less of it does. This is what makes the arrangement compatible with Rule 4 rather than an exception to it: Rule 4 forbids activity from moving the schedule, and nothing here moves the schedule.
                </p>
                <PaperRun title="Single mechanism, one schedule.">
                    The single-mechanism design is preferred for two reasons. First, surface area: a single mechanism is a single audit target and a single locus of state. Second, the genesis arithmetic: the mechanism&rsquo;s <Math>{"6 \\times 10^8"}</Math> cap is registered before the latch is tripped, and one mechanism holding the whole reserve is what lets the two registered caps sum to the ceiling exactly &mdash; which is the fact, rather than any atomicity in the deployment, that leaves no room for a third minter afterwards (Section 5).
                </PaperRun>
                <PaperRun title="One-shot per (period, address).">
                    Each (period, address) pair is marked claimed on a successful claim and checked on every entry. A given account can claim at most once per period, presenting every clause it authored and every assembly it designed &mdash; each checked against its own registry, and each required to have a live stake behind it &mdash; in that single call, with repeats within the list rejected outright. No top-up, no re-claim, no rebate.
                </PaperRun>
                <PaperRun title="Calendar boundaries, fixed budgets.">
                    Period boundaries are calendar timestamps (Unix epoch seconds) and each period&rsquo;s budget is a constant set at deployment. Neither the size of an instalment nor the moment it becomes claimable is a function of anything the network does. This is the second half of Rule 4 and the reason the rule is stated in two clauses rather than one: a supply that activity cannot enlarge could still be a supply that activity <em>accelerates</em>, if a boundary were tied to a volume threshold, and a network able to transact its way to the next instalment would be paying itself for volume by another route. Calendar timing also has the plain virtue of being predictable to everyone at deploy time, which is itself a focal property &mdash; there is nothing to watch, model, or race.
                </PaperRun>
            </PaperSection>

            <PaperSection title="8. Three Kinds of Token, and a Signal, Meet in One Process">
                <p>
                    The catalogue in the next section is a list of refusals, and a refusal is only legible against what is being refused. This section supplies the neighbors. An ordinary bonded process brings as many as four distinct kinds of token claim into contact &mdash; three of them kinds of unit something might be denominated in, and one of them not a token at all but a signal the choice of denomination emits. The florin is one of the four and only one, and saying which one it is does more to locate the design than the exclusions can do on their own.
                </p>
                <PaperRun title="Coordination tokens, of which the florin is the limiting case.">
                    A process settles in a single unit &mdash; fixed by the first signatures and binding on every later link &mdash; so the parties must agree on one. The ordinary answer is whichever unit is recognized widely enough to make agreement cheap: a fiat-referenced stablecoin, or the base network&rsquo;s own asset. Neither is chosen for what it does; each is chosen because each party expects the other to accept it, which is focal convergence operating at the settlement layer rather than at the alignment layer. The florin belongs to this kind and sits at its extreme. Everything a coordination unit might additionally be valued for &mdash; a redemption claim on an issuer, necessity for paying for computation, a reserve, a fee path &mdash; the florin refuses, and what is left when the refusals are exhausted is focality with nothing underneath it. That is the content of calling the florin the <em>pure</em> Schelling point among coordination units, and it is not a claim to be a better stablecoin: a dollar-referenced unit coordinates on the dollar and carries the dollar&rsquo;s issuer along with it, while the florin coordinates on the ecosystem and carries no one. Nothing prevents two parties from denominating a process in florins, and nothing in the protocol encourages it. The design&rsquo;s commitment is simpler and stronger than a stated preference: no operation denominates in the florin, levies anything in it, or treats it differently from any other unit, and there is no place in the stack where a florin-denominated process is cheaper, faster, better secured, or more visible than one denominated in anything else. That is the denomination exclusion of Section 9, and its point is to keep a party&rsquo;s choice to settle in florins a declaration rather than an optimization.
                </PaperRun>
                <PaperRun title="Utility tokens, which the tier above may pin.">
                    A designer who publishes an assembly &mdash; a reusable deal shape that others compose their processes from &mdash; may fix the denomination every process running that assembly settles in, and may fix it to a token of the designer&rsquo;s own. That token then does something in the strict sense: transacting through the assembly requires acquiring it, and demand for it tracks the assembly&rsquo;s adoption. This is a utility coupling of the textbook kind, and at the assembly tier it is entirely legitimate &mdash; a moat the designer builds and bears the risk of, and one users can walk away from by choosing an assembly denominated in something they already hold. The tier distinction is what keeps this from contradicting the florin&rsquo;s design. The settlement primitive takes any standard, non-rebasing unit and privileges none; the protocol levies no fee in any unit; a designer&rsquo;s pin binds the users of one assembly by their own choice to use it. The florin&rsquo;s exclusions forbid at the base exactly what a designer may do freely above it, and the two statements sit together rather than in tension.
                </PaperRun>
                <PaperRun title="Community tokens, and the value a distant purchase sends home.">
                    A third kind rests on mutual recognition within a group rather than on a reserve or a mechanism: a local economy&rsquo;s or a displaced community&rsquo;s own unit, valuable because its members treat it as valuable. A member living far from that community can transact in it where they now are, provided a counterparty will hold the unit or a conversion into the process denomination is available before commitment. Where that works, demand generated in Los Angeles or Lima accrues to a unit whose community is elsewhere, and it does so without a remittance corridor, a correspondent bank, or any fiat pipeline: the conversion is an ordinary swap at a public venue, performed by the participant for their own account, before any bonded state exists. What the substrate contributes here is not the token and not the corridor. It is that a stranger can transact safely with a member of a community they know nothing about &mdash; which is the thing the corridor and its intermediaries were previously needed to supply. Whether a self-performed swap changes any particular jurisdiction&rsquo;s treatment of the transaction is a question for that jurisdiction, on which Section 12 says what we think a token paper can responsibly say. The florin is not this kind of unit and does not aspire to be: it signals alignment with an ecosystem, not membership in a place.
                </PaperRun>
                <PaperRun title="The signal a denomination emits, which is not a token at all.">
                    The fourth thing meeting in the process is a byproduct of the other three. The denomination of every commitment is on the public record, so which unit a party was willing to accept is visible to anyone and checkable against the record rather than taken from a claim. A seller who accepted a community&rsquo;s unit where a stablecoin was available has performed a legible act of support; a designer who denominated an assembly in a token has declared what they are building on; a participant who bonded in the base asset has declared nothing beyond convenience. This is precisely the property the florin is built to concentrate, and the difference is instructive in two ways. The other three units emit the signal as a side effect of being useful for something else, so it always arrives mixed with the usefulness; the florin has nothing else to be useful for, so it arrives unmixed. And with the other three only a recorded <em>use</em> signals anything &mdash; a balance in them is mute, since it could have been acquired for any of the reasons the unit serves (Section 3) &mdash; whereas a florin balance signals on its own, there being nothing else for holding one to be for. That is what the catalogue below is protecting, one exclusion at a time.
                </PaperRun>
                <p>
                    With the neighbors in view the exclusions read as position-taking rather than as asceticism. Each one in Section 9 is a refusal to become one of the other three kinds: not a utility token (the fee-path and denomination exclusions), not a claim on anything an issuer holds (no yield, no fee pool), not an instrument whose supply responds to how much the ecosystem transacts (the schedule is fixed, and adoption divides it rather than adding to it). What survives every refusal is the one kind the florin was designed to be, and the fourth item above &mdash; the signal &mdash; is the only thing it is for.
                </p>
            </PaperSection>

            <PaperSection title="9. Design Exclusions as Focality Preservers">
                <p>
                    The cryptoeconomic content of the florin is largely defined by what the design excludes. We catalogue the exclusions and tie each to the focality property it preserves. With the Schelling-point framing the reasons unify: each exclusion removes a class of holder whose reason for holding florins would be something other than alignment signaling, and so each preserves Rule 1 (and, where noted, Rule 4).
                </p>
                <ul className="space-y-2 list-disc pl-6 text-sm">
                    <li><strong>Not a governance token.</strong> The settlement mechanism has no governance surface to vote on &mdash; nothing decides a resolution but the buyer who bonded &mdash; and the florin conveys no vote over it; a governance role would recruit governance speculators who hold to vote, not to signal alignment.</li>
                    <li><strong>Not yield-bearing.</strong> The protocol takes no fee, so there is no fee pool to distribute, and no holding of florins earns anything by being held; a stake-and-earn mechanism would recruit yield farmers and would make the supply a function of activity, which Rule 4 forbids.</li>
                    <li><strong>Not a fee path.</strong> No operation of the protocol levies a fee for itself, in florins or in anything else &mdash; no skim on a payment, no charge for a registration, and the registry stakes are returnable deposits rather than fees &mdash; so there is no flow of ecosystem activity that has to pass through florin-denominated demand. The distinction to hold is protocol-levied against network-levied: every transaction on a public chain pays that chain&rsquo;s own fee in that chain&rsquo;s own unit, which is a cost of using the network and reaches nobody here. What a third party charges for its own services is likewise that party&rsquo;s business and outside the protocol entirely; what the exclusion forbids is a protocol path that makes acquiring florins a precondition of transacting, which would recruit utility arbitrageurs who buy in order to trade rather than to signal.</li>
                    <li><strong>Not privileged as a denomination.</strong> A process settles in one unit fixed at its first signature, and the parties choose which; the florin is one candidate among every standard, non-rebasing fungible unit and is favoured nowhere &mdash; no operation denominates in it, no path is cheaper or better secured for choosing it, and no registry, assembly, or clause treats it as a default. Privileging it would couple the florin to trade through the back door and would turn a declaration into an optimization.</li>
                    <li><strong>Not founder-vested.</strong> The founder, supporter, and DAO allocations are unvested &mdash; no cliff, no schedule; vesting would recruit schedule-driven holders, whose clearest instance is a founder vesting into liquidity over years for mixed reasons.</li>
                    <li><strong>Not supply-coupled to activity.</strong> No volume of trade, and no pattern of it, raises the florin&rsquo;s supply above the schedule fixed at deployment or brings any instalment forward. The instalments are constants; adoption is a divisor applied to a constant; an unclaimed share is never minted. No mechanism that observes settlement holds mint authority beyond that schedule, and the renouncement latch closes the door on granting one later.</li>
                    <li><strong>Not a party to any bonded process, and coupled to settlement in one direction only.</strong> This is the exclusion most easily overstated, so it is stated exactly. No settlement operation mints, consults, or denominates in the florin; the coupling runs one way &mdash; the distribution layer reads what settlement has already recorded, and nothing the florin does can reach back into a bonded process. The distribution therefore <em>does</em> stand downstream of settlement, by the reading path of Section 7, and it is not a sibling of the settlement mechanism nor independent of it. What it is not is a participant: it deposits nothing, receives nothing, decides nothing, and is on no path by which a bond is released. That is why its existence leaves every result about the mechanism exactly as it was &mdash; the mechanism&rsquo;s equilibrium is derived over two operations and the parties that bonded, and a read-only observer downstream of settlement adds no node, no continuation, and no term to any payoff.</li>
                </ul>
            </PaperSection>

            <PaperSection title="10. Bootstrap and Attack Surface">
                <p>
                    A Schelling-point token cannot be declared; it must be <em>recognized</em>. This section is the most uncertain part of the design, because it concerns processes we cannot directly control.
                </p>
                <PaperRun title="Bootstrap: how the florin achieves focal status.">
                    Focal-point emergence for a newly-launched token depends on several converging factors, none of which the designer can guarantee: the <em>first recipients</em> (the first annual period&rsquo;s budget is 45M, divided among the authors and designers of record &mdash; clause authors and assembly designers on identical terms &mdash; whose clauses and assemblies real trade used in that period, with any share nobody claims never minted; these are the first holders outside the genesis allocations, and the first with an occasion to recognize the florin as a focal point); <em>design legibility</em> (the design rules and exclusions must read as consistent with focal-point coordination rather than as random design preferences &mdash; this paper is part of that legibility work); and <em>absence of competing focal candidates</em> (if an alternative token launched with better focal properties at a moment when the florin had not yet stabilized, participants might converge on it instead). The design attempts to make the florin hard to beat on focal grounds (Rule 1 purity, Rule 2 supply predictability) but cannot preempt all competitors.
                </PaperRun>
                <PaperRun title="Focal-shift attack.">
                    The relevant attack against a Schelling-point token is the <em>focal-shift attack</em>: an adversary, through concerted action, moves focal convergence to a different token. The canonical example is the decade-long debate over whether Bitcoin-Cash or Bitcoin-SV could displace Bitcoin as the store-of-value focal point; neither succeeded, but both made the attempt at significant scale. The defense is Schelling stickiness: participants who have converged on a focal point typically hold through attempts to move the focus, because moving costs coordination value.
                </PaperRun>
                <PaperRun title="Dump attacks.">
                    An adversary with large florin holdings can attempt to destabilize focal-point status by dumping supply. In a pure Schelling-point frame this is <em>less damaging</em> than in a yield-anchored or governance-anchored frame, because there is no cash flow or vote whose value a falling price impairs: florin holders are holders by alignment choice, and the price of the florin is largely decoupled from its focal status. A price crash that leaves participant alignment unchanged does not destroy the focal point; a loss of participant alignment does, at any price. This is the same distinction Rule 3 rests on, and the two statements are one position seen from opposite ends. What a sale can damage is the <em>readability of the holder population</em>, and it damages it in proportion to <em>who</em> is selling rather than how far the price moves: an anonymous holder liquidating is a market event and little else, while a party the distribution itself named selling is a declaration, and is read as one. Rule 3&rsquo;s concern with concentration is therefore a concern about how many parties are in a position to make such a declaration, and the defense against a dump was never a price defense. Two of the three named parties have foreclosed the declaration in advance, by the standing statement in the token&rsquo;s own text that neither founder nor treasury will ever sell, buy, or provide liquidity on any market. Nothing on chain holds them to it; what holds them to it is that the statement is permanent and the breach would be public, so breaking it is the strongest possible signal of exactly the thing a focal point cannot survive. The named party that has made no such statement is the supporter class, and its 3% is the residual this analysis leaves live.
                </PaperRun>
                <PaperRun title="Acquiescence attacks.">
                    The quietest attack is no attack at all: nobody converges, and the florin fails to become a focal point. This is possible and unavoidable. The defense is limited &mdash; we can support focal emergence but cannot force it. The honest statement is that if no one recognizes the florin as a focal point, the unit has no Schelling-point value and is simply an unvalued token that a fixed schedule goes on issuing. The supply-integrity and allocation properties continue to hold in that case; only the signaling function fails.
                </PaperRun>
                <PaperRun title="The griefing attack.">
                    A <em>griefing</em> attack is worth considering directly: an adversary who writes code to drain the reward pool not for profit but for spite, given that no governance or fee-extraction capture is available. The attack surface is narrow: a claim mints only to the caller, only for clauses and assemblies the registries record that caller as author or designer of and whose registration stake is still live, only in proportion to adoption the chain itself verified and has since frozen, only once per period, and only up to that period&rsquo;s fixed budget, which the minter enforces beneath the token&rsquo;s own independent cap on it. There is no pool to drain: once a period has closed, nothing anyone does can raise their own share or lower anyone else&rsquo;s, because both the numerator and the denominator have stopped moving. The sell-at-claim surface remains (a recipient can claim as soon as a period closes and sell), but that is indistinguishable from the normal operation of the distribution; it is not an exploit.
                </PaperRun>
            </PaperSection>

            <PaperSection title="11. Substrate-Neutrality and Distributional Silhouette">
                <p>
                    The bonded settlement <em>primitive</em> is a substrate on which multiple organizational forms can be expressed. The present paper describes the florin, a specific token ecosystem that ships alongside it. Those two statements are about different objects and a careful reader should not confuse them.
                </p>
                <p>
                    The florin&rsquo;s 7/3/30/60 allocation is <em>one</em> instantiation of a token economy over the substrate. The substrate is neutral; the florin is not. If the distributional silhouette of the florin &mdash; early founder and supporter allocations, a large standing treasury, authors and designers of record paid out on a calendar schedule &mdash; rhymes with the silhouette of prior platform-capital arrangements that a political-economy critique would target, that rhyme is a feature of this specific unit&rsquo;s distribution, not of the substrate, and not inherent to the Schelling-point framing. Different focal-point tokens could be launched with different silhouettes (flatter, community-only, non-founder), and the Schelling-point design principles would apply to them unchanged.
                </p>
                <p>We flag this explicitly to disentangle three claims:</p>
                <ul className="space-y-2 list-disc pl-6 text-sm">
                    <li><strong>Substrate-neutrality (true of the settlement primitive)</strong>: the bonded settlement primitive does not impose any particular distributional structure on tokens or organizations.</li>
                    <li><strong>Focal-point integrity (true of the florin)</strong>: the specific supply mechanism and exclusion catalogue enforce the allocation and the focality-preservation properties at deploy.</li>
                    <li><strong>Allocation legitimacy (out-of-scope)</strong>: whether 7/3/30/60 is the <em>right</em> allocation, whether a 30% liquid treasury is an appropriate ecosystem-coordination vehicle, and whether the implicit authority of the DAO over grant direction reproduces soft-governance patterns a platform-hegemony analysis would critique &mdash; these are political-economy questions the present paper does not resolve.</li>
                </ul>
            </PaperSection>

            <PaperSection title="12. Regulatory Framing">
                <p>
                    A token paper that takes itself seriously must address the regulatory-status question, even if the answer it produces is provisional and jurisdictionally bounded. We address the question here in three registers &mdash; US securities law, EU MiCA, and a structural register prior to specific regimes.
                </p>
                <PaperRun title="The Howey four-prong test.">
                    Under <em>SEC v. W. J. Howey Co.</em> (1946) and its extensive subsequent application to token offerings, an investment contract exists where there is (i)&nbsp;an investment of money, (ii)&nbsp;in a common enterprise, (iii)&nbsp;with an expectation of profit, (iv)&nbsp;derived from the entrepreneurial or managerial efforts of others. The SEC&rsquo;s 2019 <em>Framework for Investment Contract Analysis of Digital Assets</em> extended the test to digital-asset arrangements specifically (SEC, 2019), weighing factors that bear on each prong. The florin&rsquo;s position relative to the four prongs is, on our reading, the following.
                </PaperRun>
                <p>
                    (i)&nbsp;<em>Investment of money.</em> There are three ways to come by florins, and they answer the prong differently. The genesis allocations &mdash; founder, supporters, DAO &mdash; were minted to their wallets in the deployment transaction, with no consideration delivered by the recipient and no offering of any kind. A period claim mints a share of a closed period&rsquo;s fixed budget to an author or designer of record, and is likewise not an investment of money in the ordinary sense: nothing is delivered to an issuer, and what the claimant supplied was authorship the network adopted. Secondary-market purchase is an investment of money in the same sense any token acquisition is. Prong (i) is therefore satisfied for secondary acquisition and not for either mint path. Most analyses treat this asymmetry as not dispositive &mdash; the secondary market is the more material context &mdash; so we proceed assuming prong (i) is met for the relevant population.
                </p>
                <p>
                    (ii)&nbsp;<em>Common enterprise.</em> The doctrinal test for &ldquo;common enterprise&rdquo; is jurisdictionally split (horizontal vs. vertical commonality) but typically asks whether the investor&rsquo;s fortunes are tied to the enterprise&rsquo;s fortunes through pooling of assets or sharing of profits. The florin is not pooled, has no profit-sharing arrangement, and is not tied to a treasury whose performance distributes to holders. The DAO treasury holds 30% of supply (Section 6) and disburses grants under its own governance, but treasury distributions are not pro-rata to florin holdings and do not constitute profit-sharing. Prong (ii) is the weakest of the four for the florin; we read it as likely <em>not</em> satisfied under either commonality test for the florin as currently constituted, with the caveat that the DAO&rsquo;s disbursement policy is the relevant variable and a sufficiently mechanistic disbursement policy could re-implicate the prong.
                </p>
                <p>
                    (iii)&nbsp;<em>Expectation of profit.</em> Holders may reasonably expect the florin to appreciate if the focal convergence strengthens. This is an expectation of profit in the ordinary sense, and prong (iii) is met.
                </p>
                <p>
                    (iv)&nbsp;<em>Derived from the efforts of others.</em> This is the prong on which most token cases turn under the SEC framework. The framework weighs whether an active participant (developer, foundation, promoter) is undertaking essential managerial efforts on which the holder&rsquo;s profit expectation depends. The florin&rsquo;s deployment, as Section 5 sets it out, registers the deployer as a one-shot minter, mints the founder, supporter, and DAO allocations, and renounces &mdash; permanently, by a code-enforced one-way latch. After deploy, the founder&rsquo;s effort is not managerial in any sense the framework recognizes: the founder holds liquid florins as any holder does, has no protocol-level authority, cannot mint, cannot upgrade, cannot freeze, and has no fiduciary relationship to other holders. The DAO has treasury authority over its own allocation but not protocol authority over the florin. The development of the underlying Figaro protocol is a separate question, governed by a separate and ongoing analysis; the florin is not coupled to that development through any protocol-level mechanism. Prong (iv) is, on our reading, partially met (insofar as ecosystem development is happening and holder profit expectations may depend on it) and partially not met (insofar as the relationship between holder profit and developer effort is reflexive, not contractual or fiduciary). The prong is the hardest to assess because the SEC framework&rsquo;s factors were written with team-managed token projects in mind, and the florin is structurally a less-managed instrument than the framework contemplates.
                </p>
                <p>
                    The honest summary is that the florin&rsquo;s position relative to Howey is uncertain and varies with the development trajectory of the broader Figaro ecosystem. We do not claim the florin is not a security; we claim that the design is engineered to minimize the prongs&rsquo; applicability, and that the resulting position is defensible but not assured. This is the most we believe a cryptoeconomic paper can responsibly say. Specific jurisdictional advice belongs in a regulatory submission, not in this venue.
                </p>
                <PaperRun title="EU MiCA.">
                    The Markets in Crypto-Assets Regulation (European Parliament and Council, 2023) classifies crypto-assets into asset-referenced tokens, e-money tokens, and &ldquo;other&rdquo; crypto-assets, with distinct disclosure and authorization regimes. The florin is not asset-referenced (no reserve), not e-money (no nominal-value stability target), and would fall in the residual &ldquo;other&rdquo; category, subject to the white-paper publication requirement of MiCA Title II. The MiCA regime is more permissive of focal-point-style instruments than Howey is, conditional on disclosure compliance, and we treat MiCA as a tractable disclosure obligation rather than as an existential classification question.
                </PaperRun>
                <PaperRun title="Structural register.">
                    The DAO-allocation tension flagged in Section 6 is also a regulatory one: a 30% treasury with grant-disbursement authority is the structural feature most likely to re-implicate prong (iv) of Howey if the disbursement policy becomes mechanically tied to holding behavior. Keeping that policy at human discretion, separated from holding by the two layers of friction identified in Section 6, is therefore a regulatory discipline as well as a focality-protection discipline &mdash; but the alignment of the two is not a substitute for legal advice in any specific jurisdiction.
                </PaperRun>
            </PaperSection>

            <PaperSection title="13. Conclusion">
                <p>
                    The florin is a small design. Most of its positive content is procedural (supply cap, renouncement latch, staged distribution over accrual periods) and most of its substantive content is negative &mdash; the catalogue of exclusions of Section 9. Under the framing this paper develops, the negatives are not restraint without purpose &mdash; they are the specific design discipline required to support focal-point emergence. Every exclusion removes a class of holder whose presence would dilute the signaling value of the florin for participants who hold for alignment reasons. The exclusion most easily mis-stated is the one about settlement, and the paper has held one form of it from the abstract onward: no settlement operation mints, consults, or denominates in the florin; the coupling runs one way &mdash; the distribution layer reads what settlement has already recorded, and nothing the florin does can reach back into a bonded process. The unit stands downstream of trade and out of its way.
                </p>
                <PaperRun title="The lineage, made explicit.">
                    Nakamoto (2008) took money out of institutions and made it a protocol; Bitcoin is the Schelling point at the money layer. Buterin (2014) made contracts composable and put ETH at the focal point of programmable settlement. The present work extends the pattern to institutions: bonded commitments are composable into arbitrarily large assemblies, and the florin is the focal point for aligned participation in that composition. Each layer&rsquo;s token is a coordination anchor tied to its base, though the <em>type</em> of tie is not the same across the three (Section 3): the lineage is real; the homology is not mechanical.
                </PaperRun>
                <PaperRun title="What the design can and cannot do.">
                    Schelling-point design is a matter of supporting emergence, not causing it. The design rules of Section 4 and the exclusions of Section 9 make focal-point convergence on the florin viable: a participant who wants to signal alignment can do so by acquiring and holding florins, and the design ensures the signal is not muddied by non-alignment holders. Whether focal-point convergence <em>happens</em> is a social process we do not control. We document the design so that those who choose to converge can do so legibly, and so that those who do not can see what they are declining.
                </PaperRun>
            </PaperSection>
        </PaperLayout>
    );
}
