import type { Metadata } from "next";
import { withOg } from "@/lib/shared/pageMetadata";
import {
    PaperLayout,
    PaperSection,
    PaperRun,
} from "@/components/papers/PaperLayout";
import { Math } from "@/components/papers/Math";

export const metadata: Metadata = withOg({
    title: "From Firms to Transaction-Scoped Institutions — Figaro Protocol",
    description:
        "The Coasean collapse: when a stranger's promise enforces itself for the network's gas and the time value of a bond, the institution that a trade needs exists for the time of that trade. Its terms are the clauses the parties signed, its evidence whatever is attested between commit and resolve, its books the data it leaves, its enforcement the bonds, its close the buyer's resolution. The assets behind the wallets keep what the firm pooled for them; what remains of the firm is a legal wrapper, and its last chores are done by composition.",
});

export default function TransactionScopedInstitutionsPaper() {
    return (
        <PaperLayout slug="transaction-scoped-institutions"
            title="From Firms to Transaction-Scoped Institutions"
            subtitle="The Coasean Collapse"
            author="Figaro"
            date="April 2026"
            watermark="Figaro Protocol · Preprint"
            abstract={
                <>
                    <p>
                        Coase (1937) asked why firms exist if markets allocate, and answered that using the market has costs: discovering a counterparty, negotiating terms, and above all making a stranger&rsquo;s promise good. Every theory of the firm since has kept that premise, and the institutions that surround the firm &mdash; registries, accounts, audits, filings, counsel, courts &mdash; are the apparatus that premise requires. This paper examines what follows when the premise fails. A permissionless, decentralized kernel makes a stranger&rsquo;s promise self-enforcing: each party bonds twice what it stands to gain, only the buyer can close, and cooperation is the equilibrium, a mechanism-design result this paper takes as given and restates at the width it uses. What that enforcement costs is the network&rsquo;s gas for one commit per order and one resolution, the time value of the bonds for the life of the trade, and a balance able to bond them; Section 4 states all three in tokens. No play by independent participants has been observed, and the argument is analytic throughout.
                    </p>
                    <p>
                        What forms in the firm&rsquo;s place is an institution that lasts one transaction. Its terms are the clauses the parties signed under one hash; its evidence is whatever is attested between commit and resolve, which are its two ends; its books are the data it leaves; its enforcement is the bonds; its close is the buyer&rsquo;s resolution, after which it has no members and nothing to govern. The productive assets themselves hold wallets, so nothing needs pooling and nothing needs a container; what remains of the firm is a legal wrapper around assets, and its last chores &mdash; a distribution among the owners of one asset, a licence, a governing law &mdash; are done by composition with contracts and clauses beside the kernel. We call the whole of this the Coasean collapse, and we read the literatures of the firm &mdash; Coase and Simon, Williamson, the property-rights theory, team production and multitask incentives, the capabilities view, Knight, Hansmann, Ostrom, relational contracting, and two-sided markets &mdash; as the account of what each function of the firm was for, and of what does that work now.
                    </p>
                </>
            }
            references={
                <>
                    <li>Alchian, A. A. &amp; Demsetz, H. Production, Information Costs, and Economic Organization. <em>American Economic Review</em>, 62(5):777&ndash;795, 1972.</li>
                    <li>Baker, G., Gibbons, R., &amp; Murphy, K. J. Relational Contracts and the Theory of the Firm. <em>Quarterly Journal of Economics</em>, 117(1):39&ndash;84, 2002.</li>
                    <li>Coase, R. H. The Nature of the Firm. <em>Economica</em>, 4(16):386&ndash;405, 1937.</li>
                    <li>Dahlman, C. J. The Problem of Externality. <em>Journal of Law and Economics</em>, 22(1):141&ndash;162, 1979.</li>
                    <li>Demsetz, H. The Theory of the Firm Revisited. <em>Journal of Law, Economics, and Organization</em>, 4(1):141&ndash;161, 1988.</li>
                    <li>Eswaran, M. &amp; Kotwal, A. The Moral Hazard of Budget-Breaking. <em>RAND Journal of Economics</em>, 15(4):578&ndash;581, 1984.</li>
                    <li>Grossman, S. J. &amp; Hart, O. D. The Costs and Benefits of Ownership: A Theory of Vertical and Lateral Integration. <em>Journal of Political Economy</em>, 94(4):691&ndash;719, 1986.</li>
                    <li>Hansmann, H. <em>The Ownership of Enterprise</em>. Harvard University Press, Cambridge, MA, 1996.</li>
                    <li>Hansmann, H. &amp; Kraakman, R. The Essential Role of Organizational Law. <em>Yale Law Journal</em>, 110(3):387&ndash;440, 2000.</li>
                    <li>Hart, O. <em>Firms, Contracts, and Financial Structure</em>. Oxford University Press, Oxford, 1995.</li>
                    <li>Hart, O. &amp; Moore, J. Property Rights and the Nature of the Firm. <em>Journal of Political Economy</em>, 98(6):1119&ndash;1158, 1990.</li>
                    <li>Holmstrom, B. Moral Hazard in Teams. <em>Bell Journal of Economics</em>, 13(2):324&ndash;340, 1982.</li>
                    <li>Holmstrom, B. &amp; Milgrom, P. Multitask Principal&ndash;Agent Analyses: Incentive Contracts, Asset Ownership, and Job Design. <em>Journal of Law, Economics, and Organization</em>, 7(special issue):24&ndash;52, 1991.</li>
                    <li>Holmstrom, B. &amp; Roberts, J. The Boundaries of the Firm Revisited. <em>Journal of Economic Perspectives</em>, 12(4):73&ndash;94, 1998.</li>
                    <li>Knight, F. H. <em>Risk, Uncertainty and Profit</em>. Houghton Mifflin, Boston, 1921.</li>
                    <li>Kogut, B. &amp; Zander, U. Knowledge of the Firm, Combinative Capabilities, and the Replication of Technology. <em>Organization Science</em>, 3(3):383&ndash;397, 1992.</li>
                    <li>Langlois, R. N. Transaction-cost Economics in Real Time. <em>Industrial and Corporate Change</em>, 1(1):99&ndash;127, 1992.</li>
                    <li>Macneil, I. R. <em>The New Social Contract: An Inquiry into Modern Contractual Relations</em>. Yale University Press, New Haven, 1980.</li>
                    <li>Ostrom, E. <em>Governing the Commons: The Evolution of Institutions for Collective Action</em>. Cambridge University Press, Cambridge, 1990.</li>
                    <li>Rochet, J.-C. &amp; Tirole, J. Platform Competition in Two-Sided Markets. <em>Journal of the European Economic Association</em>, 1(4):990&ndash;1029, 2003.</li>
                    <li>Rochet, J.-C. &amp; Tirole, J. Two-Sided Markets: A Progress Report. <em>RAND Journal of Economics</em>, 37(3):645&ndash;667, 2006.</li>
                    <li>Simon, H. A. A Formal Theory of the Employment Relationship. <em>Econometrica</em>, 19(3):293&ndash;305, 1951.</li>
                    <li>Tadelis, S. &amp; Williamson, O. E. Transaction Cost Economics. In R. Gibbons &amp; J. Roberts (eds.), <em>Handbook of Organizational Economics</em>, chapter 4. Princeton University Press, Princeton, NJ, 2013.</li>
                    <li>Williamson, O. E. Credible Commitments: Using Hostages to Support Exchange. <em>American Economic Review</em>, 73(4):519&ndash;540, 1983.</li>
                    <li>Williamson, O. E. <em>The Economic Institutions of Capitalism</em>. Free Press, New York, 1985.</li>
                </>
            }
        >
            <PaperSection title="1. Introduction">
                <p>
                    Coase (1937) asked why, if markets allocate, so much economic activity happens inside organizations where nothing is priced at all. His answer was that using the market costs something: prices must be discovered and each contract negotiated. Dahlman (1979) added the third cost every later treatment carries, policing and enforcing what was agreed, and it is the third that this paper is about. Where those costs exceed the cost of directing the same activity by authority, the activity moves inside a firm. Williamson (1985) refined the answer into transaction-cost economics, with asset specificity, uncertainty, and frequency as the drivers of integration; Hart (1995) relocated the firm&rsquo;s boundary to the ownership of assets and the residual control rights that ownership carries. The traditions disagree about much and agree about one thing: making a stranger&rsquo;s promise good is expensive, slow, and bound to a jurisdiction, and the firm exists in large part so that promises need not be made between strangers at all.
                </p>
                <p>
                    That premise is also what the institutions around the firm exist for. A firm is registered so that it can be sued and can sue; keeps accounts so that its position can be reconstructed; is audited so that a stranger can believe the accounts; files so that a regulator can read them; retains counsel so that its contracts will hold in court; and litigates when they do not. Some of that apparatus serves the firm&rsquo;s own control and allocation; the part that exists so that a stranger can believe the firm is the cost of the premise.
                </p>
                <p>
                    This paper examines what happens when the premise fails. A permissionless, decentralized kernel &mdash; two calls on a public chain, with no upgrade path &mdash; makes a stranger&rsquo;s promise self-enforcing: each party bonds twice what it stands to gain, only the buyer can close the trade, and the equilibrium is cooperation at every position of a chain of arbitrary length. That equilibrium is a mechanism-design result; Section 2 restates it at the width this argument uses and derives nothing. What it costs to have it is the network&rsquo;s gas for one commit per order and one resolution, the time value of the bonds for the life of the trade, and a balance able to bond them, and Section 4 states all three in tokens. No play by independent participants has been observed; what follows is analytic.
                </p>
                <p>
                    Our argument is that the firm has always been a coordination device with a particular layer added &mdash; subordination, the organization of labour and assets under an ownership nucleus that keeps residual control and captures residual output &mdash; and that the layer was load-bearing only because enforcement between non-subordinated parties was dear. When enforcement is cents, the layer carries nothing. What forms instead is an institution that lasts one transaction (Section 3). The functions the firm bundled are done by that institution and by the assets themselves, each of which holds a wallet (Section 6), and what remains of the firm is a legal wrapper whose last chores composition performs. We call this the Coasean collapse (Section 4), state it as a proposition over the attributes of a transaction with its assumptions and its limits (Section 5), and read the literatures of the firm as the account of what each function was for and of what does that work now (Section 7). How the collapse looks from outside &mdash; to a regulator, a worker, a polity &mdash; is a political-economy question; this paper is internal institutional economics.
                </p>
            </PaperSection>
            <PaperSection title="2. The Kernel, at the Width This Paper Uses">
                <p>
                    The kernel is two calls, and they are the two ends of everything below. <em>Commit</em> forms a bilateral edge: both parties sign one typed commitment, the buyer bonds twice the payment <Math>{"P"}</Math>, and the seller bonds twice the value <Math>{"G \\geq P"}</Math> the process has accumulated through its own link, its own payment included. Neither figure is reported: the process carries a monotonic accumulator, a commitment is admitted only where its declared cumulative value equals the standing accumulator plus its own payment, and the schedule is one doubling applied at every position with nothing to tune. <em>Resolve</em> is the buyer&rsquo;s alone and atomic: every order in the process resolves at once or none does, each seller is refunded its bond and paid its payment, the buyer is refunded its bond less the payments, and the process is over. Between the two ends the middle is open: any party to the process may attest, under any clause the parties signed, forums may rule, tokens may be swapped, and none of it touches the two calls.
                </p>
                <PaperRun title="The nouns, defined once.">
                    A <em>wallet</em> is an address that signs and holds tokens; a party is a wallet. An <em>order</em> is one buyer&ndash;seller commitment with a payment; a <em>process</em> is the chain of orders under one buyer that resolves together. <em>Commit</em> and <em>resolve</em> are the kernel&rsquo;s two calls, the first opening an order and pulling both bonds, the second closing the process and paying everyone. A <em>clause</em> is one registered, content-addressed term a process can run on; an <em>agreement</em> is the clauses composed for one order, signed under one hash; an <em>assembly</em> is a published, reusable design of a process &mdash; which relationships it holds, in what order, under which agreements &mdash; and a process is its instance. Whoever publishes a clause or an assembly is its <em>designer of record</em>, and is paid from a fixed reserve on a meter of how much resolved trade used the design &mdash; <em>measured use</em>, a reward and not a price anyone pays. An <em>operator</em> is whoever holds a wallet&rsquo;s key. A <em>forum</em> is any outside body the parties name to rule on a dispute; it rules, and the buyer resolves. An <em>attestation</em> is a party&rsquo;s signed assertion under a clause: the chain checks who filed it, that the order is open, and that the clause is a leaf of the signed agreement, and checks nothing about its content. <em>Composition</em> is the use of a contract nobody in this stack wrote &mdash; a swap, a forum, a multisender &mdash; beside a process. <em>Gas</em> is what the network charges to execute a transaction.
                </PaperRun>
                <p>
                    The equilibrium, restated in the form used here. After performance, resolving is unconditionally strictly better for the buyer: it holds what it received either way, so its comparison is <Math>{"0"}</Math> against <Math>{"-P"}</Math>, the withheld payment sitting inside its own bond rather than in its wallet. Given that, performing is each seller&rsquo;s strict best response: <Math>{"+P"}</Math> against at best <Math>{"-G"}</Math>, since a seller that walks away forfeits <Math>{"2G"}</Math> and keeps at most <Math>{"G"}</Math>. Every deterrence figure is net of what a defector retains, and at each edge defection is self-destructive for whichever party holds the value; that is what makes the bond what lets two strangers trust each other with no third party between them. Along a chain of <Math>{"n"}</Math> orders under one buyer the same comparison holds at every link, and because payouts arrive together or not at all, each seller holds a bonded interest in every other&rsquo;s performance, sized from the chain: <Math>{"P_i + 2G_i"}</Math> once it has performed, at least <Math>{"P_i + G_i"}</Math> before. The mechanism supplies that interest and its size; what a seller does with it is the seller&rsquo;s conduct. The unequal size of the stakes across a deep chain is a separate fact from the symmetry of the deterrent at each edge, and Section 4 prices it.
                </p>
                <p>
                    There is no exit from the bonded state but resolution: no timeout, no administrator, no vote. Any further release would either turn on a party outside the two who bonded, or add a third continuation at a node the equilibrium was derived by weighing two, and the results would not carry over. Remedies are therefore agreed between the parties while the process stands open &mdash; a seller that cannot perform sends the buyer the payment it stands to receive, so that at resolution it nets its bond and nothing else &mdash; and an outside forum may rule on the process&rsquo;s data and on what the parties bring it, but cannot resolve. The kernel&rsquo;s invariants are machine-checked over bounded configurations, and the equilibrium argument is checked apart from the code at arbitrary chain length; the results this paper leans on are the equilibrium ones.
                </p>
            </PaperSection>
            <PaperSection title="3. The Transaction-Scoped Institution">
                <p>
                    An institution, for the purpose of this paper, is four things at once: a body of terms its members are bound by, a way of making those terms good, a memory of what happened under them, and a way of distributing what was produced. A firm supplies all four for as long as it exists: a charter and a contract of employment, managerial authority backed by the courts, a set of books, and a payroll and a dividend. A bonded process supplies all four for as long as it exists, and it exists from commit to resolve.
                </p>
                <PaperRun title="Its terms are the clauses the parties signed.">
                    Every order carries the hash of an agreement, and the agreement is composed from clauses: what is being exchanged, in which unit, delivered how and where, under which schedule, on which acceptance criteria, before which forum, under which law. The composition is an assembly, published under the hash of its own shape so that anyone may reuse it; the parties instantiate it by signing. No term exists that both parties did not sign under one hash, and no term can be changed after, though a remedy under them may be agreed while the process stands open; that is a body of terms with no board to amend them.
                </PaperRun>
                <PaperRun title="Its enforcement is the bonds.">
                    The terms are made good by the equilibrium of Section 2, not by anyone. There is no manager to direct performance and no court to compel it; a party that does not perform is worse off than one that does, by exactly what it promised, and every co-seller has a bonded reason to see the chain complete. The enforcement costs what the bonds cost to hold for the life of the trade, and it is refunded whole at the close.
                </PaperRun>
                <PaperRun title="Its evidence is whatever is attested in the middle.">
                    Between the two ends any party to the process may file, against any clause the agreement carries, a signed attestation: a hand-off, a temperature band, a measured emission, a delivered fingerprint, an inspection outcome. Each is bound by a merkle proof to the agreement both parties signed, and none is checked for truth by the chain &mdash; they are the parties&rsquo; own assertions, contestable as such, and they are the whole of what an institution&rsquo;s middle ever was: conduct under terms, witnessed. What the firm did with memos, inspections, and sign-offs inside a hierarchy, the process does with attestations under clauses, and what was attested belongs to the parties.
                </PaperRun>
                <PaperRun title="Its books are the data it leaves.">
                    A resolved process is a closed set of accounts: who committed to what, in which unit, for how much, what was bonded, what was attested, and that it closed, all signed by the parties and dated by a chain neither controls. Nothing was kept in order to be reconstructed later. A demonstration to a tax authority, an auditor, or a supervisor becomes a retrieval of what already exists, with the jurisdiction&rsquo;s own attributes attached above it. The firm&rsquo;s books, audit, and filings were the apparatus for producing that demonstration by reconstruction; here the demonstration is a byproduct of trading.
                </PaperRun>
                <PaperRun title="Its distribution is the resolution.">
                    Resolution pays each wallet its own line: the seller its payment and its bond, the buyer its bond less the payments. There is no residual to divide among owners, because nothing was pooled; the value the buyer paid decomposes into every asset that produced it, and each asset was paid its line. Whatever a party wants to do next with what it received &mdash; a fiscal set-aside, a share to a co-owner of the asset, a payment to a lender &mdash; it does afterwards, to addresses it chose, through a multisender contract that splits one payment among many in one transaction. That is the payroll and the dividend, performed by the recipient on its own tokens.
                </PaperRun>
                <PaperRun title="Its close is the buyer&rsquo;s call, and then it dissolves.">
                    After resolution the process has no members, no balance, no standing, and nothing to govern. The assembly it instantiated persists, published, for the next set of parties; the institution that ran under it does not. Two objects are at work and behave oppositely: the assembly, a published design, durable, owned by no party who uses it, and paid for by measured use; and the process, its instance, which is what dissolves. When this paper says transaction-scoped, it means the process. The persistence of the design is what makes the disposability of the instance economical.
                </PaperRun>
            </PaperSection>
            <PaperSection title="4. The Coasean Collapse">
                <p>
                    Coase&rsquo;s three costs of using the market were the costs of finding a counterparty, of negotiating with one, and of making the agreement good. The kernel and what composes beside it change each, and the third is where the collapse happens.
                </p>
                <PaperRun title="Search.">
                    Who exists, what they accept, and the fingerprints of what they have attested are on-chain; the content is the parties&rsquo; own. Discovery is a read of a decentralized, permissionless register, without charge. A register is not a match, and Section 7 takes the two-sided-market objection at full strength; what is fixed here is only that the index is non-proprietary and that the match, where it is made, is made per transaction by a buyer signing exactly one of several answers to an unsigned draft.
                </PaperRun>
                <PaperRun title="Negotiation.">
                    Terms are composed off-chain and signed once. The cost of negotiating is what it was; what changes is that the counterparty space is not a platform&rsquo;s membership under a platform&rsquo;s terms of service.
                </PaperRun>
                <PaperRun title="Enforcement.">
                    In the prior regime enforcement required a court, slow and bound to a jurisdiction; an arbitrator, a trusted third party; or a standing intermediary that internalized coordination and charged a percentage of every trade for ever. The kernel prices enforcement at the schedule of Section 2, in the parties&rsquo; own tokens, refunded at the close. What the parties pay is the network&rsquo;s gas for one commit per order and one resolution, and the time value of the bonded tokens for the life of the trade &mdash; cents per order, on the figures that follow. On a trade of 100 tokens open for a week at a yearly time value of five percent, the bonds&rsquo; time value on both sides is 0.38 tokens and the gas a few cents; a chain of ten such orders, each seller bonding twice the value accumulated through its link, carries about twelve tokens of time value across all its parties for that week, against the coordination of ten strangers by a firm and the registration, accounts, audit, filings and counsel the firm would need to make that coordination good. To hold that chain open its parties must have bonded, at once, 13,000 tokens &mdash; the buyer 2,000 and the sellers 11,000 &mdash; against 1,000 tokens of value: that balance, not the time value on it, is the requirement the schedule sets, and the next paragraph states it in full. The comparison is with everything the firm and the apparatus around it charged for, and on that comparison the gas and the time value are not close.
                </PaperRun>
                <p>
                    The schedule&rsquo;s arithmetic is stated in full because it is the one place a reader could take the collapse for less than it is. A seller at position <Math>{"i"}</Math> bonds <Math>{"2G_i"}</Math> against the value accumulated through its link, so across a chain of <Math>{"n"}</Math> equal payments <Math>{"P"}</Math> the sellers&rsquo; aggregate bond is <Math>{"P\\,n(n+1)"}</Math> and grows with the square of depth, while the buyer&rsquo;s aggregate <Math>{"2nP"}</Math> grows with its length; the time value of the whole, roughly <Math>{"P\\,n(n+3)\\,rT"}</Math> over duration <Math>{"T"}</Math> at rate <Math>{"r"}</Math>, grows with the square of depth while the value the chain carries grows with its length. Depth is priced, by the schedule and not by anyone: a chain of <Math>{"n"}</Math> equal orders must hold <Math>{"P\\,n(n+3)"}</Math> in bonds at once, and that balance is the requirement that binds. A chain deep enough to find it dear does not return to the firm; it composes, a sub-order in one process rooting another, so that a long chain of value runs as several processes, each of a depth its parties can bond. What composition buys and what it costs must both be said. Each process is its own institution, with its own buyer, its own atomic close, and its own co-seller interest, and none of the three crosses the boundary between processes; the seller that roots the next process bonds it from its own balance before the first process pays it. What the schedule rations is depth inside one process; what composition redistributes is the balance; and the guarantee runs one process at a time.
                </p>
                <PaperRun title="What the apparatus was for, and what does its work.">
                    Registration existed so that a party could be reached by a court; here the party is a key that signs and bonds, and the counterparty is made good without reaching anyone. Accounts, audit, and filings existed to reconstruct a position for someone who could not see it; here the position is the data of closed processes, signed by both sides, readable by whoever the parties admit. Counsel existed to make terms hold; here terms are clauses under one hash that nothing can change. The court existed to hear the breach afterwards; here breach is priced before the fact, and a forum, where the parties compose one, rules on data it did not have to compel. Governance existed to decide, continuously, what a standing body does next; here the only decision is the buyer&rsquo;s close, and after it there is no body. Every one of these is done by the process or by nothing, at the process&rsquo;s cost, for the process&rsquo;s life. That is the collapse: the reason the firm and its apparatus exist for enforcement does not hold, and what the firm keeps is the subject of the next section.
                </PaperRun>
            </PaperSection>
            <PaperSection title="5. A Governance-Cost Proposition">
                <p>
                    The collapse can be stated as a comparison a referee can find wrong. Let a transaction be a chain of <Math>{"n"}</Math> orders of equal payment <Math>{"P"}</Math> under one buyer, open for duration <Math>{"T"}</Math>; let <Math>{"r"}</Math> be the time value of the tokens, the rate at which what they represent erodes while they sit bonded; let <Math>{"k"}</Math> be the specificity of any investment a party must sink before the trade, <Math>{"m"}</Math> the frequency with which the same activity recurs among the same parties, and <Math>{"\\mu"}</Math> the degree to which the buyer can judge at acceptance whether what it contracted for arrived. Two loss terms carry <Math>{"k"}</Math> and <Math>{"\\mu"}</Math> into the shapes: <Math>{"h(k)"}</Math>, the expected hold-up loss on a sunk specific investment, rising in <Math>{"k"}</Math>; and <Math>{"\\sigma(\\mu)"}</Math>, the expected loss from a standoff that a buyer&rsquo;s wrong or withheld judgment leaves standing, falling in <Math>{"\\mu"}</Math>. Four governance modes are available, and each has a cost shape rather than a measurement.
                </p>
                <p>
                    <em>Market with a court.</em> <Math>{"C_M = A + q(k)\\,(L + D) + h(k)"}</Math>: the apparatus a claim presupposes, paid on every trade; the probability of a pursued breach, rising with specificity, times the cost and delay of litigation; and the hold-up loss the court cannot cure. Available only where a legal order reaches both parties. <em>Trilateral.</em> <Math>{"C_T = A' + q(k)\\,L' + h(k)"}</Math>: a lighter apparatus and an arbitrator&rsquo;s cost per dispute, the same hold-up, available where both parties can be bound to a forum. <em>Unified, the firm.</em> <Math>{"C_H = F_H/m + a"}</Math>: a standing overhead amortized over recurrence plus the agency and influence loss of directing rather than pricing, and no hold-up term, because integration is what removes it &mdash; which is why, in these shapes as in Williamson&rsquo;s, integration rises with specificity. Available only to parties a legal order recognizes and only where the activity can be brought inside. <em>The bonded process.</em> <Math>{"C_B = n\\,g_c + g_r(n) + n(n+3)\\,P\\,rT + \\sigma(\\mu) + h(k)"}</Math>: the network&rsquo;s gas for one commit per order and for the one resolution, whose cost grows with the number of orders it closes, all quoted in the process&rsquo;s unit at the network&rsquo;s price; the time value of the bonds over the life of the trade; the standoff loss; and the same hold-up the market carries, since a bond on the trade does not reach an investment sunk before it. The bonded process is subject to a constraint that is not a cost and binds per party: the buyer must hold <Math>{"2nP"}</Math> and seller <Math>{"i"}</Math> must hold <Math>{"2G_i = 2iP"}</Math> at the moment of its commit, <Math>{"P\\,n(n+3)"}</Math> in all, every bond refunded at the close and the buyer&rsquo;s less the payments it carried.
                </p>
                <p>
                    <strong>Proposition.</strong> Under those shapes: (i) against the market with a court and against trilateral governance, the hold-up term cancels, so the bonded process dominates both wherever the per-party balance constraint holds, the share <Math>{"(n+3)\\,rT"}</Math> of the trade&rsquo;s value that the bonds&rsquo; time value consumes is small &mdash; the condition is <Math>{"(n+3)\\,rT \\ll 1"}</Math>, not a duration in the calendar &mdash; and <Math>{"\\sigma(\\mu)"}</Math> lies below the apparatus and litigation terms it replaces, which is the condition that the buyer can judge the outcome at acceptance; <Math>{"A"}</Math> and <Math>{"A'"}</Math> are paid whether or not a breach occurs, and gas is not. (ii) Against the firm, the bonded process dominates below a frequency threshold <Math>{"m^{*}(k, \\mu) = F_H \\,/\\,[\\,h(k) + n(n+3)PrT + \\sigma(\\mu) + n g_c + g_r(n) - a\\,]"}</Math>: for any specificity and any measurability, there is a recurrence below which the firm cannot spread its overhead over enough trades to beat a bond that costs nothing standing, and the threshold falls as <Math>{"k"}</Math> rises and as <Math>{"\\mu"}</Math> falls. (iii) Above that threshold the firm keeps the cell, and the shapes say why: high specificity, because <Math>{"h(k)"}</Math> sits in the process&rsquo;s cost and not in the firm&rsquo;s; low measurability, because a fixed-price contract at every link is the highest-powered incentive there is and <Math>{"\\sigma(\\mu)"}</Math> grows as judgment fails (Section 7); or a balance constraint that fails, in which case the chain runs as several processes and the enforcement guarantee runs one process at a time (Section 4).
                </p>
                <p>
                    Two features of the proposition should be read exactly. First, the constraint is the substantive condition. Where a chain can be bonded at all, <Math>{"C_B"}</Math> is small at commercial durations &mdash; on the chain of Section 4, twelve tokens of time value for a week and about fifty for a month, on a thousand tokens of value &mdash; and it stops being small only as <Math>{"(n+3)\\,rT"}</Math> approaches one, which no commercial trade approaches; what decides whether a chain can be bonded is the balance each party holds at its own link, a condition on the parties rather than on the transaction. That is the balance condition of Section 6, and it is the inverse of the firm&rsquo;s: the firm needs capital pooled at the top before any trade, the process needs each party solvent for its own link at the moment of its commit. Second, <Math>{"\\mu"}</Math> is not new to the theory of the firm &mdash; the metering problem of Alchian and Demsetz and the measurement branch of transaction-cost economics are about nothing else &mdash; but the proposition makes it a parameter of the governance choice: the bonded process substitutes the buyer&rsquo;s judgment at acceptance, backed by the buyer&rsquo;s own bond, for the manager&rsquo;s continuous observation. Where acceptance criteria, attestations in the middle, and the buyer&rsquo;s inspection make the outcome judgable, <Math>{"\\mu"}</Math> is high by design of the assembly; where they cannot &mdash; a credence good, a long joint effort whose output no acceptance test separates &mdash; the process is the wrong instrument and the proposition says so.
                </p>
                <p>
                    The proposition is falsifiable in the ordinary way. A referee who shows a commercial trade with low specificity, a judgable outcome, and a bondable balance for which <Math>{"C_H"}</Math> or <Math>{"C_M"}</Math> is below <Math>{"C_B"}</Math> refutes clause (i) or (ii); a referee who shows <Math>{"m^{*}"}</Math> to lie below every observed recurrence in some industry has shown the collapse does not reach it. The empirical work on integration, which finds specificity to predict it, is consistent with the shapes rather than against them, since <Math>{"h(k)"}</Math> sits in every mode but the firm&rsquo;s.
                </p>
            </PaperSection>
            <PaperSection title="6. What Remains of the Firm: a Wrapper Around Assets">
                <p>
                    A reader of the theory of the firm will ask what happens to the functions that were never about enforcement: the pooling of assets across projects, the partitioning of a venture&rsquo;s assets from its owners&rsquo; creditors that Hansmann and Kraakman (2000) identify as organizational law&rsquo;s irreducible contribution, the bearing of risk, and legal personhood. The answer turns on what a party is, and it is not a firm.
                </p>
                <p>
                    This paper assumes, as the mechanism&rsquo;s own account does, that every wallet represents a real-world asset: a piece of productive equipment, a credentialed person&rsquo;s labour, a public service. Three layers stay apart. The asset is off the chain by definition: the aircraft that flies, the capacity that is exercised, the service that is provided. The wallet is the asset&rsquo;s on-chain representation, an address that holds balances and whatever pointers to credentials and documents the parties&rsquo; terms require. The operator is whoever holds the key. The payment an order carries is the value that asset added at its link, and it is the only quantity the mechanism holds about the asset&rsquo;s economics; what the asset spends to produce is its own affair, and it takes part for as long as it holds tokens to bond. An asset behind a wallet sustains itself the way a node on a network does: receipts from resolved processes cover what it costs to run, or its operator stops bonding it and it leaves the market it served. No rule enforces that and none needs to.
                </p>
                <p>
                    Once the asset itself holds the wallet, the firm&rsquo;s remaining functions lose their object. Nothing needs pooling, because each asset is paid its own line by every process it takes part in, and a buyer&rsquo;s payment decomposes into the assets that produced what was bought. Partitioning, in Hansmann and Kraakman&rsquo;s sense, is the one thing the chain does not do: a wallet&rsquo;s balance is its own on the chain and remains reachable by its legal owner&rsquo;s creditors off it, which is exactly the shielding a legal wrapper still supplies. Risk is borne where it always was in fact, by the asset whose receipts must cover its running, and the bond deters the one failure the market could never deter before, that the counterparty walks. What is left is legal personhood: a wrapper that a jurisdiction recognizes as able to hold title, to be licensed, to be taxed, and to distribute what an asset earns among the people who own it. The wrapper is real and this paper does not abolish it. It is reduced to a wrapper, and its last chores are done by composition: a distribution among the owners of one asset is a multisender call on the asset&rsquo;s own receipts; a licence the asset must hold is a credential clause anchored to the issuing authority&rsquo;s own register; the law that governs a trade is an applicable-law clause the parties sign; the forum that hears a dispute is a clause naming it. None of that is inside the kernel, and none of it needs a firm to be done. Value rests where each asset earns what it needs to keep taking part.
                </p>
            </PaperSection>
            <PaperSection title="7. The Literatures, Read as an Account of What Collapsed">
                <PaperRun title="Coase and Simon: the firm as a device for not transacting.">
                    Coase&rsquo;s firm is a device for not having to transact; Simon (1951) gave its inner relation its exact form, an employment contract in which one party accepts in advance the other&rsquo;s authority to direct its behaviour within a zone. Simon&rsquo;s own reason for the instruction is flexibility: under uncertainty the employer prefers to defer the choice of task, and the worker is near-indifferent across the tasks in the zone. Coase&rsquo;s reason is cost. The bonded process leaves the first reason standing and removes the second: where the promise enforces itself, the instruction is not needed to make it good, and the parties who would have been employees are counterparties bonded in their own orders, each paid the value it added.
                </PaperRun>
                <PaperRun title="Williamson: specificity, uncertainty, frequency.">
                    Williamson&rsquo;s three drivers deserve exact treatment, including a correction to how this paper once read the third. Asset specificity concerns an investment sunk before any trade, whose value depends on a particular counterparty; the bond prices defection inside one trade and reaches no further, so the hold-up that specificity creates is not priced by the kernel. It is answered elsewhere: the asset that made the specific investment holds its own wallet and its own receipts, and secures the relationship the way a relational contract does &mdash; by the value of continuing it, in the formal treatment of Baker, Gibbons, and Murphy (2002), and by the norms of the relation in Macneil&rsquo;s (1980) account &mdash; with each transaction of the relationship enforced by a bond rather than by reputation. Uncertainty favoured hierarchy because contracts are incomplete; the process narrows the classes of uncertainty that managerial fiat resolves inside the firm, since what was undertaken and whether it closed are on the chain and what happened in between is attested. Frequency, in Williamson&rsquo;s own analysis, favours hierarchy: it is what lets a standing organization amortize its overhead, while low-specificity trades go to the market whatever their frequency. The collapse therefore lands first where Williamson placed third-party governance: the occasional trade with something specific at stake, where an arbitrator stood behind the promise, and the market cell, where a court did. It reaches the firm&rsquo;s own cell, recurrent and specific, only on the enforcement component; the hold-up over the sunk investment is not priced and stays with the relationship. Williamson (1983) named the ancestor of the arrangement: a hostage, posted by the party in a position to defect, supporting an exchange that governance would otherwise have to carry. In his own terms the bonded process is market governance with a credible commitment attached, and this paper claims no fourth mode; what it claims is that the commitment costs nothing standing and ends with the transaction. Tadelis and Williamson (2013) treat the choice among market, hybrid, and hierarchy as turning on the transaction&rsquo;s attributes and survey the evidence that asset specificity predicts integration; that evidence is the test any claim about the firm&rsquo;s own cell must meet, and this paper makes none beyond the enforcement component.
                </PaperRun>
                <PaperRun title="Hart and Moore: residual control and residual income.">
                    The property-rights theory (Grossman &amp; Hart, 1986; Hart &amp; Moore, 1990; Hart, 1995) locates the firm&rsquo;s boundary at who holds the residual control rights over an asset in states no contract foresaw. Two rights must be kept apart here, because the mechanism treats them differently. Residual control &mdash; who decides how the asset is used, including in the middle of a process &mdash; stays with the wallet that represents the asset, which is to say with its operator; the bond does not take that decision and prices only its consequence for the trade in hand. Residual income &mdash; what is left after every contracted payment &mdash; is not abolished but atomized: resolution pays each asset its contracted line, and the difference between that payment and what the asset spent to produce is the residual, accruing to the operator that holds its key, one claimant per asset. Hart and Moore&rsquo;s question, which of the human parties should own the asset so that the right investments are made, is therefore neither dissolved nor answered here: the operator owns, and whether that allocation gives the right incentives for a non-contractible investment in a given relationship is exactly their question, which the bond does not reach.
                </PaperRun>
                <PaperRun title="Holmstrom and Roberts: the firm does more than prevent hold-up.">
                    Holmstrom and Roberts (1998) argue that hold-up is too narrow an account of the firm: markets achieve firm-like coordination without integration, and firms exist for reasons the ownership approach ignores, among them incentive systems and the transfer of knowledge. The first half supports this paper. The second is its strongest open objection, and it is stated rather than answered. A bonded process is a fixed-price contract at every link, the highest-powered incentive there is, and the multitask reasoning Holmstrom and Roberts draw on predicts that high-powered incentives fail where a task&rsquo;s quality is costly to measure, which is why firms use low-powered ones. Atomic resolution supplies each seller a coordination interest in the chain closing; it does not supply an incentive for effort nobody measures. What acceptance criteria, attestations in the middle, and the buyer&rsquo;s own judgment at resolution do about measurement is the question a full treatment must answer, and it is left open here.
                </PaperRun>
                <PaperRun title="Alchian and Demsetz, and Holmstrom: team production.">
                    Alchian and Demsetz (1972) explain the firm by team production: where output is the joint product of several inputs and cannot be separated into each input&rsquo;s contribution, shirking cannot be priced per input, so a monitor is needed who holds the residual claim and thereby has the incentive to monitor. Holmstrom (1982) proves the sharper result: no sharing rule that pays out the whole of a team&rsquo;s output can make every member&rsquo;s effort a best response, and the cure is a group penalty administered by a party outside the team who breaks the budget &mdash; the penalty must leave the team, or the team&rsquo;s members will not fear it. Section 3&rsquo;s premise, that a buyer&rsquo;s payment decomposes into the assets that produced what was bought, assumes separability, and where output is genuinely joint it is an act of design rather than a fact: the assembly&rsquo;s designer partitions the process into orders with a payment each, and the parties sign that partition. What atomic resolution then does is exactly Holmstrom&rsquo;s group penalty in his own sense. Nobody is paid until every order performs and the buyer accepts the whole; a defector&rsquo;s bond stays locked and benefits no one; and the party who decides is the buyer, who deposited its own bond and is outside the team. The budget is broken by a bond that goes to nobody rather than by a principal who keeps it, which removes the principal&rsquo;s own incentive to declare failure &mdash; the objection Eswaran and Kotwal (1984) raise against Holmstrom&rsquo;s budget-breaker &mdash; because the buyer that withholds resolution after performance is worse off by exactly its payment. Two qualifications keep the claim honest. No penalty is ever administered: a withheld resolution leaves the bonds standing rather than collecting them, so the penalty is a position held, not a forfeiture taken, and it lasts until the buyer closes. And the separability question has an answer the schedule supplies: the bond at a link is not sized to a member&rsquo;s marginal product, which joint output would make unmeterable, but to what the member holds at that link &mdash; the value accumulated through it &mdash; which is meterable whether output is joint or not. That is the paper&rsquo;s claim about team production, and it is where a referee should look first.
                </PaperRun>
                <PaperRun title="Holmstrom and Milgrom: multitask, and the measurement condition.">
                    Holmstrom and Milgrom (1991) show why firms use low-powered incentives: where a job has tasks whose quality is easy to measure and tasks whose quality is not, a high-powered incentive on the measurable ones pulls effort away from the rest, and the employer does better to pay a wage and direct. A bonded process is the opposite instrument, a fixed-price contract at every link with the highest-powered incentive there is, and the proposition of Section 5 makes the consequence a condition rather than an embarrassment: the process is the right instrument where the buyer can judge the outcome at acceptance, and the wrong one where it cannot. What moves a transaction across that line is design: acceptance criteria committed at signing, attestations filed in the middle under clauses the parties chose, and the buyer&rsquo;s own inspection before it resolves, each of which makes a task&rsquo;s quality judgable that the firm would have supervised instead. Where none of them can, the firm&rsquo;s low-powered arrangement keeps the cell, and this paper has no quarrel with it.
                </PaperRun>
                <PaperRun title="The capabilities view: the firm as a holder of knowledge.">
                    Demsetz (1988) argues that Coase over-weighted the cost of transacting and under-weighted the cost of acquiring and using knowledge, which firms economize on by specialization and direction; Kogut and Zander (1992) treat the firm as a repository of social knowledge, whose combinative capability recombines what its members know and moves tacit knowledge better than a market does; Langlois (1992) adds that the costs of persuading, teaching and coordinating in real time are what integration economizes, and that they are transient &mdash; integration recedes as market institutions learn to carry them. Three objects that view names have a place here, and Langlois is a witness rather than an opponent: a published, reusable assembly is exactly the institution by which coordination know-how diffuses out of the firm. The assembly is where a coordinator&rsquo;s know-how goes: a designer who knows how a chain of value should be shaped publishes that shape, reusable by anyone, paid for by measured use, so that the knowledge of how to coordinate leaves the firm and becomes a public object with a designer of record. The asset&rsquo;s own capability stays with the asset, in the operator&rsquo;s hands, as it always did. What the view names that the process does not supply is the combinative capability of a standing team learning together over time; that is a real thing, it is the firm&rsquo;s, and it lies inside the low-frequency and low-measurability boundary the proposition draws.
                </PaperRun>
                <PaperRun title="Knight: who bears the uncertainty.">
                    Knight (1921) locates profit in the bearing of uncertainty that cannot be insured, and the entrepreneur&rsquo;s firm in the concentration of judgment: the confident few assume responsibility for the outcome, guarantee the incomes of the many, and take the residual. Under the process no one guarantees anyone&rsquo;s income. Each asset bears the uncertainty of its own line, its receipts covering its running or not, and the bond is not a premium on that uncertainty but a deterrent on one act, walking away. One thing the process does that Knight&rsquo;s entrepreneur did not is redistribute the bearing sideways: under atomic resolution a seller that has performed stands exposed to a co-seller&rsquo;s failure by its whole position, so uncertainty is shared across the chain without anyone concentrating the judgment of it. Whether that is worse for operators who would rather have their income guaranteed is an empirical question this paper does not answer; what it notes is that the guarantee the entrepreneur supplied was also the residual the entrepreneur kept, and the process separates the two.
                </PaperRun>
                <PaperRun title="Hansmann: whose enterprise it is.">
                    Hansmann (1996) classifies firms by the patron class that holds the residual claim &mdash; investors, workers, customers, suppliers, and, with no owners at all, the nonprofit &mdash; and explains which class owns by the sum of two costs: contracting with the classes that do not own, and the costs of ownership for the class that does, decision-making, monitoring, and risk-bearing. In a transaction-scoped institution the residual claim is not pooled: each asset is the patron of its own line, and two of Hansmann&rsquo;s ownership costs fall on it, risk-bearing and the monitoring of its own counterparties, which is the assignment his account uses to explain why the class that supplies the capital owns, and here every asset supplies its own. His objection to worker ownership, that collective decision among workers with different preferences is costly, does not arise inside the instance, whose one decision is the buyer&rsquo;s close; it arises, if anywhere, in the design of the assembly the instance runs on, which is durable and reused.
                </PaperRun>
                <PaperRun title="Ostrom: durable institutions without a state.">
                    Ostrom (1990) identifies the design principles that long-enduring self-governing institutions share. Some hold here as architecture rather than as governance: boundaries are who signed; conflict resolution runs between the parties while the process stands open and closes at the buyer&rsquo;s call. Others do not, and the difference is instructive. What each party stands to lose is sized to its own link, which is not Ostrom&rsquo;s graduated sanction &mdash; a sanction that escalates with repeated offence and is assessed by peers &mdash; since the kernel has one consequence and no assessor. Collective choice and accountable monitoring, the two principles a firm supplies, the mechanism does not have; and nested enterprises, the eighth, is what composition across processes would have to become. The process is not a commons and does not endure; the point is that what Ostrom&rsquo;s institutions achieved by decades of governance a process has, in part, by construction for the time it lasts.
                </PaperRun>
                <PaperRun title="Rochet and Tirole: the intermediary is paid for matching, not enforcement.">
                    The strongest objection comes from the two-sided-market literature. Rochet and Tirole (2003, 2006) observe that intermediaries across payment cards, media, consoles and exchanges are paid not for enforcement but for bringing two sides together and for choosing how the total charge is split between them, subsidizing the side that is harder to attract. If that is what an intermediary is for, collapsing enforcement leaves the matching problem where it was. The answer is disaggregation, not abolition. Side attraction is served by a public register whose entry is a reclaimable stake that prices spam and pays nobody. The price level is posted by the side that performs. The match is produced per transaction: a buyer&rsquo;s unsigned draft is answered by candidates who countersign at posted terms or return a quote, and the buyer signs exactly one, so no standing party performs the match or holds the claim a platform is paid. Rochet and Tirole&rsquo;s own condition for a market to be one-sided is that the parties can bargain the allocation of charges between them without friction; the absence of a platform charge does not meet that condition, and the cross-side externality, which is what makes a market two-sided, survives here in full. Three limits stand inside the answer. It is not an efficiency comparison: whether selection among candidates from a public register matches as well as a proprietary algorithm over a private order book is a question this paper does not answer. The cross-side externality survives untouched: no formation mechanism brings a side on board that is not there, and a thin seller side yields a thin candidate set. And the absence of a charge is not the absence of a cost structure: the buyer&rsquo;s bonds grow with the length of a chain and, for equal payments, the sellers&rsquo; with the square of it, and that allocation is fixed by the equilibrium rather than chosen to court a side, which is the precise inversion of the platform&rsquo;s instrument and must be counted as a cost of the non-proprietary form where the harder side is the one the schedule burdens more.
                </PaperRun>
            </PaperSection>
            <PaperSection title="8. Conclusion">
                <p>
                    The firm was a device for not having to make promises between strangers, and the apparatus around it was the cost of the premise that such promises could not be made good cheaply. A kernel of two calls makes them good for the network&rsquo;s gas, the time value of a bond, and a balance able to hold it, and the equilibrium that does it is a mechanism-design result inherited by everything built on it. What forms in the firm&rsquo;s place is an institution that exists for the time of one transaction: its terms the clauses the parties signed, its enforcement the bonds, its evidence whatever is attested between commit and resolve, its books the data it leaves, its distribution the resolution, its close the buyer&rsquo;s signature. The assets that produce hold their own wallets and are paid their own lines, so nothing needs pooling and nothing needs a container; what remains of the firm is a legal wrapper, and its last chores are done by composition beside the kernel. That is the Coasean collapse. The literatures of the firm remain the best account of what each of its functions was for, and they read now as the account of what does that work and what the firm keeps.
                </p>
                <p>
                    The scope is the mechanism&rsquo;s. No play by independent participants has been observed, so nothing here is a prediction about how fast the collapse proceeds or in which industries first; the argument is about what the premise&rsquo;s failure makes available, and it is analytic. The one boundary the paper draws for itself is the hold-up over a specific investment sunk before any trade, which the bond does not price and the asset&rsquo;s own relationships must carry. Everything else the firm did for enforcement, a process does, once, and then dissolves.
                </p>
            </PaperSection>
        </PaperLayout>
    );
}
