import type { Metadata } from "next";
import { withOg } from "@/lib/shared/pageMetadata";
import {
    PaperLayout,
    PaperSection,
    PaperSubsection,
    PaperRun,
    PaperRemark,
} from "@/components/papers/PaperLayout";
import { Math } from "@/components/papers/Math";

export const metadata: Metadata = withOg({
    title: "From Firms to Transaction-Scoped Institutions — Figaro Protocol",
    description:
        "A Coasean re-examination: when bilateral enforcement collapses to a fixed 2x capital lockup, the firm's subordination overlay loses its cost advantage. The firm is demoted from privileged organizational container to one pattern among several — assemblies, treasury communities, peer networks, agent coalitions.",
});

export default function TransactionScopedInstitutionsPaper() {
    return (
        <PaperLayout slug="transaction-scoped-institutions"
            title="From Firms to Transaction-Scoped Institutions"
            subtitle="A Coasean Re-Examination Under Fixed-Cost Bilateral Enforcement"
            author="Figaro"
            date="April 2026"
            watermark="Figaro Protocol · Preprint"
            keywords="transaction cost economics, theory of the firm, subordination, coordination economics, two-sided markets, organizational substrate, institutional economics"
            abstract={
                <>
                    <p>
                        Coase (1937) argued that firms exist because the cost of discovering prices, negotiating terms, and enforcing contracts in open markets sometimes exceeds the cost of hierarchical management. Williamson (1985) refined this into Transaction Cost Economics (TCE), identifying asset specificity, uncertainty, and frequency as drivers of vertical integration. Hart (1995) located the firm boundary at the allocation of residual control rights over non-contractible decisions. Across these traditions, a common premise is that contract enforcement between strangers is costly, slow, and jurisdiction-dependent. This paper examines what happens to the boundary of the firm when one of those underlying costs collapses to a fixed, jurisdiction-displaced capital lockup.
                    </p>
                    <p>
                        We take as given the existence of a settlement primitive &mdash; one whose bonding equilibrium admits formal proof &mdash; that prices the cost of trust in temporarily locked capital under a fixed doubling: twice the payment from the buyer on every order, twice the value the process has accumulated at its own link from each seller, with no recurring extraction, no arbitrator, and no jurisdictional dependency. Treating this primitive as exogenous, we ask two questions. First, what does the existence of such a primitive imply for the Coasean threshold that defines the boundary of the firm? Second, what is the firm&rsquo;s status in the organizational space once that threshold has shifted?
                    </p>
                    <p>
                        Our argument is that the firm has always been a coordination mechanism with a particular layer added &mdash; <em>subordination</em>: the organization of labor and assets under an ownership nucleus that retains residual control rights and captures residual output. In Coase&rsquo;s analysis, the subordination layer is not incidental; it is load-bearing, because enforcement between non-subordinated counterparties was costly in the pre-primitive regime. A fixed-cost bilateral-bond settlement primitive prices that enforcement directly. The subordination layer loses its cost advantage for the class of transactions identified below; what emerges is not the abolition of the firm, but its demotion from the privileged organizational container to one pattern among several. How this demotion looks from the outside is a political-economy question; the present paper is internal institutional-economics.
                    </p>
                </>
            }
            references={
                <>
                    <li>Coase, R. H. The Nature of the Firm. <em>Economica</em>, 4(16):386&ndash;405, 1937.</li>
                    <li>Grossman, S. J. &amp; Hart, O. D. The Costs and Benefits of Ownership: A Theory of Vertical and Lateral Integration. <em>Journal of Political Economy</em>, 94(4):691&ndash;719, 1986.</li>
                    <li>Gibbons, R. Four Formal(izable) Theories of the Firm? <em>Journal of Economic Behavior &amp; Organization</em>, 58(2):200&ndash;245, 2005.</li>
                    <li>Hansmann, H. <em>The Ownership of Enterprise</em>. Harvard University Press, Cambridge, MA, 1996.</li>
                    <li>Hart, O. <em>Firms, Contracts, and Financial Structure</em>. Oxford University Press, Oxford, 1995.</li>
                    <li>Hart, O. &amp; Moore, J. Property Rights and the Nature of the Firm. <em>Journal of Political Economy</em>, 98(6):1119&ndash;1158, 1990.</li>
                    <li>Holmstrom, B. &amp; Roberts, J. The Boundaries of the Firm Revisited. <em>Journal of Economic Perspectives</em>, 12(4):73&ndash;94, 1998.</li>
                    <li>Macneil, I. R. <em>The New Social Contract: An Inquiry into Modern Contractual Relations</em>. Yale University Press, New Haven, 1980.</li>
                    <li>Ostrom, E. <em>Governing the Commons: The Evolution of Institutions for Collective Action</em>. Cambridge University Press, Cambridge, 1990.</li>
                    <li>Pacioli, L. <em>Summa de Arithmetica, Geometria, Proportioni et Proportionalita</em>. Paganinus de Paganinis, Venice, 1494.</li>
                    <li>Robertson, B. J. <em>Holacracy: The New Management System for a Rapidly Changing World</em>. Henry Holt and Company, New York, 2015.</li>
                    <li>Rochet, J.-C. &amp; Tirole, J. Platform Competition in Two-Sided Markets. <em>Journal of the European Economic Association</em>, 1(4):990&ndash;1029, 2003.</li>
                    <li>Rochet, J.-C. &amp; Tirole, J. Two-Sided Markets: A Progress Report. <em>RAND Journal of Economics</em>, 37(3):645&ndash;667, 2006.</li>
                    <li>Tadelis, S. &amp; Williamson, O. E. Transaction Cost Economics. In R. Gibbons &amp; J. Roberts (eds.), <em>Handbook of Organizational Economics</em>, chapter 4. Princeton University Press, Princeton, NJ, 2013.</li>
                    <li>Williamson, O. E. <em>The Economic Institutions of Capitalism</em>. Free Press, New York, 1985.</li>
                </>
            }
        >
            <PaperSection title="1. Introduction">
                <p>
                    The boundary of the firm has been the central object of theoretical attention in organizational economics since Coase (1937). Williamson&rsquo;s Transaction Cost Economics (Williamson, 1985) identified asset specificity, uncertainty, and frequency as the conditions under which hierarchical governance dominates market exchange. The property-rights theory (Hart, 1995) located the firm boundary at the allocation of residual control rights over non-contractible decisions. Across these traditions, a common premise is that market contracting between strangers is expensive: search is costly, negotiation is costly, and enforcement &mdash; through courts, arbitrators, or platforms &mdash; is costly, slow, and jurisdiction-dependent.
                </p>
                <p>
                    This paper asks what happens to that boundary when one of the underlying costs &mdash; contract enforcement between mutually distrusting parties &mdash; collapses to a fixed, jurisdiction-displaced capital lockup. The collapse is not a thought experiment: the mechanism&rsquo;s equilibrium is established by proof, and Section 2 restates the results at the width at which they are proved.
                </p>
                <p>
                    We treat that primitive as exogenous. The contribution of this paper is institutional-economic: given the primitive, what follows for the theory of the firm? We argue two things. First, the Coasean threshold shifts inward &mdash; narrowly, in a precise sense we make explicit. Second, the firm ceases to be the privileged organizational container in the region where the threshold has shifted; it becomes one pattern among several, sharing the organizational space with treasury communities, peer networks, transaction-scoped assemblies, agent coalitions, and forms whose naming is yet to stabilize.
                </p>
                <PaperRun title="Paper organization.">
                    Section 2 summarizes the settlement primitive, taking its formal development as given. Section 3 develops the Coasean threshold shift. Section 4 treats the firm as one organizational pattern among many, introducing subordination as the variable whose cost advantage the primitive erases, and developing the three concrete implications for the unit of coordination, before engaging the property-rights and two-sided-market traditions directly. Section 5 concludes.
                </PaperRun>
            </PaperSection>

            <PaperSection title="2. The Settlement Primitive">
                <p>
                    The settlement primitive is two calls, each carrying a mechanism design of its own. <em>Commit</em> forms a bilateral edge under <em>asymmetric bonding</em> (Mechanism&nbsp;1) and scales that security to processes of arbitrary length; <em>resolve</em> settles the process under <em>buyer dominance with atomic resolution</em> (Mechanism&nbsp;2). Its results are taken as given here &mdash; the <em>bonding equilibrium</em> and its extension to processes of <Math>{"n"}</Math> orders, the <em>coordination pressure</em> atomic resolution induces among sellers, and the <em>absence of any exit</em> from the bonded state &mdash; and each is restated below in the form the present argument uses it, at the width at which it is proved. This paper derives none of them; its contribution begins where the mechanism-design work ends. We write &ldquo;Mechanism&nbsp;1&rdquo; and &ldquo;Mechanism&nbsp;2&rdquo; where the distinction is load-bearing.
                </p>
                <PaperRun title="The bond schedule.">
                    An order carries a payment <Math>{"P > 0"}</Math> from the buyer to its seller, and a cumulative value <Math>{"G \\geq P"}</Math> &mdash; everything the process has accumulated through that seller&rsquo;s own link, the order&rsquo;s own payment included. The buyer locks <Math>{"2P"}</Math> and the seller locks <Math>{"2G"}</Math>. Neither figure is reported: the process carries a monotonic accumulator, and a commitment is admitted only where its declared cumulative value equals the standing accumulator plus its own payment, so the seller&rsquo;s bond base is fixed by arithmetic over the process&rsquo;s history and the payment the two parties signed. At the root nothing has accumulated before the order, <Math>{"G = P"}</Math>, and the two bonds coincide; at every position below the root the seller&rsquo;s bond is the larger &mdash; the asymmetry the mechanism is named for. The schedule is constitutive: one doubling, applied to every order at every position, with no setting to tune and no order admitted on other terms. On resolution the buyer recovers <Math>{"P"}</Math> and the seller recovers <Math>{"2G + P"}</Math>, which exhausts what was locked.
                </PaperRun>
                <PaperRun title="The boundary, and where production&rsquo;s costs sit.">
                    The goods, every passage of value from one party to the next, and the parties&rsquo; own knowledge of both are off the record and beyond the mechanism&rsquo;s reach. What the mechanism holds is the bonds, the signed accumulator, and the record of what was committed to; that record shows what was undertaken and whether it was closed, and never shows that anyone performed. Two consequences bear on the institutional argument. First, a Coasean reader will want to know where production&rsquo;s consumption of labor, inputs, and time has gone, since it plainly does not vanish: it sits outside the mechanism, as expenditure on the performing party&rsquo;s own account &mdash; the revenue and outlay of the productive asset behind the key, which the mechanism neither observes nor settles. What the mechanism asks of a participant is narrower, a balance sufficient to bond the commitment being signed, and a party whose balance no longer covers its bonds has left the market by its own arithmetic rather than by any act of the mechanism. Second, no deterrence figure below is computed from locked bonds alone. A party that defects keeps what is in its hands, so every comparison credits it with that retention, measured at the value both parties themselves signed.
                </PaperRun>
                <PaperRun title="The equilibrium.">
                    After performance, resolving is unconditionally strictly better for the buyer: it holds what it received whichever course it takes, so its comparison is <Math>{"0"}</Math> for resolving against <Math>{"-P"}</Math> for never resolving &mdash; the withheld payment being frozen inside its own bond rather than kept by it &mdash; and nothing about the seller enters that comparison. Given it, performance is each seller&rsquo;s strict best response: performing and being resolved earns <Math>{"+P"}</Math>, while holding out leaves the seller with what is in its hands, worth at most <Math>{"G"}</Math> and less where its own contribution is a service it has not rendered, against <Math>{"2G"}</Math> locked &mdash; at best <Math>{"-G"}</Math>. The two calls compose in that order, and neither result stands alone. The doubling is what puts both comparisons where they are: credit a defector with everything it retains, and the first half of its bond is merely offset by the taking while the second half is what makes the taking cost. That is mutual assured destruction with content &mdash; not equal losses, but a position that is self-destructive for whichever party holds the value. No observer of performance outside the two parties is assumed, and none is needed: the buyer judges for itself whether what it contracted for arrived, and its resolution <em>is</em> that judgement.
                </PaperRun>
                <PaperRun title={"Processes of n orders: both sides of the table."}>
                    Asymmetric bonding scales because each seller&rsquo;s bond keys to the accumulator rather than to its local payment. In a process of <Math>{"n"}</Math> orders sharing one root buyer and one denomination, seller <Math>{"i"}</Math> posts <Math>{"2G_i"}</Math> against <Math>{"G_i = \\sum_{j \\leq i} P_j"}</Math>, and the buyer posts <Math>{"2P_i"}</Math> on <em>each</em> of the <Math>{"n"}</Math> orders &mdash; its stake is per-order and accumulates across the process just as the sellers&rsquo; does. Both schedules enter the comparison of Section 3, and neither side of the table may be dropped from it. The deterrent is preserved at every position: seller <Math>{"i"}</Math>&rsquo;s gap between performing and holding out is <Math>{"\\Delta_i = P_i + G_i \\geq 2P_i"}</Math>, with equality only at the root and widening with every payment the chain has accumulated ahead of it, while its bond rises with that accumulation without qualification. The mechanism sees a linear sequence of commits extending one accumulator; whatever richer topology the parties have in mind is their own agreement, expressed above the mechanism and invisible to it.
                </PaperRun>
                <PaperRun title="Atomic resolution and the pressure among sellers.">
                    Only the buyer may trigger resolution; resolution is <em>atomic</em> &mdash; every active order settles at once or none does &mdash; and it is terminal. Under a buyer that resolves only against universal performance, each seller&rsquo;s payout therefore waits on every other&rsquo;s, which induces a weakest-link subgame among parties who need not know one another and need never have met. Its magnitude is computable from the record: a co-seller that has already performed is exposed to a peer&rsquo;s fault by <Math>{"P_i + 2G_i"}</Math>, having parted with its product and standing in its whole bond, and one that has not yet performed is exposed by at least <Math>{"P_i + G_i"}</Math>, since it still holds what is in its hands. What a co-seller then <em>does</em> with that interest &mdash; press the failing party, arrange a substitution, wait &mdash; is conduct the mechanism neither prescribes nor describes; what it supplies is the interest and its size.
                </PaperRun>
                <PaperRun title="No exit from the bonded state.">
                    The primitive has no timeout, no admin override, no governance mechanism, no protocol fee, and no upgrade path. The absence is structural. Commit and resolve are the whole state-changing surface, and any further operation that released part of a bonded position would fall into one of two cases. Either its availability turns on a party outside the two who bonded &mdash; an agent that has deposited nothing into the process and holds nothing of what the process moves, so that nothing the mechanism holds fixes its ranking of the alternatives &mdash; or it turns on the buyer or the seller, in which case it adds a third continuation at nodes where the equilibrium above was established by weighing exactly two, and that equilibrium does not carry into the augmented mechanism by inheritance. Remedies are accordingly agreed between the parties <em>while the process stands open</em>. The concrete transfer in the simplest case: a seller that cannot perform sends the buyer the payment it stands to receive, so that at resolution it takes back its bond and nets nothing from the failure while the buyer is made whole. External legal and arbitral forums compose into that same window and may rule on the record and on whatever the parties bring them; the reason composing one costs the equilibrium nothing is that no forum can resolve a process. Resolution is the buyer&rsquo;s alone, and there is no direct enforcement. It is also terminal acceptance: a buyer resolves once satisfied, and the mechanism holds nothing afterwards for anyone to recover.
                </PaperRun>
                <PaperRun title="What the primitive does not provide.">
                    For the institutional argument that follows, three non-properties matter as much as the properties. The primitive does not provide capital aggregation across projects, does not provide pooled risk-bearing across uncorrelated ventures, and does not provide legal personhood for off-chain liability. We return to these absences in Section 4.
                </PaperRun>
            </PaperSection>

            <PaperSection title="3. The Coasean Threshold Shift">
                <p>
                    Coase&rsquo;s central insight is that firms exist because market transaction costs &mdash; searching for partners, negotiating terms, enforcing agreements &mdash; sometimes exceed the cost of hierarchical management. Williamson refined this into TCE, identifying three conditions under which hierarchical governance dominates market exchange: high asset specificity, high uncertainty, and high frequency.
                </p>
                <p>
                    The settlement primitive changes the calculus by collapsing one of these costs to a fixed, predictable capital lockup. Consider the three transaction costs separately.
                </p>
                <PaperRun title="Search costs.">
                    Public on-chain signals (settlement history, accepted-token lists, attested capabilities) allow autonomous discovery through shared coordination graphs. For agents able to read blockchain state, search cost approaches zero. The substantive change is not that search is cheaper &mdash; platforms already make search cheap &mdash; but that the search index is non-proprietary: no platform owns the discovery function, and the data is not extracted as rent. A non-proprietary index is not the same thing as a performed match, and the objection that the intermediary is paid for matching rather than for enforcement is taken up in Section&nbsp;4.5.
                </PaperRun>
                <PaperRun title="Negotiation costs.">
                    Off-chain commitment building lets parties iterate on terms without on-chain cost. The negotiation is bilateral and direct; counterparties can discover and iterate through shared graph visibility rather than through a standing intermediary&rsquo;s matching function. The substantive change here is asymmetric: the <em>cost</em> of negotiating is roughly unchanged from web2 baselines, but the <em>counterparty space</em> from which one can negotiate is no longer mediated by a platform&rsquo;s terms of service.
                </PaperRun>
                <PaperRun title="Enforcement costs.">
                    This is the decisive variable. In the pre-primitive world, enforcement requires courts (slow, expensive, jurisdiction-dependent), arbitrators (trusted third parties), or standing intermediaries that internalize coordination and charge for it. The primitive prices enforcement at the doubling of Section 2 &mdash; twice the payment from the buyer on every order, twice the value accumulated at its link from each seller &mdash; posted in temporarily locked capital: a fixed, predictable, jurisdiction-displaced cost requiring no third party. The stake is posted in full for every process a participant holds open at once: concurrent positions sum, and a wallet&rsquo;s capacity to hold several is bounded by the balance it can bond &mdash; a stated cost of the mechanism, not a variable it tunes.
                </PaperRun>
                <PaperRemark title="On the enforcement-cost accounting.">
                    The headline comparison uses the opportunity cost of the locked capital &mdash; the whole bonded stake, both sides of the table, held over the process duration <Math>{"T"}</Math> at the prevailing risk-free rate <Math>{"r"}</Math>, which is the substantive change relative to the prior regime. A full accounting adds smaller terms: on-chain transaction fees for entering and settling the commitment, slippage if the bond denomination must be acquired at transaction time, and the operational-security costs of key custody. It also corrects one simplification in the other direction. A single <Math>{"T"}</Math> is written across the whole process, but the lock durations are not uniform: each order&rsquo;s bonds are locked from its own commit to the one resolution that ends them all, so only an order present at the opening carries the full span and every later one carries less. Charging every order the process&rsquo;s whole lifetime therefore over-states the carry, which is conservative for the comparison being made and is why the abstraction is taken. The comparison below abstracts all of these because they are small relative to the standing-firm overheads against which it is made for the retail-scale transactions this paper treats; the abstraction should be revisited where any of them is comparable in magnitude to the lockup&rsquo;s opportunity cost.
                </PaperRemark>
                <div className="border-l-2 border-default pl-6 my-2 space-y-3">
                    <p className="text-sm font-semibold text-ink-heading">Proposition 3.1 (Coasean Threshold Shift).</p>
                    <p>
                        For a process of <Math>{"n"}</Math> orders, the full bonded stake &mdash; both sides of the table, not the buyer&rsquo;s lockup alone &mdash; is the root buyer&rsquo;s <Math>{"2P_i"}</Math> on each of the <Math>{"n"}</Math> orders together with the sellers&rsquo; aggregate <Math>{"\\sum_{i=1}^{n} 2G_i"}</Math>, where seller <Math>{"i"}</Math> posts <Math>{"2G_i"}</Math> against the cumulative value at its own link, <Math>{"G_i = \\sum_{j \\leq i} P_j"}</Math>, its own payment included; for the illustrative chain of equal payments <Math>{"P"}</Math> the seller bond at position <Math>{"i"}</Math> is <Math>{"2iP"}</Math>, so the seller aggregate is <Math>{"P\\,n(n+1)"}</Math> &mdash; growing with the square of chain depth, against the buyer&rsquo;s aggregate <Math>{"2nP"}</Math>, which grows linearly, so for <Math>{"n \\geq 2"}</Math> the total is dominated by the seller side, the two coinciding only at the root. Where the opportunity cost of that full stake &mdash; approximately <Math>{"\\left[2nP + P\\,n(n+1)\\right] \\cdot rT = P\\,n(n+3) \\cdot rT"}</Math> over the process&rsquo;s bond duration <Math>{"T"}</Math> at rate <Math>{"r"}</Math> &mdash; is less than the firm&rsquo;s coordination overhead for the same transaction, the rational organizational choice is market exchange via the primitive rather than hierarchical integration.
                    </p>
                </div>
                <p>
                    Proposition 3.1 is a comparative-statics statement, not a sweeping institutional prediction. It identifies a class of transactions for which the make-or-buy boundary tilts toward <em>buy</em>. The class is non-empty (most retail-scale transactions in mature financial environments satisfy it) and bounded (very-high-frequency, very-low-margin, or very-long-duration transactions do not). The proposition does not claim that all transactions migrate; it claims that the migration threshold is now defined by the full stake&rsquo;s opportunity cost rather than by the cost of standing institutional infrastructure. The stake is not a hidden cost eroding that margin but its explicit price: temporarily locked and returned at settlement, not extracted as recurring rent, and posted in the open for a duration that is the process&rsquo;s own lifetime &mdash; a maritime leg may hold its bonds four to six weeks, and that span <em>is</em> the coordination being secured. The maritime figure is offered to fix what the duration <em>is</em>, not to place that transaction inside the shifted region: a lockup measured in weeks is precisely the long-duration case the class excludes, and the comparison there must be made on its own numbers.
                </p>
                <p>
                    Two bounds on depth should be kept apart, since only one of them is a limit the primitive imposes. The primitive itself sets no cap on the number of links a process may carry: the process&rsquo;s active-order count is tracked &mdash; resolution settles against it, and a settlement missing an order is refused &mdash; but nothing in the two calls bounds it, and the only ceiling is what the settlement layer will execute when a single resolution settles the whole process at once. The economic bound is a different quantity and it binds far earlier. By Proposition 3.1 the seller aggregate grows with the square of depth while the value of the chain grows linearly in it, so the stake&rsquo;s opportunity cost rises faster than what the chain is worth, and the comparison against the firm&rsquo;s coordination overhead turns adverse long before any execution limit is approached. Depth is unrationed by the mechanism and priced by the market &mdash; which is the same division of labor the rest of this paper describes, and it means the shifted region of Proposition 3.1 is bounded in chain length as well as in transaction attributes.
                </p>
                <PaperRun title="Engagement with TCE.">
                    Williamson&rsquo;s three drivers of vertical integration deserve direct treatment. <em>Asset specificity</em> continues to favor hierarchy: a specialized asset whose value is contingent on a specific counterparty cannot be efficiently coordinated through a sequence of short-lived bonded transactions, since the holdup risk is in the asset&rsquo;s pre-transaction sunk investment, not in the transaction itself. <em>Uncertainty</em> cuts both ways: contract incompleteness favors hierarchy, but the primitive&rsquo;s evidence trail (timestamped commitments, signed disclosures) reduces some classes of uncertainty &mdash; specifically those that hierarchical authority historically resolved by managerial fiat. <em>Frequency</em> is the condition under which the shift is most pronounced: high-frequency exchanges with low asset specificity are exactly where the standing firm&rsquo;s overhead is hardest to amortize and the primitive&rsquo;s per-transaction capital lockup is easiest to absorb.
                </PaperRun>
                <p>
                    The proposition therefore narrows rather than overturns TCE. It identifies a region of the asset-specificity / uncertainty / frequency space where hierarchical governance was previously the equilibrium outcome but is no longer. Tadelis &amp; Williamson (2013) update this picture for the contemporary literature, treating the transaction as the unit of analysis and the choice among market, hybrid, and hierarchy as turning on transaction attributes; Proposition 3.1 adds a new entry to that menu of governance modes &mdash; the bonded transaction-scoped assembly &mdash; whose attributes are different from any of the three Williamson catalogs.
                </p>
                <PaperRun title="Holmstrom and Roberts&rsquo; caution.">
                    Holmstrom &amp; Roberts (1998) argue that asset-specificity-based hold-up is not by itself sufficient to explain firm boundaries: firms also do work that markets do not, particularly in promoting cooperation and coordinating decisions that no single contract can fully specify. The caution applies to our argument: pricing enforcement addresses one component of the firm&rsquo;s bundle, not all of it. The cooperation-promotion component is discharged by the weakest-link subgame &mdash; each seller&rsquo;s payout depends on universal cooperation &mdash; rather than by a manager (Section&nbsp;4.2 develops this). The non-coordination components &mdash; capital aggregation, risk pooling, organizational knowledge &mdash; remain durable requirements, and we return to them in Section 4.
                </PaperRun>
            </PaperSection>

            <PaperSection title="4. The Firm as One Pattern Among Many">
                <p>
                    The implication of Proposition 3.1 is not that the firm dissolves but that the firm&rsquo;s status in the organizational space changes. The firm has always been a coordination mechanism. What distinguishes the modern corporate firm from older coordination forms &mdash; partnerships, guilds, cooperatives, market exchange &mdash; is not the coordination function itself but a particular overlay placed on top of it: <em>subordination</em>.
                </p>
                <PaperSubsection title="4.1 Subordination as the Variable">
                    <p>
                        By subordination we mean the allocation of labor and productive assets under a single ownership nucleus, combined with an employment contract that transfers residual output rights and residual control rights to that nucleus in exchange for a wage. In the Coasean analysis, subordination is not incidental to the firm; it is load-bearing. Prior to the settlement primitive, enforcement between non-subordinated counterparties was costly, and aggregation under an ownership nucleus that resolved enforcement internally through managerial authority was the institutional response.
                    </p>
                    <div className="border-l-2 border-default pl-6 my-2 space-y-3">
                        <p className="text-sm font-semibold text-ink-heading">Proposition 4.1 (Subordination as an Enforcement Economy).</p>
                        <p>
                            In the pre-primitive regime, subordination is a response to enforcement cost. The firm&rsquo;s subordination layer secures coordination between counterparties whose direct bilateral enforcement would be prohibitively costly, at the price of aggregating residual rights under a single nucleus. When bilateral enforcement is priced at a fixed capital lockup, the subordination layer loses its cost advantage in the region identified by Proposition 3.1.
                        </p>
                    </div>
                    <p>
                        Proposition 4.1 reframes what is dissolving. It is not the firm&rsquo;s coordination function that becomes unnecessary &mdash; coordination is still required. It is the subordination overlay &mdash; the transfer of residual control rights from the producing party to an ownership nucleus &mdash; that becomes economically optional where the primitive is applicable. What is left behind is coordination without subordination: the same productive assets, the same coordination requirements, but without the ownership aggregation that historically secured them.
                    </p>
                </PaperSubsection>
                <PaperSubsection title="4.2 What Emerges in the Shifted Region">
                    <p>
                        The viability of the alternative patterns named below rests on a property of the primitive that Section 2 introduced but that the Coasean argument of Section 3 did not yet deploy: atomic resolution. Mechanism&nbsp;1 (asymmetric bonding) supplies the bilateral equilibrium at every edge of an arbitrary multi-party process, but a mesh of independently secured bilateral edges is not by itself an organization &mdash; coordinating a process of <Math>{"n"}</Math> orders to a single settlement under Mechanism&nbsp;1 alone would still require either a standing intermediary, an arbitrator, or an <Math>{"n"}</Math>-way mutual signing at the moment of resolution. Any of those three responses re-introduces the firm-shaped container under a different name. Mechanism&nbsp;2 (buyer dominance with atomic resolution) makes the mesh of edges resolvable as a unit at the buyer&rsquo;s signature, and the weakest-link subgame propagates cooperation pressure through the mesh without managerial authority or external choreography. The transaction-scoped assembly clears itself. The Coasean shift of Section 3 is what makes the assembly competitive with the firm at the cost margin; Mechanism&nbsp;2 is what makes the assembly structurally available at all.
                    </p>
                    <PaperRemark title="Two things the word &ldquo;assembly&rdquo; names.">
                        The term does double duty in this literature and the two referents behave oppositely, so we fix them here and use them consistently. An <em>assembly</em> in the first sense is a composed deal-shape: a multi-party arrangement someone has authored &mdash; who stands where in the chain, on what terms, in what denomination &mdash; published so that anyone may reuse it. That object persists. It is a durable piece of coordination capital, it is not owned by any of the parties who use it, and its author may earn from its reuse without holding any claim on the transactions that use it. An assembly in the second sense is an <em>instance</em>: one particular set of parties who have bonded into one particular process on that shape. That object is what dissolves at settlement, having no residual to carry and no member after the payouts are made. When this paper calls an assembly <em>transaction-scoped</em>, it is always the instance that is scoped to the transaction; the shape it instantiates outlives every instance of it, and the persistence of the one is what makes the disposability of the other economical.
                    </PaperRemark>
                    <p>
                        Where subordination is no longer load-bearing, the firm becomes one organizational pattern among several. The organizational space in that region admits multiple viable coordination patterns that were previously suppressed by the enforcement-cost structure: transaction-scoped assemblies that form around a process and dissolve at settlement; standing treasury communities whose members recurrently participate in compatible multi-party processes; peer networks of independent bonded counterparties without a common treasury; agent coalitions mixing human, software, and machine participants. The firm continues to exist; it shares the space with these other forms rather than occupying it alone. Which form dominates for a given industry is an empirical question about the parameters of Proposition 3.1 and the non-coordination functions (capital aggregation, risk pooling, legal personhood) that the primitive does not itself address.
                    </p>
                    <PaperRun title="Hansmann&rsquo;s typology of ownership.">
                        The closest comparator in the existing literature is Hansmann (1996), who classifies firms by the patron class that holds residual claims and control rights: investor-owned, worker-owned, customer-owned, supplier-owned, and mutual. Each form is an ownership nucleus, and Hansmann&rsquo;s central observation is that one form dominates within an industry when the costs of contracting with the other patron classes exceed the costs of ownership by the dominant class. Transaction-scoped assemblies sit outside this typology: they have no standing residual claim to allocate, because resolution dissolves the per-process residual into deterministic per-order payouts, fixed at settlement. This is not a fifth Hansmann form; it is what becomes available when the residual-claim allocation question is discharged at settlement rather than carried over time. Hansmann&rsquo;s heterogeneity-cost objection to worker cooperatives &mdash; that collective decision-making among workers with different preferences is expensive enough to outweigh the benefits of worker ownership &mdash; does not bind here because the assembly&rsquo;s lifespan is bounded by a single process: there is no continuing collective decision to make. Where the assembly form is feasible and the firm form is not (the shifted region of Proposition 3.1), the assembly is chosen for the same Hansmann-style reason that a particular firm form is chosen elsewhere: the contracting costs against the alternative are higher.
                    </PaperRun>
                    <PaperRun title="Ostrom&rsquo;s design principles.">
                        Ostrom (1990) identifies eight design principles that long-enduring self-governing institutions tend to share: clearly defined boundaries, congruence between rules and local conditions, collective-choice arrangements, monitoring, graduated sanctions, conflict-resolution mechanisms, recognition by external authorities, and (for systems above a threshold size) nested enterprises. Transaction-scoped assemblies satisfy several of these structurally rather than by governance: boundaries are defined by who has signed a process commitment; sanctions are graduated by the bonded mesh&rsquo;s payoff structure rather than set as policy, what a party stands to lose being its own live position at its own link, scaled to the value the process has accumulated there; conflict resolution runs between the parties while the process stands open and closes at the buyer&rsquo;s signature, with external legal forums able to rule on the record and on what the parties bring them, and none able to settle a process itself. Other principles &mdash; collective choice, congruence with local conditions &mdash; are properties of the graph the parties compose on top of the kernel, not of the kernel itself. The point is not that the assembly is an Ostrom commons (it is not); it is that several Ostrom-identified properties of durable institutions appear here as architectural rather than as governance achievements.
                    </PaperRun>
                    <PaperRun title="Relational contracts and Macneil.">
                        The relational-contract literature (Macneil, 1980; Gibbons, 2005) treats long-running counterparty relationships as governance structures in their own right &mdash; self-enforcing through reputation and continuation value when formal contracting is incomplete. The bonded primitive does not replace relational contracting; it composes with it. A standing peer network or treasury community is precisely a long-running relationship in Macneil&rsquo;s sense, and the primitive supplies the per-transaction enforcement that the relational contract would otherwise have to underwrite via reputation. The two substitute for each other along one axis (formal enforcement of each transaction) and complement each other along another (the relational layer carries reputation; the bonded layer carries the equilibrium).
                    </PaperRun>
                    <PaperRun title="Holacracy as an intra-firm precedent.">
                        Intra-firm experiments with flat coordination &mdash; most visibly the Zappos adoption of Holacracy (Robertson, 2015), announced in 2013 and carried company-wide by 2015 &mdash; previewed what some of these patterns look like when they remain confined to a single ownership nucleus. Such experiments are informative as data points about what flat coordination requires operationally, but they are not what the primitive generalizes. Holacracy, once the subordination nucleus is retained, operates at the mercy of that nucleus. The primitive enables flat coordination where the nucleus itself is not required; that is a stronger condition than any intra-firm reform can provide.
                    </PaperRun>
                </PaperSubsection>
                <PaperSubsection title="4.3 Three Concrete Implications">
                    <PaperRemark title="On the kernel / protocol / runtime distinction.">
                        The three implications below are pitched at different layers, so we fix the distinction before using it. The <em>kernel</em> is the irreducible settlement primitive of Section 2, guaranteeing only the bond-and-settlement structure; the <em>protocol</em> adds the composition doctrine, where the attestation-and-credential layer is realized; the <em>runtime</em> adds the semantic and builder surfaces above it. A fourth thing is not a tier at all and is easy to mistake for one: <em>composition</em> with contracts nobody in this stack wrote, which is how anything the primitive does not itself hold gets attached to a process.
                    </PaperRemark>
                    <PaperRun title="(a) The wallet is the unit of coordination.">
                        Each productive asset is represented directly by a wallet address. At the protocol tier the wallet can hold content-addressed credentials &mdash; attested capabilities, participant profiles &mdash; that certify the asset&rsquo;s identity and performance history. Title to the asset is a different matter and does not live in this stack at all: where a deed or registration exists on-chain, it is held by some external contract of the issuer&rsquo;s own, and the parties reach it by composing against that contract rather than by any credential the primitive issues. In the firm model, the cook&rsquo;s skill, the kitchen&rsquo;s equipment, the courier&rsquo;s vehicle are subsumed under the firm&rsquo;s legal identity and cease to be individually addressable. In the wallet model, each asset is its own coordination endpoint. The productive asset <em>is</em> the identity; it remains an identity whether the firm persists or not.
                    </PaperRun>
                    <PaperRun title="(b) Tokens replace stock.">
                        Participants in the shifted region do not receive shares in a firm; they hold tokens denominated by the communities with which they coordinate. Token holdings signal community affiliation and participation-history, not residual-output ownership in a centralized nucleus. The relationship between productive asset and community is market-mediated rather than hierarchically internalized. Tokens are borderless, community-defined rather than jurisdiction-issued, and the community&rsquo;s definition is itself an open parameter.
                    </PaperRun>
                    <PaperRun title="(c) Actor type is neutral.">
                        Nothing in the primitive&rsquo;s coordination layer distinguishes an AI capable of bearing capital risk from a human capable of the same risk. A person with a law degree and an AI trained on legal precedent compete on identical terms &mdash; each as a bonded counterparty whose capabilities, if attested at all, are attested at the protocol tier rather than asserted at the kernel tier. Actor-type neutrality is a property of the kernel&rsquo;s coordination layer, not a policy choice; it follows directly from the kernel&rsquo;s indifference to what sits behind a wallet.
                    </PaperRun>
                </PaperSubsection>
                <PaperSubsection title="4.4 Engagement with the Property-Rights Tradition">
                    <p>
                        The property-rights tradition (Hart, 1995; Grossman &amp; Hart, 1986; Hart &amp; Moore, 1990) locates the firm boundary at the allocation of residual control rights over non-contractible decisions. The primitive does not abolish non-contractibility; rather, it changes <em>where</em> residual control rights are allocated, and it narrows the temporal window over which they are exercised. In the firm model, those rights are allocated to the ownership nucleus and exercised continuously through managerial authority. In the wallet model, they are allocated to whoever controls the wallet &mdash; which, under self-sovereign key management, is the productive asset itself (or the individual operating it), with whatever external title contract records its ownership composed against rather than absorbed &mdash; and Mechanism&nbsp;2 closes the temporal window: atomic resolution dissolves the per-process residual claim into deterministic per-order payouts at settlement, leaving no ongoing residual that requires standing custody. Residual control rights do not disappear; they are held by the asset rather than aggregated under an ownership layer, and the per-process residual claim is discharged at the moment of resolution rather than accumulated over time.
                    </p>
                    <p>
                        This is the institutional-economics translation of what Section 4 has been describing throughout: the decision about who holds residual rights, previously answered by the firm&rsquo;s ownership structure, is now a property of the asset&rsquo;s wallet architecture. This relocates the allocation question rather than dissolving it; Hart &amp; Moore (1990) applies to the wallet-layer question just as it applied to the firm-layer question before, with a different set of empirical facts about costs and observability.
                    </p>
                    <PaperRun title="Williamson&rsquo;s drivers, revisited.">
                        Our treatment of Williamson&rsquo;s three drivers (Section 3) likewise does not dissolve TCE; it relocates the question. Asset specificity continues to matter wherever a productive asset&rsquo;s value is contingent on a specific bond-specific investment; the primitive does not change that. What changes is that the institutional response to asset specificity need not be subordination under an ownership nucleus &mdash; a treasury community, a long-term peer network, or a serial bonded-commitment pattern can, for some parameter regions, secure the specific investment without aggregating residual rights.
                    </PaperRun>
                    <p>
                        The non-coordination functions of the firm &mdash; capital aggregation, organizational knowledge, risk pooling, legal personhood &mdash; persist as durable requirements that some institution must satisfy. They do not necessarily re-bundle into a firm-shaped container; they can be satisfied by treasuries, DAOs, mutuals, cooperatives, or jurisdiction-specific legal wrappers attached to wallet clusters. The empirical question of which bundling pattern dominates in a given industry is outside the scope of this paper.
                    </p>
                    <PaperRun title="The firm&rsquo;s self-knowledge function dissolves alongside.">
                        A function we have not separately named is that the firm historically has been the unit at which <em>books</em> are kept &mdash; the unit whose position is tracked over time through double-entry bookkeeping in the tradition of Pacioli (1494). That function is one of the things a boundary is drawn around: a firm consolidates because its constituent activities have no position of their own that anyone outside can read. Under the primitive they do. A bonded process holds every party&rsquo;s position for its own duration and discharges all of them at settlement, and a wallet participating in many processes carries its position in each without any consolidating entity to draw it together. The unit at which position is tracked therefore becomes the process and the wallet rather than the firm, which removes one more of the boundary&rsquo;s historical justifications. What follows for the accounting apparatus itself &mdash; what remains to be kept, by whom, and to what standard &mdash; is a question about records rather than about organizational form, and it is not this paper&rsquo;s subject.
                    </PaperRun>
                </PaperSubsection>
                <PaperSubsection title="4.5 Engagement with the Two-Sided-Market Tradition">
                    <p>
                        A distinct objection comes from the two-sided-market literature, and it is the strongest one available against Section 3. Rochet &amp; Tirole (2003) observe that intermediaries across a wide class of industries &mdash; payment cards, media, video-game consoles, exchanges &mdash; are not paid for enforcement at all. They are paid for bringing two user groups together whose members do not internalize the value their own participation creates for the other side, and their central instrument is the <em>price structure</em>: the allocation of the total charge between the two sides, as distinct from its level. Rochet &amp; Tirole (2006) make this the definition &mdash; a market is two-sided when the volume of transactions depends on the structure and not only on the overall level of the fees charged, so that moving a unit of charge from the seller side to the buyer side, with the total held fixed, changes how much trade occurs. On that account the platform earns its keep by choosing the allocation: it courts, and where necessary subsidizes, whichever side is harder to attract, recovers the subsidy from the side whose participation is less elastic, and thereby internalizes an externality the end-users will not internalize themselves. If that is what an intermediary is for, pricing enforcement at a capital lockup does not dissolve it. The coordination rent, on this reading, is compensation for solving a matching problem, and an enforcement-cost collapse leaves the matching problem exactly where it was.
                    </p>
                    <p>
                        The objection lands squarely on Section 3&rsquo;s treatment of search costs, which claimed only that the discovery index is non-proprietary. That claim is weaker than it looks: a public register of who exists and what they charge does not produce a counterparty for a particular job at a particular moment, and producing that counterparty is precisely what the two-sided-market literature says the intermediary is paid for. Answering the objection requires a formation mechanism, not an index. There is one, and it belongs to the protocol rather than to a standing party that sells access to it: a permissionless, per-transaction formation mechanism in which a buyer&rsquo;s <em>unsigned</em> draft is answered by candidates who countersign it at posted terms or return a counter-quote, and the buyer selects among the answers by signing exactly one &mdash; so that the match is produced anew for each transaction and no standing party performs it or owns it. That the drafts go out unsigned is the safety property rather than a detail of etiquette: settlement takes both signatures, so an unsigned draft binds nobody and cannot be submitted by anyone, which is what lets a buyer solicit many answers while committing capital to exactly one. <em>Scope.</em> How that mechanism operates &mdash; its choreography, its verification, and what a participant spends to take part in it &mdash; is protocol mechanics and lies outside this paper&rsquo;s subject. What the institutional argument needs from it is the single structural fact just stated, that a formation mechanism exists which no standing intermediary holds, and that fact is what the remainder of this section reasons from.
                    </p>
                    <p>
                        What this does to the two-sided problem is disaggregation, not abolition. The functions Rochet &amp; Tirole bundle inside the platform come apart. Side attraction is served by a public register whose entry price is a live deposit that prices spam rather than rationing access, returned to its poster when it withdraws and collected by nobody as revenue. The price level is authored by the side that bears the cost of performing &mdash; posted in a catalogue, or quoted per job. The match itself is produced per transaction, by the buyer&rsquo;s selection among candidates who have already signed. No standing party performs the matching, so no standing party holds the residual claim that Rochet &amp; Tirole&rsquo;s platform is paid. Their own framing sharpens the point: two-sidedness in their sense is a property of an intermediary&rsquo;s charges, and they observe that where the end-users negotiate the allocation of those charges away &mdash; where the Coase theorem applies &mdash; the market is one-sided. Here there is no fee to allocate and no residual claimant to allocate it. Nor is the investment a platform recovers through its price structure simply unfunded: composing a reusable multi-party deal-shape is costly work &mdash; the persisting sense of &ldquo;assembly&rdquo; fixed in Section 4.2, not the instance that dissolves &mdash; and in the shifted region its return is retroactive and graduated by measured use, a claim on a fixed protocol endowment rather than a standing claim on the transactions that use the composition.
                    </p>
                    <p>
                        Three limits belong inside this argument rather than after it. <em>First, none of the above is an efficiency comparison.</em> That the matching function need not be owned is a structural claim. Whether selection among candidates discovered from a public register produces matches &mdash; or prices &mdash; as good as those a proprietary algorithm produces ranking a private order book is a different question, and answering it requires a model of match quality and of what each regime learns from the transactions it observes. This paper offers no such model and asserts no equivalence: the argument establishes that the non-proprietary form is available, not that it is superior, nor even that it is at parity.
                    </p>
                    <p>
                        <em>Second, the cross-side externality survives untouched.</em> No formation mechanism brings a side on board that is not there. A thin seller side yields a thin candidate set, and a selection among one respondent is a bilateral negotiation wearing a market&rsquo;s clothes. The chicken-and-egg problem Rochet &amp; Tirole place at the center of their analysis is a statement about participation, not about who owns the matching apparatus, and it applies here with full force.
                    </p>
                    <p>
                        <em>Third, and sharpest: the absence of a fee is not the absence of a cost structure.</em> The two sides do not face symmetric participation costs under the primitive. The buyer&rsquo;s lockup is <Math>{"2P"}</Math> on each order and so grows linearly in the length of the chain, while the sellers&rsquo; aggregate grows with the square of it (Proposition 3.1), so the burden of participating falls unevenly across the sides, and the unevenness is fixed by what the bonding equilibrium requires rather than chosen to attract whichever side is harder to attract. This is the precise inversion of Rochet &amp; Tirole&rsquo;s instrument: their platform can move the allocation between the sides and does so deliberately; the primitive cannot move it at all, because the allocation is what the equilibrium is made of. Where the harder-to-attract side is the one the structure burdens more &mdash; deep sellers in long chains &mdash; no rebalancing is available, and a comparison against an intermediary that can subsidize a side must count that as a cost of the non-proprietary form.
                    </p>
                </PaperSubsection>
            </PaperSection>

            <PaperSection title="5. Conclusion">
                <p>
                    Asymmetric bonding (Mechanism&nbsp;1) prices the cost of trust under a fixed doubling &mdash; twice the payment from the buyer on every order, twice the value accumulated at its link from each seller &mdash; in temporarily locked (not spent) capital, with zero recurring extraction. Buyer dominance with atomic resolution (Mechanism&nbsp;2) makes the resulting mesh of bonded edges resolvable as a single coordinated unit at the buyer&rsquo;s signature. The Coasean threshold shift is the work of Mechanism&nbsp;1; the structural availability of transaction-scoped assemblies as a firm-substituting organizational form is the work of Mechanism&nbsp;2.
                </p>
                <p>
                    For any economic activity where the coordination rent exceeds the opportunity cost of locked capital, the standing firm &mdash; as Coase conceived it &mdash; is no longer the uniquely efficient unit of economic organization in that activity. The stronger consequence is that the firm becomes one organizational pattern among several in the shifted region: transaction-scoped assemblies, treasury communities, peer networks, and agent coalitions share the coordination space alongside it. The settlement primitive does not abolish coordination, nor does it abolish the firm; it retires the <em>subordination overlay</em> that previously made the firm the privileged container, and leaves a richer organizational space in its place.
                </p>
                <PaperRun title="A note on scope.">
                    This paper bounds its claim by two scope conditions, both stated in Section 3: the Coasean comparison (Proposition 3.1 &mdash; the full bonded stake&rsquo;s opportunity cost against the firm&rsquo;s coordination overhead, which also bounds how deep a chain the comparison survives) and low asset specificity, which continues to favor hierarchy and which Section 4.4 revisits at the residual-rights layer. Both must hold for a transaction to lie within the paper&rsquo;s argumentative domain; readers constructing arguments about transactions that satisfy one condition but not the other should treat the argument with corresponding partial force.
                </PaperRun>
            </PaperSection>
        </PaperLayout>
    );
}
