name: Foundry CI

on:
    push:
        branches: [main, develop]
        paths:
            - "src/**"
            - "test/**"
            - "script/**"
            - "foundry.toml"
            - ".github/workflows/foundry-ci.yml"
    pull_request:
        branches: [main, develop]
        paths:
            - "src/**"
            - "test/**"
            - "script/**"
            - "foundry.toml"

permissions:
    contents: read

jobs:
    test:
        name: Forge Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
              with:
                  submodules: recursive

            - name: Install Foundry
              uses: foundry-rs/foundry-toolchain@b00af27efadbc7b4ca8b82abbd903b17cc874d2a # v1.9.0

            - name: Run forge build
              run: forge build --via-ir

            - name: Run forge tests
              run: forge test --via-ir -vvv

            - name: Run forge fmt check
              run: forge fmt --check
